// Fans of TD · Inglés (1/3): cómo se juega, modo VS, mundos de Phony y torres de cada facción.
'use strict';
IDIOMA.add({
  "(los líderes de las facciones)": "(the leaders of the factions)",
  ", y la vida que le quitas a su base se suma a la tuya.": ", and the health you take from their base is added to yours.",
  ". Cada carta es torre y unidad a la vez: casi todo mejora solo una de las dos. Y en": ". Every card is a tower and a unit at once: almost every upgrade improves only one of the two. And in",
  ". Lo ganas tumbando enemigos y al acabar cada oleada.": ". You earn it by knocking down enemies and at the end of each wave.",
  ": Rabia, Renacer, Hype, Experiencia, Escudos, RNG, Comunidad, Nostalgia y Secuela. La eliges antes de cada partida.": ": Rage, Rebirth, Hype, Experience, Shields, RNG, Community, Nostalgia and Sequel. You pick it before every match.",
  ": así se llega a los niveles 4 y 5.": ": that's how you reach levels 4 and 5.",
  ": con ellas montas tu laberinto. Los enemigos van siempre por el camino más corto (la línea de puntos) y": ": you build your maze with them. Enemies always take the shortest path (the dotted line) and",
  "Aguanta todas las oleadas": "Survive all the waves",
  "CAOS: lo que gastas en torres dentro de la partida": "CHAOS: what you spend on towers during the match",
  "Cada torre gasta": "Each tower costs",
  "Campo de batalla": "Battlefield",
  "ENVIAR UNIDADES": "SEND UNITS",
  "En el": "In the",
  "La Rebelión de los Fans: libera cada mundo corrompido por Microblizz montando tu laberinto de torres.": "The Fans' Rebellion: free every world corrupted by Microblizz by building your tower maze.",
  "La llama de Rabia, el punto de la mutación y las estrellas de las unidades mejoradas.": "Rage's flame, the mutation dot and the stars of upgraded units.",
  "Las torres": "The towers",
  "Los que llegan a tu base se quedan pegándole. Si se queda sin vida, pierdes.": "Those that reach your base stay and hit it. If it runs out of health, you lose.",
  "MODO VS": "VS MODE",
  "NIVEL 1-1": "LEVEL 1-1",
  "OLEADA": "WAVE",
  "Oleada": "Wave",
  "Raza": "Race",
  "Toca una torre para": "Tap a tower to",
  "Velocidad": "Speed",
  "Vida de La Madriguera": "The Burrow's health",
  "a una casilla del campo, o tócala y luego toca la casilla. La carta se queda elegida unos segundos por si quieres poner varias.": "to a square on the field, or tap it and then tap the square. The card stays selected for a few seconds in case you want to place several.",
  "bloquean el paso": "block the way",
  "con oro y con lo que salga en el": "with gold and with what comes out of the",
  "del todo.": "completely.",
  "fusionar": "merge",
  "mejorarla": "upgrade it",
  "modo VS": "VS mode",
  "nunca puedes cerrarlo": "you can never close it",
  "o venderla. Dos torres iguales, del mismo nivel y pegadas se pueden": "or sell it. Two identical towers of the same level and next to each other can be",
  "oleadas": "waves",
  "también mandas unidades al campo del rival. Cada envío sube tu": "you also send units to the rival's field. Each send raises your",
  "torres en pie": "towers standing",
  "tu líder gana oro aunque no juegues.": "your leader earns gold even when you're not playing.",
  "y ganas.": "and you win.",
  "¡OLEADA!": "WAVE!",
  "«¡Chaos Jump!», «¡Despedido!», «¡Fusión!»…: encima de su cabeza o en una caja abajo a la derecha.": "«Chaos Jump!», «Fired!», «Fusion!»…: above their head or in a box at the bottom right.",
  "TORRE": "TOWER",
  "UNIDAD": "UNIT",
  "inmune a aturdimientos y frenazos": "immune to stuns and slows",
  "la TORRE": "the TOWER",
  "la UNIDAD": "the UNIT",
  "No hace nada en este juego.": "Does nothing in this game.",
  "mejora las dos facetas": "improves both facets",
  "no hace nada en este juego": "does nothing in this game",
  "· LAS DOS": "· BOTH",
  "COMUNIDAD: juntos son más fuertes, todos tienen mucha más vida.": "COMMUNITY: stronger together, they all have much more health.",
  "ESCUDOS: llevan un escudo del 25 % que se recarga si pasan 3 s sin recibir daño.": "SHIELDS: they carry a 25 % shield that recharges after 3 s without taking damage.",
  "EXPERIENCIA: se hacen más duros con cada oleada.": "EXPERIENCE: they get tougher with every wave.",
  "En el último piso, el Presidente sube otra vez la suscripción mientras los fans protestan en la puerta. Es hora de recuperar los discos.": "On the top floor, the President raises the subscription again while the fans protest at the door. Time to get the discs back.",
  "En los estudios de Phony solo se ruedan secuelas, remakes y anuncios de la PayStation. Los de Cultura Pop están hartos de repetir la misma película.": "At Phony's studios they only shoot sequels, remakes and PayStation ads. The Pop Culture crew are sick of repeating the same movie.",
  "HYPE: todos corren un 20 % más.": "HYPE: everyone runs 20 % faster.",
  "NOSTALGIA: tus torres tardan 2 s en acordarse de cada enemigo antes de dispararle.": "NOSTALGIA: your towers take 2 s to remember each enemy before shooting it.",
  "Phony ha comprado los servidores de la comunidad: ahora para jugar online hay que pagar, y los gamers ya no juegan por diversión.": "Phony has bought the community's servers: now you have to pay to play online, and the gamers no longer play for fun.",
  "Phony ha quitado el lector de discos de su consola, la PayStation. Ahora todo es digital, todo es de alquiler… y lo que compras te lo pueden borrar.": "Phony has removed the disc drive from its console, the PayStation. Now everything is digital, everything is rented… and what you buy can be deleted.",
  "RENACER: cada enemigo se levanta una vez con el 60 % de su vida.": "REBIRTH: every enemy gets up once with 60 % of its health.",
  "RNG: cada enemigo sale con una mutación al azar (gigante, turbo, de cristal o normal).": "RNG: every enemy comes out with a random mutation (giant, turbo, glass or normal).",
  "Robots de oficina. Sin trucos… salvo los del jefe.": "Office robots. No tricks… except the boss's.",
  "SECUELA: 3 de cada 10 enemigos vuelven en versión «2», con la mitad de vida.": "SEQUEL: 3 in 10 enemies come back as a «2» version, with half the health.",
  "SUSCRIPCIÓN: cada golpe a tu base te quita además 2 de CAOS.": "SUBSCRIPTION: every hit on your base also takes 2 CHAOS from you.",
  "Sin trucos: solo muerden.": "No tricks: they just bite.",
  "¡ARRIBA, HUESOS!": "UP, BONES!",
  "¡BANEADO!": "BANNED!",
  "¡COBRADA!": "CHARGED!",
  "¡COMBO!": "COMBO!",
  "¡CORTEN!": "CUT!",
  "¡DESCARGANDO!": "DOWNLOADING!",
  "¡HACKEADA!": "HACKED!",
  "¡MÁS BECARIOS!": "MORE INTERNS!",
  "¡OLVIDADA!": "FORGOTTEN!",
  "¡SUSCRIPCIÓN!": "SUBSCRIPTION!",
  "¡SUSCRIPTORES!": "SUBSCRIBERS!",
  "¡TROLEADA!": "TROLLED!",
  "Arregla el juego mejor que la empresa: las torres cercanas atacan un 30 % más rápido.": "Fixes the game better than the company: nearby towers attack 30 % faster.",
  "Ataca desde las sombras: cada tercer golpe hace el triple. Perfecta contra los tanques.": "Attacks from the shadows: every third hit does triple damage. Perfect against tanks.",
  "Bichos de un juego que nunca salió. Baratísimos y con muchas ganas de morder.": "Critters from a game that never came out. Dirt cheap and eager to bite.",
  "Bolsas de basura desde muy lejos: daño en área y los enemigos pringados van más lentos.": "Garbage bags from very far away: area damage and the messy enemies move slower.",
  "Cada 10 bajas, todas tus torres atacan un 5 % más rápido (hasta +25 %).": "Every 10 kills, all your towers attack 5 % faster (up to +25 %).",
  "Cada 12 bajas subes de nivel: +5 % de daño a todas tus torres (hasta nivel 5).": "Every 12 kills you level up: +5 % damage for all your towers (up to level 5).",
  "Cada 5 s provoca a los enemigos cercanos, que se paran a discutir con él.": "Every 5 s he taunts nearby enemies, who stop to argue with him.",
  "Cada 8 s hackea al enemigo más duro que tenga cerca y lo deja 2,5 s parado.": "Every 8 s it hacks the toughest enemy nearby and leaves it frozen for 2.5 s.",
  "Cada 9 s se enfada, tira el mando y explota: 110 de daño a todos los que tiene cerca.": "Every 9 s it gets angry, throws the controller and explodes: 110 damage to everything nearby.",
  "Cada golpe pega un 15 % más que el anterior (hasta +150 %) mientras tenga a quién pegar.": "Every hit hits 15 % harder than the last (up to +150 %) as long as there's someone to hit.",
  "Cada torre pega un 10 % más por cada torre aliada en las casillas de alrededor, hasta +50 %.": "Each tower hits 10 % harder for every allied tower on the squares around it, up to +50 %.",
  "Cada torre sale con una mutación al azar: gigante (+25 % de daño), turbo (ataca más rápido), de cristal (+60 % de daño, menos alcance) o normal.": "Each tower comes out with a random mutation: giant (+25 % damage), turbo (attacks faster), glass (+60 % damage, less range) or normal.",
  "Cámara voladora: cada clip que graba deja al enemigo aturdido un instante.": "Flying camera: every clip it records leaves the enemy stunned for a moment.",
  "Dos ardillas que tiran bellotas a toda velocidad. Baratas y nunca paran.": "Two squirrels throwing acorns at top speed. Cheap and they never stop.",
  "Dos perros muy wow. Baratos y muerden rápido.": "Two very wow dogs. Cheap and they bite fast.",
  "Droide de soporte: las torres que tiene alrededor atacan un 30 % más rápido.": "Support droid: the towers around it attack 30 % faster.",
  "El doble de acción salta hasta el enemigo: cuerpo a cuerpo con mucho alcance.": "The stunt double leaps to the enemy: melee with a long reach.",
  "El moderador: cada martillazo golpea a todos alrededor y los deja parados un momento.": "The moderator: every hammer blow hits everything around and freezes them for a moment.",
  "El tren del hype: un golpe enorme a un solo enemigo. Ideal contra los grandes.": "The hype train: one huge hit on a single enemy. Ideal against big ones.",
  "Embestida: su primer golpe a cada enemigo hace más del doble y lo aturde.": "Charge: its first hit on each enemy does more than double and stuns it.",
  "Encuentra el punto débil: cada disparo marca al enemigo 4 s y todas las torres le hacen un 25 % más de daño.": "Finds the weak spot: every shot marks the enemy for 4 s and all towers deal 25 % more damage to it.",
  "Escupe veneno y cada 8 s se baja las gafas de sol y petrifica a los enemigos cercanos.": "Spits venom and every 8 s lowers her sunglasses and petrifies nearby enemies.",
  "Espada rúnica de hielo: golpes fuertes que dejan al enemigo a media velocidad.": "Runic ice sword: heavy hits that leave the enemy at half speed.",
  "Esqueletos piratas: pegan poco pero rapidísimo. Lo más barato para levantar muros.": "Pirate skeletons: low damage but lightning fast. The cheapest way to build walls.",
  "Extras con disfraz de cartón. Cobran poco: lo más barato para levantar muros.": "Extras in cardboard costumes. They're paid little: the cheapest way to build walls.",
  "Francotirador invisible: dispara despacio, desde muy lejos y con muchísimo daño.": "Invisible sniper: shoots slowly, from very far away and with huge damage.",
  "Francotiradora: dispara despacio, pero desde lejísimos y con muchísimo daño.": "Sniper: shoots slowly, but from extremely far away and with huge damage.",
  "Golpea a todos alrededor. Si tu base baja de la mitad de vida, se enfada y pega un 50 % más.": "Hits everything around. If your base drops below half health, it gets angry and hits 50 % harder.",
  "Golpea con el escudo: cada golpe deja al enemigo parado un instante.": "Strikes with the shield: every hit leaves the enemy frozen for a moment.",
  "Hasta arriba de bebida energética: pega rapidísimo.": "Wired on energy drinks: hits lightning fast.",
  "La enfermera no pega: las torres que tiene alrededor atacan un 30 % más rápido.": "The nurse doesn't hit: the towers around her attack 30 % faster.",
  "Lanza cartuchos de dinamita: daño en área, ideal para los grupos de becarios.": "Throws dynamite sticks: area damage, ideal for groups of interns.",
  "Lanza sus juegos en disco: cada disco rebota a otro enemigo cercano.": "Throws her games on disc: each disc bounces to another nearby enemy.",
  "Los no-muertos siempre vuelven: al vender una torre recuperas todo el CAOS, así que puedes rehacer el laberinto gratis.": "The undead always come back: when you sell a tower you get all the CHAOS back, so you can rebuild the maze for free.",
  "Líder (solo uno). Ataca rapidísimo y cada 4.º golpe es un ¡COMBO!: triple de daño y aturde.": "Leader (only one). Attacks lightning fast and every 4th hit is a COMBO!: triple damage and a stun.",
  "Líder (solo uno). Cada 7 s juega una carta al azar: bola de fuego, aturdir, CAOS o una jauría de perros.": "Leader (only one). Every 7 s plays a random card: fireball, stun, CHAOS or a pack of dogs.",
  "Líder (solo uno). Cada 8 s grita ¡ACCIÓN! y las torres cercanas atacan un 40 % más rápido durante 4 s.": "Leader (only one). Every 8 s shouts ACTION! and nearby towers attack 40 % faster for 4 s.",
  "Líder (solo uno). Cada 8 s grita ¡Team Fight! y todas las torres cercanas dan a la vez un golpe extra con +50 % de daño.": "Leader (only one). Every 8 s shouts Team Fight! and all nearby towers land an extra hit at the same time with +50 % damage.",
  "Líder (solo uno). Cada 8 s levanta un muro de escudos que deja parados a los enemigos cercanos.": "Leader (only one). Every 8 s raises a shield wall that freezes nearby enemies.",
  "Líder (solo uno). Fusil rápido y cada 9 s le caen del cielo 2 drones que se estrellan contra los enemigos.": "Leader (only one). Fast rifle and every 9 s 2 drones drop from the sky and crash into the enemies.",
  "Líder (solo uno). Lanza rayos de sombra y cada 8 s levanta 2 esqueletos que se lanzan contra los enemigos.": "Leader (only one). Casts shadow bolts and every 8 s raises 2 skeletons that charge at the enemies.",
  "Líder (solo uno). Pega fuerte y cada 8 s salta sobre el grupo más grande: daño en área y los deja aturdidos.": "Leader (only one). Hits hard and every 8 s jumps on the biggest group: area damage and a stun.",
  "Líder (solo uno). Pega fuerte y, mientras está en directo, las torres cercanas hacen un 30 % más de daño.": "Leader (only one). Hits hard and, while live, nearby towers deal 30 % more damage.",
  "Marine espacial de 1998: ráfagas rapidísimas desde lejos.": "Space marine from 1998: lightning-fast bursts from afar.",
  "Mecha de asedio: cañonazos con daño en área desde muy lejos.": "Siege mech: cannon shots with area damage from very far away.",
  "Nadie es más rápida: golpes sin parar.": "Nobody is faster: non-stop hits.",
  "Nadie se acuerda de ellos: el primer golpe de cada torre a cada enemigo hace el doble de daño.": "Nobody remembers them: each tower's first hit on each enemy does double damage.",
  "Programadores zombis. Lentos, pero cada mordisco duele.": "Zombie programmers. Slow, but every bite hurts.",
  "Rayos de escarcha desde lejos: cada impacto frena al enemigo.": "Frost bolts from afar: every hit slows the enemy.",
  "Reparte bocadillos: las torres que tiene alrededor atacan un 30 % más rápido.": "Hands out sandwiches: the towers around her attack 30 % faster.",
  "Robots diminutos que muerden sin parar. Lo más barato para levantar muros.": "Tiny robots that bite non-stop. The cheapest way to build walls.",
  "Se teletransporta para dar el golpe: cuerpo a cuerpo con mucho alcance.": "Teleports to strike: melee with a long reach.",
  "Su rayo salta del objetivo a otros 2 enemigos cercanos.": "His lightning jumps from the target to 2 other nearby enemies.",
  "Superhéroe de película barata: vuela hasta el enemigo y pega fuerte.": "Cheap-movie superhero: flies to the enemy and hits hard.",
  "Sus ondas golpean en área y cada 7 s grita y aturde a todos los enemigos cercanos.": "Its waves hit an area and every 7 s it screams and stuns all nearby enemies.",
  "Tira periódicos y cada 7 s grita el final de la película: los enemigos cercanos se quedan en shock.": "Throws newspapers and every 7 s shouts the movie's ending: nearby enemies go into shock.",
  "Toda buena película tiene secuela: 3 de cada 10 ataques se repiten enseguida con la mitad de daño.": "Every good movie has a sequel: 3 in 10 attacks repeat right away with half the damage.",
  "Todas tus torres pegan un 5 % más por cada tipo distinto de torre que tengas en el campo (hasta +30 %).": "All your towers hit 5 % harder for every different tower type you have on the field (up to +30 %).",
  "Tres novatos con gorro de hélice. No saben jugar, pero son baratos y le ponen ganas.": "Three newbies with propeller hats. They can't play, but they're cheap and try hard.",
  "Tres soldados con lanza larga: llegan más lejos que otras torres de cuerpo a cuerpo.": "Three soldiers with long spears: they reach further than other melee towers.",
  "Tres suscriptores con dedo de espuma. Baratos, rápidos y muy entregados.": "Three subscribers with foam fingers. Cheap, fast and fully committed.",
  "Tres vikingos con escudo y espada. Fiables en cualquier muro.": "Three vikings with shield and sword. Reliable in any wall.",
  "Tu base lleva un escudo de plasma de 25 que se recarga si pasa 3 s sin recibir daño.": "Your base has a 25 plasma shield that recharges after 3 s without taking damage.",
  "Un coche de carreras con lanzamisiles: daño en área.": "A race car with a missile launcher: area damage.",
  "Un gato enorme: golpea a todos alrededor y cada 6 s se sienta encima y los aturde.": "A huge cat: hits everything around and every 6 s sits on them and stuns them.",
  "Un mecha rosa con una vaca dentro. Cada pisotón golpea a todos los que tiene cerca y los frena.": "A pink mech with a cow inside. Every stomp hits everything nearby and slows it.",
  "Un monstruo de goma: cada pisotón golpea a todos los que tiene alrededor.": "A rubber monster: every stomp hits everything around it.",
  "Un querubín con arco: flechas rápidas desde lejos. Barato y fiable.": "A cherub with a bow: fast arrows from afar. Cheap and reliable.",
  "Una mole cosida a trozos. Cada golpe revienta a todos los que tiene alrededor.": "A hulk stitched together from pieces. Every hit bursts everything around it.",
  "Una máquina arcade con piernas: golpea a todos alrededor y cada 8 s dispara 2 monedas.": "An arcade machine with legs: hits everything around and every 8 s fires 2 coins.",
  ", el botón rojo, para que salgan los robots de Microblizz.": ", the red button, to send out the Microblizz robots.",
  ". Pon 2 más para que los enemigos den un rodeo: la línea de puntos es el camino que seguirán. Nunca puedes cerrarlo del todo.": ". Place 2 more so the enemies take a detour: the dotted line is the path they'll follow. You can never close it completely.",
  "Cada baja te da CAOS.": "Every kill gives you CHAOS.",
  "Cada torre": "Each tower",
  "Pulsa": "Press",
  "Toca una torre": "Tap a tower",
  "Tutorial reiniciado: entra en Campaña y juega el nivel 1-1": "Tutorial restarted: go to Campaign and play level 1-1",
  "bloquea el paso": "blocks the way",
  "de abajo a una casilla del campo para poner tu primera torre. También puedes tocar la carta y luego la casilla.": "from below to a square on the field to place your first tower. You can also tap the card and then the square.",
  "para mejorarla, o pon otra igual pegada a ella para fusionarlas.": "to upgrade it, or place an identical one next to it to merge them.",
  "¡Eso es todo! Aguanta todas las oleadas sin que caiga tu base. En el menú tienes el equipo, el gashapón y el modo VS.": "That's all! Survive all the waves without your base falling. In the menu you have the gear, the gacha and the VS mode.",
  "%1 de daño": "%1 damage",
  "%1 · alcance %2%3%4": "%1 · range %2%3%4",
  "%1, %2 de CAOS": "%1, %2 CHAOS",
  "+%1 % velocidad": "+%1 % speed",
  "AQUÍ NO": "NOT HERE",
  "CAMPO DE": "FIELD OF",
  "ES LA ENTRADA": "IT'S THE ENTRANCE",
  "Enviar %1 de nivel %2: %3 de CAOS, +%4 de income": "Send %1 of level %2: %3 CHAOS, +%4 income",
  "FALTA CAOS": "NOT ENOUGH CHAOS",
  "HAY ENEMIGOS": "ENEMIES HERE",
  "NV %2": "LV %2",
  "TORRES": "TOWERS",
  "TU CAMPO": "YOUR FIELD",
  "VENDER": "SELL",
  "YA HAY UNA TORRE": "THERE'S ALREADY A TOWER",
  "a tu campo": "to your field",
  "ver su campo": "view their field",
  "¡EMPEZAR!": "START!",
  "¡NO CIERRES EL CAMINO!": "DON'T CLOSE THE PATH!",
  "· ESCUDO": "· SHIELD",
  "· income +%1 en %2 s": "· income +%1 in %2 s",
  ". ¿Quieres seguir aquí con ese progreso?": ". Do you want to continue here with that progress?",
  ": estrellas, oro, gemas, niveles y objetos.": ": stars, gold, gems, levels and items.",
  "CARGAR": "LOAD",
  "Copia a mano el código de la caja": "Copy the code from the box by hand",
  "Código copiado. Pégalo en el otro dispositivo.": "Code copied. Paste it on the other device.",
  "Equipo freak solo para los líderes: arma, cabeza y accesorio. Cada objeto sale con su propia calidad.": "Freak gear for leaders only: weapon, head and accessory. Each item comes with its own quality.",
  "Ese código no vale. Cópialo entero desde el otro dispositivo y pégalo en la caja.": "That code isn't valid. Copy it in full from the other device and paste it in the box.",
});
