// Fans of TD · Inglés (2/3): importar progreso, novedades del TD, modo VS y logros.
'use strict';
IDIOMA.add({
  "IDIOMAS": "LANGUAGES",
  ": el juego está ahora en español y en inglés. Se elige solo según el idioma de tu navegador y puedes cambiarlo en Opciones (Idioma / Language).": ": the game is now in Spanish and English. It's picked automatically from your browser's language and you can change it in Options (Language).",
  "El inglés cubre los menús, las cartas, las torres, las misiones y los logros. Si ves algo que sigue en español, ya lo sabemos.": "English covers the menus, the cards, the towers, the missions and the achievements. If you see something still in Spanish, we know.",
  "Microblizz ha descubierto que existen más idiomas y quiere cobrarte la traducción.": "Microblizz has discovered there are more languages and wants to charge you for the translation.",
  "Phony lo llama «localización premium». Tú, «por fin».": "Phony calls it «premium localisation». You call it «finally».",
  "Modo pruebas activado": "Test mode on",
  "No se puede deshacer, salvo empezando de cero.": "It can't be undone, except by starting from scratch.",
  "No se puede deshacer.": "It can't be undone.",
  "Se borra": "This deletes",
  "Se cambia todo tu progreso de este navegador por el del código.": "All your progress in this browser is replaced by the one in the code.",
  "Sustituye al progreso guardado en esta dirección. No se puede deshacer.": "It replaces the progress saved at this address. It can't be undone.",
  "TRAER": "BRING",
  "Vienes de la dirección antigua del juego, donde tenías": "You come from the game's old address, where you had",
  "¿CARGAR ESE PROGRESO?": "LOAD THAT PROGRESS?",
  "¿EMPEZAR DE CERO?": "START FROM SCRATCH?",
  "¿TRAER TU PROGRESO?": "BRING YOUR PROGRESS?",
  ", como en Fans of Rumble: arma, cabeza y accesorio son suyos, y las demás cartas llevan solo su habilidad. Lo que tuvieran puesto otras cartas ha vuelto a tu inventario.": ", as in Fans of Rumble: weapon, head and accessory are theirs, and the other cards carry only their ability. What other cards were wearing has returned to your inventory.",
  ", con el mismo código: colección, inventario, gashapón, tienda, horas extra y sonido.": ", with the same code: collection, inventory, gacha, shop, overtime and sound.",
  ", con una épica segura por cada 10.": ", with a guaranteed epic for every 10.",
  ": 30 niveles con pista gratis y pista Ejecutiva (de prueba: no se cobra nada). Jugar partidas y cobrar misiones da puntos.": ": 30 levels with a free track and an Executive track (trial: nothing is charged). Playing matches and claiming missions gives points.",
  ": Lola te pregunta cómo te llamas. Toca tu avatar arriba a la izquierda para ver tus números, cambiar el nombre o elegir avatar.": ": Lola asks what your name is. Tap your avatar at the top left to see your numbers, change your name or pick an avatar.",
  ": al colocar una torre, su carta se queda elegida unos segundos. Toca otra casilla y pones otra igual, sin volver a la bandeja.": ": when you place a tower, its card stays selected for a few seconds. Tap another square and you place another one, without going back to the tray.",
  ": cada líder hace ahora su propio especial. NecroLord invoca esqueletos, CyberMarine llama a sus drones, el Vikingo levanta su muro de escudos… Antes todos saltaban como CrazyBunny.": ": every leader now does their own special. NecroLord summons skeletons, CyberMarine calls his drones, the Viking raises his shield wall… Before, they all jumped like CrazyBunny.",
  ": cada torre que pones y cada unidad que envías da XP a su carta. Para subirla de nivel hace falta XP y oro, como en el original.": ": every tower you place and every unit you send gives XP to its card. To level it up you need XP and gold, as in the original.",
  ": colección, inventario, gashapón con su máquina de cápsulas, tienda y horas extra tienen ahora su mismo aspecto.": ": collection, inventory, gacha with its capsule machine, shop and overtime now look the same.",
  ": cuatro diarias y cuatro semanales, con oro, gemas y puntos de pase. Colocar torres, superar oleadas, fusionar, ganar en el modo VS…": ": four daily and four weekly, with gold, gems and pass points. Placing towers, clearing waves, merging, winning in VS mode…",
  ": desde Opciones puedes instalar el juego como una app, a pantalla completa. Instalado también funciona sin conexión.": ": from Options you can install the game as an app, full screen. Once installed it also works offline.",
  ": dos torres iguales, del mismo nivel y pegadas se funden en una mejor.": ": two identical towers of the same level and next to each other merge into a better one.",
  ": durante la partida se apagaban y encendían solas varias veces por segundo. Ahora solo se apagan cuando no te llega el CAOS.": ": during the match they turned off and on by themselves several times a second. Now they only turn off when you don't have enough CHAOS.",
  ": el campo es todo camino, lo cierras tú con torres y nunca del todo.": ": the field is all path, you close it with towers and never completely.",
  ": el juego vive ahora en microblizz.github.io/FansOf. La dirección antigua te trae aquí sola.": ": the game now lives at microblizz.github.io/FansOf. The old address brings you here by itself.",
  ": esta ventana. Sale una vez con cada versión y puedes volver a verla en NOVEDADES.": ": this window. It shows up once with each version and you can see it again in NEWS.",
  ": la portada, la campaña, la pantalla de antes de jugar, la pausa y el final de la partida tienen ahora su mismo aspecto.": ": the title screen, the campaign, the pre-match screen, the pause and the end of the match now look the same.",
  ": los comentarios falsos del original, durante la partida. Se quita en Opciones.": ": the original's fake comments, during the match. You can turn them off in Options.",
  ": mejora tus unidades dentro de la partida, y el rival gasta más en mandarte las suyas. Lo de dentro de la partida ahora se llama": ": upgrade your units during the match, and the rival spends more sending you theirs. What happens inside the match is now called",
  ": más de 1.300, por niveles, y cada uno da gemas una sola vez. Los hay de batallas, de cada facción y cada carta, de campaña, de enemigos, de gashapón, de constancia… y secretos.": ": over 1,300, in tiers, and each gives gems only once. There are ones for battles, for each faction and each card, for the campaign, for enemies, for the gacha, for consistency… and secret ones.",
  ": música del menú a elegir (la de cualquier raza o jefe), avisos encima o en una caja, chapas, sangre y chat.": ": menu music of your choice (any race's or boss's), alerts above or in a box, badges, blood and chat.",
  ": oro y gemas, niveles de carta, habilidades, equipo, gashapón, tienda y horas extra.": ": gold and gems, card levels, abilities, gear, gacha, shop and overtime.",
  ": todas tus copias con su calidad. Puedes bloquearlas, volver a sortear sus números o despedirlas (también en masa).": ": all your copies with their quality. You can lock them, re-roll their numbers or dismiss them (also in bulk).",
  ": un resumen en 8 pasos, en la portada.": ": an 8-step summary, on the title screen.",
  ": un tema por raza, el de cada jefe y los de victoria y derrota. Después de sonar entera sigue subiendo de tono sin fin (paradoja de Shepard) para que no canse.": ": one theme per race, each boss's and the victory and defeat ones. After playing all the way through it keeps rising in pitch endlessly (Shepard's paradox) so it doesn't get tiring.",
  ": una misma copia la pueden llevar varios a la vez. En la colección, «PONER ESTE EQUIPO A TODOS LOS LÍDERES» lo hace de un toque.": ": several leaders can wear the same copy at once. In the collection, «EQUIP THIS GEAR ON ALL LEADERS» does it in one tap.",
  ": una partida guiada en el nivel 1-1 para quien empieza. Se puede repetir desde Opciones.": ": a guided match in level 1-1 for beginners. It can be repeated from Options.",
  ": volumen, música, números de daño, temblor de pantalla y modo pruebas. Están en el menú principal.": ": volume, music, damage numbers, screen shake and test mode. They're on the main menu.",
  "Antes de jugar": "Before playing",
  "Arreglado el parpadeo de las cartas de torres": "Fixed the flicker of the tower cards",
  "Arreglado el parpadeo de los botones de la torre durante el combate.": "Fixed the flicker of the tower buttons during combat.",
  "Arreglados colores que faltaban en algunos menús (los fondos de la cartera y de varias cajas salían transparentes).": "Fixed missing colours in some menus (the wallet's and several boxes' backgrounds were transparent).",
  "Cada carta es una": "Every card is a",
  "Cambio interno: el juego se ha ordenado por dentro para compartir razas, cartas, objetos, menús y música con los próximos juegos de Fans of Rumble.": "Internal change: the game has been reorganised inside to share races, cards, items, menus and music with the upcoming Fans of Rumble games.",
  "Cambio interno: los números propios de Fans of TD (qué hace cada objeto y cada habilidad, y sus recompensas) están ahora en un archivo de ajustes aparte. No cambia nada al jugar.": "Internal change: Fans of TD's own numbers (what each item and ability does, and their rewards) are now in a separate settings file. Nothing changes when playing.",
  "Defensa de torres de": "Tower defence from",
  "Despedir copias, volver a sortearlas y girar el gashapón cuentan ya para los logros.": "Dismissing copies, re-rolling them and spinning the gacha now count towards achievements.",
  "Dirección nueva": "New address",
  "Doce mundos y ni un solo día de vacaciones.": "Twelve worlds and not a single day off.",
  "El CEO ha preguntado por qué las torres no tienen contrato temporal.": "The CEO asked why the towers don't have temporary contracts.",
  "El botón de sonido de la portada pasa a Opciones para dejar sitio al perfil.": "The title screen's sound button moves to Options to make room for the profile.",
  "El chat pregunta dónde se compra el CAOS. Microblizz está tomando nota.": "The chat asks where to buy CHAOS. Microblizz is taking notes.",
  "El equipo se comparte entre líderes": "Gear is shared between leaders",
  "El gashapón tiene tiradas": "The gacha has pulls",
  "El juego se llama Fans of TD": "The game is now called Fans of TD",
  "El modo sin conexión guarda el juego entero desde la primera visita.": "Offline mode saves the whole game from the first visit.",
  "El pase de batalla dura «hasta que Microblizz lo cierre». No han querido dar fecha.": "The battle pass lasts «until Microblizz shuts it down». They wouldn't give a date.",
  "El rival también es un becario. No se lo digas.": "The rival is an intern too. Don't tell them.",
  "En el gashapón de equipo, los": "In the gear gacha, the",
  "En la portada, los tres personajes de tu facción salen subidos a su": "On the title screen, the three characters of your faction stand on their",
  "Fusiones": "Merges",
  "Informe de parches": "Patch notes",
  "Instalar": "Install",
  "LOGROS": "ACHIEVEMENTS",
  "La música era gratis. Microblizz está investigando cómo ha podido pasar.": "The music was free. Microblizz is investigating how that could happen.",
  "La sangre es opcional. Los despidos, no.": "Blood is optional. Layoffs are not.",
  "Las": "The",
  "Las habilidades y los objetos ya no llevan la etiqueta de TORRE o UNIDAD: dicen lo que hacen y ya está. El": "Abilities and items no longer carry the TOWER or UNIT label: they just say what they do. The",
  "Las horas extra no se pagan. Se «acumulan».": "Overtime isn't paid. It «accumulates».",
  "Los menús son ya los mismos que en Fans of Rumble": "The menus are now the same as in Fans of Rumble",
  "Los menús suenan como en el Rumble y, después de ganar, vuelve la canción de menú que tengas elegida en Opciones.": "The menus sound like in Rumble and, after winning, the menu song you chose in Options comes back.",
  "Los objetos, solo en el líder": "Items, only on the leader",
  "Menús como los del original": "Menus like the original's",
  "Microblizz aclara que el parpadeo era una función prémium de discoteca. Se retira por falta de suscriptores.": "Microblizz clarifies that the flicker was a premium nightclub feature. It's withdrawn for lack of subscribers.",
  "Microblizz estudia cobrar por cada toque que te ahorras.": "Microblizz is considering charging for every tap you save.",
  "Microblizz ha añadido un botón de opciones. La opción de no pagar sigue en desarrollo.": "Microblizz has added an options button. The option not to pay is still in development.",
  "Microblizz ha descubierto que sus empleados también tienen habilidades propias. Las ha puesto de pago.": "Microblizz has discovered that its employees have abilities of their own too. It has made them pay-to-use.",
  "Microblizz ha encontrado la forma de que vuelvas cada día: regalarte cosas. Le ha dolido.": "Microblizz has found a way to make you come back every day: giving you stuff. It hurt.",
  "Microblizz ha fusionado dos departamentos de menús en uno. Sobran becarios.": "Microblizz has merged two menu departments into one. There are interns to spare.",
  "Microblizz ha patentado «andar en línea recta».": "Microblizz has patented «walking in a straight line».",
  "Microblizz ha registrado «Fans Of» en 40 países. Por si acaso.": "Microblizz has registered «Fans Of» in 40 countries. Just in case.",
  "Microblizz ha renovado los menús. Los precios, también.": "Microblizz has renovated the menus. The prices too.",
  "Microblizz ha retirado el equipo a toda la plantilla menos al jefe. Dice que así «se simplifica».": "Microblizz has taken the gear away from the whole staff except the boss. It says this «simplifies things».",
  "Microblizz ha separado «sistemas» de «datos». A los becarios los ha dejado en «gastos».": "Microblizz has separated «systems» from «data». It has left the interns under «expenses».",
  "Microblizz llama a esto «sinergias». Normalmente después despide a alguien.": "Microblizz calls this «synergies». Usually it fires someone afterwards.",
  "Microblizz quería cobrar 0,99 € por leer estas notas. Al becario se le olvidó poner el botón de pagar.": "Microblizz wanted to charge 0.99 € for reading these notes. The intern forgot to add the pay button.",
  "Microblizz se ha mudado de oficina. Los despidos también se han mudado.": "Microblizz has moved offices. The layoffs have moved too.",
  "Modo VS": "VS Mode",
  "Música del original": "Music from the original",
  "Opciones como las del original": "Options like the original's",
  "PASE DE BATALLA": "BATTLE PASS",
  "Pasar el progreso": "Transfer progress",
  "Phony anuncia que la música subirá de tono para siempre. También el precio.": "Phony announces the music will rise in pitch forever. So will the price.",
  "Phony asegura que la pantalla de pausa es una función exclusiva.": "Phony claims the pause screen is an exclusive feature.",
  "Phony lo llama «sinergia». Tú, «por fin».": "Phony calls it «synergy». You call it «finally».",
  "Phony recuerda que instalar el juego no te da la propiedad del juego.": "Phony reminds you that installing the game doesn't give you ownership of the game.",
  "Poner varias torres seguidas": "Placing several towers in a row",
  "Progreso": "Progress",
  "Se suelta sola a los 4 segundos, si no te llega el CAOS para otra, o si tocas la carta o una torre ya puesta.": "It lets go by itself after 4 seconds, if you don't have enough CHAOS for another one, or if you tap the card or a tower already placed.",
  "Si lo tienes instalado como app, el nombre nuevo sale al reinstalarlo.": "If you have it installed as an app, the new name shows up when you reinstall it.",
  "Si vienes de la antigua con progreso guardado, al llegar te pregunta si quieres": "If you come from the old address with saved progress, on arrival it asks whether you want to",
  "Tu progreso se conserva. Si lo tenías": "Your progress is kept. If you had it",
  "Tutorial": "Tutorial",
  "a otro móvil o PC con un código, y empezar de cero si quieres.": "to another phone or PC with a code, and start from scratch if you want.",
  "con sus torres y su pasiva, y los": "with their towers and their passive, and the",
  "contra un rival que lleva el juego: envía unidades, sube tu income y róbale vida a su base.": "against a rival that runs the game: send units, raise your income and steal health from their base.",
  "daño": "damage",
  "de la campaña con sus jefes.": "of the campaign with their bosses.",
  "eliges tu facción en una pantalla propia, con su pasiva. En el modo VS eliges ahí también el rival.": "you pick your faction on a screen of its own, with its passive. In VS mode you pick the rival there too.",
  "instalado como app": "installed as an app",
  "objetos de facción": "faction items",
  "peana de torre": "tower pedestal",
  "por entrar cada día: el séptimo, 10 tiradas gratis.": "for logging in every day: on the seventh, 10 free pulls.",
  "que comparten nivel, habilidad y equipo: casi todo mejora solo una de las dos.": "that share level, ability and gear: almost every upgrade improves only one of the two.",
  "salen más a menudo: la mitad de las veces que toca su rareza.": "come up more often: half of the times their rarity comes up.",
  "traértelo": "bring it",
  "vale para las dos cosas: la torre pega más y la unidad le quita más vida a la base rival.": "counts for both: the tower hits harder and the unit takes more health from the rival base.",
  "x1, x10 y x50": "x1, x10 and x50",
  "y no abre bien, desinstálalo y vuelve a instalarlo desde Opciones.": "and it doesn't open properly, uninstall it and reinstall it from Options.",
  "y una": "and a",
  "%1 han tirado %2 en %3:%4.": "%1 took down %2 in %3:%4.",
  "Contra un rival que lleva el juego, con una raza al azar. Cada uno defiende su campo y manda unidades al del otro: gana quien tumba la base rival.": "Against a rival that runs the game, with a random race. Each defends their own field and sends units to the other's: whoever takes down the rival base wins.",
  "El CEO aprovecha la pausa para subir los precios.": "The CEO uses the pause to raise prices.",
  "Estrellas: ganar · con media base en pie · con la base casi intacta.": "Stars: win · with half the base standing · with the base almost intact.",
  "Gana más income que tú": "Earns more income than you",
  "Han tirado %1 en la oleada %2 de %3.": "%1 was taken down in wave %2 of %3.",
  "Has tirado la base de %1 en %2:%3.": "You took down %1's base in %2:%3.",
  "La PayStation sigue descargando una actualización.": "The PayStation is still downloading an update.",
  "Los becarios no tienen pausa. Tú sí.": "Interns don't get a pause. You do.",
  "Mundo %2: %3. Rival: %4, %5 oleadas%6.": "World %2: %3. Rival: %4, %5 waves%6.",
  "NIVEL %1": "LEVEL %1",
  "Pausa disponible solo con conexión.": "Pause available only with a connection.",
  "Phony te cobra la pausa en la próxima suscripción.": "Phony will charge you for the pause in your next subscription.",
  "Recompensa: %1, %2 o %3 de oro según el rival si ganas (%4 si pierdes), y experiencia para tus cartas.": "Reward: %1, %2 or %3 gold depending on the rival if you win (%4 if you lose), and experience for your cards.",
  "income final": "final income",
  "unidades enviadas": "units sent",
  "COLA LLENA": "QUEUE FULL",
  "de CAOS": "CHAOS",
  "de income": "income",
  "¡FUSIÓN! NIVEL": "MERGE! LEVEL",
  "¡ZAS!": "ZAP!",
  "· NIVEL": "· LEVEL",
  "· ¡LA ÚLTIMA!": "· THE LAST ONE!",
  "%1 efectos más": "%1 more effects",
  "1 efecto más": "1 more effect",
  "Vida %1 · %2 · Alcance %3": "Health %1 · %2 · Range %3",
  "de velocidad de ataque": "attack speed",
  "+15 DE CAOS": "+15 CHAOS",
  "ESQUIVA": "DODGE",
  "¡LA SECUELA!": "THE SEQUEL!",
  "Acaba una partida con un camino de 60 casillas o más.": "Finish a match with a path of 60 squares or more.",
  "Arquitecto del caos": "Architect of Chaos",
  "Campaña: %1 ★ · Pase nivel %2": "Campaign: %1 ★ · Pass level %2",
  "Cara a cara": "Face to Face",
  "Cinco becarios en un solo cuerpo.": "Five interns in a single body.",
  "Coleccionista de estrellas": "Star Collector",
  "Coloca %1 torres.": "Place %1 towers.",
  "Coloca 25 torres": "Place 25 towers",
  "Coloca 250 torres": "Place 250 towers",
  "Coloca a %1 por primera vez.": "Place %1 for the first time.",
  "Coloca a tu líder %1 veces.": "Place your leader %1 times.",
  "Coloca a tu líder 3 veces": "Place your leader 3 times",
  "Consigue %1 estrellas en el mundo %2.": "Get %1 stars in world %2.",
  "Consigue %1 estrellas en la campaña.": "Get %1 stars in the campaign.",
  "Consigue las 12 estrellas del mundo %1.": "Get all 12 stars in world %1.",
  "Consigue todas las estrellas de la campaña.": "Get all the stars in the campaign.",
  "Contra": "Against",
  "Derrota a 3.000 enemigos": "Defeat 3,000 enemies",
  "Derrota a 300 enemigos": "Defeat 300 enemies",
  "Derrota a 500 enemigos en una sola partida.": "Defeat 500 enemies in a single match.",
  "Dos hacen el trabajo de una. Pero mejor.": "Two do the work of one. But better.",
  "ENEMIGOS": "ENEMIES",
  "El Minotauro aprueba": "The Minotaur Approves",
  "El que ríe el último": "He Who Laughs Last",
  "El rival también es un becario.": "The rival is an intern too.",
  "En Microblizz eso se paga aparte.": "At Microblizz that costs extra.",
  "Envía %1 unidades en el modo VS.": "Send %1 units in VS mode.",
  "Envía 10 unidades en el modo VS": "Send 10 units in VS mode",
  "Envío urgente": "Express Delivery",
  "Formación continua": "Continuous Training",
  "Fusiona 15 torres": "Merge 15 towers",
  "Fusiona 2 torres": "Merge 2 towers",
  "Fusiona dos torres.": "Merge two towers.",
  "Fusión de departamentos": "Department Merger",
  "Fusión total": "Total Merger",
  "Gana 3 partidas del modo VS": "Win 3 VS mode matches",
  "Gana 5 partidas sin que toquen tu base": "Win 5 matches without your base being touched",
  "Gana al CEO de Microblizz (nivel 7-4).": "Beat the Microblizz CEO (level 7-4).",
  "Gana al Presidente de Phony (nivel 12-4).": "Beat the Phony President (level 12-4).",
  "Gana sin que toquen tu base": "Win without your base being touched",
  "Gana un nivel de jefe.": "Win a boss level.",
  "Gana una partida del modo VS.": "Win a VS mode match.",
  "Gana una partida sin que toquen tu base.": "Win a match without your base being touched.",
  "Gasta 3.000 de CAOS": "Spend 3,000 CHAOS",
  "Gasta 6.000 de CAOS en una sola partida.": "Spend 6,000 CHAOS in a single match.",
  "Juega una partida del modo VS": "Play a VS mode match",
  "Juega una partida del modo VS.": "Play a VS mode match.",
  "Libera a los Olvidados del sótano de Microblizz (nivel 8-4).": "Free the Forgotten from Microblizz's basement (level 8-4)."
});
