// Fans of TD · Inglés (plantillas): efectos de habilidades y objetos (con sus números) y logros con números.
'use strict';
IDIOMA.add({
  ", me despidió Microblizz. Antes de empezar, ¿cómo quieres que te llame? Será tu nombre en tu perfil y en el chat de las partidas.": ", Microblizz fired me. Before we start, what should I call you? It'll be your name in your profile and in the match chat.",
  "%1 % de alcance": "%1 % range",
  "%1 % de daño": "%1 % damage",
  "%1 % de daño a la base rival": "%1 % damage to the rival base",
  "%1 % de velocidad": "%1 % speed",
  "%1 % de vida": "%1 % health",
  "al caer se divide en 2 copias con el %1 % de su vida": "on death it splits into 2 copies with %1 % of its health",
  "al llegar a la base rival le roba %1 de CAOS": "on reaching the rival base it steals %1 CHAOS",
  "ataca un %1 % más rápido": "attacks %1 % faster",
  "cada 9 s aturde %1 s a los enemigos cercanos": "every 9 s it stuns nearby enemies for %1 s",
  "cada enemigo que derrota da %1 de CAOS extra": "every enemy it defeats gives %1 extra CHAOS",
  "cada golpe salpica el %1 % del daño alrededor": "every hit splashes %1 % of the damage around",
  "cada golpe salta a otro enemigo con el %1 % del daño": "every hit jumps to another enemy with %1 % of the damage",
  "con tu base a menos de la mitad, +%1 % de daño": "with your base below half, +%1 % damage",
  "el %1 % de sus golpes son críticos (triple)": "%1 % of its hits are critical (triple)",
  "escudo del %1 % de su vida que se recarga": "a shield worth %1 % of its health that recharges",
  "esquiva el %1 % de los golpes": "dodges %1 % of hits",
  "las torres rivales tardan %1 s en verle": "rival towers take %1 s to see it",
  "los jefes dejan parada su torre un %1 % menos de tiempo": "bosses leave their tower stopped for %1 % less time",
  "los primeros %1 s va al triple de velocidad": "for the first %1 s it moves at triple speed",
  "recibe un %1 % menos de daño": "takes %1 % less damage",
  "revive una vez con el %1 % de su vida": "revives once with %1 % of its health",
  "roba un %1 % más de vida a la base rival": "steals %1 % more health from the rival base",
  "se cura un %1 % de su vida cada segundo": "heals %1 % of its health every second",
  "sus golpes frenan al enemigo %1 s": "its hits slow the enemy for %1 s",
  "una vez, cuando va a caer, es invulnerable %1 s": "once, when it's about to fall, it's invulnerable for %1 s",
  "%1+%2 income": "%1+%2 income",
  "Coloca a %1 %2 veces.": "Place %1 %2 times.",
  "Fusiona torres %1 veces.": "Merge towers %1 times.",
  "Gana %1 niveles de jefe.": "Win %1 boss levels.",
  "Gana %1 partidas del modo VS.": "Win %1 VS mode matches.",
  "Gana %1 partidas sin que toquen tu base.": "Win %1 matches without your base being touched.",
  "Juega %1 partidas del modo VS.": "Play %1 VS mode matches.",
  // Descripciones de habilidades y objetos partidas por su número (solo el TD)
  "% de daño y escudo del": "% damage and a shield worth",
  "% de daño y las torres rivales tardan": "% damage and rival towers take",
  "% de daño y sus golpes frenan al enemigo": "% damage and its hits slow the enemy for",
  "% de los golpes.": "% of hits.",
  "Al llegar a la base rival le roba": "When it reaches the rival base, it steals",
  "Las torres rivales tardan": "Rival towers take",
  "Roba un": "Steals",
  // (más trozos del TD)
  "s en verle.": "s to spot it.",
  "% menos de daño.": "% less damage.",
  "<b>SESIÓN MÁS ESTABLE</b>: arreglado el error «invalid refresh token» que a veces te sacaba de la cuenta.": "<b>MORE STABLE SESSION</b>: fixed the “invalid refresh token” error that sometimes logged you out of your account.",
  "Microblizz asegura que la sesión ahora es de las que no se cae. Ya lo dijo del puente.": "Microblizz swears the session is now the kind that doesn't drop. It said the same about the bridge.",
  "<b>PASE CON ASPECTO NUEVO</b>: el pase tiene un diseño renovado y pasa a funcionar como en Rumble.": "<b>PASS WITH A NEW LOOK</b>: the pass has a renewed design and now works as in Rumble.",
  "Microblizz ha pintado el pase de otro color y lo llama «rediseño».": "Microblizz painted the pass another colour and calls it a “redesign”.",
  "<b>INICIAR SESIÓN, MÁS FÁCIL</b>: el menú tiene un botón «Iniciar sesión / crear cuenta» para guardar tu progreso con Google o con tu email.": "<b>EASIER SIGN-IN</b>: the menu has a «Sign in / create account» button to save your progress with Google or email.",
  "Microblizz ha puesto un cartel de «Entrada» en la puerta. Antes había que adivinar dónde estaba.": "Microblizz has put an «Entrance» sign on the door. Before, you had to guess where it was.",
  "+%1 % de daño y −%2 % de vida.": "+%1 % damage and −%2 % health.",
  "+%1 % de vida y −%2 % de velocidad.": "+%1 % health and −%2 % speed.",
});
