// Fans Of · Inglés de lo común (extra): lo que no cabía en los otros diccionarios.
'use strict';
IDIOMA.add({
  "COBRAR TODO%10": "CLAIM ALL%10",
  "Campero": "Camper",
  "Automático (el idioma del navegador)": "Automatic (the browser's language)",
  "torre": "tower",
  "unidad": "unit",
  "laberinto": "maze",
  "9 razas": "9 races",
  "12 mundos": "12 worlds",
  "Versión %1": "Version %1",
  "¿QUÉ PARTIDA QUIERES?": "WHICH SAVE DO YOU WANT?",
  "Has jugado en este aparato y en otro, y las dos partidas son distintas. Elige con cuál sigues; la otra se pierde. ▲ marca dónde hay más.": "You've played on this device and on another one, and the two saves are different. Choose which one to keep; the other one is lost. ▲ marks where there is more.",
  "Nivel de las cartas (suma)": "Card levels (total)",
  "XP de las cartas": "Card XP",
  "Cartas conseguidas": "Cards owned",
  "Estrellas de las cartas": "Card stars",
  "Habilidades y objetos": "Abilities and items",
  "Estrellas de los niveles": "Level stars",
  "Niveles de campaña pasados": "Campaign levels cleared",
  "XP del pase": "Pass XP",
  "Logros": "Achievements",
  "Apartados de la partida que difieren: {n}": "Save sections that differ: {n}",
  "Con contrato indefinido": "On indefinite contract",
  "Equipados": "Equipped",
  "Mazos": "Decks",
  "Tickets": "Tickets",
  "Facciones desbloqueadas": "Unlocked factions",
  "En este aparato": "On this device",
  "En la nube": "In the cloud",
  "LA DE LA NUBE": "THE CLOUD ONE",
  "LA DE ESTE APARATO": "THIS DEVICE'S",
  "El enlace no vale o ha caducado. Pide otro.": "The link isn't valid or has expired. Ask for a new one.",
  "Listo: tu progreso se guarda en tu cuenta.": "Done: your progress is saved to your account.",
  "No se ha podido entrar. Prueba otra vez.": "Couldn't sign in. Try again.",
  "No ha salido bien: {m}": "That didn't work: {m}",
  "ENVIAR": "SEND",
  "Ese email no parece bien escrito": "That email doesn't look right",
  "Para guardar tu cuenta tienes que tener 14 años o más. Si eres menor, pide a tu padre, madre o tutor que lo haga contigo.": "To save your account you must be 14 or older. If you're younger, ask your parent or guardian to do it with you.",
  "Cuenta": "Account",
  "Te hemos enviado un enlace a {e}. Ábrelo en este aparato para terminar.": "We've sent a link to {e}. Open it on this device to finish.",
  "Tu progreso se guarda como invitado, solo en este navegador. Guárdalo con tu email para no perderlo y jugar en otros aparatos.": "Your progress is saved as a guest, only in this browser. Save it with your email so you don't lose it and can play on other devices.",
  "GUARDAR CON EMAIL": "SAVE WITH EMAIL",
  "GUARDAR TU PROGRESO": "SAVE YOUR PROGRESS",
  "Te mandaremos un enlace, sin contraseña. Al abrirlo, tu progreso queda guardado en tu cuenta.": "We'll send you a link, no password. When you open it, your progress is saved to your account.",
  "Mira tu correo y abre el enlace": "Check your email and open the link",
  "YA TENGO CUENTA": "I HAVE AN ACCOUNT",
  "ENTRAR EN TU CUENTA": "SIGN IN TO YOUR ACCOUNT",
  "Te mandaremos un enlace para entrar. Si aquí también has jugado, después te preguntaremos con qué partida sigues.": "We'll send you a link to sign in. If you've also played here, we'll then ask which save you want to keep.",
  "No hay ninguna cuenta con ese email": "There's no account with that email",
  "Tu progreso se guarda en tu cuenta {e}: puedes jugar en cualquier aparato.": "Your progress is saved to your account {e}: you can play on any device.",
  "CERRAR SESIÓN": "SIGN OUT",
  "¿CERRAR SESIÓN?": "SIGN OUT?",
  "Tu progreso sigue en tu cuenta y en este aparato. Para recuperarlo en otro, usa «Ya tengo cuenta».": "Your progress stays in your account and on this device. To get it back on another one, use \"I have an account\".",
  "Sesión cerrada": "Signed out",
  "BORRAR CUENTA": "DELETE ACCOUNT",
  "¿BORRAR TU CUENTA?": "DELETE YOUR ACCOUNT?",
  "Se borran tu cuenta y tus partidas en la nube, de todos los juegos. Lo que hay en este aparato se queda.": "Your account and your cloud saves for all games are deleted. What's on this device stays.",
  "No se puede deshacer.": "This can't be undone.",
  "Cuenta borrada": "Account deleted",
  "<b>CUENTA</b>: tu progreso se guarda ahora también en la nube, sin que tengas que hacer nada. En Opciones → Cuenta puedes guardarlo con tu email (sin contraseña) para no perderlo y seguir jugando en otro móvil o PC.": "<b>ACCOUNT</b>: your progress is now also saved in the cloud, without you doing anything. In Options → Account you can save it with your email (no password) so you never lose it and can keep playing on another phone or PC.",
  "Si juegas en dos aparatos y las dos partidas cambian, el juego te pregunta con cuál sigues.": "If you play on two devices and both saves change, the game asks you which one to keep.",
  "Microblizz guarda tu partida en «la nube». Por lo visto, la nube es el ordenador de otro.": "Microblizz keeps your save in «the cloud». Apparently, the cloud is someone else's computer.",
  // Biblioteca (v0.9.31)
  "BIBLIOTECA": "LIBRARY",
  "Biblioteca": "Library",
  "Objetos": "Items",
  "Lo tengo": "I have it",
  "Me falta": "Missing",
  "Tienes %#1 de %#2 habilidades.": "You have %1 of %2 abilities.",
  "Tienes %#1 de %#2 objetos.": "You have %1 of %2 items.",
  "Toca una para ver qué hace.": "Tap one to see what it does.",
  "Toca uno para ver qué hace.": "Tap one to see what it does.",
  "Aún no tienes ninguno: salen en el gashapón.": "You don't have any yet: they come from the gashapon.",
  "¡Lo tienes todo!": "You have everything!",
  "Del pase": "From the pass",
  "Solo %1": "Only %1",
  "TE FALTA": "MISSING",
  "HABILIDAD": "ABILITY",
  "OBJETO": "ITEM",
  "Según la calidad de la copia:": "Depending on the copy's quality:",
  "Tienes %1 copias.": "You have %1 copies.",
  "Tienes 1 copia.": "You have 1 copy.",
  "Sin usar": "Unused",
  "Te falta. Es un premio del pase: no sale en el gashapón.": "Missing. It's a battle pass reward: it doesn't come from the gashapon.",
  "Te falta. Sale en el gashapón.": "Missing. It comes from the gashapon.",
  "IR AL GASHAPÓN": "GO TO THE GASHAPON",
  "<b>ARREGLADO</b>: el botón Misiones no abría las misiones diarias.": "<b>FIXED</b>: the Missions button didn't open the daily missions.",
  "<b>BIBLIOTECA</b>: un botón nuevo en el menú con todas las habilidades y objetos del juego. Ves de un vistazo cuáles tienes (y cuántas copias), cuáles te faltan y qué hace cada uno. Puedes filtrar por «Lo tengo» y «Me falta».": "<b>LIBRARY</b>: a new menu button with every ability and item in the game. See at a glance which ones you have (and how many copies), which ones you're missing and what each one does. You can filter by «I have it» and «Missing».",
  "Microblizz ha catalogado todo lo que no te va a tocar en el gashapón. Es una lista larga.": "Microblizz has catalogued everything you won't get from the gashapon. It's a long list.",
  // Descripciones de habilidades y objetos partidas por su número (las de los dos juegos)
  "% de sus golpes son críticos (triple) y +": "% of its hits are critical (triple) and +",
  "% de vida y recibe un": "% health and takes",
  "% más rápido y +": "% faster and +",
  "Ataca un": "Attacks",
  "Cada 9 s aturde": "Every 9 s, stuns nearby enemies for",
  "Esquiva el": "Dodges",
  "Los primeros": "For the first",
  "Recibe un": "Takes",
  "Revive una vez con el": "Revives once with",
  "Se cura un": "Heals",
  "Sus golpes frenan al enemigo": "Its hits slow the enemy for",
  "s a los enemigos cercanos.": "s.",
  "s va al triple de velocidad.": "s it moves at triple speed.",
  "<b>INGLÉS</b>: las descripciones de habilidades y objetos ya salen enteras en inglés (antes se quedaban trozos en español).": "<b>ENGLISH</b>: ability and item descriptions are now fully in English (some bits used to stay in Spanish).",
  "Microblizz ha despedido al becario de traducción. Lo ha sustituido otro becario.": "Microblizz fired the translation intern. They replaced them with another intern.",
  "<b>MENÚ</b>: colores más ordenados. Naranja para jugar, violeta para los modos de juego y dorado para conseguir cosas (gashapón y tienda). Los iconos de abajo, todos en dorado.": "<b>MENU</b>: tidier colours. Orange to play, violet for game modes and gold for getting stuff (gashapon and shop). The icons at the bottom are all gold now.",
  "Microblizz ha contratado a un consultor de color. Cobró por decir «menos colores».": "Microblizz hired a colour consultant. They got paid to say «fewer colours».",
  "<b>MENÚ</b>: los iconos de abajo vuelven a tener color, ahora con una paleta que combina: coral, naranja, dorado y violeta.": "<b>MENU</b>: the bottom icons have colour again, now with a palette that matches: coral, orange, gold and violet.",
  "El consultor de color de Microblizz ha cambiado de opinión. Ha vuelto a cobrar.": "Microblizz's colour consultant changed their mind. They got paid again.",
  // v0.9.38: el modo pruebas común (core/js/sistema/pruebas.js)
  "Las cartas al nivel 10, todas las habilidades y objetos perfectos, toda la campaña con 3 estrellas, 3.000.000 de oro y 5.000 gemas. Guarda una copia de tu partida para volver a ella.": "Cards at level 10, every ability and item perfect, the whole campaign with 3 stars, 3,000,000 gold and 5,000 gems. It keeps a copy of your save so you can go back to it.",
  "QUITAR MODO PRUEBAS": "TURN OFF TEST MODE",
  "MODO PRUEBAS": "TEST MODE",
  "VOLVER": "BACK",
  "Vuelves a la partida que tenías antes de activarlo, tal como estaba.": "You go back to the save you had before turning it on, exactly as it was.",
  "Lo que hayas hecho en el modo pruebas se pierde.": "Whatever you did in test mode is lost.",
  "Todo abierto y al máximo: las cartas al nivel 10, todas las habilidades y objetos con calidad perfecta y toda la campaña con 3 estrellas. Y 3.000.000 de oro y 5.000 gemas.": "Everything unlocked and maxed out: cards at level 10, every ability and item at perfect quality and the whole campaign with 3 stars. Plus 3,000,000 gold and 5,000 gems.",
  "Antes se guarda una copia de tu partida. Para volver a ella, toca QUITAR en este mismo botón.": "A copy of your save is kept first. To go back to it, tap REMOVE on this same button.",
  "Tienes la cuenta abierta: el modo pruebas también se guarda en la nube y lo verás en tus otros aparatos hasta que lo quites aquí.": "You're signed in: test mode is also saved to the cloud and you'll see it on your other devices until you turn it off here.",
  "Modo pruebas activado: todo al máximo": "Test mode on: everything maxed out",
  "No se ha podido volver a tu partida": "Couldn't go back to your save",
  "<b>MODO PRUEBAS</b> (en Opciones): ahora lo da todo al máximo. Las cartas suben solas al nivel 10, tienes todas las habilidades y objetos con calidad perfecta y toda la campaña con 3 estrellas. Antes guarda una copia de tu partida: con QUITAR vuelves a ella tal como estaba.": "<b>TEST MODE</b> (in Options): now it maxes everything out. Cards go straight to level 10, you get every ability and item at perfect quality and the whole campaign with 3 stars. It keeps a copy of your save first: REMOVE takes you back to it exactly as it was.",
  "Microblizz llama a esto «edición coleccionista». Los demás lo llamamos trampas.": "Microblizz calls this the «collector's edition». Everyone else calls it cheating.",
  "<b>RECURSOS</b>: por dentro, el oro, las gemas y las entradas pasan ahora por un solo sitio. No cambia nada de lo que ves, pero prepara el guardado de tu cuenta en la nube y la futura tienda.": "<b>RESOURCES</b>: behind the scenes, gold, gems and tickets now go through a single place. Nothing you see changes, but it prepares saving your account in the cloud and the future shop.",
  "Microblizz asegura que ahora cuida mejor de tus recursos. De los suyos ya se encargaba su contable.": "Microblizz swears it now takes better care of your resources. Its accountant already took care of its own.",
  "<b>AVISO IMPORTANTE</b>: abre el juego con conexión antes del <b>21 de octubre</b> para subir tu progreso actual (oro, gemas, objetos y niveles) a tu cuenta. Pasada esa fecha, una partida antigua que no se haya subido ya no podrá subirse: seguirá en tu aparato, pero tu cuenta empezará desde cero.": "<b>IMPORTANT NOTICE</b>: open the game while online before <b>21 October</b> to upload your current progress (gold, gems, items and levels) to your account. After that date, an old save that hasn't been uploaded can no longer be uploaded: it stays on your device, but your account will start from zero.",
  "Microblizz recuerda que las fechas límite son como sus promesas: se acercan solas.": "Microblizz reminds you that deadlines are like its promises: they approach on their own.",
  "<b>TU ECONOMÍA EN LA NUBE</b>: con tu cuenta, el gashapón, despedir copias, volver a tirar sus números y subir de nivel las cartas los hace nuestro servidor, y tu oro y tus gemas quedan guardados en ella. Para hacerlo hace falta conexión.": "<b>YOUR ECONOMY IN THE CLOUD</b>: with your account, the gashapon, scrapping copies, rerolling their numbers and levelling up cards are now done by our server, and your gold and gems are saved in it. You need a connection to do it.",
  "El servidor de Microblizz ya cuenta tu oro. Dice que le sobra tiempo desde que dejó de contar el suyo.": "Microblizz's server now counts your gold. It says it has spare time since it stopped counting its own.",
  "<b>JUEGO LIMPIO</b>: las recompensas, el gashapón y las compras se validan en nuestro servidor, y vigilamos las trampas. Quien las haga puede perder ventajas o su cuenta. Gracias por jugar limpio.": "<b>FAIR PLAY</b>: rewards, the gashapon and purchases are validated on our server, and we watch for cheating. Anyone who cheats may lose advantages or their account. Thanks for playing fair.",
  "Microblizz también vigila a su plantilla. De momento sin éxito.": "Microblizz also monitors its staff. No success so far.",
  "GUARDAR CON GOOGLE": "SAVE WITH GOOGLE",
  "ENTRAR CON GOOGLE": "SIGN IN WITH GOOGLE",
  "CONTINUAR": "CONTINUE",
  "Entrarás con tu cuenta de Google y tu progreso quedará guardado en ella.": "You will sign in with your Google account and your progress will be saved in it.",
  "Privacidad": "Privacy",
  "Condiciones de uso": "Terms of use",
  "<b>PRIVACIDAD Y CONDICIONES</b>: ya puedes leer cómo guardamos tu progreso y las reglas del juego, en Opciones → Cuenta y en la página de inicio.": "<b>PRIVACY AND TERMS</b>: you can now read how we keep your progress and the rules of the game, in Options → Account and on the home page.",
  "Microblizz asegura que sus condiciones de uso son cortas. El departamento legal dice que es lo único corto que tiene.": "Microblizz says its terms of use are short. Legal says it is the only short thing they have.",
  "PROBABILIDADES DEL GASHAPÓN": "GACHA ODDS",
  "Son las probabilidades reales de cada tirada, sin contar las garantías. Las calcula el servidor con las mismas cifras que se enseñan aquí. Comprar gemas o oro no cambia ninguna.": "These are the real odds of each pull, not counting the guarantees. The server uses the same figures shown here. Buying gems or gold doesn't change any of them.",
  "<b>PROBABILIDADES A LA VISTA</b>: la tienda tiene una sección con las probabilidades reales del gashapón, objeto por objeto.": "<b>ODDS IN PLAIN SIGHT</b>: the shop has a section with the real gacha odds, item by item.",
  "Microblizz jura que los porcentajes siempre estuvieron a la vista. Debajo de la letra pequeña, eso sí.": "Microblizz swears the percentages were always in plain sight. Under the fine print, admittedly.",
  "OBJETOS DE EQUIPO": "EQUIPMENT ITEMS",
  "Rareza": "Rarity",
  "Probabilidad": "Chance",
  "Objeto": "Item",
  "Calidad": "Quality",
  "%1: cada objeto": "%1: each item",
  "CALIDAD DE CADA COPIA": "QUALITY OF EACH COPY",
  "En el equipo, la mitad de las veces sale un objeto de una facción que ya tienes (si tienes alguna) y la otra mitad uno general.": "For equipment, half of the time you get an item from a faction you already have (if you have any) and the other half a general one.",
  "Solo salen cartas de las facciones que ya tienes.": "Only cards from factions you already have can come up.",
  "<b>ENTRA CON GOOGLE</b>: ya puedes guardar tu progreso con tu cuenta de Google (Opciones → Cuenta). Ahora está en pruebas: escribe a fansofmicroblizz@gmail.com con tu correo de Google y te añadimos a mano.": "<b>SIGN IN WITH GOOGLE</b>: you can now save your progress with your Google account (Options → Account). It is in testing for now: email fansofmicroblizz@gmail.com with your Google address and we will add you by hand.",
  "Microblizz se compromete a abrir el acceso con Google a todo el mundo en menos de un año. Tiene la firma de un becario.": "Microblizz promises to open Google sign-in to everyone in under a year. It has the intern's signature.",
});
