// Fans Of · Inglés de lo común (extra): lo que no cabía en los otros diccionarios.
'use strict';
IDIOMA.add({
  "COBRAR TODO%10": "CLAIM ALL%10",
  "Campero": "Camper",
  "Automático (el idioma del navegador)": "Automatic (the browser's language)",
  "torre": "tower",
  "unidad": "unit",
  "laberinto": "maze",
  "9 razas": "9 races",
  "12 mundos": "12 worlds",
  "Versión %1": "Version %1",
  "¿QUÉ PARTIDA QUIERES?": "WHICH SAVE DO YOU WANT?",
  "Has jugado en este aparato y en otro, y las dos partidas han cambiado. Elige con cuál sigues; la otra se pierde.": "You've played on this device and on another one, and both saves have changed. Choose which one to keep; the other one is lost.",
  "En este aparato": "On this device",
  "En la nube": "In the cloud",
  "LA DE LA NUBE": "THE CLOUD ONE",
  "LA DE ESTE APARATO": "THIS DEVICE'S",
  "El enlace no vale o ha caducado. Pide otro.": "The link isn't valid or has expired. Ask for a new one.",
  "Listo: tu progreso se guarda en tu cuenta.": "Done: your progress is saved to your account.",
  "No se ha podido entrar. Prueba otra vez.": "Couldn't sign in. Try again.",
  "No ha salido bien: {m}": "That didn't work: {m}",
  "ENVIAR": "SEND",
  "Ese email no parece bien escrito": "That email doesn't look right",
  "Para guardar tu cuenta tienes que tener 14 años o más. Si eres menor, pide a tu padre, madre o tutor que lo haga contigo.": "To save your account you must be 14 or older. If you're younger, ask your parent or guardian to do it with you.",
  "Cuenta": "Account",
  "Te hemos enviado un enlace a {e}. Ábrelo en este aparato para terminar.": "We've sent a link to {e}. Open it on this device to finish.",
  "Tu progreso se guarda como invitado, solo en este navegador. Guárdalo con tu email para no perderlo y jugar en otros aparatos.": "Your progress is saved as a guest, only in this browser. Save it with your email so you don't lose it and can play on other devices.",
  "GUARDAR CON EMAIL": "SAVE WITH EMAIL",
  "GUARDAR TU PROGRESO": "SAVE YOUR PROGRESS",
  "Te mandaremos un enlace, sin contraseña. Al abrirlo, tu progreso queda guardado en tu cuenta.": "We'll send you a link, no password. When you open it, your progress is saved to your account.",
  "Mira tu correo y abre el enlace": "Check your email and open the link",
  "YA TENGO CUENTA": "I HAVE AN ACCOUNT",
  "ENTRAR EN TU CUENTA": "SIGN IN TO YOUR ACCOUNT",
  "Te mandaremos un enlace para entrar. Si aquí también has jugado, después te preguntaremos con qué partida sigues.": "We'll send you a link to sign in. If you've also played here, we'll then ask which save you want to keep.",
  "No hay ninguna cuenta con ese email": "There's no account with that email",
  "Tu progreso se guarda en tu cuenta {e}: puedes jugar en cualquier aparato.": "Your progress is saved to your account {e}: you can play on any device.",
  "CERRAR SESIÓN": "SIGN OUT",
  "¿CERRAR SESIÓN?": "SIGN OUT?",
  "Tu progreso sigue en tu cuenta y en este aparato. Para recuperarlo en otro, usa «Ya tengo cuenta».": "Your progress stays in your account and on this device. To get it back on another one, use \"I have an account\".",
  "Sesión cerrada": "Signed out",
  "BORRAR CUENTA": "DELETE ACCOUNT",
  "¿BORRAR TU CUENTA?": "DELETE YOUR ACCOUNT?",
  "Se borran tu cuenta y tus partidas en la nube, de todos los juegos. Lo que hay en este aparato se queda.": "Your account and your cloud saves for all games are deleted. What's on this device stays.",
  "No se puede deshacer.": "This can't be undone.",
  "Cuenta borrada": "Account deleted",
  "<b>CUENTA</b>: tu progreso se guarda ahora también en la nube, sin que tengas que hacer nada. En Opciones → Cuenta puedes guardarlo con tu email (sin contraseña) para no perderlo y seguir jugando en otro móvil o PC.": "<b>ACCOUNT</b>: your progress is now also saved in the cloud, without you doing anything. In Options → Account you can save it with your email (no password) so you never lose it and can keep playing on another phone or PC.",
  "Si juegas en dos aparatos y las dos partidas cambian, el juego te pregunta con cuál sigues.": "If you play on two devices and both saves change, the game asks you which one to keep.",
  "Microblizz guarda tu partida en «la nube». Por lo visto, la nube es el ordenador de otro.": "Microblizz keeps your save in «the cloud». Apparently, the cloud is someone else's computer.",
  // Biblioteca (v0.9.31)
  "BIBLIOTECA": "LIBRARY",
  "Biblioteca": "Library",
  "Objetos": "Items",
  "Lo tengo": "I have it",
  "Me falta": "Missing",
  "Tienes %#1 de %#2 habilidades.": "You have %1 of %2 abilities.",
  "Tienes %#1 de %#2 objetos.": "You have %1 of %2 items.",
  "Toca una para ver qué hace.": "Tap one to see what it does.",
  "Toca uno para ver qué hace.": "Tap one to see what it does.",
  "Aún no tienes ninguno: salen en el gashapón.": "You don't have any yet: they come from the gashapon.",
  "¡Lo tienes todo!": "You have everything!",
  "Del pase": "From the pass",
  "Solo %1": "Only %1",
  "TE FALTA": "MISSING",
  "HABILIDAD": "ABILITY",
  "OBJETO": "ITEM",
  "Según la calidad de la copia:": "Depending on the copy's quality:",
  "Tienes %1 copias.": "You have %1 copies.",
  "Tienes 1 copia.": "You have 1 copy.",
  "Sin usar": "Unused",
  "Te falta. Es un premio del pase: no sale en el gashapón.": "Missing. It's a battle pass reward: it doesn't come from the gashapon.",
  "Te falta. Sale en el gashapón.": "Missing. It comes from the gashapon.",
  "IR AL GASHAPÓN": "GO TO THE GASHAPON",
  "<b>ARREGLADO</b>: el botón Misiones no abría las misiones diarias.": "<b>FIXED</b>: the Missions button didn't open the daily missions.",
  "<b>BIBLIOTECA</b>: un botón nuevo en el menú con todas las habilidades y objetos del juego. Ves de un vistazo cuáles tienes (y cuántas copias), cuáles te faltan y qué hace cada uno. Puedes filtrar por «Lo tengo» y «Me falta».": "<b>LIBRARY</b>: a new menu button with every ability and item in the game. See at a glance which ones you have (and how many copies), which ones you're missing and what each one does. You can filter by «I have it» and «Missing».",
  "Microblizz ha catalogado todo lo que no te va a tocar en el gashapón. Es una lista larga.": "Microblizz has catalogued everything you won't get from the gashapon. It's a long list.",
  // Descripciones de habilidades y objetos partidas por su número (las de los dos juegos)
  "% de sus golpes son críticos (triple) y +": "% of its hits are critical (triple) and +",
  "% de vida y recibe un": "% health and takes",
  "% más rápido y +": "% faster and +",
  "Ataca un": "Attacks",
  "Cada 9 s aturde": "Every 9 s, stuns nearby enemies for",
  "Esquiva el": "Dodges",
  "Los primeros": "For the first",
  "Recibe un": "Takes",
  "Revive una vez con el": "Revives once with",
  "Se cura un": "Heals",
  "Sus golpes frenan al enemigo": "Its hits slow the enemy for",
  "s a los enemigos cercanos.": "s.",
  "s va al triple de velocidad.": "s it moves at triple speed.",
  "<b>INGLÉS</b>: las descripciones de habilidades y objetos ya salen enteras en inglés (antes se quedaban trozos en español).": "<b>ENGLISH</b>: ability and item descriptions are now fully in English (some bits used to stay in Spanish).",
  "Microblizz ha despedido al becario de traducción. Lo ha sustituido otro becario.": "Microblizz fired the translation intern. They replaced them with another intern.",
  "<b>MENÚ</b>: colores más ordenados. Naranja para jugar, violeta para los modos de juego y dorado para conseguir cosas (gashapón y tienda). Los iconos de abajo, todos en dorado.": "<b>MENU</b>: tidier colours. Orange to play, violet for game modes and gold for getting stuff (gashapon and shop). The icons at the bottom are all gold now.",
  "Microblizz ha contratado a un consultor de color. Cobró por decir «menos colores».": "Microblizz hired a colour consultant. They got paid to say «fewer colours».",
});
