// Fans Of · Inglés: frases y emoticonos (core/js/frases.js y frases-arte.js): la pestaña del armario, el pase y el premio
'use strict';
IDIOMA.add({
  "FRASES": "PHRASES",
  "LLEVAS PUESTAS": "EQUIPPED",
  "EMOTICONOS": "EMOTES",
  "PUESTA": "EQUIPPED",
  "FRASE": "PHRASE",
  "EMOTICONO": "EMOTE",
  "Las que llevas puestas salen en la partida. Toca una de abajo para cambiarla por otra.": "The ones you have equipped show up in battle. Tap one below to swap it in.",
  "Toca la frase de arriba que quieres cambiar. Toca otra vez para cancelar.": "Tap the phrase above you want to replace. Tap again to cancel.",
  "Toca la casilla de arriba que quieres cambiar. Toca otra vez para cancelar.": "Tap the slot above you want to replace. Tap again to cancel.",
  "Ya la llevas puesta": "You already have it equipped",
  "Ya lo llevas puesto": "You already have it equipped",
  "Toca una frase de abajo para ponerla aquí": "Tap a phrase below to put it here",
  "Toca un emoticono de abajo para ponerlo aquí": "Tap an emote below to put it here",
  "¡FRASE NUEVA!": "NEW PHRASE!",
  "¡EMOTICONO NUEVO!": "NEW EMOTE!",
  "¡PONÉRMELA!": "EQUIP IT!",
  "la frase «%1»": "the phrase «%1»",
  "el emoticono %1": "the emote %1",
  "Las frases y los emoticonos se usan en la partida con el botón del bocadillo.": "Phrases and emotes are used in battle with the speech bubble button.",
  "JA": "HA",
  "BUAA": "WAAH",
  "MUUU": "MOOO",
  "EN VIVO": "LIVE",
  "BIP": "BEEP",
  "BUP": "BOOP",
  "¡AAAH!": "AAAH!",
  "MEJORAS POR DENTRO": "IMPROVEMENTS UNDER THE HOOD",
  ": el pase ya sabe dar frases y emoticonos, que estrenan los Animales Locos en Fans of Rumble. Aquí no cambia nada… de momento.": ": the pass can now give out phrases and emotes, which the Crazy Animals debut in Fans of Rumble. Nothing changes here… for now.",
  "Microblizz ha descubierto que puede vender frases hechas. Ha mandado a todo el departamento de marketing a buscar más.": "Microblizz has found out it can sell stock phrases. It has sent the whole marketing department to find more.",
});
