// Fans Of · Inglés: los pases (temporada y PvP) y el armario (marcos y títulos)
'use strict';
IDIOMA.add({
  // pase
  "TEMPORADA": "SEASON",
  "PVP": "PVP",
  "NIVEL": "LEVEL",
  "%1 niveles": "%1 levels",
  "termina hoy": "ends today",
  "termina mañana": "ends tomorrow",
  "termina en %1 días": "ends in %1 days",
  "La temporada ha terminado: cobra lo que te falte.": "The season is over: claim whatever you have left.",
  "Pase Ejecutivo": "Executive Pass",
  "Pase Ejecutivo ✓": "Executive Pass ✓",
  "Pase del Pase": "Pass of the Pass",
  "Pase del Pase ✓": "Pass of the Pass ✓",
  "PASE EJECUTIVO": "EXECUTIVE PASS",
  "PASE DEL PASE": "PASS OF THE PASS",
  "PASE DEL PASE ✓": "PASS OF THE PASS ✓",
  "EJECUTIVO": "EXECUTIVE",
  "EJECUTIVO ✓": "EXECUTIVE ✓",
  "Próximo premio gordo:": "Next big prize:",
  "Próximo premio gordo: nivel %1": "Next big prize: level %1",
  "nivel %1": "level %1",
  "(Pase Ejecutivo)": "(Executive Pass)",
  "(Pase del Pase)": "(Pass of the Pass)",
  "Partida PvP": "PvP match",
  "Ganar": "Win",
  "Juego limpio: aquí todo es para lucirse": "Fair play: everything here is just for show",
  "GRATIS": "FREE",
  "CAPÍTULO %1": "CHAPTER %1",
  "Completado ✓": "Completed ✓",
  "Niveles %1 a %2": "Levels %1 to %2",
  "MARCO": "FRAME",
  "TÍTULO": "TITLE",
  "OBJETO EXCLUSIVO": "EXCLUSIVE ITEM",
  "Cobrado": "Claimed",
  "Llega al nivel %1 para cobrarlo": "Reach level %1 to claim it",
  "Marco %1": "%1 frame",
  "el marco %1": "the %1 frame",
  "el título «%1»": "the title «%1»",
  "¡PASE COMPLETADO!": "PASS COMPLETED!",
  "¡Ya tienes el Pase del Pase! (sin cobrar nada)": "You've got the Pass of the Pass! (no charge)",
  "Versión de prueba: no se cobra nada. Vale para esta temporada.": "Test version: nothing is charged. Valid for this season.",
  "El": "The",
  ": porque un pase solo no bastaba.": ": because one pass wasn't enough.",
  "para presumir en el PvP, más oro y gemas. No da ninguna ventaja en la partida.": "to show off in PvP, plus more gold and gems. It gives no advantage in the match.",
  "más oro y gemas. No da ninguna ventaja en la partida.": "more gold and gems. It gives no advantage in the match.",
  "Desbloquea la pista Ejecutiva de la %1: más oro, gemas, tiradas gratis": "Unlocks the Executive track of %1: more gold, gems, free pulls",
  "Desbloquea la pista Ejecutiva de la %1: más oro, gemas, tiradas gratis,": "Unlocks the Executive track of %1: more gold, gems, free pulls,",
  "Desbloquea la pista Ejecutiva de la %1: más oro, gemas, tiradas gratis, ": "Unlocks the Executive track of %1: more gold, gems, free pulls, ",
  "y la": "and the",
  ", exclusiva.": ", exclusive.",
  "%1 marcos y %2 títulos": "%1 frames and %2 titles",
  "%1 marcos": "%1 frames",
  "%1 títulos": "%1 titles",
  "1 marco": "1 frame",
  "1 título": "1 title",
  "Temporada · nivel %1": "Season · level %1",
  "Ejecutivo · nivel %1": "Executive · level %1",
  "Pase PvP · nivel %1": "PvP Pass · level %1",
  "Pase del Pase · nivel %1": "Pass of the Pass · level %1",
  "Pase PvP: +%1 puntos": "PvP Pass: +%1 points",
  // armario
  "ARMARIO": "WARDROBE",
  "✏️ NOMBRE": "✏️ NAME",
  "TU ASPECTO": "YOUR LOOK",
  "MARCOS": "FRAMES",
  "TÍTULOS": "TITLES",
  "Sin título": "No title",
  "Toca para no llevar ninguno": "Tap to wear none",
  "No llevas ninguno": "You aren't wearing one",
  "PUESTO": "EQUIPPED",
  "¡NUEVO!": "NEW!",
  "Solo para lucirse: no dan ninguna ventaja en las partidas. Se ganan en los pases.": "Just for show: they give no advantage in matches. You earn them in the passes.",
  "¡MARCO NUEVO!": "NEW FRAME!",
  "¡TÍTULO NUEVO!": "NEW TITLE!",
  "¡PONÉRMELO!": "WEAR IT!",
  "LUEGO": "LATER",
  "Y 1 cosa más para tu armario.": "And 1 more thing for your wardrobe.",
  "Y %1 cosas más para tu armario.": "And %1 more things for your wardrobe.",
  "Llevas el marco %1": "You're wearing the %1 frame",
  "Ahora eres «%1»": "Now you are «%1»",
  "Próximamente": "Coming soon",
  "FRÁGIL": "FRAGILE",
});
