// Fans Of · Inglés del Salón de la Fama (core/js/clasificacion.js).
'use strict';
IDIOMA.add({
  "SALÓN DE LA FAMA": "HALL OF FAME",
  "Salón de la Fama": "Hall of Fame",
  "RANKING": "RANKING",
  "Clasificación": "Ranking",
  "OBRAS": "WIP",
  "(tú)": "(you)",
  "Contando a los fans…": "Counting the fans…",
  "Microblizz está comprobando que nadie haya pagado por subir. Todavía.": "Microblizz is checking that nobody paid to climb. Yet.",
  "Microblizz está comprobando que nadie haya pagado por subir.": "Microblizz is checking that nobody paid to climb.",
  "Todavía.": "Yet.",
  "SIN CONEXIÓN": "OFFLINE",
  "NO SE HA PODIDO CARGAR": "COULDN'T LOAD IT",
  "El Salón de la Fama vive en los servidores de Microblizz y ahora mismo no los encontramos. Probablemente los estén vendiendo.": "The Hall of Fame lives on Microblizz's servers and right now we can't find them. They're probably being sold.",
  "El Salón de la Fama vive en los servidores de Microblizz y ahora mismo no los encontramos.": "The Hall of Fame lives on Microblizz's servers and right now we can't find them.",
  "Probablemente los estén vendiendo.": "They're probably being sold.",
  "Los servidores de Microblizz no responden. Han dicho que vuelven en cinco minutos, como siempre.": "Microblizz's servers aren't answering. They said they'll be back in five minutes, as always.",
  "Los servidores de Microblizz no responden.": "Microblizz's servers aren't answering.",
  "Han dicho que vuelven en cinco minutos, como siempre.": "They said they'll be back in five minutes, as always.",
  "REINTENTAR": "TRY AGAIN",
  "EL SALÓN ESTÁ VACÍO": "THE HALL IS EMPTY",
  "Nadie ha entrado todavía. Es tu oportunidad de ser el número 1 sin tener que pagar a nadie.": "Nobody has made it in yet. It's your chance to be number 1 without paying anyone.",
  "Nadie ha entrado todavía.": "Nobody has made it in yet.",
  "Es tu oportunidad de ser el número 1 sin tener que pagar a nadie.": "It's your chance to be number 1 without paying anyone.",
  "Y %1 fans más intentándolo.": "And %1 more fans trying.",
  "Aún no estás en el Salón": "You're not in the Hall yet",
  "EN CONSTRUCCIÓN": "UNDER CONSTRUCTION",
  "Toca el cartel para otra excusa": "Tap the sign for another excuse",
  "Otra excusa": "Another excuse",
  "PRÓXIMAMENTE™": "COMING SOON™",
  "PRÓXIMAMENTE™ · PRÓXIMAMENTE™ · PRÓXIMAMENTE™ · PRÓXIMAMENTE™": "COMING SOON™ · COMING SOON™ · COMING SOON™ · COMING SOON™",
  "Obra patrocinada por Microblizz · Presupuesto: tres conos y un becario": "Works sponsored by Microblizz · Budget: three cones and an intern",
  "Obra patrocinada por Microblizz": "Works sponsored by Microblizz",
  "Presupuesto: tres conos y un becario": "Budget: three cones and an intern",
  // las excusas del cartel (SALON_EXCUSAS)
  "Para acelerar las obras hemos tomado una decisión valiente: despedir al equipo que hacía las obras.": "To speed up the works we made a brave decision: we fired the team doing the works.",
  "Fecha de apertura: Pronto™. Es el mismo Pronto™ que prometimos en 2019, pero ahora con más sinergias.": "Opening date: Soon™. It's the same Soon™ we promised in 2019, but now with more synergies.",
  "Puedes reservar tu primer puesto por solo 19,99 €. No te garantiza nada, pero te da una sensación muy agradable.": "You can pre-order first place for just €19.99. It guarantees nothing, but it feels really nice.",
  "Nuestros mejores ingenieros están trabajando en ello. Bueno, uno. Es el becario. Está de vacaciones.": "Our best engineers are working on it. Well, one. It's the intern. He's on vacation.",
  "Esta sección ha sido adquirida por Microblizz por 69.000 millones. Su único cambio: ahora tiene el logo más grande.": "This section was acquired by Microblizz for 69 billion. The only change: the logo is bigger now.",
  "Hemos encargado un estudio de 400 páginas para decidir de qué color pintar el cartel. Ha salido amarillo.": "We commissioned a 400-page study to decide what color to paint the sign. It came out yellow.",
  "Los premios ya están comprados. Los hemos guardado en una caja de botín: te tocarán con un 0,03 % de probabilidad.": "The rewards are already bought. We put them in a loot box: you'll get them with a 0.03% chance.",
  "Hemos contratado a una consultora para acabar antes. Su primera recomendación: una reunión para planificar la siguiente reunión.": "We hired a consultancy to finish sooner. Their first recommendation: a meeting to plan the next meeting.",
  "Las obras van según lo previsto. Lo previsto era no acabar nunca.": "The works are going as planned. The plan was to never finish.",
  "Para que esto abra antes, puedes comprar el Pase de Obras Premium. Incluye un casco amarillo (cosmético, no protege).": "To open this sooner, you can buy the Premium Works Pass. It includes a yellow hard hat (cosmetic, offers no protection).",
  "El cartel ha costado más que todo lo que hay detrás. Prioridades.": "The sign cost more than everything behind it. Priorities.",
  "Retraso causado por factores externos: el becario ha encontrado otro trabajo. Con sueldo.": "Delay caused by external factors: the intern found another job. A paid one.",
  "Estamos escuchando a la comunidad. Y la comunidad pide que acabemos. Seguimos escuchando.": "We're listening to the community. And the community is asking us to finish. We're still listening.",
  "Microblizz anuncia una versión remasterizada de esta obra. Es la misma, pero con el cartel en 4K.": "Microblizz announces a remastered version of these works. Same works, but the sign is in 4K.",
  "Toda la información sobre la apertura se dará en la MicroBlizzCon. Las entradas cuestan 300 €.": "All the opening details will be revealed at MicroBlizzCon. Tickets cost €300.",
});
