// Fans Of · Inglés de la serie (2/3): cartas de Gamer, Héroes, Memes, Microblizz, No-Muertos, Olvidados, Phony y Cultura Pop.
'use strict';
IDIOMA.add({
  "La comunidad llena la tienda de reseñas de 1 estrella: las torres y la sede del rival en la zona reciben un 40 % más de daño durante 8 s.": "The community floods the store with 1-star reviews: the rival's towers and HQ in the area take 40 % more damage for 8 s.",
  "Lag horrible: los enemigos de la zona dan un salto hacia atrás y se quedan congelados 1 s.": "Horrible lag: the enemies in the area jump backwards and freeze for 1 s.",
  "Lanza sus juegos en disco (los físicos, los de verdad). Cada disco rebota a otro enemigo cercano.": "Throws her games on disc (the physical ones, the real ones). Each disc bounces to another nearby enemy.",
  "Pierde y se enfada. Al caer, tira el mando y explota: 100 de daño a los enemigos de alrededor.": "Loses and gets angry. When it falls, it throws the controller and explodes: 100 damage to the enemies around.",
  "Ping de 999": "999 Ping",
  "Recreativa": "Arcade Cabinet",
  "Rompe torres": "Tower Breaker",
  "Sale escondido en un arbusto y, cuando ve a un sanador o a un tirador, salta a por él. A esos les hace el doble de daño.": "Comes out hidden in a bush and, when it sees a healer or a shooter, jumps at it. Those take double damage.",
  "Se salta a los enemigos (como en sus partidas) y corre directa a por las torres. Nadie corre más que ella.": "Skips past the enemies (like in her runs) and goes straight for the towers. Nobody runs faster than her.",
  "Tanque + noobs": "Tank + noobs",
  "Tres novatos con gorro de hélice. No saben jugar, pero le ponen muchas ganas.": "Three newbies with propeller hats. They can't play, but they try really hard.",
  "Una lata para todos: cura 120 a tus tropas de la zona y atacan un 30 % más rápido durante 5 s.": "A can for everyone: heals 120 to your troops in the area and they attack 30 % faster for 5 s.",
  "Una máquina arcade con piernas. Aguanta muchísimo y, cuando cae, salen 2 noobs a seguir jugando.": "An arcade machine with legs. It takes a ton of damage and, when it falls, 2 noobs come out to keep playing.",
  "los Gamers": "the Gamers",
  "tu LAN Party": "your LAN Party",
  "¡CRÍTICO! Un golpe enorme en una zona pequeña: 300 de daño.": "CRITICAL! A huge hit on a small area: 300 damage.",
  "Ambrosía": "Ambrosia",
  "Arpía": "Harpy",
  "Blindada": "Armoured",
  "Cada 3 bajas, +5 % de vida y daño a todo tu ejército": "Every 3 kills, +5 % health and damage for your whole army",
  "Cada 8 s grita ¡Team Fight! y todos los aliados cercanos dan a la vez un golpe extra con +50 % de daño.": "Every 8 s she shouts Team Fight! and all nearby allies land an extra hit at the same time with +50 % damage.",
  "Cada 8 s se baja las gafas de sol y petrifica a los enemigos cercanos.": "Every 8 s she lowers her sunglasses and petrifies nearby enemies.",
  "Cada bot que despides da experiencia a todo tu ejército: cada 3 bajas subís de nivel, +5 % de vida y daño, hasta nivel 5.": "Every bot you lay off gives experience to your whole army: every 3 kills you level up, +5 % health and damage, up to level 5.",
  "Dios del trueno: su rayo salta del objetivo a otros 2 enemigos cercanos.": "God of thunder: his lightning jumps from the target to 2 other nearby enemies.",
  "EL TEMPLO": "THE TEMPLE",
  "Embestida": "Charge",
  "La bebida de los dioses: cura 200 a tus tropas de la zona.": "The drink of the gods: heals 200 to your troops in the area.",
  "Lanzas · x3": "Spears · x3",
  "Los dioses publican un parche: los enemigos de la zona encogen y pegan un 40 % menos durante 6 s.": "The gods release a patch: the enemies in the area shrink and hit 40 % less for 6 s.",
  "Mitad pájaro y muy mal humor: vuela por encima de la pelea y cae sobre el sanador o el tirador enemigo. A esos les hace el doble de daño.": "Half bird and in a very bad mood: flies over the fight and swoops on the enemy healer or shooter. Those take double damage.",
  "Mole con hacha doble. Si llega corriendo, su primer golpe hace más del doble y aturde.": "A hulk with a double axe. If it arrives running, its first hit does more than double and stuns.",
  "NIVEL": "LEVEL",
  "Nerfeo divino": "Divine Nerf",
  "Petrifica": "Petrifies",
  "Rayo divino": "Divine Lightning",
  "Tres soldados con escudo y lanza larga. Aguantan bien en grupo.": "Three soldiers with shields and long spears. They hold up well as a group.",
  "Un dios enfadado lanza un rayo: 260 de daño en una zona pequeña.": "An angry god throws a lightning bolt: 260 damage on a small area.",
  "Un querubín con arco que dispara flechas rápidas desde lejos.": "A cherub with a bow that fires fast arrows from afar.",
  "Valquiria con escudo: recibe un 35 % menos de daño. Perfecta para ir delante.": "Valkyrie with a shield: takes 35 % less damage. Perfect for leading the way.",
  "tu Templo": "your Temple",
  "Aplasta": "Crushes",
  "Cada 7 s juega una carta al azar: curación, aturdir, bola de fuego o invocar perros.": "Every 7 s he plays a random card: heal, stun, fireball or summon dogs.",
  "Cada unidad sale con una mutación al azar": "Every unit comes out with a random mutation",
  "Cada unidad sale con una mutación al azar: gigante, turbo, de cristal o normal. Nunca sabes lo que va a salir.": "Every unit comes out with a random mutation: giant, turbo, glass or normal. You never know what you'll get.",
  "Carta viral": "Viral Card",
  "Confusión": "Confusion",
  "Dos perros muy wow. Corren mucho y muerden más.": "Two very wow dogs. They run a lot and bite even more.",
  "EL FORO": "THE FORUM",
  "Ejecutivo que solo ataca edificios: cada golpe pega un 15 % más que el anterior.": "An executive that only attacks buildings: each hit hits 15 % harder than the last.",
  "Like masivo": "Mass Like",
  "Llueven gatos (enfadados): 120 de daño en una zona grande y, a veces, cae uno gordo que hace el doble.": "It's raining cats (angry ones): 120 damage on a big area and, sometimes, a fat one lands that does double.",
  "Lluvia de gatos": "Cat Rain",
  "Mil likes de golpe: curan 140 a tus tropas de una zona grande.": "A thousand likes at once: they heal 140 to your troops in a big area.",
  "Nadie entiende el meme: los enemigos de la zona se pelean entre ellos durante 3 s.": "Nobody gets the meme: the enemies in the area fight each other for 3 s.",
  "Obliga a los enemigos y torres cercanos a atacarle a él. Aguanta y se ríe.": "Forces nearby enemies and towers to attack him. He takes it and laughs.",
  "Provoca": "Taunts",
  "Ráfagas": "Bursts",
  "Rápidos · x2": "Fast · x2",
  "Un gato enorme. Cada 6 s se sienta encima de los enemigos cercanos y los aturde.": "A huge cat. Every 6 s it sits on nearby enemies and stuns them.",
  "tu Foro": "your Forum",
  "«¡NO VAS A CREER A QUIÉN ATACA!»: salta a por el sanador o el tirador enemigo. A esos les hace el doble de daño.": "«YOU WON'T BELIEVE WHO IT ATTACKS!»: jumps at the enemy healer or shooter. Those take double damage.",
  "CajaBotín": "LootBoxBot",
  "Despido fulminante": "Instant Layoff",
  "Parche Día 1": "Day 1 Patch",
  "SoporteBot": "SupportBot",
  "la Sede de Microblizz": "Microblizz HQ",
  "Caballero esqueleto con espada rúnica de hielo: cada golpe frena al enemigo.": "Skeleton knight with a runic ice sword: every hit slows the enemy.",
  "Cada no-muerto revive una vez con el 60 % de su vida": "Every undead revives once with 60 % of its health",
  "Cada no-muerto revive una vez, con el 60 % de su vida, poco después de caer. Los esqueletos invocados no.": "Every undead revives once, with 60 % of its health, shortly after falling. Summoned skeletons don't.",
  "Caen lápidas del cielo: 170 de daño y un pequeño aturdimiento a los enemigos de la zona.": "Tombstones fall from the sky: 170 damage and a short stun to the enemies in the area.",
  "Conserva a tus tropas como nuevas: cura 150 a las de la zona.": "Keeps your troops like new: heals 150 to those in the area.",
  "Cuatro esqueletos piratas, frágiles y muy rápidos. Rodean al enemigo y distraen a las torres.": "Four pirate skeletons, fragile and very fast. They surround the enemy and distract the towers.",
  "Grita cada 7 s y aturde a los enemigos cercanos. Entre grito y grito, lanza ondas que golpean en área.": "Screams every 7 s and stuns nearby enemies. Between screams, it sends out waves that hit an area.",
  "Grito aturde": "Scream stuns",
  "Horas extra eternas": "Eternal Overtime",
  "Invoca": "Summons",
  "LA CRIPTA": "THE CRYPT",
  "Lanza rayos de sombra y cada 8 s levanta 2 esqueletos a su lado. Si cae del todo, vuelve a los 12 s.": "Casts shadow bolts and every 8 s raises 2 skeletons by his side. If he falls completely, he comes back after 12 s.",
  "Lentos · x3": "Slow · x3",
  "Lluvia de lápidas": "Tombstone Rain",
  "Los enemigos de la zona se arrastran como zombis: andan y atacan a la mitad de velocidad durante 6 s.": "The enemies in the area shuffle like zombies: they move and attack at half speed for 6 s.",
  "Mago fantasma que lanza rayos de escarcha desde lejos. Cada impacto frena al enemigo.": "Ghost mage that fires frost bolts from afar. Each hit slows the enemy.",
  "Poción de formol": "Formaldehyde Potion",
  "Ralentiza": "Slows",
  "Semana de crunch: tus tropas de la zona atacan el doble de rápido durante 6 s… pero se van quemando (pierden un 4 % de vida por segundo).": "Crunch week: your troops in the area attack twice as fast for 6 s… but they burn out (they lose 4 % health per second).",
  "Sombra": "Shadow",
  "Tanque tóxico": "Toxic Tank",
  "Tres programadores convertidos en zombis por trabajar meses sin parar. Lentos pero duros, y no se quejan.": "Three programmers turned into zombies from working for months non-stop. Slow but tough, and they don't complain.",
  "Una mole cosida a trozos que va directa a por las torres. Aguanta muchísimo y, al morir, revienta en una nube tóxica.": "A hulk stitched together from pieces that heads straight for the towers. It takes a ton of damage and, when it dies, bursts into a toxic cloud.",
  "Una sombra sin cara: se desliza por encima de la pelea y cae junto al sanador o al tirador enemigo. A esos les hace el doble de daño.": "A faceless shadow: glides over the fight and lands next to the enemy healer or shooter. Those take double damage.",
  "tu Cripta": "your Crypt",
  "Agente de un juego que se canceló en secreto. Sale invisible y su primer disparo hace el doble. Si derriba a alguien, vuelve a desaparecer.": "Agent from a game that was secretly cancelled. Comes out invisible and its first shot does double. If it takes someone down, it vanishes again.",
  "Caen cartuchos de juegos olvidados: 150 de daño en la zona.": "Cartridges of forgotten games fall: 150 damage in the area.",
  "Cuatro bichos de un juego de estrategia que nunca salió. Rapidísimos y con muchas ganas de morder.": "Four critters from a strategy game that never came out. Lightning fast and eager to bite.",
  "EL ALMACÉN": "THE WAREHOUSE",
  "EspíaCancelado": "CancelledSpy",
  "Furia": "Fury",
  "Invisible · francotirador": "Invisible · sniper",
  "Juego cancelado": "Cancelled Game",
  "Las torres enemigas tardan 3 s en acordarse de cada unidad tuya": "Enemy towers take 3 s to remember each of your units",
  "Lleva años perdido en el sótano. Cada 8 s levanta un muro de escudos: él y sus aliados cercanos reciben una barrera dorada que para 80 de daño. Si cae, vuelve a los 12 s.": "He's been lost in the basement for years. Every 8 s he raises a shield wall: he and his nearby allies get a golden barrier that stops 80 damage. If he falls, he comes back after 12 s.",
  "Lluvia de cartuchos": "Cartridge Rain",
  "Los enemigos de la zona se quedan en gris, como un juego cancelado: no hacen nada durante 3 s.": "The enemies in the area turn grey, like a cancelled game: they do nothing for 3 s.",
  "Los fans arreglan lo que la empresa abandonó: cura 160 a tus tropas de la zona.": "The fans fix what the company abandoned: heals 160 to your troops in the area.",
  "Marine espacial de 1998 con hombreras enormes. Dispara ráfagas rapidísimas desde lejos.": "Space marine from 1998 with huge shoulder pads. Fires lightning-fast bursts from afar.",
  "Muro de escudos": "Shield Wall",
  "Nadie se acuerda de ellos: las torres y la base enemigas no les disparan hasta que llevan 3 s a su alcance.": "Nobody remembers them: enemy towers and base don't shoot at them until they've been in range for 3 s.",
  "Parche de la comunidad": "Community Patch",
  "Protagonista de un juego de espías que nunca salió: salta por encima de la pelea y cae junto al sanador o al tirador enemigo. A esos les hace el doble de daño.": "Lead of a spy game that never came out: jumps over the fight and lands next to the enemy healer or shooter. Those take double damage.",
  "Tres vikingos que se perdieron en un juego cancelado. Con escudo y espada, aguantan bien en grupo.": "Three vikings who got lost in a cancelled game. With shield and sword, they hold up well as a group.",
  "Un coche de carreras con lanzamisiles. Corre muchísimo y solo dispara a los edificios.": "A race car with a missile launcher. It's very fast and only shoots at buildings.",
  "Un gigante de un juego que se quedó en la beta. Con menos de la mitad de vida se enfada: pega un 50 % más y anda más rápido.": "A giant from a game that never left beta. Below half health it gets angry: hits 50 % harder and moves faster.",
  "VikingoPerdido": "LostViking",
  "Vikingos": "Vikings",
  "tu Almacén": "your Warehouse",
  "TitánBeta": "BetaTitan",
  "Cobro automático": "Automatic Charge",
  "LicenciaBot": "LicenseBot",
  "Servidor Caído": "Server Down",
  "Suscripción": "Subscription",
  "la Sede de Phony": "Phony HQ",
  "3 de cada 10 unidades que caen vuelven en versión «2»": "3 in 10 units that fall come back as a «2» version",
  "Acrobacias": "Stunts",
  "Aturde": "Stuns",
  "Cuatro extras con disfraz de cartón. Cobran poco y se caen enseguida, pero distraen a las torres.": "Four extras in cardboard costumes. They're paid little and fall quickly, but they distract the towers.",
  "Cultura Pop corrompida": "Corrupted Pop Culture",
  "Dirige la batalla con su megáfono. Cada 8 s grita ¡ACCIÓN! y sus aliados cercanos atacan un 40 % más rápido y corren más durante 4 s. Si cae, vuelve a los 12 s.": "Directs the battle with her megaphone. Every 8 s she shouts ACTION! and her nearby allies attack 40 % faster and run faster for 4 s. If she falls, she comes back after 12 s.",
  "DobleDeAcción": "StuntDouble",
  "EL ESTUDIO": "THE STUDIO",
  "El doble que rueda las escenas peligrosas. Cada 5 s da un salto acrobático hasta su objetivo.": "The double who shoots the dangerous scenes. Every 5 s it makes an acrobatic leap to its target.",
  "El enemigo más fuerte de la zona sale en versión remake: más pequeño, con un 35 % menos de vida y pegando menos durante 10 s. Y más caro.": "The strongest enemy in the area comes out as a remake: smaller, with 35 % less health and hitting less for 10 s. And more expensive.",
  "Encuentra el punto débil: cada disparo marca al enemigo 4 s y todo tu equipo le hace un 25 % más de daño.": "Finds the weak spot: every shot marks the enemy for 4 s and your whole team deals 25 % more damage to it.",
  "Explosión de taquilla": "Box Office Blast",
  "Grita el final de la película cada 7 s: los enemigos cercanos se quedan en shock 1,3 s. Entre grito y grito, tira periódicos.": "Shouts the movie's ending every 7 s: nearby enemies are in shock for 1.3 s. Between shouts, he throws newspapers.",
  "HéroeDeSaldo": "BargainHero",
  "KaijuDeGoma": "RubberKaiju",
  "LaDirectora": "TheDirector",
  "Maquillaje de rodaje": "Film Set Makeup",
  "Marca al enemigo": "Marks the enemy",
  "Rompe torres · pisotón": "Tower Breaker · stomp",
  "Salta a por el sanador o el tirador enemigo y lo deslumbra con el flash (1 s sin moverse). A esos les hace el doble de daño.": "Jumps at the enemy healer or shooter and dazzles them with the flash (1 s without moving). Those take double damage.",
  "Secuela": "Sequel",
  "Superhéroe de película barata, con capa de cortina. Vuela y recibe un 30 % menos de daño.": "Superhero from a cheap movie, with a curtain for a cape. Flies and takes 30 % less damage.",
  "Toda buena película tiene secuela: cuando una de tus unidades cae, 3 de cada 10 veces vuelve en versión «2», más pequeña y con la mitad de vida.": "Every good movie has a sequel: when one of your units falls, 3 times in 10 it comes back as a «2» version, smaller and with half the health.",
  "Un monstruo de película (es un actor con un disfraz de goma). Va a por los edificios y cada pisotón da también a los enemigos de alrededor.": "A movie monster (it's an actor in a rubber suit). It goes for the buildings and every stomp also hits the enemies around.",
  "Un retoque rápido antes de la toma: cura 160 a tus tropas de la zona.": "A quick touch-up before the take: heals 160 to your troops in the area.",
  "Una explosión de 200 millones de presupuesto: 170 de daño en una zona grande.": "A 200-million-dollar-budget explosion: 170 damage on a big area.",
  "Vuela · blindado": "Flies · armoured",
  "los de Cultura Pop": "the Pop Culture crew",
  "tu Estudio": "your Studio",
  "¡Acción!": "Action!",
  "Ban temporal": "Temporary Ban",
  "Cada 3 bajas, tu equipo ataca un 5 % más rápido (hasta +25 %)": "Every 3 kills, your team attacks 5 % faster (up to +25 %)",
  "Cada bot que despides suma espectadores al chat. Cada 3, todo tu equipo ataca un 5 % más rápido (hasta +25 %). Si pierdes una torre, el chat se va.": "Every bot you lay off adds viewers to the chat. Every 3, your whole team attacks 5 % faster (up to +25 %). If you lose a tower, the chat leaves.",
  "Caen monedas de los fans: 130 de daño en la zona, y cada enemigo al que da te devuelve 0,3 de CAOS (hasta 1,5).": "Fan coins rain down: 130 damage in the area, and every enemy it hits gives you back 0.3 CHAOS (up to 1.5).",
  "Cámara voladora que graba clips: cada disparo aturde un instante al objetivo.": "Flying camera that records clips: every shot briefly stuns the target.",
  "EL PLATÓ": "THE SET",
  "El moderador banea a los enemigos de la zona: desaparecen 3 s y no pueden hacer nada.": "The moderator bans the enemies in the area: they disappear for 3 s and can't do anything.",
  "El moderador. Aguanta muchísimo y cada martillazo golpea en área y aparta a los enemigos.": "The moderator. Takes a ton of damage and every hammer blow hits an area and knocks enemies back.",
  "El rey del directo. Mientras siga en pie, los aliados que tiene cerca pegan un 30 % más.": "The king of live streaming. As long as he's standing, nearby allies hit 30 % harder.",
  "El tren del hype va directo a por los edificios. No hay quien lo pare.": "The hype train goes straight for the buildings. Nothing can stop it."
});
