// Fans Of · Inglés de la serie (3/3): cartas de Streamers y las frases del chat y de los titulares comunes.
'use strict';
IDIOMA.add({
  "Escribe «ESTO ES MALÍSIMO» y salta a por el sanador o el tirador enemigo. A esos les hace el doble de daño.": "Types «THIS IS TERRIBLE» and jumps at the enemy healer or shooter. Those take double damage.",
  "Fan con ropa de marca y hasta arriba de bebida energética. Pega rapidísimo.": "A fan in designer clothes, wired on energy drinks. Hits lightning fast.",
  "La madre del streamer trae la merienda: cura 160 a tus tropas de la zona.": "The streamer's mum brings snacks: heals 160 to your troops in the area.",
  "La madre del streamer va detrás de tus tropas y reparte bocadillos a las que tiene delante.": "The streamer's mum follows your troops and hands out sandwiches to the ones in front of her.",
  "Lluvia de donaciones": "Donation Rain",
  "Pausa para merendar": "Snack Break",
  "Rápido": "Fast",
  "Tres suscriptores con dedo de espuma. Frágiles, rápidos y muy entregados.": "Three subscribers with foam fingers. Fragile, fast and fully committed.",
  "tu Plató": "your Set",
  "Área · empuja": "Area · pushes",
  "Empate. Microblizz dirá que ha ganado.": "Draw. Microblizz will say it won.",
  "Empate. Phony te cobrará la revancha.": "Draw. Phony will charge you for the rematch.",
  "Error 37: no se pudo conectar con la victoria.": "Error 37: could not connect to victory.",
  "Error de conexión: no se pudo cargar la victoria.": "Connection error: victory failed to load.",
  "FASE 2 😱": "PHASE 2 😱",
  "La PayStation ha sido devuelta. Sin ticket.": "The PayStation has been returned. No receipt.",
  "Microblizz anuncia que cerrará otro juego para recuperar el dinero.": "Microblizz announces it will shut down another game to get its money back.",
  "Microblizz compró mi juego favorito y lo cerró 😭": "Microblizz bought my favourite game and shut it down 😭",
  "Microblizz dirá que lo tenía planeado": "Microblizz will say it was planned",
  "Microblizz ha cerrado otro juego hoy": "Microblizz has shut down another game today",
  "Microblizz ha cerrado tu facción. Tus cosas están en esa caja.": "Microblizz has shut down your faction. Your things are in that box.",
  "Microblizz ha vuelto a subir el precio de las gemas": "Microblizz has raised the price of gems again",
  "Microblizz lo celebra subiendo los precios": "Microblizz celebrates by raising prices",
  "Microblizz promete arreglar su robot… dentro de diez años.": "Microblizz promises to fix its robot… in ten years.",
  "Microblizz te da las gracias por tu dinero.": "Microblizz thanks you for your money.",
  "Microblizz va a cerrar este juego por envidia": "Microblizz is going to shut this game down out of jealousy",
  "Microblizz ya prepara el comunicado": "Microblizz is already preparing the statement",
  "Microblizz: «aquí no se mueve nadie»": "Microblizz: «nobody move»",
  "Microblizz: «esa torre nos sobraba»": "Microblizz: «we didn't need that tower anyway»",
  "Microblizz: «esto lo arreglamos en el próximo parche»": "Microblizz: «we'll fix this in the next patch»",
  "POV: eres un becario de Microblizz": "POV: you're a Microblizz intern",
  "Phony anuncia que subirá la suscripción para compensar la derrota.": "Phony announces it will raise the subscription to make up for the defeat.",
  "Phony cobrando la suscripción en plena partida": "Phony charging the subscription mid-match",
  "Phony lo vuelve a vender, como siempre": "Phony sells it again, as always",
  "Phony promete volver a poner lector de discos… en la PayStation 7.": "Phony promises to bring back the disc drive… in the PayStation 7.",
  "Phony te da las gracias por tu suscripción.": "Phony thanks you for your subscription.",
  "Phony te ha quitado la licencia de la victoria.": "Phony has revoked your victory licence.",
  "Renacer: el mejor seguro de vida": "Rebirth: the best life insurance",
  "SurvivalBot ha sido cancelado. Otra vez.": "SurvivalBot has been cancelled. Again.",
  "ahora sí": "now we're talking",
  "ahora sí, a toda velocidad": "now we're talking, full speed",
  "apuesto 100 gemas a que gana": "I bet 100 gems it wins",
  "aquí sin subir cartas no se gana": "you can't win here without levelling up your cards",
  "barrera dorada, qué bonito": "golden barrier, how pretty",
  "boom boom boom": "boom boom boom",
  "cancela la suscripción, ¡ya!": "cancel the subscription, now!",
  "compra el pack (es broma)": "buy the pack (just kidding)",
  "congelados como el sueldo": "frozen like my salary",
  "contenido no disponible en tu región 😂": "content not available in your region 😂",
  "curas gratis, no como en Microblizz": "free heals, unlike at Microblizz",
  "el CEO de Microblizz no sabe jugar a su propio juego": "the Microblizz CEO can't play his own game",
  "el CEO es mi tío, no digáis nada": "the CEO is my uncle, don't tell anyone",
  "el CEO ha tirado el café al ver esto": "the CEO spilled his coffee seeing this",
  "el castor ha cobrado su finiquito": "the beaver got his severance pay",
  "el chat está más vivo que los servidores de Microblizz": "the chat is more alive than Microblizz's servers",
  "el jefe despide a todo el mundo": "the boss fires everyone",
  "empate y casi sin tiempo": "a draw and almost no time left",
  "en Difícil hasta los becarios pegan fuerte": "on Hard even the interns hit hard",
  "esa habilidad está rotísima": "that ability is so broken",
  "ese CAOS no se gasta solo": "that CHAOS won't spend itself",
  "ese robot ya lo había comprado": "I'd already bought that robot",
  "ese vikingo protege a todos": "that viking protects everyone",
  "eso es un recorte de movimiento": "that's a movement cut",
  "eso es una habilidad del gashapón 😮": "that's a gacha ability 😮",
  "eso ha sido un recorte de plantilla, pero al revés": "that was a staff cut, but the other way round",
  "eso le ha dolido a la torre": "the tower felt that",
  "eso le ha dolido al CEO en la cartera": "the CEO felt that in his wallet",
  "eso pasa por alquilar": "that's what you get for renting",
  "eso pasa por no comprar el pack": "that's what you get for not buying the pack",
  "esto es mejor que la tele": "this is better than TV",
  "esto es mejor que lo de Microblizz": "this is better than anything Microblizz makes",
  "esto es para los que no duermen": "this is for those who don't sleep",
  "esto no se acaba hasta que se acaba": "it ain't over till it's over",
  "esto pide tercera parte": "this needs a third part",
  "esto se decide al final 😬": "this will be decided at the end 😬",
  "esto se pone feo": "this is getting ugly",
  "golpe por la espalda, clásico": "backstab, a classic",
  "hola?? ¿hay alguien jugando?": "hello?? is anyone playing?",
  "jajaja el becario": "hahaha the intern",
  "jajaja, le ha caducado la licencia": "hahaha, its licence expired",
  "la Directora lo tiene todo controlado": "the Director has everything under control",
  "la culpa es del lag": "it's the lag's fault",
  "la ruleta de esta semana es cruel": "this week's wheel is cruel",
  "la secuela siempre vuelve": "the sequel always comes back",
  "menos mal que hay enfermera": "thank goodness for the nurse",
  "menuda suerte en las cápsulas": "what luck with the capsules",
  "mi abuela juega mejor (y tiene 90 años)": "my grandma plays better (and she's 90)",
  "mi primo trabaja en Microblizz y dice que todo va bien": "my cousin works at Microblizz and says everything's fine",
  "modo mítico: aquí no gana nadie": "mythic mode: nobody wins here",
  "más ardillas, menos anuncios": "more squirrels, fewer ads",
  "nadie la pidió, pero ahí está la 2": "nobody asked for it, but here's the 2",
  "nadie lo ha visto venir": "nobody saw that coming",
  "nerf Microblizz": "nerf Microblizz",
  "nerf conejo": "nerf bunny",
  "ni la licencia les dura": "they can't even keep their licence",
  "ni muerto se rinde": "not even dead does it give up",
  "nunca dudé (mentira)": "never doubted (lie)",
  "nunca había visto tanto caos junto": "never seen so much chaos in one place",
  "otra torre cerrada, como sus juegos jajaja": "another tower closed, just like their games hahaha",
  "pago y pago y sigo sin disco": "I pay and pay and still no disc",
  "pon algo delante, ¡rápido!": "put something in front, quick!",
  "primera vez aquí, ¿de qué va esto?": "first time here, what is this about?",
  "que alguien tire una torre ya": "somebody knock a tower down already",
  "que no entren, que no entren": "don't let them in, don't let them in",
  "remaster = mismo juego, nuevo precio": "remaster = same game, new price",
  "se ha enfadado el jefe": "the boss got angry",
  "se ha ido a por un café": "went to get a coffee",
  "se viene lo gordo": "here comes the big one",
  "su líder va equipado hasta los dientes": "their leader is armed to the teeth",
  "tienes el CAOS a tope, ¡saca algo!": "your CHAOS is maxed out, play something!",
  "una torre menos, un despido más para Microblizz": "one tower less, one more layoff for Microblizz",
  "vuelve del más allá": "back from beyond",
  "ya viene el bueno": "here comes the good one",
  "¡BOOM! 💥": "BOOM! 💥",
  "¡CAOS x2! ahora sí": "CHAOS x2! now we're talking",
  "¡Empieza! A ver si hoy gana alguien que no sea Microblizz": "It's on! Let's see if someone other than Microblizz wins today",
  "¡LÍDER EN PISTA!": "LEADER ON THE FIELD!",
  "¡MURO DE ESCUDOS! 🛡️": "SHIELD WALL! 🛡️",
  "¡REMONTADA! 🔥": "COMEBACK! 🔥",
  "¡SECUELA! 🎬": "SEQUEL! 🎬",
  "¡defiende la base!": "defend the base!",
  "¡empate! ¡qué partida!": "a draw! what a match!",
  "¡fuera robots!": "robots out!",
  "¡gasta el CAOS!": "spend the CHAOS!",
  "¡los ha congelado a todos! 🥶": "it froze them all! 🥶",
  "¡que salga el jefe!": "bring out the boss!",
  "¡se levanta! 🧟": "it's getting up! 🧟",
  "¡triple despido!": "triple layoff!",
  "¡vamos rebelión!": "let's go, rebellion!",
  "¿AFK?": "AFK?",
  "¿Difícil? a ver cuánto aguanta": "Hard? let's see how long it lasts",
  "¿Mítica? valiente 😱": "Mythic? brave 😱",
  "¿alguien ha leído los términos y condiciones?": "has anyone read the terms and conditions?",
  "¿cuándo sale para móvil?": "when does it come out for mobile?",
  "¿cuántos juegos ha cerrado ya Microblizz?": "how many games has Microblizz shut down by now?",
  "¿de dónde ha salido ese?": "where did that one come from?",
  "¿dónde se compra el CAOS?": "where do you buy CHAOS?",
  "¿el pase de batalla merece la pena?": "is the battle pass worth it?",
  "¿otra vez despidos?": "layoffs again?",
  "¿otra vez me cobran? 😡": "charging me again? 😡",
  "¿otra vez? ¿y a 70 €? 😤": "again? and at 70 €? 😤",
  "¿qué ha sido eso?": "what was that?",
  "¿se ha dormido?": "did it fall asleep?",
  "¿se puede jugar con mando?": "can you play with a controller?",
  "último minuto, nervios": "last minute, nerves"
});
