// Fans Of · Inglés de la serie (1/3): rótulos de los edificios, objetos, habilidades y las cartas de Animales Locos y Ciberpunks. Cada línea es «texto en español»: «English».
'use strict';
IDIOMA.add({
  "BÚNKER": "BUNKER",
  "ARCADE": "ARCADE",
  "NO COMPRAR": "DON'T BUY",
  "FUERA": "OUT",
  "¿OFF/ON?": "OFF/ON?",
  "ALMACÉN": "WAREHOUSE",
  "SIN LECTOR": "NO DRIVE",
  "PAGA AQUÍ": "PAY HERE",
  "ESTRENO": "PREMIERE",
  "¡FINAL!": "FINALE!",
  "BUUU": "BOOO",
  "Accesorio": "Accessory",
  "Alfombrilla XXL": "XXL Mousepad",
  "Almohada de viaje": "Travel Pillow",
  "Arma": "Weapon",
  "Auriculares con cancelación de ruido": "Noise-Cancelling Headphones",
  "Baguette de ayer": "Yesterday's Baguette",
  "BanHammer de oro": "Golden BanHammer",
  "Bebida energética XXL": "XXL Energy Drink",
  "Becario (básica)": "Intern (basic)",
  "Botón de pausa": "Pause Button",
  "Llamada del CEO": "CEO Call",
  "Modo Súper": "Super Mode",
  "Wallhack": "Wallhack",
  "Ragdoll": "Ragdoll",
  "Lag": "Lag",
  "Modo Dios": "God Mode",
  "Bullet Time": "Bullet Time",
  "Lootbox humana": "Human Lootbox",
  "Spam de emotes": "Emote Spam",
  "Ping 999": "Ping 999",
  "Clipping": "Clipping",
  "Palo selfie": "Selfie Stick",
  "Cable HDMI enrollado": "Tangled HDMI Cable",
  "Pincho de kebab": "Kebab Skewer",
  "Micrófono de karaoke": "Karaoke Microphone",
  "Mazo del hotfix": "Hotfix Mallet",
  "Joystick de recreativa": "Arcade Joystick",
  "Katana de oferta de Steam": "Steam Sale Katana",
  "Gorro de lana de la abuela": "Grandma's Wool Beanie",
  "Gorro de cumpleaños": "Birthday Hat",
  "Casco de moto": "Motorbike Helmet",
  "Máscara de luchador": "Wrestler Mask",
  "Corona del troll": "Troll Crown",
  "Patinete eléctrico": "Electric Scooter",
  "Bolsa de pipas": "Bag of Sunflower Seeds",
  "Llavero de la suerte": "Lucky Keychain",
  "Mochila con ruedas": "Rolling Backpack",
  "Powerbank": "Power Bank",
  "Capa de disfraz de superhéroe": "Superhero Costume Cape",
  "CEO (perfecta)": "CEO (perfect)",
  "Cartucho dorado": "Golden Cartridge",
  "Casco con cuernos": "Horned Helmet",
  "Casco de realidad virtual": "VR Headset",
  "Claqueta de oro": "Golden Clapperboard",
  "Clon viral": "Viral Clone",
  "Cofre de botín sin abrir": "Unopened Loot Chest",
  "Corona de hamburguesería": "Burger Joint Crown",
  "Corona de huesos": "Crown of Bones",
  "Diadema de orejas de gato": "Cat-Ear Headband",
  "Diploma de Becario del Mes": "Intern of the Month Diploma",
  "Director (excelente)": "Director (excellent)",
  "Disco físico de coleccionista": "Collector's Physical Disc",
  "Escarcha": "Frost",
  "Escudo de plasma": "Plasma Shield",
  "Espada de cartón piedra": "Papier-Mâché Sword",
  "Furia legendaria": "Legendary Fury",
  "Gafas pixeladas": "Pixelated Glasses",
  "Gorra del revés": "Backwards Cap",
  "Gorro de papel de aluminio": "Tinfoil Hat",
  "Grito": "Scream",
  "Hitbox dudosa": "Dodgy Hitbox",
  "Imán de CAOS": "CHAOS Magnet",
  "Junior (normal)": "Junior (normal)",
  "Lanzaconfeti": "Confetti Launcher",
  "Mando con cable de 3 metros": "Controller with a 3-Metre Cable",
  "Microtransacción": "Microtransaction",
  "Micrófono de oro": "Golden Microphone",
  "Modo foto": "Photo Mode",
  "Modo gigante": "Giant Mode",
  "Núcleo de plasma": "Plasma Core",
  "Pase de batalla caducado": "Expired Battle Pass",
  "Piel dura": "Thick Skin",
  "Provocación": "Taunt",
  "Puños de hierro": "Iron Fists",
  "Ratón de 16.000 DPI": "16,000 DPI Mouse",
  "Ratón del campeón": "Champion's Mouse",
  "Rayo en cadena": "Chain Lightning",
  "Reflejos": "Reflexes",
  "Renacer": "Rebirth",
  "Senior (buena)": "Senior (good)",
  "Sigilo inicial": "Opening Stealth",
  "Silla gamer portátil": "Portable Gaming Chair",
  "Taza del becario": "Intern's Mug",
  "Teclado mecánico RGB": "RGB Mechanical Keyboard",
  "Vampirismo": "Vampirism",
  "Yelmo del Olimpo": "Helm of Olympus",
  "Zanahoria de oro": "Golden Carrot",
  "Botiquín del bosque": "Forest First-Aid Kit",
  "Cada animal pega un 10 % más por cada aliado que tenga cerca, hasta +50 %. Cuanto más juntos, más locos.": "Each animal hits 10 % harder for every ally nearby, up to +50 %. The closer they are, the crazier they get.",
  "Corre a la torre más cercana con dinamita y explota: 180 al edificio. Él no sobrevive, claro.": "Runs to the nearest tower with dynamite and blows up: 180 to the building. He doesn't survive, of course.",
  "Cura aliados": "Heals allies",
  "Daño en área": "Area damage",
  "Enfermera con alas de ángel. Va detrás de tus tropas y cura a las que tiene delante. Casi no pega.": "A nurse with angel wings. She follows your troops and heals the ones in front of her. She barely hits.",
  "HurónNinja": "NinjaFerret",
  "Invisible hasta que ataca. Su primer golpe hace el triple y, si mata, vuelve a desaparecer.": "Invisible until it attacks. Its first hit does triple damage and, if it kills, it vanishes again.",
  "Invisible · x3": "Invisible · x3",
  "Lanza bolsas de basura explosivas desde lejos. Ideal contra grupos de becarios.": "Throws explosive garbage bags from afar. Ideal against groups of interns.",
  "LA MADRIGUERA": "THE BURROW",
  "Lluvia de bellotas": "Acorn Rain",
  "Ninja del bosque: salta por encima de la primera línea y cae junto al sanador o al tirador enemigo. A esos les hace el doble de daño.": "Forest ninja: jumps over the front line and lands next to the enemy healer or shooter. Those take double damage.",
  "Pulgas": "Fleas",
  "Rabia": "Rage",
  "Rápidas · x2": "Fast · x2",
  "Salen dos. Rápidas y frágiles: perfectas para distraer a las torres.": "Two come out. Fast and fragile: perfect for distracting towers.",
  "Salta sobre el grupo enemigo más grande y hace 50 de daño en área cada 8 s. Si cae, vuelve a los 12 s.": "Jumps onto the biggest enemy group and deals 50 area damage every 8 s. If it falls, it comes back after 12 s.",
  "Tanque + vaca": "Tank + cow",
  "Tiritas, hojas y mucho cariño: cura 170 a tus tropas de la zona.": "Plasters, leaves and lots of love: heals 170 to your troops in the area.",
  "Tus animales pegan +10 % por cada aliado cerca, hasta +50 %": "Your animals hit +10 % for every ally nearby, up to +50 %",
  "Una plaga de pulgas: los enemigos de la zona se rascan sin parar y no pueden atacar durante 4 s.": "A plague of fleas: the enemies in the area scratch non-stop and can't attack for 4 s.",
  "Una tormenta de bellotas cae sobre la zona: 150 de daño a los enemigos (y un poco a los edificios).": "A storm of acorns hits the area: 150 damage to enemies (and a little to buildings).",
  "Una vaca en un mecha rosa. Aguanta muchísimo y, cuando el mecha revienta, la vaca sale y sigue peleando.": "A cow in a pink mech. It takes a ton of damage and, when the mech blows up, the cow climbs out and keeps fighting.",
  "tu Madriguera": "your Burrow",
  "Actualización obligatoria": "Mandatory Update",
  "Artillería": "Artillery",
  "Ataque orbital": "Orbital Strike",
  "Cada 8 s hackea la torre enemiga más cercana y la deja 3,5 s sin disparar.": "Every 8 s it hacks the nearest enemy tower and stops it from shooting for 3.5 s.",
  "Cada unidad lleva un escudo de plasma del 25 % de su vida que se recarga si pasa 3 s sin recibir daño.": "Every unit carries a plasma shield worth 25 % of its health that recharges after 3 s without taking damage.",
  "Cuatro robots diminutos y rápidos que rodean al enemigo.": "Four tiny, fast robots that surround the enemy.",
  "Dispara muy despacio, pero desde muy lejos y con muchísimo daño.": "Shoots very slowly, but from very far away and with huge damage.",
  "Droide de soporte: va detrás de tus tropas y repara a las que tiene delante.": "Support droid: follows your troops and repairs the ones in front of it.",
  "Dron de caza: vuela por encima de la pelea y se lanza a por el sanador o el tirador enemigo. A esos les hace el doble de daño.": "Hunter drone: flies over the fight and dives at the enemy healer or shooter. Those take double damage.",
  "DronCazador": "HunterDrone",
  "EL BÚNKER": "THE BUNKER",
  "Escudo de plasma del 25 % que se recarga a los 3 s sin daño": "25 % plasma shield that recharges after 3 s without damage",
  "Escudos": "Shields",
  "Francotiradora": "Sniper",
  "Hackea torres": "Hacks towers",
  "Los enemigos de la zona se quedan «instalando la actualización 1 de 47»: no se mueven ni atacan durante 3 s.": "The enemies in the area get stuck «installing update 1 of 47»: they can't move or attack for 3 s.",
  "Marine con armadura y fusil rápido. Cada 9 s le caen del cielo 2 drones de apoyo.": "Armoured marine with a fast rifle. Every 9 s, 2 support drones drop from the sky.",
  "Mecha de asedio con cañón: daño en área desde lejos. Lento pero demoledor.": "Siege mech with a cannon: area damage from afar. Slow but devastating.",
  "Nanobots que reparan: curan 130 a tus tropas de la zona y les dan un escudo de 60.": "Repairing nanobots: they heal 130 to your troops in the area and give them a 60 shield.",
  "Ninja con katana de neón: cada 5 s se teletransporta hacia su objetivo.": "Ninja with a neon katana: every 5 s it teleports to its target.",
  "Parche de nanobots": "Nanobot Patch",
  "Repara": "Repairs",
  "Salen 4": "4 come out",
  "Teletransporte": "Teleport",
  "Un satélite marca la zona y, un segundo después, dispara: 240 de daño.": "A satellite marks the area and, a second later, fires: 240 damage.",
  "tu Búnker": "your Bunker",
  "+5 % de daño por cada tipo distinto de unidad en el campo (hasta +30 %)": "+5 % damage for every different unit type on the field (up to +30 %)",
  "Arregla el juego mejor que la empresa: va detrás de tus tropas y repara a las que tiene delante.": "Fixes the game better than the company: follows your troops and repairs the ones in front of it.",
  "Bebida energética": "Energy Drink",
  "Campeón de torneos con un teclado como espada. Ataca rapidísimo y cada 4.º golpe es un ¡COMBO!: triple de daño y aturde. Si cae, vuelve a los 12 s.": "Tournament champion with a keyboard for a sword. Attacks lightning fast and every 4th hit is a COMBO!: triple damage and a stun. If it falls, it comes back after 12 s.",
  "Coleccionista": "Collector",
  "Comunidad": "Community",
  "Disco que rebota": "Bouncing Disc",
  "Explota al caer": "Explodes on death",
  "Golpe crítico": "Critical Hit",
  "Juntos son más fuertes: todo tu equipo pega un 5 % más por cada tipo distinto de unidad que tengas en el campo, hasta +30 %.": "Stronger together: your whole team hits 5 % harder for every different unit type you have on the field, up to +30 %."
});
