// Fans of Rumble · Las cifras de las cartas: coste de CAOS, cuántas salen, reaparición y hechizos. Son de este juego y se añaden a las cartas de core (nombre, rareza y texto).
'use strict';
const HEALER_SPELL = 1.5;   // v0.9.15: los hechizos de daño hacen un 50 % más a los sanadores
(() => {
  const poner = (obj, tabla) => { for (const k in tabla) Object.assign(obj[k], tabla[k]); };
  poner(CFG.cards, {
    // Animales Locos
    bunny: { cost: 5, count: 1, respawn: 12 },
    squirrel: { cost: 2, count: 2 },
    beaver: { cost: 2, count: 1 },
    fox: { cost: 3, count: 1 },
    meercat: { cost: 3, count: 1 },
    junkcoon: { cost: 4, count: 1 },
    mechavaca: { cost: 5, count: 1 },
    huron: { cost: 3, count: 1 },
    sp_bellotas: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 80, amt: 150, bld: 0.35, fx: "acorn", col: "#c0742e" } },
    sp_botiquin: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 90, amt: 170, fx: "leaf", col: "#7be04a" } },
    sp_pulgas: { cost: 3, count: 1, spell: { side: "foe", kind: "disarm", r: 85, t: 4, fx: "flea", col: "#8b5530", label: "¡QUÉ PICOR!" } },
    // No-Muertos
    necrolord: { cost: 5, count: 1, respawn: 12 },
    skeleton: { cost: 2, count: 4 },
    zombie: { cost: 3, count: 3 },
    ghostmage: { cost: 3, count: 1 },
    banshee: { cost: 4, count: 1 },
    skullknight: { cost: 4, count: 1 },
    stitchbrute: { cost: 5, count: 1 },
    sombra: { cost: 3, count: 1 },
    sp_lapidas: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 70, amt: 170, bld: 0.35, stun: 0.5, fx: "tomb", col: "#9aa3b2" } },
    sp_formol: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 85, amt: 150, fx: "potion", col: "#7dffb8" } },
    sp_eternas: { cost: 3, count: 1, spell: { side: "foe", kind: "slow", r: 90, t: 6, fx: "clock", col: "#7d5fff", label: "HORAS EXTRA" } },
    sp_crunch: { cost: 3, count: 1, spell: { side: "ally", kind: "crunch", r: 85, t: 6, drain: 0.04, fx: "clock", col: "#ff8a3d", label: "¡CRUNCH!" } },
    // Streamers
    twitchking: { cost: 5, count: 1, respawn: 12 },
    subswarm: { cost: 2, count: 3 },
    hypebeast: { cost: 3, count: 1 },
    viralbot: { cost: 3, count: 1 },
    snackmom: { cost: 3, count: 1 },
    hypetrain: { cost: 4, count: 1 },
    banhammer: { cost: 5, count: 1 },
    hater: { cost: 3, count: 1 },
    sp_donaciones: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 85, amt: 130, bld: 0.3, gain: 0.3, fx: "coin", col: "#ffcb3d" } },
    sp_merienda: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 90, amt: 160, fx: "sandwich", col: "#ffb04f" } },
    sp_baneo: { cost: 4, count: 1, spell: { side: "foe", kind: "ban", r: 75, t: 3, fx: "hammer", col: "#a855f7", label: "BANEADO" } },
    // Héroes
    epicchampion: { cost: 5, count: 1, respawn: 12 },
    cupidarcher: { cost: 2, count: 1 },
    hoplite: { cost: 3, count: 3 },
    shieldmaiden: { cost: 3, count: 1 },
    thundergod: { cost: 4, count: 1 },
    medusa: { cost: 4, count: 1 },
    minotaur: { cost: 5, count: 1 },
    arpia: { cost: 3, count: 1 },
    sp_rayo: { cost: 4, count: 1, spell: { side: "foe", kind: "dmg", r: 55, amt: 260, bld: 0.4, fx: "bolt", col: "#ffe14d" } },
    sp_ambrosia: { cost: 4, count: 1, spell: { side: "ally", kind: "heal", r: 85, amt: 200, fx: "goblet", col: "#ffd166" } },
    sp_nerfeo: { cost: 3, count: 1, spell: { side: "foe", kind: "shrink", r: 85, t: 6, f: 0.6, fx: "arrow", col: "#63cfe0", label: "¡NERFEADO!" } },
    // Ciberpunks
    cybermarine: { cost: 5, count: 1, respawn: 12 },
    nanobot: { cost: 2, count: 4 },
    cyberninja: { cost: 3, count: 1 },
    techdroid: { cost: 3, count: 1 },
    hackerkid: { cost: 3, count: 1 },
    neonsniper: { cost: 4, count: 1 },
    siegemech: { cost: 5, count: 1 },
    dron: { cost: 3, count: 1 },
    sp_orbital: { cost: 4, count: 1, spell: { side: "foe", kind: "dmg", r: 65, amt: 240, bld: 0.5, delay: 1.2, fx: "laser", col: "#22e3ff" } },
    sp_nanobots: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 85, amt: 130, shield: 60, fx: "chip", col: "#7df3ff" } },
    sp_update: { cost: 4, count: 1, spell: { side: "foe", kind: "stun", r: 80, t: 3, sk: "update", fx: "bar", col: "#22e3ff", label: "INSTALANDO 1/47…" } },
    // Memes
    memelord: { cost: 5, count: 1, respawn: 12 },
    suchdog: { cost: 2, count: 2 },
    gifblaster: { cost: 3, count: 1 },
    synthcat: { cost: 3, count: 1 },
    trollbot: { cost: 4, count: 1 },
    stonks: { cost: 4, count: 1 },
    chonkcat: { cost: 5, count: 1 },
    clickbait: { cost: 3, count: 1 },
    sp_gatos: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 95, amt: 120, bld: 0.3, crit: 0.25, fx: "cat", col: "#ffb04f" } },
    sp_likes: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 100, amt: 140, fx: "heart", col: "#ff5fa8" } },
    sp_confusion: { cost: 4, count: 1, spell: { side: "foe", kind: "confuse", r: 80, t: 3, fx: "swirl", col: "#ff3df0", label: "¿EH?" } },
    // Comunidad Gamer
    progamer: { cost: 5, count: 1, respawn: 12 },
    noobs: { cost: 2, count: 3 },
    speedrunner: { cost: 3, count: 1 },
    modder: { cost: 3, count: 1 },
    coleccionista: { cost: 4, count: 1 },
    ragequitter: { cost: 4, count: 1 },
    recreativa: { cost: 5, count: 1 },
    campero: { cost: 3, count: 1 },
    sp_critico: { cost: 4, count: 1, spell: { side: "foe", kind: "dmg", r: 45, amt: 300, bld: 0.45, fx: "sword", col: "#ff4b5c" } },
    sp_review: { cost: 3, count: 1, spell: { side: "foe", kind: "review", r: 80, t: 8, amp: 0.4, fx: "letter", col: "#ffcb3d", label: "★☆☆☆☆" } },
    sp_energetica: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 85, amt: 120, haste: 5, fx: "can", col: "#7be04a" } },
    sp_ping: { cost: 3, count: 1, spell: { side: "foe", kind: "knock", r: 85, d: 80, t: 1, fx: "wifi", col: "#ff4b5c", label: "LAG" } },
    // Olvidados
    vikingo: { cost: 5, count: 1, respawn: 12 },
    swarmbug: { cost: 2, count: 4 },
    vikingsquad: { cost: 3, count: 3 },
    retromarine: { cost: 3, count: 1 },
    ghostagent: { cost: 4, count: 1 },
    rockracer: { cost: 4, count: 1 },
    titanbeta: { cost: 5, count: 1 },
    espia: { cost: 3, count: 1 },
    sp_cartuchos: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 80, amt: 150, bld: 0.35, fx: "cart", col: "#a16207" } },
    sp_parchefan: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 90, amt: 160, fx: "patch", col: "#fde68a" } },
    sp_cancelado: { cost: 4, count: 1, spell: { side: "foe", kind: "stun", r: 80, t: 3, sk: "stone", fx: "stamp", col: "#9aa3a0", label: "CANCELADO" } },
    // Cultura Pop
    directora: { cost: 5, count: 1, respawn: 12 },
    extras: { cost: 2, count: 4 },
    doble: { cost: 3, count: 1 },
    detective: { cost: 3, count: 1 },
    heroe: { cost: 4, count: 1 },
    spoiler: { cost: 4, count: 1 },
    kaiju: { cost: 5, count: 1 },
    paparazzi: { cost: 3, count: 1 },
    sp_taquilla: { cost: 4, count: 1, spell: { side: "foe", kind: "dmg", r: 95, amt: 170, bld: 0.35, fx: "boom", col: "#ff7a1a" } },
    sp_maquillaje: { cost: 3, count: 1, spell: { side: "ally", kind: "heal", r: 90, amt: 160, fx: "brush", col: "#ff9ab8" } },
    sp_remake: { cost: 4, count: 1, spell: { side: "foe", kind: "remake", r: 90, t: 10, f: 0.6, cut: 0.35, fx: "clap", col: "#ff9ab8", label: "REMAKE" } },
  });
  poner(CFG.enemyCards, {
    // Microblizz
    becario: { cost: 2, count: 2 },
    starbot: { cost: 3, count: 1 },
    fallen: { cost: 5, count: 1 },
    cajabotin: { cost: 3, count: 1 },
    soportebot: { cost: 3, count: 1 },
    parchebot: { cost: 4, count: 1 },
    sp_despido: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 70, amt: 170, bld: 0.3, fx: "letter", col: "#fff6ea", label: "¡DESPEDIDO!" } },
    // Phony
    descargabot: { cost: 2, count: 3 },
    licenciabot: { cost: 3, count: 1 },
    plusbot: { cost: 3, count: 1 },
    cobradlc: { cost: 4, count: 1 },
    servidorbot: { cost: 5, count: 1 },
    remasterbot: { cost: 5, count: 1 },
    sp_cobro: { cost: 3, count: 1, spell: { side: "foe", kind: "dmg", r: 80, amt: 150, bld: 0.3, steal: 0.5, fx: "card9", col: "#ffcb3d", label: "-9,99 €" } },
  });
})();
// los hechizos de daño hacen más a los sanadores, y la carta lo dice
for (const k in CFG.cards) { const c = CFG.cards[k]; if (c.spell && c.spell.kind === 'dmg') c.desc += ' A los sanadores, un 50 % más.'; }
