// Fans of Rumble · Inglés: el armario (nombres de marcos y títulos) y los pases de este juego (temporada y PvP)
'use strict';
IDIOMA.add({
  // marcos
  "De serie": "Standard",
  "Billetes": "Banknotes",
  "Corporativo": "Corporate",
  "Caja de despido": "Layoff Box",
  "Accionista": "Shareholder",
  "Maletín de oro": "Golden Briefcase",
  "Trono del CEO": "CEO's Throne",
  "Duelista": "Duelist",
  "Neón de sala": "Arcade Neon",
  "Pay to Win": "Pay to Win",
  "Leyenda del sofá": "Couch Legend",
  "Trofeo de plástico": "Plastic Trophy",
  // títulos (con y sin comillas: salen de las dos maneras)
  "Becario sin sueldo": "Unpaid Intern", "«Becario sin sueldo»": "«Unpaid Intern»",
  "Cliente fiel": "Loyal Customer", "«Cliente fiel»": "«Loyal Customer»",
  "Accionista minoritario": "Minority Shareholder", "«Accionista minoritario»": "«Minority Shareholder»",
  "Despedido del mes": "Fired of the Month", "«Despedido del mes»": "«Fired of the Month»",
  "Inversor de riesgo": "Risky Investor", "«Inversor de riesgo»": "«Risky Investor»",
  "Ejecutivo agresivo": "Aggressive Executive", "«Ejecutivo agresivo»": "«Aggressive Executive»",
  "Tiburón de las fusiones": "Merger Shark", "«Tiburón de las fusiones»": "«Merger Shark»",
  "Consejo de administración": "Board of Directors", "«Consejo de administración»": "«Board of Directors»",
  "CEO en funciones": "Acting CEO", "«CEO en funciones»": "«Acting CEO»",
  "Duelista de sofá": "Couch Duelist", "«Duelista de sofá»": "«Couch Duelist»",
  "Sin pase y sin miedo": "No Pass, No Fear", "«Sin pase y sin miedo»": "«No Pass, No Fear»",
  "Pay to Pray": "Pay to Pray", "«Pay to Pray»": "«Pay to Pray»",
  "Ballena competitiva": "Competitive Whale", "«Ballena competitiva»": "«Competitive Whale»",
  "Leyenda con tarjeta": "Legend With a Credit Card", "«Leyenda con tarjeta»": "«Legend With a Credit Card»",
  // pases
  "Pase Competitivo Pro": "Pro Competitive Pass",
  "Microblizz compra la cafetera": "Microblizz buys the coffee machine",
  "La primera adquisición. Ahora el café es de suscripción.": "The first acquisition. Coffee is now a subscription.",
  "Microblizz compra tu estudio indie favorito": "Microblizz buys your favourite indie studio",
  "Y lo cierra «para cuidarlo mejor».": "And shuts it down «to take better care of it».",
  "Microblizz compra un museo": "Microblizz buys a museum",
  "Los cuadros ahora llevan anuncios antes de poder mirarlos.": "Paintings now show ads before you can look at them.",
  "Microblizz compra tu partida guardada": "Microblizz buys your save file",
  "Para continuar, acepta los nuevos términos (2.000 páginas).": "To continue, accept the new terms (2,000 pages).",
  "Microblizz se compra a sí misma": "Microblizz buys itself",
  "El CEO firma consigo mismo y se pone un bonus por la operación.": "The CEO signs with himself and gives himself a bonus for the deal.",
  // consejos de Lola (v0.9.92)
  "Microblizz ha relanzado el ": "Microblizz has relaunched the ",
  " y fecha de caducidad, como los yogures. Cada 5 niveles hay un premio con ": " and an expiry date, like yoghurt. Every 5 levels there's a reward with a ",
  ": marcos y títulos para tu ": ": frames and titles for your ",
  ". Ah, y todos empezamos de cero. «Por justicia», dicen.": ". Oh, and everyone starts from zero. «For fairness», they say.",
  " solo sube jugando contra personas: ": " only goes up by playing against people: ",
  " por partida y ": " per match and ",
  " si ganas. Sus premios son solo para presumir, porque aquí gana el que mejor juega. Microblizz no soportaba no cobrar nada, así que se inventó el ": " if you win. Its rewards are just for showing off, because here the best player wins. Microblizz couldn't stand not charging for anything, so it invented the ",
  ": marcos para tu cara y títulos para debajo de tu nombre. No dan ni un punto de vida, pero hay que tener estilo hasta en el paro. Se ganan en los pases: toca uno para ponértelo.": ": frames for your face and titles for under your name. They don't give a single hit point, but you need style even when unemployed. You earn them in the passes: tap one to wear it.",
  "estrella": "star",
  "armario": "wardrobe",
  "PASE PVP": "PVP PASS",
  // Mítica semanal (js/10d-mitica-semanal.js, la pestaña Mítica del Salón y el consejo de Lola)
  "TEMPORADA MÍTICA": "MYTHIC SEASON",
  "Se reinicia en %1": "Resets in %1",
  "ESTA SEMANA": "THIS WEEK",
  "DE SIEMPRE": "ALL TIME",
  "★ %1": "★ %1",
  "Cada lunes las estrellas de la Mítica vuelven a 0, pero los niveles siguen abiertos. Las que ganes suben tu puesto en el Salón de la Fama.": "Every Monday your Mythic stars go back to 0, but the levels stay open. The ones you win raise your rank in the Hall of Fame.",
  "Cada lunes las estrellas de la Mítica vuelven a 0, pero los niveles siguen abiertos.": "Every Monday your Mythic stars go back to 0, but the levels stay open.",
  "Cada lunes las estrellas de la Mítica vuelven a 0 (y con ellas sus premios de oro y gemas), pero los niveles siguen abiertos. Las que ganes suben tu puesto en el Salón de la Fama.": "Every Monday your Mythic stars go back to 0 (and so do their gold and gem rewards), but the levels stay open. The ones you win raise your rank in the Hall of Fame.",
  "Cada lunes las estrellas de la Mítica vuelven a 0 (y con ellas sus premios de oro y gemas), pero los niveles siguen abiertos.": "Every Monday your Mythic stars go back to 0 (and so do their gold and gem rewards), but the levels stay open.",
  "Primera vez esta semana: %1 de oro y %2 gemas": "First time this week: %1 gold and %2 gems",
  "Primera vez esta semana": "First time this week",
  "Las que ganes suben tu puesto en el Salón de la Fama.": "The ones you win raise your rank in the Hall of Fame.",
  "VER LA CLASIFICACIÓN": "SEE THE RANKING",
  "¡Quedaste %#1.º en la Mítica! Título nuevo en tu armario: «%2»": "You finished #%1 in Mythic! New title in your wardrobe: “%2”",
  "Esta semana": "This week",
  "Semana pasada": "Last week",
  "De siempre": "All time",
  "Estrellas de la Mítica ganadas esta semana. Cada lunes vuelven a 0: los 10 primeros se llevan un título.": "Mythic stars won this week. Every Monday they go back to 0: the top 10 get a title.",
  "Estrellas de la Mítica ganadas esta semana.": "Mythic stars won this week.",
  "Cada lunes vuelven a 0: los 10 primeros se llevan un título.": "Every Monday they go back to 0: the top 10 get a title.",
  "Así quedó la semana pasada. Los 10 primeros ya tienen su título en el armario.": "This is how last week ended. The top 10 already have their title in the wardrobe.",
  "Así quedó la semana pasada.": "This is how last week ended.",
  "Los 10 primeros ya tienen su título en el armario.": "The top 10 already have their title in the wardrobe.",
  "Todas las estrellas de la Mítica semanal, sumando todas las semanas.": "Every weekly Mythic star, adding up all the weeks.",
  "Gana una estrella en la Mítica esta semana para entrar.": "Win a Mythic star this week to get in.",
  "La semana pasada no ganaste estrellas en la Mítica.": "Last week you didn't win any Mythic stars.",
  "Gana tu primera estrella en la Mítica para entrar.": "Win your first Mythic star to get in.",
  "1 nivel": "1 level",
  "%#1 niveles": "%1 levels",
  "1 semana": "1 week",
  "%#1 semanas": "%1 weeks",
  "Top 10 de la Mítica": "Mythic Top 10",
  "Podio mítico": "Mythic podium",
  "Empleado de la semana": "Employee of the Week",
  "Acaba una semana entre los 10 primeros de la Mítica": "Finish a week in the Mythic top 10",
  "Acaba una semana entre los 3 primeros de la Mítica": "Finish a week in the Mythic top 3",
  "Gana una semana de la Mítica": "Win a week of Mythic",
  "ahora se reinicia": "now resets",
  "cada lunes": "every Monday",
  ": tus estrellas vuelven a 0, pero los niveles siguen abiertos. Las que ganes suben tu puesto en el": ": your stars go back to 0, but the levels stay open. The ones you win raise your rank in the",
  ", y los 10 primeros se llevan un título. Microblizz lo llama «contenido renovado». Yo lo llamo trabajar gratis cada semana.": ", and the top 10 get a title. Microblizz calls it “refreshed content”. I call it working for free every week.",
  // el aspecto del rival en el PvP (v0.9.110)
  "TU RIVAL": "YOUR RIVAL",
  "CONTRA": "VS",
});
