// Fans of Rumble · Inglés: dificultades Fácil y Heroica de la campaña (v0.9.55)
'use strict';
IDIOMA.add({
  "<b>RAREZAS CON LOS COLORES DE SIEMPRE</b>: Poco común en verde, Rara en azul, Épica en lila y Legendaria en naranja (los líderes también). Lo que antes era Común ahora se llama Poco común. Y llegan dos rarezas nuevas que aún no tienen nada: Común (gris) y Mítica (roja), reservada para premios de eventos y torneos.": "<b>RARITIES IN THE USUAL COLORS</b>: Uncommon in green, Rare in blue, Epic in purple and Legendary in orange (leaders too). What used to be Common is now called Uncommon. And two new rarities arrive with nothing in them yet: Common (gray) and Mythic (red), saved for event and tournament prizes.",
  "<b>CALIDAD CON ESTRELLAS</b>: la calidad de cada copia ahora se ve con estrellas, de ★☆☆☆☆ (Becario) a ★★★★★ (CEO). Así el color solo te dice la rareza.": "<b>QUALITY WITH STARS</b>: the quality of each copy is now shown with stars, from ★☆☆☆☆ (Intern) to ★★★★★ (CEO). That way the color only tells you the rarity.",
  "Microblizz ha pintado de rojo una rareza que todavía no existe. Ya están preparando el precio.": "Microblizz has painted a rarity that doesn't exist yet in red. They're already working on the price.",
  "Fácil": "Easy",
  "Heroica": "Heroic",
  "FÁCIL": "EASY",
  "HEROICA": "HEROIC",
  "Fácil: rivales más flojos, sin hechizos ni equipo, para practicar o subir tus cartas con calma. Premios a la mitad, y aquí no se liberan facciones.": "Easy: weaker rivals, no spells or gear, to practise or level up your cards calmly. Half rewards, and factions aren't freed here.",
  "Heroica: rivales de nivel 8 a 11, buen equipo y la ruleta de la semana, pero solo con la ventaja de la CPU (sin castigo para ti). Premios x2,5.": "Heroic: level 8 to 11 rivals, good gear and the weekly wheel, but only with the CPU's advantage (no punishment for you). Rewards x2.5.",
  "premios a la mitad": "half rewards",
  "premios x2,5": "rewards x2.5",
  "Pásate este mundo en Difícil para jugarlo en Heroica.": "Beat this world on Hard to play it on Heroic.",
  "Pásate este mundo en Heroica para jugarlo en Mítica.": "Beat this world on Heroic to play it on Mythic.",
  "Bloqueado: gana al jefe del mundo anterior en Fácil (o ábrelo en Normal).": "Locked: beat the previous world's boss on Easy (or unlock it on Normal).",
  "ESTA SEMANA EN HEROICA": "THIS WEEK IN HEROIC",
  "LA VENTAJA DE LA CPU EN HEROICA": "THE CPU'S HEROIC ADVANTAGE",
  "En Heroica no hay castigo para ti, pero Microblizz le hace un regalo a la CPU. Cambia cada lunes.": "On Heroic there's no punishment for you, but Microblizz gives the CPU a gift. It changes every Monday.",
  "Rivales más flojos. ¡A practicar!": "Weaker rivals. Time to practise!",
  "Ventaja de la CPU: %1": "CPU advantage: %1",
  "%1: rival de nivel %2, con menos CAOS, tropas más flojas y torres más débiles.": "%1: level %2 rival, with less CHAOS, weaker troops and weaker towers.",
  "En Fácil no se liberan facciones: gana este jefe en Normal para que se unan %1.": "Factions aren't freed on Easy: beat this boss on Normal so that %1 join you.",
  "en Heroica": "on Heroic",
  "(Heroica)": "(Heroic)",
  "Heroicidades": "Heroics",
  "Gana a un jefe en Heroica.": "Beat a boss on Heroic.",
  "Gana a %1 jefes en Heroica.": "Beat %1 bosses on Heroic.",
  "Microblizz le dio ventaja a la CPU y ni con esas.": "Microblizz gave the CPU an edge and it still wasn't enough.",
  "La CPU tenía enchufe, y aun así.": "The CPU had connections, and still.",
  "Gira la ruleta de la semana.": "Spin the weekly wheel.",
  "Gira %1 veces la ruleta de la semana.": "Spin the weekly wheel %1 times.",
  "<b>DOS DIFICULTADES NUEVAS EN LA CAMPAÑA</b>: ahora hay cinco, de la más fácil a la más dura: Fácil, Normal, Difícil, Heroica y Mítica.": "<b>TWO NEW CAMPAIGN DIFFICULTIES</b>: there are now five, from easiest to hardest: Easy, Normal, Hard, Heroic and Mythic.",
  "<b>FÁCIL</b>: rivales más flojos, sin hechizos ni equipo. Para practicar o subir tus cartas con calma. Premios a la mitad, y aquí no se liberan facciones.": "<b>EASY</b>: weaker rivals, no spells or gear. To practise or level up your cards calmly. Half rewards, and factions aren't freed here.",
  "<b>HEROICA</b>: entre Difícil y Mítica. Rivales de nivel 8 a 11, buen equipo y la ruleta de la semana, pero solo gira la ventaja de la CPU: a ti no te castiga. Premios x2,5. Se abre al pasar cada mundo en Difícil, y ahora la Mítica se abre al pasarlo en Heroica (si ya tenías estrellas en Mítica, ese mundo sigue abierto).": "<b>HEROIC</b>: between Hard and Mythic. Level 8 to 11 rivals, good gear and the weekly wheel, but only the CPU's advantage spins: no punishment for you. Rewards x2.5. It unlocks when you beat each world on Hard, and Mythic now unlocks when you beat it on Heroic (if you already had stars on Mythic, that world stays open).",
  "Microblizz ha añadido un modo Fácil para los accionistas. Siguen perdiendo.": "Microblizz added an Easy mode for its shareholders. They're still losing.",
  "<b>PROBABILIDADES MÁS CLARAS</b>: en el Gashapón, la letra pequeña de abajo ahora es una lista: una probabilidad por línea, y las garantías aparte.": "<b>CLEARER ODDS</b>: in the Gacha, the small print at the bottom is now a list: one probability per line, with the guarantees separate.",
  "Microblizz ha puesto las probabilidades en lista para que se lean mejor. Las malas, igual de pequeñas.": "Microblizz put the odds in a list so they're easier to read. The bad ones are just as small.",
  "<b>GARANTÍAS CON BARRA</b>: en el Gashapón, cada garantía (épica, legendaria, calidad Director) ahora tiene su barra de progreso: ves cuánto llevas y cuánto te falta, y cuando estás cerca la barra se pone naranja y late.": "<b>PITY BARS</b>: in the Gacha, each guarantee (epic, legendary, Director quality) now has a progress bar: you see how far along you are and how much is left, and when you're close the bar turns orange and pulses.",
  "Microblizz ha añadido una barrita de progreso. Casi seguro que no tiene nada que ver con que gastes más gemas.": "Microblizz added a little progress bar. It almost certainly has nothing to do with you spending more gems.",
});
