// Fans of Rumble · Inglés: el PvP (pantalla de buscar rival, avisos y pantalla final)
'use strict';
IDIOMA.add({
  "Estándar": "Standard",
  "Salvaje": "Wild",
  "Cuentan tu mazo y el nivel y las estrellas de tus cartas. Los objetos y las habilidades no entran.": "Your deck and the level and stars of your cards count. Items and abilities do not.",
  "Cuenta todo lo que llevas puesto: las habilidades de tus cartas y el equipo de tu líder.": "Everything you wear counts: your cards' abilities and your leader's gear.",
  "BUSCAR RIVAL": "FIND A RIVAL",
  "CANCELAR": "CANCEL",
  "JUGAR CONTRA LA IA": "PLAY AGAINST THE AI",
  "Buscando rival… %1 s": "Looking for a rival… %1 s",
  "No hay rivales ahora. ¿Juegas contra la IA?": "No rivals right now. Play against the AI?",
  "Red: %1": "Network: %1",
  "Pruebas (dos pestañas de este navegador)": "Test (two tabs of this browser)",
  "Rival: %1": "Rival: %1",
  "No se ha podido empezar la partida": "The match could not start",
  "Esperando al rival…": "Waiting for the rival…",
  "¿Rendirte?": "Give up?",
  "Si te rindes, la partida cuenta como una derrota.": "If you give up, the match counts as a defeat.",
  "ME RINDO": "I GIVE UP",
  "PARTIDA ANULADA": "MATCH VOIDED",
  "Has tirado la base de %1.": "You took down %1's base.",
  "%1 ha tirado tu base.": "%1 took down your base.",
  "%1 se ha ido de la partida.": "%1 left the match.",
  "Te has rendido.": "You gave up.",
  "Las dos copias de la partida no coinciden. No cuenta para nadie.": "The two copies of the match do not agree. It counts for nobody.",
  "No se ha podido seguir con la partida. No cuenta para nadie.": "The match could not continue. It counts for nobody.",
  "Partida de pruebas: de momento sin puntos ni premios.": "Test match: no points or prizes for now.",
  "OTRO RIVAL": "ANOTHER RIVAL",
  "Campo normal": "Normal field",
  "tu rival": "your rival",
});
