// Fans of Rumble · Inglés: textos que se quedaban en español (misiones de estrellas, habilidades de varias unidades, pantalla de victoria)
'use strict';
IDIOMA.add({
  "Consigue %1 estrellas en el mundo %2 en Fácil.": "Get %1 stars in world %2 on Easy.",
  "Consigue %1 estrellas en el mundo %2 en Heroica.": "Get %1 stars in world %2 on Heroic.",
  "Consigue las 12 estrellas del mundo %1 en Fácil.": "Get all 12 stars in world %1 on Easy.",
  "Consigue las 12 estrellas del mundo %1 en Heroica.": "Get all 12 stars in world %1 on Heroic.",
  "Si la carta saca varias unidades, las copias son más pequeñas.": "If the card brings several units, the copies are smaller.",
  "Si la carta saca varias unidades, se lo reparten.": "If the card brings several units, they share it.",
  "¡3 estrellas!": "3 stars!",
  "(perdiste una torre)": "(you lost a tower)",
  "(te faltó tirar su base)": "(you missed taking down its base)",
  "+%1 % de daño. Hecha a mano en una convención.": "+%1 % damage. Handmade at a convention.",
  "+%1 % de alcance y +%2 % de daño.": "+%1 % range and +%2 % damage.",
  "+%1 % de daño y cada golpe aparta al enemigo.": "+%1 % damage and every hit pushes the enemy away.",
  "+%1 % de vida y +%2 % de daño.": "+%1 % health and +%2 % damage.",
  "Inmune a las habilidades del jefe y +%1 % de vida.": "Immune to the boss's abilities and +%1 % health.",
  "Se cura un %1 % de su vida cada segundo.": "Heals %1 % of its health every second.",
  "+%1 % a todo. Algo es algo.": "+%1 % to everything. Better than nothing.",
  "Si cae, vuelve un %1 % antes.": "If it falls, it comes back %1 % sooner.",
  "Recibe un %1 % menos de daño.": "Takes %1 % less damage.",
  "Cada partida, un efecto sorpresa (o ninguno) con un %1 % de potencia.": "Each match, a surprise effect (or none) at %1 % power.",
  "+%1 % de vida y +%2 % de daño. Enmarcado en plástico. Exclusivo del pase.": "+%1 % health and +%2 % damage. Framed in plastic. Pass exclusive.",
  "+%1 % de vida, +%2 % de daño y +%3 % de velocidad. Viste como el que te despide. Exclusivo del Pase Ejecutivo.": "+%1 % health, +%2 % damage and +%3 % speed. Dresses like the one who fires you. Executive Pass exclusive.",
  "El %1 % de sus golpes son críticos y hacen el triple. Está durísima.": "%1 % of its hits are critical and deal triple damage. It's brutal.",
  "Cada golpe salpica el %1 % del daño a los enemigos de alrededor.": "Every hit splashes %1 % of the damage onto nearby enemies.",
  "+%1 % de velocidad. Más estilo, más rápido.": "+%1 % speed. More style, more speed.",
  "No ve el peligro: +%1 % de daño, pero un 10 % menos de vida.": "Can't see the danger: +%1 % damage, but 10 % less health.",
  "Los enemigos de alrededor pegan un %1 % menos. Es que es muy mono.": "Nearby enemies hit %1 % less. It's just so cute.",
  "Los primeros 10 s: +%1 % de daño y de velocidad.": "First 10 s: +%1 % damage and speed.",
  "+%1 % de vida. Es suyo para siempre: nadie se lo puede quitar.": "+%1 % health. It's theirs forever: nobody can take it away.",
  "Los aliados de alrededor se curan un %1 % de su vida cada segundo.": "Nearby allies heal %1 % of their health every second.",
  "+%1 % de daño y su Chaos Jump vuelve un %2 % antes.": "+%1 % damage and its Chaos Jump comes back %2 % sooner.",
  "+%1 % de vida y se cura un %2 % de su vida cada segundo.": "+%1 % health and heals %2 % of its health every second.",
  "+%1 % de daño y los aliados de alrededor se curan un %2 % cada segundo.": "+%1 % damage and nearby allies heal %2 % every second.",
  "+%1 % de vida y recibe un %2 % menos de daño.": "+%1 % health and takes %2 % less damage.",
  "Escudo de plasma del %1 % de su vida y +%2 % de daño.": "Plasma shield of %1 % of its health and +%2 % damage.",
  "El %1 % de sus golpes son críticos (triple) y +%2 % de velocidad. Deal with it.": "%1 % of its hits are critical (triple) and +%2 % speed. Deal with it.",
  "Ataca un %1 % más rápido y +%2 % de alcance.": "Attacks %1 % faster and +%2 % range.",
  "+%1 % de vida y de daño, y las torres tardan %2 s más en acordarse de él.": "+%1 % health and damage, and towers take %2 s longer to remember it.",
  "+%1 % de daño y cada golpe salpica el %2 % a los de alrededor.": "+%1 % damage and every hit splashes %2 % onto those around it.",
  "Una vez por vida, cuando va a caer, se pausa y es invulnerable %1 s.": "Once per life, when it is about to fall, it pauses and is invulnerable for %1 s.",
  "+%1 % de daño y se cura un %2 % de su vida cada segundo. Pone «Me voy a mi hora».": "+%1 % damage and heals %2 % of its health every second. Says «I'm leaving on my own time».",
  "+%1 % de alcance. El cable llega a todas partes.": "+%1 % range. The cable reaches everywhere.",
  "<b>MENOS TECNICISMOS</b>: en español, el PvP pasa a llamarse JcJ y el RANKING, CLASIFICACIÓN. Y en inglés hemos traducido más descripciones de objetos, misiones y la pantalla de victoria.": "<b>FEWER TECHNICAL TERMS</b>: in Spanish, PvP is now called JcJ and RANKING is now CLASIFICACIÓN. And in English we have translated more item descriptions, missions and the victory screen.",
  "Microblizz quería explicar el JcJ con menos siglas. Phony ha propuesto «JvJ». Se le ha dicho que no.": "Microblizz wanted to explain PvP with fewer acronyms. Phony suggested «JvJ». He was told no.",
  "<b>PVP VUELVE A SU NOMBRE</b>: lo de JcJ no convencía, así que en español vuelve a decir PvP. La CLASIFICACIÓN y los «ingresos» se quedan.": "<b>PVP IS PVP AGAIN</b>: JcJ didn't catch on, so Spanish says PvP again. CLASIFICACIÓN and «ingresos» stay.",
  "Phony reclama que le devuelvan su «JvJ». Microblizz no sabe de qué le habla.": "Phony demands his «JvJ» back. Microblizz has no idea what he is talking about.",
});
