// Fans of Rumble · Inglés: la Arena con dos pestañas (Contra jugadores y Entrenamiento), copas y ligas del PvP
'use strict';
IDIOMA.add({
  // las pestañas
  "CONTRA JUGADORES": "VS PLAYERS",
  "Contra jugadores": "VS Players",
  "PvP en directo": "Live PvP",
  "cuenta para tu liga": "counts for your league",
  "ENTRENAMIENTO": "TRAINING",
  "contra la CPU": "vs the CPU",
  "sin cuenta": "no account needed",
  "Tipo de rival": "Type of rival",
  "El PvP está cerrado ahora mismo": "PvP is closed right now",
  // entrenamiento
  "PRACTICA SIN PRESIÓN": "PRACTICE, NO PRESSURE",
  "Rivales de la CPU. Tus copas no cambian. Ganas oro y avanzas en las misiones. Sin internet y sin cuenta.": "CPU rivals. Your cups don't change. You earn gold and progress your missions. No internet or account needed.",
  "ELIGE RIVAL": "CHOOSE A RIVAL",
  "Otros rivales": "Other rivals",
  "Racha %#1": "Streak %#1",
  "Nivel %#1": "Level %#1",
  "Si ganas: %1": "If you win: %1",
  "Si pierdes: %1": "If you lose: %1",
  "%#1 de oro": "%#1 gold",
  "cuenta para las misiones": "counts for missions",
  "¿Listo para subir de liga? Las copas solo se ganan en": "Ready to climb a league? Cups are only won in",
  "¿Listo para subir de liga?": "Ready to climb a league?",
  "Las copas solo se ganan en": "Cups are only won in",
  "ENTRENAR": "TRAIN",
  "contra %1": "vs %1",
  "Esto es el <b>ENTRENAMIENTO</b> de la Arena: eliges uno de 3 rivales de la CPU y ganas oro y misiones. Las <b>copas</b> y las ligas, de Becario a CEO, se ganan en <b>CONTRA JUGADORES</b>. Como en una empresa, pero aquí los ascensos existen.": "This is the Arena's <b>TRAINING</b>: pick one of 3 CPU rivals and earn gold and missions. <b>Cups</b> and leagues, from Intern to CEO, are won in <b>VS PLAYERS</b>. Like a company, except here promotions actually exist.",
  // contra jugadores
  "LIGA %1": "%1 LEAGUE",
  "Liga %1": "%1 League",
  "%1 copas": "%1 cups",
  "Récord %1": "Record %1",
  "%#1 ganadas": "%#1 won",
  "%#1 perdidas": "%#1 lost",
  "LIGA MÁXIMA": "TOP LEAGUE",
  "%1 / %2 → %3": "%1 / %2 → %3",
  "unas +12 copas": "about +12 cups",
  "puntos del Pase PvP": "PvP Pass points",
  "unas −12 copas": "about −12 cups",
  "CLASIFICACIÓN": "LEADERBOARD",
  "Ver entera": "See all",
  "%1 (tú)": "%1 (you)",
  "Entra con tu cuenta para ver la clasificación.": "Sign in to see the leaderboard.",
  "Cargando…": "Loading…",
  "Sin conexión: no se puede ver la clasificación.": "Offline: the leaderboard can't be loaded.",
  "Todavía no hay nadie en la clasificación.": "Nobody on the leaderboard yet.",
  "Partidas en la última hora: %1": "Matches in the last hour: %1",
  "FACCIÓN": "FACTION",
  "MAZO": "DECK",
  "LISTO": "DONE",
  // buscando rival
  "%1 · LIGA %2": "%1 · %2 LEAGUE",
  "VS": "VS",
  "Buscando…": "Searching…",
  "un rival de verdad": "a real rival",
  "Buscamos a alguien para jugar contigo. Puedes cancelar cuando quieras.": "We're looking for someone to play with you. You can cancel any time.",
  "Hay poca gente ahora mismo. Sigues en la cola.": "Not many people around right now. You're still in the queue.",
  "¿Hay poca gente ahora?": "Not many people around?",
  "Juega un entrenamiento contra la CPU. Da oro y cuenta para tus misiones.": "Play a training match against the CPU. It gives gold and counts for your missions.",
  "MIENTRAS ESPERAS": "WHILE YOU WAIT",
  "Una partida PvP dura unos 4 minutos. Si te rindes, cuenta como derrota.": "A PvP match lasts about 4 minutes. If you surrender, it counts as a loss.",
  "CANCELAR": "CANCEL",
  // final de partida y perfil
  "%1 COPAS · %2 · LIGA %3": "%1 CUPS · %2 · %3 LEAGUE",
  "PVP": "PVP",
  "RÉCORD DE COPAS": "CUP RECORD",
  "ganadas - perdidas": "won - lost",
  "tu mejor marca": "your best",
  // novedades 0.9.110
  "<b>LA ARENA, TODA JUNTA</b>: un solo botón ARENA con dos pestañas. CONTRA JUGADORES es el PvP de verdad: ahí ganas o pierdes copas y subes de liga, de Becario a CEO, y ves tu puesto en la clasificación. ENTRENAMIENTO es la arena de siempre contra la CPU: no mueve copas, pero da oro y cuenta para las misiones, y funciona sin internet ni cuenta.": "<b>THE ARENA, ALL IN ONE</b>: a single ARENA button with two tabs. VS PLAYERS is real PvP: that's where you win or lose cups, climb leagues from Intern to CEO and see your spot on the leaderboard. TRAINING is the classic arena against the CPU: no cups, but it gives gold, counts for missions and works with no internet or account.",
  "<b>BUSCAR RIVAL, MÁS CLARO</b>: mientras esperas ves tu líder contra un «?», el reloj y un botón para entrenar si hay poca gente. Las misiones de la Arena cuentan también las partidas de PvP.": "<b>FINDING A RIVAL, CLEARER</b>: while you wait you see your leader against a «?», the clock and a button to train if few people are around. Arena missions now count PvP matches too.",
  "Microblizz ha juntado sus dos arenas en una para ahorrar en alquiler. Los becarios siguen en la de la CPU.": "Microblizz merged its two arenas into one to save on rent. The interns are still in the CPU one.",
  // novedades 0.9.111
  "<b>FACCIONES EN LA ARENA</b>: en CONTRA JUGADORES, el botón FACCIÓN enseña las facciones en dos filas de 5 con su nombre, igual que en el resto del juego.": "<b>FACTIONS IN THE ARENA</b>: in VS PLAYERS, the FACTION button shows the factions in two rows of 5 with their names, just like the rest of the game.",
  "Microblizz quería poner 9 y 1 por pura asimetría corporativa. El becario lo ha cuadrado.": "Microblizz wanted 9 and 1 out of pure corporate asymmetry. The intern squared it up.",
  "<b>MÍTICA SEMANAL</b>: en la dificultad Mítica las estrellas vuelven a 0 cada lunes. La campaña tiene una caja TEMPORADA MÍTICA con la cuenta atrás, y el Salón de la Fama una pestaña Mítica (esta semana, la pasada y de siempre). Cada semana vuelves a cobrar su oro y sus gemas, y los 10 primeros se llevan un título.": "<b>WEEKLY MYTHIC</b>: on Mythic difficulty, stars reset to 0 every Monday. The campaign has a MYTHIC SEASON box with the countdown, and the Hall of Fame has a Mythic tab (this week, last week and all time). Every week you can earn its gold and gems again, and the top 10 get a title.",
  "<b>TU CARA EN EL PVP</b>: tu rival ve tu avatar, tu marco y tu título en la cuenta atrás, en la pantalla final y en la clasificación.": "<b>YOUR FACE IN PVP</b>: your rival sees your avatar, frame and title in the countdown, the end screen and the leaderboard.",
});
