// Fans of Rumble · Inglés: logros nuevos de la 0.9.112 (PvP, CEO, misiones fijas, Mítica semanal, sanadores y armario)
'use strict';
IDIOMA.add({
  "PvP": "PvP",
  "Cara a cara": "Face to Face",
  "Gana una partida PvP.": "Win a PvP match.",
  "Gana %#1 partidas PvP.": "Win %1 PvP matches.",
  "Esta vez el rival no era un robot.": "This time the rival wasn't a robot.",
  "Trepa corporativo": "Corporate Climber",
  "Llega a la liga %1 en el PvP.": "Reach the %1 league in PvP.",
  "Ascenso por méritos. Por fin.": "Promoted on merit. Finally.",
  "Relaciones públicas": "Public Relations",
  "Usa %1 frases o emoticonos en el chat.": "Use %1 phrases or emotes in the chat.",
  "Comunicación corporativa de primer nivel.": "Top-tier corporate communication.",
  "Despacho del CEO": "The CEO's Office",
  "Gana una partida rápida en CEO.": "Win a quick match on CEO.",
  "Gana %#1 partidas rápidas en CEO.": "Win %1 quick matches on CEO.",
  "Ahora el despacho es tuyo.": "The office is yours now.",
  "Mantenimiento de edificios": "Building Maintenance",
  "Tus sanadores curan %1 de vida a tus torres.": "Your healers restore %1 health to your towers.",
  "Sin presupuesto, pero con tiritas.": "No budget, but plenty of plasters.",
  "Empleado ejemplar": "Model Employee",
  "Sé Empleado del día.": "Be Employee of the Day.",
  "Sé Empleado del día %#1 veces.": "Be Employee of the Day %1 times.",
  "Tu foto ya cuelga en la pared de la oficina.": "Your photo already hangs on the office wall.",
  "Empleado del año": "Employee of the Year",
  "Completa «Empleado del mes».": "Complete «Employee of the Month».",
  "Completa «Empleado del mes» %#1 veces.": "Complete «Employee of the Month» %1 times.",
  "Microblizz te sube el sueldo un 0,1 %.": "Microblizz gives you a 0.1 % raise.",
  "Fondo de armario": "Wardrobe Staples",
  "Consigue %#1 marcos o títulos.": "Get %1 frames or titles.",
  "Consigue todos los marcos y títulos.": "Get every frame and title.",
  "Vestido para el éxito. Y para el despido.": "Dressed for success. And for the layoff.",
  "Habitual de la Mítica": "Mythic Regular",
  "Consigue estrellas en la Mítica una semana.": "Earn stars in the Mythic one week.",
  "Consigue estrellas en la Mítica %#1 semanas distintas.": "Earn stars in the Mythic in %1 different weeks.",
  "La ruleta ya te saluda por tu nombre.": "The wheel already greets you by name.",
  "Top 10": "Top 10",
  "Acaba entre los 10 primeros de la Mítica semanal.": "Finish in the top 10 of the weekly Mythic.",
  "Acaba %#1 semanas entre los 10 primeros de la Mítica semanal.": "Finish in the top 10 of the weekly Mythic %1 weeks.",
  "Sales en la foto del Salón de la Fama.": "You're in the Hall of Fame photo.",
  "Contra todo pronóstico": "Against All Odds",
  "Gana en CEO con el castigo «Torres de cartón».": "Win on CEO with the «Cardboard towers» punishment.",
  "Las torres eran de cartón. Tu estrategia, no.": "The towers were cardboard. Your strategy wasn't.",
  "Pista: gana al CEO con las torres más frágiles.": "Hint: beat the CEO with the flimsiest towers.",
  "Ni un rasguño ejecutivo": "Not an Executive Scratch",
  "Gana en CEO sin perder ninguna torre.": "Win on CEO without losing a tower.",
  "El CEO pide revisar las cámaras.": "The CEO wants to review the footage.",
  "Pista: contra el CEO, sin un rasguño.": "Hint: against the CEO, without a scratch.",
  "Te lo dije": "Told You So",
  "Gana una partida PvP después de perder dos torres.": "Win a PvP match after losing two towers.",
  "Tu rival ya estaba escribiendo «GG».": "Your rival was already typing «GG».",
  "Pista: contra otra persona, nunca te rindas.": "Hint: against another person, never give up.",
  "<b>13 LOGROS NUEVOS</b>: hay pestaña de <b>PvP</b> (Cara a cara, Trepa corporativo y Relaciones públicas) y logros para el modo CEO, Empleado del día y del mes, la Mítica semanal, el Top 10, el armario y los sanadores que curan torres. Y tres secretos más.": "<b>13 NEW ACHIEVEMENTS</b>: there is a <b>PvP</b> tab (Face to Face, Corporate Climber and Public Relations) and achievements for CEO mode, Employee of the Day and of the Month, the weekly Mythic, the Top 10, the wardrobe and healers that heal towers. And three more secrets.",
  "<b>GASHAPÓN MÁS EXIGENTE</b>: en las máquinas de habilidades y de objetos las legendarias salen menos (de 1 de cada 23 tiradas a 1 de cada 50), y la legendaria asegurada llega a las 90 tiradas. Así tener una vuelve a ser algo especial.": "<b>A TOUGHER GACHA</b>: in the abilities and items machines legendaries are rarer (from 1 in 23 pulls to 1 in 50), and the guaranteed legendary arrives at 90 pulls. So getting one feels special again.",
  "<b>ARREGLO</b>: la Corbata del CEO ya no aparece en la cara de los líderes.": "<b>FIX</b>: the CEO's Tie no longer shows up on the leaders' faces.",
  "Microblizz ha recortado las legendarias para pagar los logros nuevos. Lo llama «optimizar la experiencia».": "Microblizz cut legendaries to pay for the new achievements. It calls it «optimising the experience».",
});
