// Fans of Rumble · Inglés: el PvP (pantalla de buscar rival, avisos y pantalla final) y la partida guiada larga con los consejos de Lola (v0.9.91)
'use strict';
IDIOMA.add({
  "Estándar": "Standard",
  "Salvaje": "Wild",
  "Cuentan tu mazo y el nivel y las estrellas de tus cartas. Los objetos y las habilidades no entran.": "Your deck and the level and stars of your cards count. Items and abilities do not.",
  "Cuenta todo lo que llevas puesto: las habilidades de tus cartas y el equipo de tu líder.": "Everything you wear counts: your cards' abilities and your leader's gear.",
  "BUSCAR RIVAL": "FIND A RIVAL",
  "CANCELAR": "CANCEL",
  "JUGAR CONTRA LA IA": "PLAY AGAINST THE AI",
  "Buscando rival… %1 s": "Looking for a rival… %1 s",
  "No hay rivales todavía. Sigues en la cola… %1 s. ¿Juegas contra la IA mientras tanto?": "No rivals yet. You are still in the queue… %1 s. Play against the AI meanwhile?",
  "Red: %1": "Network: %1",
  "Pruebas (dos pestañas de este navegador)": "Test (two tabs of this browser)",
  "Rival: %1": "Rival: %1",
  "No se ha podido empezar la partida": "The match could not start",
  "Esperando al rival…": "Waiting for the rival…",
  "¿Rendirte?": "Give up?",
  "Si te rindes, la partida cuenta como una derrota.": "If you give up, the match counts as a defeat.",
  "ME RINDO": "I GIVE UP",
  "PARTIDA ANULADA": "MATCH VOIDED",
  "Has tirado la base de %1.": "You took down %1's base.",
  "%1 ha tirado tu base.": "%1 took down your base.",
  "%1 se ha ido de la partida.": "%1 left the match.",
  "Te has rendido.": "You gave up.",
  "Las dos copias de la partida no coinciden. No cuenta para nadie.": "The two copies of the match do not agree. It counts for nobody.",
  "No se ha podido seguir con la partida. No cuenta para nadie.": "The match could not continue. It counts for nobody.",
  "Partida de pruebas: de momento sin puntos ni premios.": "Test match: no points or prizes for now.",
  "OTRO RIVAL": "ANOTHER RIVAL",
  "Campo normal": "Normal field",
  "tu rival": "your rival",
  "<b>CAMPO IGUAL PARA LOS DOS</b>: tu sede y la del rival están ahora a la misma distancia del río (antes la suya estaba más cerca) y las zonas de los campos de jefe se reparten iguales arriba y abajo. Así es justo, también para el PvP que viene.": "<b>THE SAME FIELD FOR BOTH SIDES</b>: your HQ and the rival's are now the same distance from the river (before, theirs was closer) and the zones on boss fields are laid out identically on both halves. It's fair now, also for the PvP that is coming.",
  "Microblizz ha medido el campo con una cinta métrica y ha descubierto que llevaba años jugando en cuesta. Y sí, la versión ha saltado de la 0.9.72 a la 0.9.82: en el taller pasaron muchas cosas con la puerta cerrada y el equipo de contabilidad se ha negado a contarlas.": "Microblizz measured the field with a tape measure and discovered it had been playing uphill for years. And yes, the version jumped from 0.9.72 to 0.9.82: a lot happened in the workshop behind closed doors and the accounting team refused to talk about it.",
  "Para jugar PvP necesitas vincular tu cuenta (Opciones → Cuenta)": "To play PvP you need to link your account (Options → Account)",
  "Tu sesión ha caducado: vuelve a abrir el juego (una cuenta por navegador o perfil)": "Your session has expired: open the game again (one account per browser or profile)",
  "Tu mazo no vale para el PvP": "Your deck is not valid for PvP",
  "Llevas un objeto que no está en tu cuenta": "You are wearing an item that is not in your account",
  "La sala ya no existe": "The room no longer exists",
  "Demasiadas jugadas seguidas": "Too many plays in a row",
  "Necesitas conexión para jugar PvP": "You need a connection to play PvP",
  "El PvP necesita conexión": "PvP needs a connection",
  "CLASIFICACIÓN": "LEADERBOARD",
  "ESTÁNDAR": "STANDARD",
  "SALVAJE": "WILD",
  "%1 partidas": "%1 matches",
  "Todavía no hay nadie en la clasificación.": "Nobody is on the leaderboard yet.",
  "Esperando al servidor…": "Waiting for the server…",
  "%1 PUNTOS": "%1 POINTS",
  "Esperando a que el rival confirme el resultado…": "Waiting for the rival to confirm the result…",
  "El resultado está en revisión: no cuenta por ahora.": "The result is under review: it doesn't count for now.",
  "Esta partida no cuenta para nadie.": "This match counts for nobody.",
  "<b>LA IA SE DEFIENDE CON CABEZA</b>: cuando le atacas, responde con la unidad que mejor contrarresta la tuya (contra un tanque, asesinos o control; contra un enjambre, control o tiradores…).": "<b>THE AI DEFENDS WITH ITS HEAD</b>: when you attack it, it answers with the unit that best counters yours (against a tank, assassins or control; against a swarm, control or shooters…).",
  "<b>ARREGLO: JEFES Y RIVALES QUE SE QUEDABAN QUIETOS</b>: los hechizos de la máquina ya no se le atascan en la mano, así que los jefes siguen sacando tropas hasta el final. Y en las fases con pocas cartas, la máquina puede repetir carta como antes.": "<b>FIX: BOSSES AND RIVALS THAT STOOD STILL</b>: the machine's spells no longer get stuck in its hand, so bosses keep sending troops until the end. And in levels with few cards, the machine can repeat a card like before.",
  "<b>FÁCIL, PERO NO TONTA</b>: en la partida rápida en Fácil la máquina piensa un poco más deprisa. Sigue siendo fácil de ganar, pero ya juega a tiempo.": "<b>EASY, NOT DUMB</b>: in Easy quick matches the machine thinks a bit faster. It's still easy to beat, but now it plays on time.",
  "Microblizz ha descubierto que su IA guardaba los hechizos en el bolsillo «por si acaso» y se olvidaba de jugar. La han mandado a un curso de productividad.": "Microblizz found out its AI kept its spells in its pocket \"just in case\" and forgot to play. It has been sent on a productivity course.",
  "<b>PVP: ¡A POR EL RIVAL!</b> Ya puedes retar a otros jugadores en el modo Estándar (con tu mazo, niveles y estrellas; los objetos no cuentan) y subir en la clasificación. Necesitas vincular tu cuenta (Opciones → Cuenta). Si no aparece nadie en 30 s, puedes jugar contra la IA sin salir de la cola.": "<b>PVP: GO FOR THE RIVAL!</b> You can now challenge other players in Standard mode (your deck, levels and stars count; items don't) and climb the ranking. You need to link your account (Options → Account). If nobody shows up in 30 s, you can play against the AI without leaving the queue.",
  "<b>IA RIVAL MÁS LISTA</b>: la máquina juega con la misma mano de 4 cartas que tú, responde a lo que tienes en el campo, contraataca por el carril que acaba de defender y ya no desperdicia el CAOS casi lleno.": "<b>SMARTER RIVAL AI</b>: the machine plays with the same 4-card hand as you, reacts to what you have on the field, counterattacks in the lane it just defended and no longer wastes an almost full CHAOS.",
  "Microblizz ha puesto una arena donde los jugadores se pegan por internet y ha descubierto que, sorpresa, todos quieren ganar. Detrás: el campo igual para los dos, matemáticas iguales en todos los navegadores y muchas sesiones de rey de la pista.": "Microblizz has built an arena where players fight over the internet and discovered that, surprise, everyone wants to win. Behind it: the same field for both sides, identical maths in every browser and many sessions of king of the track.",
  // v0.9.91: partida guiada más larga y consejos de Lola en cada modo
  "¡Mira qué te ha tocado! Ya te lo pondrás en Colección. Toca": "Look what you got! You can equip it in the Collection later. Tap",
  ": aún queda otra máquina.": ": there's one more machine.",
  "Esta es la máquina de": "This is the",
  ": de aquí salen tropas especiales y hechizos para tu mazo. Tócala.": " machine: special troops and spells for your deck come from here. Tap it.",
  "otra vez: también es gratis.": "again: it's free too.",
  "Vuelve al": "Go back to the",
  ": aún te queda una tirada gratis para la máquina de cartas.": ": you still have a free spin for the card machine.",
  "¡Una carta nueva! Toca": "A new card! Tap",
  "y la metemos en tu mazo.": "and let's put it in your deck.",
  "para meter tu carta nueva en el mazo.": "to put your new card in your deck.",
  "Este es": "This is",
  "tu mazo": "your deck",
  ": tu líder y 6 cartas, las que salen en la partida. Toca": ": your leader and 6 cards, the ones you get in battle. Tap",
  "EDITAR MAZO": "EDIT DECK",
  "Toca tu carta nueva:": "Tap your new card:",
  "Ahora toca la carta de tu mazo que quieres cambiar por ella. Por ejemplo, esta.": "Now tap the card in your deck you want to swap it for. This one, for example.",
  "¡Perfecto! Toca": "Perfect! Tap",
  ": encargos con premio.": ": tasks with rewards.",
  "Cada día tienes encargos nuevos, y otros cada semana. Cúmplelos jugando y vuelve aquí a": "Every day you get new tasks, and more every week. Complete them by playing and come back here to",
  "cobrar": "claim",
  "oro y gemas. En": "gold and gems. In",
  "hay más premios… y chistes.": "there are more rewards… and jokes.",
  "¡ENTENDIDO!": "GOT IT!",
  "Y esto son las": "And this is",
  ": tu líder sigue currando aunque cierres el juego. Como en Microblizz, pero sin cobrar. Vuelve de vez en cuando a": ": your leader keeps working even when you close the game. Like at Microblizz, but unpaid. Come back now and then to",
  "lo que gana. Tocando su cara eliges quién trabaja.": "what they earn. Tap their face to choose who works.",
  "Lo último: toca": "Last thing: tap",
  "Aquí cambias el sonido, el idioma y más cosas. Y si se te olvida algo, abajo del todo puedes repetir este tutorial. ¡Ya sabes lo básico! Cuando abras un modo nuevo, saldré a contarte cómo va.": "Here you change the sound, the language and more. And if you forget something, you can repeat this tutorial at the very bottom. You know the basics! When you open a new mode, I'll pop up to tell you how it works.",
  "Sin consejos": "No more tips",
  "Lola ya no dará consejos. Puedes volver a verlos con TUTORIAL, en Opciones": "Lola won't give any more tips. You can see them again with TUTORIAL, in Options",
  "Esto es la": "This is the",
  ". Eliges uno de 3 rivales: si ganas, te llevas": ". You pick one of 3 rivals: win and you get",
  ", oro y gemas; si pierdes, te quitan copas. Con más copas subes de liga, de Becario a CEO. Como en una empresa, pero aquí los ascensos existen.": ", gold and gems; lose and they take trophies away. With more trophies you move up a league, from Intern to CEO. Like a company, except here promotions are real.",
  "copas": "trophies",
  "En la": "In",
  "juegas cuando quieras, sin campaña.": "you play whenever you want, no campaign.",
  "es para practicar,": "is for practice,",
  "va en serio y": "is the real deal and",
  "gira la ruleta trucada de Microblizz antes de cada partida… pero paga mucho mejor.": "spins Microblizz's rigged wheel before every match… but pays much better.",
  "En el": "In",
  "te enfrentas una y otra vez a los jefes de la campaña que ya has desbloqueado. Cuanto más daño les haces, más premios. Y no se rinden nunca, como el departamento legal.": "you fight the campaign bosses you've unlocked again and again. The more damage you deal, the more rewards. And they never give up, like the legal department.",
  "La": "The",
  ": CAOS infinito, las torres no se caen y tú eliges qué enemigos salen. No da premios: es para probar mazos, hechizos y habilidades sin miedo a perder.": ": infinite CHAOS, towers don't fall and you choose which enemies appear. No rewards: it's for testing decks, spells and abilities with nothing to lose.",
  "Aquí juegas contra": "Here you play against",
  "personas de verdad": "real people",
  ". Microblizz lo llama «contenido generado por los usuarios», y no te paga. Gana para subir en la clasificación.": ". Microblizz calls it «user-generated content», and doesn't pay you. Win to climb the leaderboard.",
  ": todas las cartas, habilidades y objetos del juego, también los que aún no tienes. Mira qué hace cada cosa antes de gastarte las gemas.": ": every card, ability and item in the game, even the ones you don't have yet. Check what each one does before spending your gems.",
  "Tu": "Your",
  ": todas tus habilidades y objetos. Cada copia sale con su": ": all your abilities and items. Every copy comes with its own",
  "calidad": "quality",
  ", de Becario a CEO. Las que no te sirvan, despídelas a cambio de oro. Microblizz lo hace con personas.": ", from Intern to CEO. Fire the ones you don't need for gold. Microblizz does it with people.",
  ": al jugar ganas experiencia, y cada nivel del pase trae un premio. La fila de pago trae más, porque Microblizz no regala nada.": ": playing earns experience, and every pass level brings a reward. The paid row brings more, because Microblizz gives nothing away.",
  ". Aquí tienes un": ". Here you get a",
  "regalo gratis cada día": "free gift every day",
  ": no te lo dejes. Lo demás te lo explica mejor Microblizz con tu tarjeta de crédito.": ": don't miss it. Microblizz will explain the rest better with your credit card.",
  "RULETA": "WHEEL",
  "de Microblizz decide antes de jugar un castigo para ti, una ventaja para la CPU o las dos. Trucada, por supuesto. A cambio, el premio es mucho mayor.": "from Microblizz decides before the match a penalty for you, a bonus for the CPU, or both. Rigged, of course. In return, the reward is much bigger.",
  // novedades 0.9.91 (por trozos: el título en negrita y el resto aparte)
  "LOLA TE ENSEÑA MÁS": "LOLA TEACHES YOU MORE",
  ": la partida guiada sigue después del gashapón. Ahora te lleva a la máquina de cartas, te ayuda a meter tu carta nueva en el mazo y te enseña las misiones, las horas extra y las opciones.": ": the guided match goes on after the gacha. Now she takes you to the card machine, helps you put your new card in your deck and shows you missions, overtime and options.",
  "CONSEJOS EN CADA MODO": "TIPS IN EVERY MODE",
  ": la primera vez que abres la Arena, la Partida rápida, el Modo Jefe, el PvP, la Tienda y otras pantallas, Lola te cuenta en dos frases cómo va. Si no los quieres, toca «Sin consejos». Si ya habías hecho el tutorial, no te saldrán; los recuperas con TUTORIAL, en Opciones.": ": the first time you open the Arena, Quick Match, Boss Mode, PvP, the Shop and other screens, Lola tells you how it works in two sentences. If you don't want them, tap «No more tips». If you had already done the tutorial, you won't see them; get them back with TUTORIAL, in Options.",
  "HABILIDADES MÁS JUSTAS": "FAIRER ABILITIES",
  ": DLC, Microtransacción, Clon, Rage Quit y Gigante ganaban casi todas las partidas, así que bajan. Y si una carta saca varias unidades, el efecto de DLC, Microtransacción, Clon y Rage Quit se reparte entre ellas.": ": DLC, Microtransaction, Clone, Rage Quit and Giant were winning almost every match, so they go down. And if a card brings several units, the effect of DLC, Microtransaction, Clone and Rage Quit is split between them.",
  "Microblizz ha contratado a Lola como formadora de nuevos empleados. Sigue despedida, pero ahora también trabaja gratis.": "Microblizz has hired Lola to train new employees. She is still fired, but now she also works for free.",
  "Tu rival tiene otra versión del juego: recarga la página": "Your rival has another version of the game: reload the page",
});
