// Fans of Rumble · Inglés: misiones con título y descripción, semanal fija, misiones de la Arena y logros de Fácil (v0.9.67 y v0.9.68)
'use strict';
IDIOMA.add({
  "<b>MISIONES CON NOMBRE</b>: todas las misiones tienen ahora un título (Doble despido, ERE masivo, Pausa para el café…) y debajo lo que hay que hacer.": "<b>MISSIONS WITH NAMES</b>: every mission now has a title (Double Layoff, Mass Redundancy, Coffee Break…) and underneath, what you have to do.",
  "<b>EMPLEADO DEL MES</b>: en las semanales hay una misión fija: sé Empleado del día 7 veces en la semana. Da un premio gordo.": "<b>EMPLOYEE OF THE MONTH</b>: there is a fixed weekly mission: be Employee of the Day 7 times in the week. It pays big.",
  "<b>SEMANALES MÁS LARGAS</b>: ahora hay 5 a la semana y están pensadas para durar varios días. También se pueden cambiar con un anuncio (menos la fija).": "<b>LONGER WEEKLIES</b>: there are now 5 a week and they are meant to take several days. You can also swap them by watching an ad (except the fixed one).",
  "Recursos Humanos de Microblizz ha puesto nombre a cada tarea. El presupuesto para pagarlas todavía no ha llegado.": "Microblizz HR has named every task. The budget to pay for them hasn't arrived yet.",
  "en Fácil": "on Easy",
  "(Fácil)": "(Easy)",
  "Hasta un becario lo consigue.": "Even an intern can manage it.",
  "<b>MISIÓN «5 DIARIAS»</b>: cada día hay 6 misiones. La de «Completa 5 misiones diarias» va siempre la primera y da más premio. En la semana hay un reto: completarla 7 veces.": "<b>«5 DAILY» MISSION</b>: there are 6 missions each day. The «Complete 5 daily missions» one is always first and pays more. This week there's a challenge: complete it 7 times.",
  "<b>MISIONES DE LA ARENA</b>: jugar y ganar en la Arena cuenta para las misiones del día y de la semana.": "<b>ARENA MISSIONS</b>: winning and playing in the Arena counts toward the daily and weekly missions.",
  "<b>LOGROS DE FÁCIL</b>: la campaña en Fácil también tiene logros por estrellas, como las demás dificultades.": "<b>EASY LEVEL ACHIEVEMENTS</b>: the Easy campaign now has star achievements, like the other difficulties.",
  "Microblizz ha puesto una misión para que cumplas las demás. Es lo más parecido a un jefe que ha hecho en años.": "Microblizz has added a mission so you'll complete the others. It's the closest thing to a boss they've made in years.",
  "Empleado del día": "Employee of the Day",
  "Empleado del mes (en una semana)": "Employee of the Month (in a week)",
  "Doble despido": "Double Layoff",
  "Reparto de tareas": "Task Delegation",
  "Recorte de plantilla": "Staff Cuts",
  "Reforma de oficinas": "Office Renovation",
  "Valoración positiva": "Positive Review",
  "Reunión con el jefe": "Meeting with the Boss",
  "Una cápsula y lo dejo": "Just One More Capsule",
  "Ascenso exprés": "Fast-Track Promotion",
  "Jornada completa": "Full-Time Shift",
  "El jefe baja al campo": "The Boss Hits the Field",
  "Ni un rasguño": "Not a Scratch",
  "Modo historia": "Story Mode",
  "Pausa para el café": "Coffee Break",
  "Presupuesto ejecutado": "Budget Spent",
  "Cierre de sede": "Headquarters Closed",
  "Orgullo de facción": "Faction Pride",
  "Lo único gratis": "The Only Free Thing",
  "Afterwork en la Arena": "Arena Afterwork",
  "Clasificación trimestral": "Quarterly Ranking",
  "Maratón de historia": "Story Marathon",
  "ERE masivo": "Mass Redundancy",
  "Productividad de récord": "Record Productivity",
  "Doble orgullo": "Double Pride",
  "Barra libre de CAOS": "Open Bar of CAOS",
  "Tres cafés": "Three Coffees",
  "Semana de resultados": "Results Week",
  "Reestructuración total": "Total Restructuring",
  "Demolición controlada": "Controlled Demolition",
  "Reseñas de cinco estrellas": "Five-Star Reviews",
  "Montaña de papeleo": "Mountain of Paperwork",
  "Comité de dirección": "Board Meeting",
  "Plan de carrera": "Career Plan",
  "Adicción patrocinada": "Sponsored Addiction",
  "Trabajador incansable": "Tireless Worker",
  "Auditoría limpia": "Clean Audit",
  "Liga de empresa": "Company League",
  "Completa 5 misiones diarias.": "Complete 5 daily missions.",
  "Sé Empleado del día 7 veces esta semana.": "Be Employee of the Day 7 times this week.",
  "Gana 2 partidas.": "Win 2 matches.",
  "Juega 20 cartas.": "Play 20 cards.",
  "Derrota a 40 enemigos.": "Defeat 40 enemies.",
  "Derriba 3 torres.": "Destroy 3 towers.",
  "Consigue 3 estrellas en la campaña.": "Get 3 stars in the campaign.",
  "Juega una partida del Modo Jefe.": "Play a Boss Mode match.",
  "Gira una vez el gashapón.": "Spin the gacha once.",
  "Sube de nivel una unidad.": "Level up a unit.",
  "Juega 3 partidas.": "Play 3 matches.",
  "Saca a tu líder 5 veces.": "Deploy your leader 5 times.",
  "Gana sin perder ninguna torre.": "Win without losing a tower.",
  "Juega 2 partidas de la campaña.": "Play 2 campaign matches.",
  "Juega 2 partidas rápidas.": "Play 2 quick matches.",
  "Gasta 120 de CAOS.": "Spend 120 CAOS.",
  "Tira una base enemiga.": "Destroy an enemy base.",
  "Gana una partida con %1.": "Win a match with %1.",
  "Recoge el regalo diario de la tienda.": "Collect the daily gift from the shop.",
  "Juega 2 partidas en la Arena.": "Play 2 Arena matches.",
  "Gana 1 partida en la Arena.": "Win 1 Arena match.",
  "Juega 5 partidas de la campaña.": "Play 5 campaign matches.",
  "Derrota a 100 enemigos.": "Defeat 100 enemies.",
  "Juega 40 cartas.": "Play 40 cards.",
  "Gana 2 partidas con %1.": "Win 2 matches with %1.",
  "Gasta 200 de CAOS.": "Spend 200 CAOS.",
  "Juega 3 partidas rápidas.": "Play 3 quick matches.",
  "Gana 30 partidas.": "Win 30 matches.",
  "Derrota a 2.500 enemigos.": "Defeat 2,500 enemies.",
  "Derriba 75 torres.": "Destroy 75 towers.",
  "Consigue 40 estrellas en la campaña.": "Get 40 stars in the campaign.",
  "Juega 1.300 cartas.": "Play 1,300 cards.",
  "Juega 8 partidas del Modo Jefe.": "Play 8 Boss Mode matches.",
  "Sube 12 niveles de unidades.": "Level up units 12 times.",
  "Gira 30 veces el gashapón.": "Spin the gacha 30 times.",
  "Completa 25 misiones diarias.": "Complete 25 daily missions.",
  "Gana 15 partidas sin perder torres.": "Win 15 matches without losing towers.",
  "Gana 12 partidas en la Arena.": "Win 12 Arena matches.",
  "Cambiar una misión (diaria o semanal)": "Swap a mission (daily or weekly)",
  "<b>6 SEMANALES Y 7 NUEVAS</b>: ahora hay 6 misiones semanales (Empleado del mes y 5 más) y 7 misiones semanales nuevas para que no se repitan tanto. Esta semana se añade la que falta sin tocar las que ya tenías.": "<b>6 WEEKLIES AND 7 NEW ONES</b>: there are now 6 weekly missions (Employee of the Month and 5 more) and 7 new weekly missions so they repeat less. This week the missing one is added without touching the ones you already had.",
  "<b>CAMBIAR SEMANALES</b>: las semanales tienen su propio cupo de cambios con anuncio: 6 a la semana, para usarlos cuando quieras (aunque sea todos el domingo).": "<b>SWAP WEEKLIES</b>: weekly missions have their own ad swap allowance: 6 a week, to use whenever you like (even all on Sunday).",
  "Microblizz ha ampliado la semana laboral a 6 misiones. El séptimo día descansa. Bueno, descansa el CEO.": "Microblizz has extended the working week to 6 missions. On the seventh day it rests. Well, the CEO rests.",
  "Cambiar una misión semanal": "Swap a weekly mission",
  "quedan %1 esta semana": "%1 left this week",
  "La semana que viene": "Next week",
  "Esta semana ya no quedan más cambios. ¡El lunes más!": "No more swaps left this week. More on Monday!",
  "<b>FACCIONES DESDE CERO</b>: cuando liberas una facción en la campaña, sus cartas empiezan a nivel 1. Te toca subirlas a ti.": "<b>FACTIONS FROM SCRATCH</b>: when you free a faction in the campaign, its cards start at level 1. Leveling them up is up to you.",
  "Fichaje completo": "Full Attendance",
  "Juega 50 partidas.": "Play 50 matches.",
  "Presupuesto anual": "Annual Budget",
  "Gasta 4.000 de CAOS.": "Spend 4,000 CAOS.",
  "Cierre de sedes": "Headquarters Shutdown",
  "Tira 20 bases enemigas.": "Destroy 20 enemy bases.",
  "El jefe no descansa": "The Boss Never Rests",
  "Saca a tu líder 25 veces.": "Deploy your leader 25 times.",
  "Temporada de historia": "Story Season",
  "Juega 25 partidas de la campaña.": "Play 25 campaign matches.",
  "Pausas para el café": "Coffee Breaks",
  "Juega 20 partidas rápidas.": "Play 20 quick matches.",
  "Temporada de la Arena": "Arena Season",
  "Juega 20 partidas en la Arena.": "Play 20 Arena matches.",
  "Ruleta trucada y premio gordo": "Rigged wheel, big prize",
  "¡Gana al jefe y %1 se unen a ti!": "Beat the boss and %1 join you!",
  "En Fácil no se libera: gana al jefe en Normal y %1 se unen a ti.": "Not freed on Easy: beat the boss on Normal and %1 join you.",
  "%1: ¡se unen a la rebelión!": "%1: they join the rebellion!",
  "Sus cartas empiezan a nivel 1.": "Their cards start at level 1.",
  "SI GANAS…": "IF YOU WIN…",
  "EN FÁCIL NO SE LIBERA": "NOT FREED ON EASY",
  "Gana a este jefe en Normal para que %1 se unan a ti.": "Beat this boss on Normal so %1 join you.",
  "Nueva facción": "New faction",
  "¡NUEVA FACCIÓN!": "NEW FACTION!",
  "Sus cartas empiezan a nivel 1: súbelas en la Colección. Ya puedes elegirla al jugar.": "Its cards start at level 1: level them up in the Collection. You can now pick it when you play.",
  "VER EN COLECCIÓN": "SEE IN COLLECTION",
  "SEGUIR": "CONTINUE",
  "Recompensa: %#1 de oro en Becario, %#2 en Ejecutivo o %#3 de oro y %#4 gemas en CEO si ganas (%#5 si pierdes), y experiencia para tus cartas.": "Reward: %1 gold on Intern, %2 on Executive or %3 gold and %4 gems on CEO if you win (%5 if you lose), and experience for your cards.",
  "MODO CEO": "CEO MODE",
  "La CPU juega %#1 niveles por encima de tu media y antes de cada partida gira la ruleta de Microblizz: un castigo para ti y una ventaja para la CPU.": "The CPU plays %1 levels above your average, and before every match the Microblizz wheel spins: a punishment for you and an advantage for the CPU.",
  "TU CASTIGO EN ESTA PARTIDA": "YOUR PUNISHMENT THIS MATCH",
  "Modo CEO: la ruleta de Microblizz gira en cada partida. Primero, tu castigo.": "CEO mode: Microblizz's wheel spins every match. First, your punishment.",
  "Y ahora, el regalo de Microblizz para la CPU. ¡Suerte!": "And now, Microblizz's gift for the CPU. Good luck!",
  "No jugar": "Don't play",
  "CEO: rival de nivel %#1, más agresivo y con mata-sanadores.": "CEO: level %1 rival, more aggressive and with healer-killers.",
  "Récord: %1 (%#2 %)": "Record: %1 (%2 %)",
  "Jefe %#1 de %#2": "Boss %1 of %2",
  "derrotado %1": "defeated %1",
  "Gánale en la campaña para retarle": "Beat it in the campaign to challenge it",
  "Para retar a este jefe en el Modo Jefe, gánale primero en la campaña (mundo %#1: %2).": "To challenge this boss in Boss Mode, beat it first in the campaign (world %1: %2).",
  "¡A POR ÉL!": "GO GET HIM!",
  "BLOQUEADO": "LOCKED",
  "Jefe anterior": "Previous boss",
  "Jefe siguiente": "Next boss",
  "Sede de %1 de vida y %#2 minutos para hacerle todo el daño posible. Rival de nivel %#3.": "HQ with %1 health and %2 minutes to deal as much damage as possible. Level %3 rival.",
  "Sede de %1 de vida y %#2 minutos para hacerle todo el daño posible. Rival de nivel %#3, con tropas de élite y equipo.": "HQ with %1 health and %2 minutes to deal as much damage as possible. Level %3 rival, with elite troops and gear.",
  "<b>PARTIDA RÁPIDA «CEO»</b>: la dificultad más dura. La CPU juega 2 niveles por encima y antes de cada partida gira la ruleta de Microblizz: un castigo para ti y una ventaja para la CPU. Si ganas: 150 de oro y 15 gemas.": "<b>QUICK MATCH «CEO»</b>: the hardest difficulty. The CPU plays 2 levels higher and before every match the Microblizz wheel spins: a punishment for you and an advantage for the CPU. If you win: 150 gold and 15 gems.",
  "<b>MODO JEFE RENOVADO</b>: el jefe sale en grande y con su aura. Cambia de jefe con las flechas y elige tu facción en una sola línea.": "<b>BOSS MODE REVAMPED</b>: the boss appears big and with its aura. Switch bosses with the arrows and pick your faction in a single line.",
  "<b>¡NUEVA FACCIÓN!</b>: en la campaña y antes de cada jefe se ve qué facción se une a ti si ganas, y al liberarla sale una celebración que no se cierra sola.": "<b>NEW FACTION!</b>: in the campaign and before each boss you can see which faction joins you if you win, and when you free it there is a celebration that stays until you close it.",
  "<b>TODO EN ORDEN</b>: las facciones salen en dos filas de 5 en la colección, al elegir facción y en el perfil.": "<b>EVERYTHING LINED UP</b>: factions now show in two rows of 5 in the collection, when picking a faction and in your profile.",
  "<b>SANADORES MÁS LISTOS</b>: MeerCat y los demás sanadores ya no se van solos al puente. Si no hay tropas a las que curar, se ponen detrás de tus torres y las curan. Y prefieren cubrir a los que pelean cuerpo a cuerpo.": "<b>SMARTER HEALERS</b>: MeerCat and the other healers no longer wander to the bridge alone. If there are no troops to heal, they stand behind your towers and heal them. And they prefer to cover the ones fighting up close.",
  "<b>SIN HECHIZOS EN RÁFAGA</b>: la máquina ya no puede lanzar dos hechizos seguidos. Entre uno y otro espera 12 segundos, como tú con tu mano de cartas.": "<b>NO MORE SPELL BURSTS</b>: the CPU can no longer cast two spells in a row. It waits 12 seconds between them, just like you with your hand of cards.",
  "Microblizz ha despedido a la enfermera por curar torres sin permiso. Ha vuelto como autónoma.": "Microblizz fired the nurse for healing towers without permission. She came back as a freelancer.",
  "<b>HECHIZOS DE VERDAD</b>: cada hechizo hace llover lo suyo (bellotas, monedas, pociones, relojes, latas…) y los gordos (el martillo del baneo, la espada del crítico, el sello de cancelado y la bomba) caen enteros y golpean. Ya no baja la carta como una bola.": "<b>REAL SPELLS</b>: every spell rains its own stuff (acorns, coins, potions, clocks, cans…) and the big ones (the ban hammer, the critical sword, the cancelled stamp and the bomb) drop whole and slam. The card no longer falls like a ball.",
  "<b>ZONAS QUE BRILLAN</b>: las zonas del campo (hechizos, auras, el líder, la ralentización…) brillan con su color, como el cono de MeerCat. Sin rayas ni puntitos.": "<b>GLOWING AREAS</b>: the areas on the field (spells, auras, the leader, slowdowns…) glow in their colour, like MeerCat's cone. No more dashes or dots.",
});
