// Fans of Rumble · Inglés: el PvP (pantalla de buscar rival, avisos y pantalla final)
'use strict';
IDIOMA.add({
  "Estándar": "Standard",
  "Salvaje": "Wild",
  "Cuentan tu mazo y el nivel y las estrellas de tus cartas. Los objetos y las habilidades no entran.": "Your deck and the level and stars of your cards count. Items and abilities do not.",
  "Cuenta todo lo que llevas puesto: las habilidades de tus cartas y el equipo de tu líder.": "Everything you wear counts: your cards' abilities and your leader's gear.",
  "BUSCAR RIVAL": "FIND A RIVAL",
  "CANCELAR": "CANCEL",
  "JUGAR CONTRA LA IA": "PLAY AGAINST THE AI",
  "Buscando rival… %1 s": "Looking for a rival… %1 s",
  "No hay rivales ahora. ¿Juegas contra la IA?": "No rivals right now. Play against the AI?",
  "Red: %1": "Network: %1",
  "Pruebas (dos pestañas de este navegador)": "Test (two tabs of this browser)",
  "Rival: %1": "Rival: %1",
  "No se ha podido empezar la partida": "The match could not start",
  "Esperando al rival…": "Waiting for the rival…",
  "¿Rendirte?": "Give up?",
  "Si te rindes, la partida cuenta como una derrota.": "If you give up, the match counts as a defeat.",
  "ME RINDO": "I GIVE UP",
  "PARTIDA ANULADA": "MATCH VOIDED",
  "Has tirado la base de %1.": "You took down %1's base.",
  "%1 ha tirado tu base.": "%1 took down your base.",
  "%1 se ha ido de la partida.": "%1 left the match.",
  "Te has rendido.": "You gave up.",
  "Las dos copias de la partida no coinciden. No cuenta para nadie.": "The two copies of the match do not agree. It counts for nobody.",
  "No se ha podido seguir con la partida. No cuenta para nadie.": "The match could not continue. It counts for nobody.",
  "Partida de pruebas: de momento sin puntos ni premios.": "Test match: no points or prizes for now.",
  "OTRO RIVAL": "ANOTHER RIVAL",
  "Campo normal": "Normal field",
  "tu rival": "your rival",
  "<b>CAMPO IGUAL PARA LOS DOS</b>: tu sede y la del rival están ahora a la misma distancia del río (antes la suya estaba más cerca) y las zonas de los campos de jefe se reparten iguales arriba y abajo. Así es justo, también para el PvP que viene.": "<b>THE SAME FIELD FOR BOTH SIDES</b>: your HQ and the rival's are now the same distance from the river (before, theirs was closer) and the zones on boss fields are laid out identically on both halves. It's fair now, also for the PvP that is coming.",
  "Microblizz ha medido el campo con una cinta métrica y ha descubierto que llevaba años jugando en cuesta. Y sí, la versión ha saltado de la 0.9.72 a la 0.9.82: en el taller pasaron muchas cosas con la puerta cerrada y el equipo de contabilidad se ha negado a contarlas.": "Microblizz measured the field with a tape measure and discovered it had been playing uphill for years. And yes, the version jumped from 0.9.72 to 0.9.82: a lot happened in the workshop behind closed doors and the accounting team refused to talk about it.",
});
