// Fans of Rumble · Inglés (1/8): cómo se juega, la pantalla principal, el jefe y el chat de despedidas.
'use strict';
IDIOMA.add({
  "(los líderes de tus facciones)": "(the leaders of your factions)",
  ", con una ruleta que cambia cada semana.": ", with a wheel that changes every week.",
  ". En el": ". In the",
  ". Se recarga solo, 1 cada 3 segundos, y al doble en el último minuto.": ". It recharges by itself, 1 every 3 seconds, and twice as fast in the last minute.",
  ": Rabia, Renacer, Hype, Experiencia, Escudos, RNG, Comunidad, Nostalgia y Secuela. Toca el botón de la pasiva, arriba a la izquierda, para ver qué hace. Microblizz tiene": ": Rage, Rebirth, Hype, Experience, Shields, RNG, Community, Nostalgia and Sequel. Tap the passive button, top left, to see what it does. Microblizz has",
  ": cada 20 s te cobra un poco de CAOS.": ": every 20 s it charges you a little CHAOS.",
  ": cada bot que despides le devuelve algo de CAOS. Y Phony,": ": every bot you lay off gives it back some CHAOS. And Phony,",
  ": súbelas de nivel con oro y toca sus": ": level them up with gold and tap their",
  ": tu líder sigue luchando aunque no juegues y gana oro, gemas y a veces objetos. Cuanto más fuerte es, más gana; recógelo antes de 12 horas. En": ": your leader keeps fighting even when you're not playing and earns gold, gems and sometimes items. The stronger it is, the more it earns; collect it before 12 hours. In",
  "ARENA": "ARENA",
  "Arena de combate": "Combat arena",
  "Arrastra una carta a tu lado del campo": "Drag a card to your side of the field",
  "CAOS gastado": "CHAOS spent",
  "CAOS x2": "CHAOS x2",
  "COMPARTIR": "SHARE",
  "Cada carta gasta": "Each card costs",
  "Cada torre derribada es una corona.": "Every tower knocked down is a crown.",
  "Coronas": "Crowns",
  "Coste medio 3": "Average cost 3",
  "Cuidado: SurvivalBot": "Careful: SurvivalBot",
  "DESCARGAR": "DOWNLOAD",
  "Desbloquea todas las facciones y mundos, da toda la experiencia hasta el nivel 10 (subir lo haces tú en la Colección), 3.000.000 de oro y 5.000 gemas.": "Unlocks all factions and worlds, gives all the experience up to level 10 (you do the levelling in the Collection), 3,000,000 gold and 5,000 gems.",
  "Dificultad del jefe": "Boss difficulty",
  "Difícil": "Hard",
  "En el menú,": "On the menu,",
  "Hechizos 0/2": "Spells 0/2",
  "Imagen de tu resultado para compartir": "Image of your result to share",
  "Jefe": "Boss",
  "La Rebelión de los Fans: libera cada mundo corrompido por Microblizz y su facción se unirá a ti.": "The Fans' Rebellion: free every world corrupted by Microblizz and its faction will join you.",
  "Las siglas de la habilidad, la llama de Rabia y la estrella de los Héroes.": "The ability's initials, Rage's flame and the Heroes' star.",
  "Liga Becario": "Intern League",
  "MODO JEFE": "BOSS MODE",
  "Mantén pulsada": "Press and hold",
  "Mantén pulsada la imagen (o clic derecho) para guardarla y compártela donde quieras.": "Press and hold the image (or right-click) to save it and share it wherever you like.",
  "Mazo": "Deck",
  "Mítica": "Mythic",
  "Nivel medio 1": "Average level 1",
  "Normal": "Normal",
  "PARTIDA RÁPIDA": "QUICK MATCH",
  "POR DEFECTO": "DEFAULT",
  "PRUEBAS": "TESTS",
  "Pasiva de facción: Rabia. Pulsa para ver qué hace": "Faction passive: Rage. Press to see what it does",
  "RULETA DE LA SEMANA": "WHEEL OF THE WEEK",
  "Saltar la animación": "Skip the animation",
  "Siguiente carta": "Next card",
  "Suscripción obligatoria": "Mandatory Subscription",
  "TU MAZO": "YOUR DECK",
  "TUS TROPAS": "YOUR TROOPS",
  "Tira la Sede de Microblizz": "Bring down the Microblizz HQ",
  "Tus unidades": "Your units",
  "Velocidad normal. Pulsa para ir el doble de rápido": "Normal speed. Press to go twice as fast",
  "a las unidades que cruzan a su lado y, a media vida, empieza los": "the units that cross past it and, at half health, starts the",
  "a tu lado del campo, o tócala y luego toca el campo. Tienes 4 unidades en la mano y a tu": "to your side of the field, or tap it and then tap the field. You have 4 units in hand and your",
  "cartas jugadas": "cards played",
  "congela": "freezes",
  "de arriba a la derecha, la partida va el doble de rápido.": "at the top right, the match goes twice as fast.",
  "despidos masivos": "mass layoffs",
  "logros": "achievements",
  "líder": "leader",
  "para ponerles habilidades y objetos del": "to give them abilities and items from the",
  "que dan gemas.": "that give gems.",
  "ranuras": "slots",
  "siempre disponible; al jugar una, entra la": "always available; when you play one, the",
  "siguen su carril": "follow their lane",
  "siguiente": "next one comes in",
  "tienes más de 1.500": "you have over 1,500",
  "una carta para ver qué hace.": "a card to see what it does.",
  "ves todo lo que tienes y su calidad, de Becario (básica) a CEO (perfecta). Al pasarte un mundo, se abre en": "you see everything you own and its quality, from Intern (basic) to CEO (perfect). When you beat a world, it opens in",
  "y después en": "and then in",
  "y ganas al instante.": "and you win instantly.",
  "y pelean solas. El puente que elijas decide el carril. Con el botón": "and fight on their own. The bridge you pick decides the lane. With the",
  "¡GIRAR!": "SPIN!",
  "«¡Rabia máxima!», «¡Tropiezo!», «Equipado»…: encima de su cabeza o en una caja abajo a la derecha.": "«Max Rage!», «Trip!», «Equipped»…: above their head or in a box at the bottom right.",
  "¡+%1 % DE DAÑO!": "+%1 % DAMAGE!",
  "¡+%1 % DE VIDA!": "+%1 % HEALTH!",
  "¡REGENERACIÓN!": "REGENERATION!",
  "…estaba vacío": "…it was empty",
  "Directora": "Director",
  "El CEO": "The CEO",
  "La sede de Phony. En el último piso, el Presidente sube otra vez la suscripción mientras los fans protestan en la puerta. Es hora de recuperar los discos.": "Phony's HQ. On the top floor, the President raises the subscription again while the fans protest at the door. Time to get the discs back.",
  "Phony ha comprado los servidores de la comunidad: ahora para jugar online hay que pagar. A los gamers les ha obligado a firmar contratos de exclusividad y ya no juegan por diversión.": "Phony has bought the community's servers: now you have to pay to play online. It has forced the gamers to sign exclusivity contracts and they no longer play for fun.",
  "Phony ha quitado el lector de discos de su consola, la PayStation, para ahorrarse millones. Ahora todo es digital, todo es de alquiler… y lo que compras te lo pueden borrar.": "Phony has removed the disc drive from its console, the PayStation, to save millions. Now everything is digital, everything is rented… and what you buy can be deleted.",
  "Phony también tiene estudios de cine. Allí solo se ruedan secuelas, remakes y anuncios de la PayStation. Los de Cultura Pop están hartos de repetir la misma película.": "Phony also owns film studios. They only shoot sequels, remakes and PayStation ads there. The Pop Culture crew are sick of repeating the same movie.",
  "Presidente": "President",
  "Vikingo": "Viking",
  "Animales Locos > cualquier DLC": "Crazy Animals > any DLC",
  "BoomBeaver: héroe sin capa (ni futuro)": "BoomBeaver: hero without a cape (or a future)",
  "ChonkCat se ha sentado y no hay quien lo levante": "ChonkCat sat down and nobody can make it get up",
  "Comunidad al máximo = +30 %": "Community maxed out = +30 %",
  "Contenido no disponible": "Content not available",
  "CrazyBunny ha puesto los ojos en espiral": "CrazyBunny's eyes are spiralling",
  "Ctrl+Alt+Victoria": "Ctrl+Alt+Victory",
  "CyberMarine en el campo: todos a cubierto": "CyberMarine on the field: everyone take cover",
  "CyberNinja, teletranspórtate a mi trabajo": "CyberNinja, teleport to my job",
  "Dejo el juego a medias": "I'm leaving the game half-finished",
  "Dile a Microblizz que me voy": "Tell Microblizz I'm leaving",
  "Dile a Phony que me voy": "Tell Phony I'm leaving",
  "El CEO se ha comprado otro yate": "The CEO bought another yacht",
  "EpicChampion, el carry de la partida": "EpicChampion, the carry of the match",
  "Era un plan": "It was a plan",
  "Error 404: trabajo no encontrado": "Error 404: job not found",
  "Error: se requiere conexión": "Error: connection required",
  "GG desde ya": "GG already",
  "GG, very victory, much wow": "GG, very victory, much wow",
  "Gracias, necesitaba vacaciones": "Thanks, I needed a holiday",
  "HackerKid ha hackeado mi wifi": "HackerKid hacked my wifi",
  "MVP para todos": "MVP for everyone",
  "Me cambian por un robot más barato": "They're replacing me with a cheaper robot",
  "Me faltaban 2 años para ser fijo": "I was 2 years away from a permanent contract",
  "Me han borrado de la biblioteca": "They deleted me from the library",
  "Me han dado de baja": "They've signed me off",
  "Me han reportado": "I've been reported",
  "Me llevo la grapadora": "I'm taking the stapler",
  "Medusa, unas gafas de sol, por favor": "Medusa, sunglasses please",
  "MeerCat cura mejor que mi médico de cabecera": "MeerCat heals better than my GP",
  "MemeLord ha vuelto a sacar carta al azar": "MemeLord drew a random card again",
  "Mi contrato tenía letra pequeña": "My contract had small print",
  "Mi jefe dijo que éramos una familia": "My boss said we were a family",
  "Microblizz enterrado (otra vez)": "Microblizz buried (again)",
  "Microblizz ha sido memeado": "Microblizz got memed",
  "Microblizz me prometió fama": "Microblizz promised me fame",
  "Microblizz vuelve a cerrar el Olimpo": "Microblizz shuts down Olympus again",
  "Microblizz, ¿a que ahora sí te acuerdas?": "Microblizz, now you remember us, don't you?",
  "NecroLord, ¿quieres una bufanda?": "NecroLord, want a scarf?",
  "NeonSniper dispara desde la otra punta del mapa": "NeonSniper shoots from the other side of the map",
  "Nerfeadme esto": "Nerf this for me",
  "Ocho años aquí y me echan por correo": "Eight years here and they fire me by email",
  "POV: eres un becario de Phony": "POV: you're a Phony intern",
  "Pagué 70 € por esto": "I paid 70 € for this",
  "Phony ha borrado otra película de mi biblioteca": "Phony deleted another movie from my library",
  "Phony ha subido otra vez la suscripción": "Phony raised the subscription again",
  "Phony lo celebra subiendo los precios": "Phony celebrates by raising prices",
  "Phony me prometió fama": "Phony promised me fame",
  "Phony va a subir la suscripción por envidia": "Phony will raise the subscription out of jealousy",
  "Phony ya prepara el comunicado": "Phony is already preparing the statement",
  "Phony: «esa torre era una exclusiva temporal»": "Phony: «that tower was a limited-time exclusive»",
  "Phony: «estamos en mantenimiento»": "Phony: «we're under maintenance»",
  "Phony: «lo arreglamos en la próxima suscripción»": "Phony: «we'll fix it in the next subscription»",
  "RIP torre": "RIP tower",
  "Rabia x5 = paz mundial": "Rage x5 = world peace",
  "RageQuitter, respira hondo": "RageQuitter, take a deep breath",
  "Renacer GOD": "Rebirth GOD",
  "Respawn, por favor": "Respawn, please",
  "SlyFox ha ido a por tabaco y no vuelve": "SlyFox went out for cigarettes and isn't coming back",
  "Solo era un alquiler": "It was only a rental",
  "Spoiler: gana la rebelión (o no)": "Spoiler: the rebellion wins (or not)",
  "StitchBrute solo quiere abrazos (y torres)": "StitchBrute only wants hugs (and towers)",
  "StreamKing modo hype ON": "StreamKing hype mode ON",
  "StreamKing, ¿me saludas?": "StreamKing, can you say hi to me?",
  "ThunderGod lleva años pidiendo un parche": "ThunderGod has been asking for a patch for years",
  "TitánBeta: cancelado pero con ganas": "BetaTitan: cancelled but still keen",
  "TrollBot va ganando sin hacer nada": "TrollBot is winning without doing anything",
  "ViralBot me está grabando sin permiso": "ViralBot is recording me without permission",
  "Volveré… en el DLC": "I'll be back… in the DLC",
  "Volveré… en el remake": "I'll be back… in the remake",
  "Vuelvo en 5 minutos": "Back in 5 minutes",
  "Vuelvo en la próxima suscripción": "Back in the next subscription",
  "XP para todos": "XP for everyone",
  "a ver ese combo": "let's see that combo",
  "al Kaiju se le ve la cremallera": "you can see the Kaiju's zipper",
  "beep boop, GG": "beep boop, GG",
  "clip del año": "clip of the year",
  "clip, clip, CLIP": "clip, clip, CLIP",
  "cuidado, que el moderador es el BanHammer": "careful, the moderator is the BanHammer",
  "curas gratis, sin suscripción": "free heals, no subscription",
  "directa al olvido de las plataformas": "straight to platform oblivion",
  "dono 5 € si tiras la torre": "I'll donate 5 € if you take down the tower",
  "drones del cielo: envío urgente versión guerra": "drones from the sky: express delivery, war edition",
  "el Coleccionista tira sus discos… ¡los físicos! 💿": "the Collector throws his discs… the physical ones! 💿",
  "el Detective ya sabe quién es el culpable: Phony": "the Detective knows who's guilty: Phony",
  "el DobleDeAcción se lleva todos los golpes": "the StuntDouble takes all the hits",
  "el GhostAgent está aquí… creo": "the GhostAgent is here… I think",
  "el GifBlaster tiene más GIFs que mi grupo de amigos": "the GifBlaster has more GIFs than my friend group",
  "el HéroeDeSaldo vuela con una capa de cortina": "the BargainHero flies with a curtain cape",
  "el Minotauro aún busca la salida de su laberinto": "the Minotaur is still looking for the exit of his maze",
  "el Modder arregla lo que Phony rompe": "the Modder fixes what Phony breaks",
  "el Presidente ha tirado su café": "the President spilled his coffee",
  "el RNG manda": "RNG rules",
  "el RNG nos odia": "RNG hates us",
  "el RetroMarine lleva hombreras de 1998": "the RetroMarine wears 1998 shoulder pads",
  "el VikingoPerdido aún busca la salida del sótano": "the LostViking is still looking for the way out of the basement",
  "el chat está más vivo que los servidores de Phony": "the chat is more alive than Phony's servers",
  "el chat ha ganado esta partida": "the chat won this match",
  "el chat se va a otro canal 😢": "the chat is moving to another channel 😢",
  "el conejo da miedo, no sé si es de los buenos": "the bunny is scary, I'm not sure it's one of the good guys",
  "el conejo necesita unas vacaciones": "the bunny needs a holiday",
  "el jefe cobra hasta por respirar": "the boss charges even for breathing",
  "el mapache se lleva la basura de Microblizz": "the raccoon takes out Microblizz's trash",
  "el perrito dice wow, y tiene razón": "the doggo says wow, and he's right",
  "el querubín me ha enamorado de este juego": "the cherub made me fall in love with this game",
  "el rey de la cripta en directo": "the king of the crypt, live",
  "el vikingo ha encontrado la salida": "the viking found the exit",
  "en el Sector Neón hay más neón que gente": "there's more neon than people in Neon Sector"
});
