// Fans of Rumble · Inglés: el armario (nombres de marcos y títulos) y los pases de este juego (temporada y PvP)
'use strict';
IDIOMA.add({
  // marcos
  "De serie": "Standard",
  "Billetes": "Banknotes",
  "Corporativo": "Corporate",
  "Caja de despido": "Layoff Box",
  "Accionista": "Shareholder",
  "Maletín de oro": "Golden Briefcase",
  "Trono del CEO": "CEO's Throne",
  "Duelista": "Duelist",
  "Neón de sala": "Arcade Neon",
  "Pay to Win": "Pay to Win",
  "Leyenda del sofá": "Couch Legend",
  "Trofeo de plástico": "Plastic Trophy",
  // títulos (con y sin comillas: salen de las dos maneras)
  "Becario sin sueldo": "Unpaid Intern", "«Becario sin sueldo»": "«Unpaid Intern»",
  "Cliente fiel": "Loyal Customer", "«Cliente fiel»": "«Loyal Customer»",
  "Accionista minoritario": "Minority Shareholder", "«Accionista minoritario»": "«Minority Shareholder»",
  "Despedido del mes": "Fired of the Month", "«Despedido del mes»": "«Fired of the Month»",
  "Inversor de riesgo": "Risky Investor", "«Inversor de riesgo»": "«Risky Investor»",
  "Ejecutivo agresivo": "Aggressive Executive", "«Ejecutivo agresivo»": "«Aggressive Executive»",
  "Tiburón de las fusiones": "Merger Shark", "«Tiburón de las fusiones»": "«Merger Shark»",
  "Consejo de administración": "Board of Directors", "«Consejo de administración»": "«Board of Directors»",
  "CEO en funciones": "Acting CEO", "«CEO en funciones»": "«Acting CEO»",
  "Duelista de sofá": "Couch Duelist", "«Duelista de sofá»": "«Couch Duelist»",
  "Sin pase y sin miedo": "No Pass, No Fear", "«Sin pase y sin miedo»": "«No Pass, No Fear»",
  "Pay to Pray": "Pay to Pray", "«Pay to Pray»": "«Pay to Pray»",
  "Ballena competitiva": "Competitive Whale", "«Ballena competitiva»": "«Competitive Whale»",
  "Leyenda con tarjeta": "Legend With a Credit Card", "«Leyenda con tarjeta»": "«Legend With a Credit Card»",
  // pases
  "Pase Competitivo Pro": "Pro Competitive Pass",
  "Microblizz compra la cafetera": "Microblizz buys the coffee machine",
  "La primera adquisición. Ahora el café es de suscripción.": "The first acquisition. Coffee is now a subscription.",
  "Microblizz compra tu estudio indie favorito": "Microblizz buys your favourite indie studio",
  "Y lo cierra «para cuidarlo mejor».": "And shuts it down «to take better care of it».",
  "Microblizz compra un museo": "Microblizz buys a museum",
  "Los cuadros ahora llevan anuncios antes de poder mirarlos.": "Paintings now show ads before you can look at them.",
  "Microblizz compra tu partida guardada": "Microblizz buys your save file",
  "Para continuar, acepta los nuevos términos (2.000 páginas).": "To continue, accept the new terms (2,000 pages).",
  "Microblizz se compra a sí misma": "Microblizz buys itself",
  "El CEO firma consigo mismo y se pone un bonus por la operación.": "The CEO signs with himself and gives himself a bonus for the deal.",
  // consejos de Lola (v0.9.92)
  "Microblizz ha relanzado el ": "Microblizz has relaunched the ",
  " y fecha de caducidad, como los yogures. Cada 5 niveles hay un premio con ": " and an expiry date, like yoghurt. Every 5 levels there's a reward with a ",
  ": marcos y títulos para tu ": ": frames and titles for your ",
  ". Ah, y todos empezamos de cero. «Por justicia», dicen.": ". Oh, and everyone starts from zero. «For fairness», they say.",
  " solo sube jugando contra personas: ": " only goes up by playing against people: ",
  " por partida y ": " per match and ",
  " si ganas. Sus premios son solo para presumir, porque aquí gana el que mejor juega. Microblizz no soportaba no cobrar nada, así que se inventó el ": " if you win. Its rewards are just for showing off, because here the best player wins. Microblizz couldn't stand not charging for anything, so it invented the ",
  ": marcos para tu cara y títulos para debajo de tu nombre. No dan ni un punto de vida, pero hay que tener estilo hasta en el paro. Se ganan en los pases: toca uno para ponértelo.": ": frames for your face and titles for under your name. They don't give a single hit point, but you need style even when unemployed. You earn them in the passes: tap one to wear it.",
  "estrella": "star",
  "armario": "wardrobe",
  "PASE JCJ": "PVP PASS",
});
