// Fans of Rumble · Inglés de las pestañas del Salón de la Fama (js/clasificacion.js).
'use strict';
IDIOMA.add({
  "Copas PvP": "PvP Trophies",
  "Poder": "Power",
  "estrellas": "stars",
  "poder": "power",
  "Máximo:": "Best:",
  "Quién tiene más estrellas de campaña, sumando todas las dificultades. Si empatan, gana quien haya superado la más difícil.": "Who has the most campaign stars, across all difficulties. On a tie, whoever beat the hardest one wins.",
  "Quién tiene más estrellas de campaña, sumando todas las dificultades.": "Who has the most campaign stars, across all difficulties.",
  "Si empatan, gana quien haya superado la más difícil.": "On a tie, whoever beat the hardest one wins.",
  "Poder es la suma de los niveles de todos tus personajes. Cada mejora te sube en el Salón.": "Power is the sum of the levels of all your characters. Every upgrade moves you up the Hall.",
  "Poder es la suma de los niveles de todos tus personajes.": "Power is the sum of the levels of all your characters.",
  "Cada mejora te sube en el Salón.": "Every upgrade moves you up the Hall.",
  "Aquí irán las copas del PvP: ganas contra gente de verdad y subes; pierdes y bajas.": "PvP trophies will go here: beat real people and you go up; lose and you go down.",
  "Gana tu primera estrella en la campaña para entrar.": "Earn your first campaign star to get in.",
  "Mejora un personaje para entrar.": "Upgrade a character to get in.",
  "Juega una partida de PvP para entrar.": "Play a PvP match to get in.",
  "1 personaje mejorado": "1 character upgraded",
  "%1 personajes mejorados": "%1 characters upgraded",
  "1 partida": "1 match",
  "%1 partidas": "%1 matches",
  "<b>PVP SIN TIRONES</b>: las partidas contra otros jugadores iban a saltos; ahora la red tiene más margen (tus cartas salen una fracción de segundo más tarde, pero todo se mueve fluido).": "<b>SMOOTH PVP</b>: matches against other players were choppy; the network now has more margin (your cards drop a fraction of a second later, but everything moves smoothly).",
  "<b>ARMARIO Y PASE NUEVO</b>: marcos para tu avatar y títulos bajo tu nombre, que se ganan en los pases. Hay un pase de temporada nuevo (50 niveles, capítulos de La Gran Compra e hitos) y un pase PvP que sube al jugar partidas PvP. Son solo para lucirse: no dan ventaja.": "<b>WARDROBE AND NEW PASS</b>: frames for your avatar and titles under your name, earned in the passes. There is a new season pass (50 levels, chapters of The Great Purchase and milestones) and a PvP pass that levels up as you play PvP matches. Cosmetic only: no advantage.",
  "<b>SALÓN DE LA FAMA</b>: botón RANKING en el menú con la clasificación mundial (campaña y poder; las copas PvP, en obras).": "<b>HALL OF FAME</b>: RANKING button in the menu with the world leaderboard (campaign and power; PvP cups under construction).",
  "Microblizz ha estrenado un armario para que los perdedores del PvP puedan perder con estilo. El salto a la 0.9.92 incluye muchas cosas del taller que no caben en una nota.": "Microblizz has opened a wardrobe so PvP losers can lose in style. The jump to 0.9.92 includes lots of workshop stuff that doesn't fit in one note.",
  // el consejo de Lola (11b-consejos.js), por trozos: el título en negrita y el resto aparte
  ": los mejores fans del mundo en estrellas de campaña y en poder. Lo cuenta todo el servidor, así que aquí no se sube pagando… de momento.": ": the best fans in the world in campaign stars and power. The server counts everything, so here you can't pay to climb… for now.",
  // novedades 0.9.93
  "<b>LOLA EN EL SALÓN DE LA FAMA</b>: la primera vez que abres el RANKING, Lola te cuenta cómo funciona.": "<b>LOLA IN THE HALL OF FAME</b>: the first time you open the RANKING, Lola tells you how it works.",
  "LOLA EN EL SALÓN DE LA FAMA": "LOLA IN THE HALL OF FAME",
  ": la primera vez que abres el RANKING, Lola te cuenta cómo funciona.": ": the first time you open the RANKING, Lola tells you how it works.",
  "Lola ha intentado comprar el primer puesto del Salón. No la han dejado: el servidor no acepta sobornos. Microblizz está investigando cómo arreglarlo.": "Lola tried to buy first place in the Hall. They didn't let her: the server doesn't take bribes. Microblizz is investigating how to fix that.",
  "<b>LOLA TE LO CUENTA</b>: la primera vez que abras el pase nuevo, el pase PvP o el armario, Lola te explica en dos frases cómo va. También si ya habías hecho el tutorial.": "<b>LOLA EXPLAINS IT</b>: the first time you open the new pass, the PvP pass or the wardrobe, Lola tells you how it works in two sentences. Even if you had already done the tutorial.",
  "Microblizz ha obligado a Lola a explicar sus pases nuevos. Ha aceptado a cambio de un marco de cartón, que es lo que le dieron al despedirla.": "Microblizz forced Lola to explain its new passes. She agreed in exchange for a cardboard frame, which is what they gave her when they fired her.",
  // las novedades se traducen por trozos (lo que va en negrita va aparte)
  "LOLA TE LO CUENTA": "LOLA EXPLAINS IT",
  ": la primera vez que abras el pase nuevo, el pase PvP o el armario, Lola te explica en dos frases cómo va. También si ya habías hecho el tutorial.": ": the first time you open the new pass, the PvP pass or the wardrobe, Lola tells you how it works in two sentences. Even if you had already done the tutorial.",
  "ARMARIO Y PASE NUEVO": "WARDROBE AND NEW PASS",
  ": marcos para tu avatar y títulos bajo tu nombre, que se ganan en los pases. Hay un pase de temporada nuevo (50 niveles, capítulos de La Gran Compra e hitos) y un pase PvP que sube al jugar partidas PvP. Son solo para lucirse: no dan ventaja.": ": frames for your avatar and titles under your name, earned in the passes. There's a new season pass (50 levels, chapters of The Big Buyout and milestones) and a PvP pass that goes up by playing PvP matches. They're just for show: no advantage.",
  "PVP MÁS ESTABLE": "MORE STABLE PVP",
  ": si el móvil se atasca un momento, la partida ya no intenta recuperar el tiempo perdido de golpe. Y si tu rival tiene otra versión del juego, te avisa.": ": if your phone stalls for a moment, the match no longer tries to catch up on the lost time all at once. And if your rival has a different version of the game, it tells you.",
  "<b>RENDIRSE EN PVP</b>: el botón ME RINDO no hacía nada contra otros jugadores; ahora pierdes y tu rival gana al momento.": "<b>SURRENDERING IN PVP</b>: the SURRENDER button did nothing against other players; now you lose and your rival wins at once.",
  "Microblizz reconoce que el botón de rendirse se había rendido primero.": "Microblizz admits the surrender button had surrendered first.",
  "<b>PVP EN OBRAS</b>: cerramos el PvP un rato para afinar la conexión con el servidor: las partidas iban a tirones. Volverá en cuanto vaya fino.": "<b>PVP UNDER CONSTRUCTION</b>: we are closing PvP for a while to tune the connection to the server: matches were choppy. It will be back as soon as it runs smoothly.",
  "Microblizz ha puesto un cartel de «vuelvo en 5 minutos» en el PvP. Lleva 5 minutos desde hace tiempo.": "Microblizz has put a “back in 5 minutes” sign on PvP. It has been 5 minutes for a while now.",
  "<b>PVP ABIERTO (EN PRUEBAS)</b>: ya puedes retar a otros jugadores en el modo Estándar. Está en pruebas: puede ir a tirones, y las puntuaciones son de la Temporada 0, que se borrará cuando todo vaya estable. Cada temporada se reiniciará. Necesitas vincular tu cuenta (Opciones → Cuenta). También: sin botón x2 en PvP, rendirse funciona y el retardo de red es más amplio.": "<b>PVP OPEN (TESTING)</b>: you can now challenge other players in Standard mode. It is in testing: it may be choppy, and the scores belong to Season 0, which will be wiped once everything is stable. Each season will reset. You need to link your account (Options → Account). Also: no x2 button in PvP, surrendering works and the network delay is wider.",
  "Microblizz abre el PvP «en pruebas», que en lenguaje de empresa significa que los probadores sois vosotros.": "Microblizz opens PvP “in testing”, which in company language means the testers are you.",
  "<b>PVP CON TU FACCIÓN</b>: en la pantalla de PvP ya puedes elegir cualquiera de las facciones que tengas desbloqueadas, no solo los Animales Locos.": "<b>PVP WITH YOUR FACTION</b>: on the PvP screen you can now pick any of the factions you have unlocked, not just the Crazy Animals.",
  "Microblizz estaba convencido de que todas las facciones querían ser Animales Locos. Ha tenido que preguntar.": "Microblizz was convinced every faction wanted to be the Crazy Animals. It had to ask.",
  "<b>TODAS LAS FACCIONES EN EL PVP</b>: en la pantalla de PvP salen todas las facciones; las que aún no tienes desbloqueadas se ven en gris.": "<b>ALL FACTIONS IN PVP</b>: the PvP screen now shows every faction; the ones you haven't unlocked yet appear greyed out.",
  "Microblizz ha puesto las facciones bloqueadas en gris para que dé más ganas de desbloquearlas. Funciona.": "Microblizz greyed out the locked factions to make unlocking them more tempting. It works.",
  "Aún no has desbloqueado esta facción": "You have not unlocked this faction yet",
  "<b>PVP: HÉROE EN LA MANO</b>: si tu rival sacaba el héroe de tu misma facción, tu carta de héroe salía como «en el campo» aunque el tuyo no estuviera. Arreglado.": "<b>PVP: HERO IN YOUR HAND</b>: if your rival deployed the hero of your same faction, your hero card showed “on the field” even though yours wasn't. Fixed.",
  "Microblizz ha explicado que en PvP los héroes se parecen tanto que ni su propia botonera los distinguía.": "Microblizz explained that in PvP the heroes look so alike that not even its own button bar could tell them apart.",
  "<b>PVP SIN PARONES</b>: arreglada la partida que se quedaba parada (sin subir ni el CAOS) por un fallo de la conexión con el servidor.": "<b>PVP WITHOUT FREEZES</b>: fixed the match that froze (not even CHAOS went up) because of a server connection bug.",
  "Microblizz ha descubierto que dos mensajes a la vez se pisaban entre sí. Ahora hacen cola, como en la cafetería.": "Microblizz discovered that two messages at once stepped on each other. Now they queue, like in the cafeteria.",
  "<b>PVP MÁS ROBUSTO</b>: ajustes en los cálculos de la partida para que dos navegadores distintos no se separen, y la partida guarda más pistas para encontrar los desajustes que queden.": "<b>MORE ROBUST PVP</b>: tweaks to the match calculations so that two different browsers don't drift apart, and the match keeps more clues to track down any remaining mismatches.",
  "Microblizz ha instalado un chivato en cada partida. Ya sabe dónde se le va el hilo.": "Microblizz has installed a snitch in every match. It now knows where it loses the thread.",
  "<b>EL CHAT, TAMBIÉN EN PVP</b>: el chat de directo vuelve a comentar la partida en el PvP (solo lo ves tú, no se sincroniza con nadie).": "<b>THE CHAT, NOW IN PVP TOO</b>: the live chat is back to commenting on the match in PvP (only you see it, it isn't synced with anyone).",
  "Microblizz asegura que el chat nunca se fue del PvP: estaba de descanso.": "Microblizz insists the chat never left PvP: it was on a break.",
  "<b>INICIAR SESIÓN, MÁS FÁCIL</b>: el menú tiene un botón «Iniciar sesión / crear cuenta» y, si entras en PvP sin cuenta, te sale una ventana para crearla o entrar con Google o con tu email (y al terminar pasas directo a PvP). También hemos afinado el PvP para que dos navegadores distintos jueguen la misma partida.": "<b>EASIER SIGN-IN</b>: the menu has a «Sign in / create account» button and, if you enter PvP without an account, a window lets you create one or sign in with Google or email (then you go straight into PvP). We also tuned PvP so two different browsers play the same match.",
  "Microblizz ha puesto un cartel de «Entrada» en la puerta. Antes había que adivinar dónde estaba.": "Microblizz has put an «Entrance» sign on the door. Before, you had to guess where it was.",
  "ÚLTIMA HORA EN EL PVP": "LAST HOUR IN PVP",
  "Partidas: %1 en la última hora · %2 en total": "Matches: %1 in the last hour · %2 in total",
  "Unidades caídas: %1": "Units fallen: %1",
  "Hechizos lanzados: %1": "Spells cast: %1",
  "CAOS gastado: %1": "CHAOS spent: %1",
});
