// Fans of Rumble · Inglés: misiones con título y descripción, semanal fija, misiones de la Arena y logros de Fácil (v0.9.67 y v0.9.68)
'use strict';
IDIOMA.add({
  "<b>MISIONES CON NOMBRE</b>: todas las misiones tienen ahora un título (Doble despido, ERE masivo, Pausa para el café…) y debajo lo que hay que hacer.": "<b>MISSIONS WITH NAMES</b>: every mission now has a title (Double Layoff, Mass Redundancy, Coffee Break…) and underneath, what you have to do.",
  "<b>EMPLEADO DEL MES</b>: en las semanales hay una misión fija: sé Empleado del día 7 veces en la semana. Da un premio gordo.": "<b>EMPLOYEE OF THE MONTH</b>: there is a fixed weekly mission: be Employee of the Day 7 times in the week. It pays big.",
  "<b>SEMANALES MÁS LARGAS</b>: ahora hay 5 a la semana y están pensadas para durar varios días. También se pueden cambiar con un anuncio (menos la fija).": "<b>LONGER WEEKLIES</b>: there are now 5 a week and they are meant to take several days. You can also swap them by watching an ad (except the fixed one).",
  "Recursos Humanos de Microblizz ha puesto nombre a cada tarea. El presupuesto para pagarlas todavía no ha llegado.": "Microblizz HR has named every task. The budget to pay for them hasn't arrived yet.",
  "en Fácil": "on Easy",
  "(Fácil)": "(Easy)",
  "Hasta un becario lo consigue.": "Even an intern can manage it.",
  "<b>MISIÓN «5 DIARIAS»</b>: cada día hay 6 misiones. La de «Completa 5 misiones diarias» va siempre la primera y da más premio. En la semana hay un reto: completarla 7 veces.": "<b>«5 DAILY» MISSION</b>: there are 6 missions each day. The «Complete 5 daily missions» one is always first and pays more. This week there's a challenge: complete it 7 times.",
  "<b>MISIONES DE LA ARENA</b>: jugar y ganar en la Arena cuenta para las misiones del día y de la semana.": "<b>ARENA MISSIONS</b>: winning and playing in the Arena counts toward the daily and weekly missions.",
  "<b>LOGROS DE FÁCIL</b>: la campaña en Fácil también tiene logros por estrellas, como las demás dificultades.": "<b>EASY LEVEL ACHIEVEMENTS</b>: the Easy campaign now has star achievements, like the other difficulties.",
  "Microblizz ha puesto una misión para que cumplas las demás. Es lo más parecido a un jefe que ha hecho en años.": "Microblizz has added a mission so you'll complete the others. It's the closest thing to a boss they've made in years.",
  "Empleado del día": "Employee of the Day",
  "Empleado del mes (en una semana)": "Employee of the Month (in a week)",
  "Doble despido": "Double Layoff",
  "Reparto de tareas": "Task Delegation",
  "Recorte de plantilla": "Staff Cuts",
  "Reforma de oficinas": "Office Renovation",
  "Valoración positiva": "Positive Review",
  "Reunión con el jefe": "Meeting with the Boss",
  "Una cápsula y lo dejo": "Just One More Capsule",
  "Ascenso exprés": "Fast-Track Promotion",
  "Jornada completa": "Full-Time Shift",
  "El jefe baja al campo": "The Boss Hits the Field",
  "Ni un rasguño": "Not a Scratch",
  "Modo historia": "Story Mode",
  "Pausa para el café": "Coffee Break",
  "Presupuesto ejecutado": "Budget Spent",
  "Cierre de sede": "Headquarters Closed",
  "Orgullo de facción": "Faction Pride",
  "Lo único gratis": "The Only Free Thing",
  "Afterwork en la Arena": "Arena Afterwork",
  "Ranking trimestral": "Quarterly Ranking",
  "Maratón de historia": "Story Marathon",
  "ERE masivo": "Mass Redundancy",
  "Productividad de récord": "Record Productivity",
  "Doble orgullo": "Double Pride",
  "Barra libre de CAOS": "Open Bar of CAOS",
  "Tres cafés": "Three Coffees",
  "Semana de resultados": "Results Week",
  "Reestructuración total": "Total Restructuring",
  "Demolición controlada": "Controlled Demolition",
  "Reseñas de cinco estrellas": "Five-Star Reviews",
  "Montaña de papeleo": "Mountain of Paperwork",
  "Comité de dirección": "Board Meeting",
  "Plan de carrera": "Career Plan",
  "Adicción patrocinada": "Sponsored Addiction",
  "Trabajador incansable": "Tireless Worker",
  "Auditoría limpia": "Clean Audit",
  "Liga de empresa": "Company League",
  "Completa 5 misiones diarias.": "Complete 5 daily missions.",
  "Sé Empleado del día 7 veces esta semana.": "Be Employee of the Day 7 times this week.",
  "Gana 2 partidas.": "Win 2 matches.",
  "Juega 20 cartas.": "Play 20 cards.",
  "Derrota a 40 enemigos.": "Defeat 40 enemies.",
  "Derriba 3 torres.": "Destroy 3 towers.",
  "Consigue 3 estrellas en la campaña.": "Get 3 stars in the campaign.",
  "Juega una partida del Modo Jefe.": "Play a Boss Mode match.",
  "Gira una vez el gashapón.": "Spin the gacha once.",
  "Sube de nivel una unidad.": "Level up a unit.",
  "Juega 3 partidas.": "Play 3 matches.",
  "Saca a tu líder 5 veces.": "Deploy your leader 5 times.",
  "Gana sin perder ninguna torre.": "Win without losing a tower.",
  "Juega 2 partidas de la campaña.": "Play 2 campaign matches.",
  "Juega 2 partidas rápidas.": "Play 2 quick matches.",
  "Gasta 120 de CAOS.": "Spend 120 CAOS.",
  "Tira una base enemiga.": "Destroy an enemy base.",
  "Gana una partida con %1.": "Win a match with %1.",
  "Recoge el regalo diario de la tienda.": "Collect the daily gift from the shop.",
  "Juega 2 partidas en la Arena.": "Play 2 Arena matches.",
  "Gana 1 partida en la Arena.": "Win 1 Arena match.",
  "Juega 5 partidas de la campaña.": "Play 5 campaign matches.",
  "Derrota a 100 enemigos.": "Defeat 100 enemies.",
  "Juega 40 cartas.": "Play 40 cards.",
  "Gana 2 partidas con %1.": "Win 2 matches with %1.",
  "Gasta 200 de CAOS.": "Spend 200 CAOS.",
  "Juega 3 partidas rápidas.": "Play 3 quick matches.",
  "Gana 30 partidas.": "Win 30 matches.",
  "Derrota a 2.500 enemigos.": "Defeat 2,500 enemies.",
  "Derriba 75 torres.": "Destroy 75 towers.",
  "Consigue 40 estrellas en la campaña.": "Get 40 stars in the campaign.",
  "Juega 1.300 cartas.": "Play 1,300 cards.",
  "Juega 8 partidas del Modo Jefe.": "Play 8 Boss Mode matches.",
  "Sube 12 niveles de unidades.": "Level up units 12 times.",
  "Gira 30 veces el gashapón.": "Spin the gacha 30 times.",
  "Completa 25 misiones diarias.": "Complete 25 daily missions.",
  "Gana 15 partidas sin perder torres.": "Win 15 matches without losing towers.",
  "Gana 12 partidas en la Arena.": "Win 12 Arena matches.",
  "Cambiar una misión (diaria o semanal)": "Swap a mission (daily or weekly)",
  "<b>7 SEMANALES</b>: ahora hay 7 misiones semanales (Empleado del mes y 6 más). Esta semana se añaden las que faltan sin tocar las que ya tenías.": "<b>7 WEEKLIES</b>: there are now 7 weekly missions (Employee of the Month and 6 more). This week the missing ones are added without touching the ones you already had.",
  "<b>CAMBIAR SEMANALES</b>: las semanales tienen su propio cupo de cambios con anuncio: 6 a la semana, para usarlos cuando quieras (aunque sea todos el domingo).": "<b>SWAP WEEKLIES</b>: weekly missions have their own ad swap allowance: 6 a week, to use whenever you like (even all on Sunday).",
  "Microblizz ha ampliado la semana laboral a 7 misiones. Dice que el domingo también es un día.": "Microblizz has extended the working week to 7 missions. It says Sunday is a day too.",
  "Cambiar una misión semanal": "Swap a weekly mission",
  "quedan %1 esta semana": "%1 left this week",
  "La semana que viene": "Next week",
  "Esta semana ya no quedan más cambios. ¡El lunes más!": "No more swaps left this week. More on Monday!",
});
