// Fans of Rumble · Inglés: las frases, los emoticonos y lo que dice la CPU (js/retos-armario.js y js/22-frases.js)
'use strict';
IDIOMA.add({
  "¡Hola!": "Hi!",
  "Bien jugado": "Well played",
  "¡Gracias!": "Thanks!",
  "Uy…": "Oops…",
  "Es una característica, no un bug": "It's a feature, not a bug",
  "Lo arreglamos en el parche del día 1": "We'll fix it in the day-one patch",
  "¿Has probado a reiniciar?": "Have you tried restarting?",
  "Tu feedback es muy importante para nosotros": "Your feedback is very important to us",
  "Nos vemos en Recursos Humanos": "See you in HR",
  "Esta reunión podía ser un email": "This meeting could have been an email",
  "Reestructuración estratégica": "Strategic restructuring",
  "Te despido con cariño": "You're fired, with love",
  "Esto lo arreglo con la tarjeta": "I'll fix this with my credit card",
  "GG EZ… según mi abogado": "GG EZ… according to my lawyer",
  "¡LAG!": "LAG!",
  "Sinergias": "Synergies",
  "Era mi primera partida, lo juro": "It was my first match, I swear",
  "Skill issue (tuyo)": "Skill issue (yours)",
  "Me parto": "Dying of laughter",
  "Drama": "Drama",
  "Guiño": "Wink",
  "Por favor": "Pretty please",
  "Bum": "Boom",
  "Muuu": "Mooo",
  "Eso es basura": "That's trash",
  "Estás muerto": "You're dead",
  "Pose de héroe": "Hero pose",
  "Lluvia de billetes": "Money rain",
  "Desde el sofá": "From the couch",
  "Tryhard": "Tryhard",
  "Bip bup": "Beep boop",
  "Al ataque": "Charge!",
  "Armario": "Wardrobe",
  "TUS FRASES": "YOUR PHRASES",
  "Silenciar al rival": "Mute rival",
  "Rival silenciado": "Rival muted",
  "Cámbialas en el": "Change them in the",
  "(tu perfil).": "(your profile).",
  "Frases y emoticonos": "Phrases and emotes",
  "Más despacio: hasta Microblizz respira entre reunión y reunión": "Slow down: even Microblizz breathes between meetings",
  "Frases del rival": "Rival's phrases",
  "Las frases y los emoticonos que te manda el rival (o la CPU) durante la partida.": "The phrases and emotes your rival (or the CPU) sends you during the match.",
  "Tu juego ha sido adquirido": "Your game has been acquired",
  "Bienvenido a la reestructuración": "Welcome to the restructuring",
  "Hemos tomado nota": "Duly noted",
  "Pasa por caja": "Please pay at the till",
  "Eso no estaba en el contrato": "That wasn't in the contract",
  "Tu opinión ha sido archivada": "Your opinion has been filed",
  "Despedido": "Fired",
  "Rentabilidad récord": "Record profits",
  "Esa torre nos sobraba": "We didn't need that tower anyway",
  "Ya la cobraremos en un DLC": "We'll charge for it in a DLC",
  "Esto ahora es de suscripción": "This is subscription-only now",
  "Mensaje solo para suscriptores Plus": "Message for Plus subscribers only",
  "Remasterizado a 70 €": "Remastered for €70",
  "Error de conexión. Pague para reintentar": "Connection error. Pay to retry",
  "Renovación automática activada": "Auto-renewal activated",
  "Servidores en mantenimiento": "Servers under maintenance",
  "Te ha sustituido una IA": "You've been replaced by an AI",
  "Generado en 3 segundos": "Generated in 3 seconds",
  "Como modelo de lenguaje, me río": "As a language model, I laugh",
  "Respuesta optimizada": "Optimized response",
  "Optimizado": "Optimized",
  "Error 404: torre no encontrada": "Error 404: tower not found",
  "Que gane el mejor": "May the best one win",
  "JAJAJA": "HAHAHA",
  "¿Y eso?": "What was that?",
  "¡Toma!": "Take that!",
  "Para la próxima": "Better luck next time",
  "Ha sido el lag": "It was the lag",
  "Tus": "Your",
  ": en la partida, toca el": ": in battle, tap the",
  "bocadillo": "speech bubble",
  "pases": "passes",
  "de abajo a la derecha para decirle algo al rival (y la CPU te contesta). No se puede escribir, así que nadie insulta… salvo Microblizz, que lo tiene en el contrato. Más frases y emoticonos en los": "at the bottom right to say something to your rival (and the CPU talks back). You can't type, so nobody can insult anyone… except Microblizz, which has it in the contract. More phrases and emotes in the",
  // novedades 0.9.109
  "FRASES Y EMOTICONOS": "PHRASES AND EMOTES",
  ": toca el bocadillo de abajo a la derecha durante la partida y dile algo al rival: «Es una característica, no un bug», «Nos vemos en Recursos Humanos»… Y emoticonos dibujados a mano de tus personajes. Sin escribir, así que nadie insulta.": ": tap the speech bubble at the bottom right during battle and say something to your rival: «It's a feature, not a bug», «See you in HR»… Plus hand-drawn emotes of your characters. No typing, so nobody can insult anyone.",
  "LA CPU CONTESTA": "THE CPU TALKS BACK",
  ": Microblizz, Phony e IAhorro te responden, y también dicen lo suyo al tirarte una torre o al perder una. En el PvP, tus frases las ve tu rival.": ": Microblizz, Phony and IAhorro reply, and have something to say when they knock down your tower or lose one. In PvP, your rival sees your phrases.",
  "EN EL ARMARIO Y EN LOS PASES": "IN THE WARDROBE AND THE PASSES",
  ": empiezas con 8. Hay 26 más en el Pase de Temporada y en el Pase PvP. Elige cuáles llevas en la pestaña FRASES del Armario. Si ya habías cobrado esos niveles del pase, ya son tuyas.": ": you start with 8. There are 26 more in the Season Pass and the PvP Pass. Choose which ones you take in the PHRASES tab of the Wardrobe. If you had already claimed those pass levels, they're already yours.",
  "SILENCIO": "SILENCE",
  ": «Silenciar al rival» en el panel de la partida, y «Frases del rival» en Opciones para no verlas nunca.": ": «Mute rival» in the battle panel, and «Rival's phrases» in Options to never see them.",
  "Microblizz quería un chat libre, pero su departamento legal tardó 3 segundos en ver lo que la gente iba a escribir. Ahora vende las frases por temporadas.": "Microblizz wanted free chat, but its legal department took 3 seconds to see what people would write. Now it sells phrases by the season.",
});
