// Fans of Rumble · Inglés (2/8): frases del chat de las partidas (1/2).
'use strict';
IDIOMA.add({
  "esa torre era de cartón piedra": "that tower was made of papier-mâché",
  "esa torre era de madera de pino barato": "that tower was made of cheap pine",
  "esa torre era de un noob": "that tower belonged to a noob",
  "esa torre no tiene Renacer": "that tower doesn't have Rebirth",
  "escena de acción de 10": "a 10-out-of-10 action scene",
  "ese HypeBeast va con 3 bebidas energéticas": "that HypeBeast is on 3 energy drinks",
  "ese casco tiene wifi": "that helmet has wifi",
  "ese coche tenía un juego increíble (que nunca salió)": "that car had an amazing game (that never came out)",
  "ese mecha tiene más RGB que mi PC": "that mech has more RGB than my PC",
  "eso ha sido mitológico": "that was mythological",
  "eso ha sido un reembolso, pero al revés": "that was a refund, but the other way round",
  "eso le ha dolido a Phony en la cartera": "Phony felt that in its wallet",
  "eso merece un GIF": "that deserves a GIF",
  "eso pasa por no pagar la suscripción": "that's what you get for not paying the subscription",
  "eso va directo a los destacados": "that's going straight to the highlights",
  "esqueletos piratas > esqueletos normales": "pirate skeletons > normal skeletons",
  "esto es mejor que cualquier torneo de pago": "this is better than any pay-to-enter tournament",
  "esto es más épico que la última cinemática de Microblizz": "this is more epic than Microblizz's last cutscene",
  "esto es un meme y aun así juega mejor que yo": "this is a meme and still plays better than me",
  "esto huele a cartucho viejo": "this smells like an old cartridge",
  "esto me recuerda a cierto rey con corona de pinchos 👀": "this reminds me of a certain king with a spiky crown 👀",
  "esto me suena a un juego de 1998…": "this sounds like a 1998 game…",
  "esto pide una tercera parte": "this calls for a third part",
  "final feliz 🍿": "happy ending 🍿",
  "firewall atravesado": "firewall breached",
  "firewall de Microblizz 0, rebelión 1": "Microblizz firewall 0, rebellion 1",
  "fracaso de taquilla 📉": "box office flop 📉",
  "ha entrado el campeón": "the champion has entered",
  "ha llegado el rey del streaming": "the king of streaming has arrived",
  "ha llegado el señor de los memes": "the lord of memes has arrived",
  "huele a cripta desde aquí": "it smells like a crypt from here",
  "héroes a nivel 5 sin pagar nada": "heroes at level 5 without paying a thing",
  "la Banshee necesita un micro con menos ganancia": "the Banshee needs a mic with less gain",
  "la MechaVaca es mi animal espiritual": "the MechaVaca is my spirit animal",
  "la Recreativa tiene más vidas que yo": "the Arcade Cabinet has more lives than me",
  "la ShieldMaiden aguanta más que mi portátil": "the ShieldMaiden lasts longer than my laptop",
  "la comunidad ha hablado": "the community has spoken",
  "la culpa es de los servidores": "it's the servers' fault",
  "la granja le gana al capitalismo": "the farm beats capitalism",
  "la madre del streamer cura más que mi seguro": "the streamer's mum heals more than my insurance",
  "la secuela será aún mejor": "the sequel will be even better",
  "la torre ni lo vio venir": "the tower didn't even see it coming",
  "lag, seguro que es el lag": "lag, it must be the lag",
  "le di a comprar y era un alquiler": "I hit buy and it was a rental",
  "leyendas de verdad": "real legends",
  "los Extras cobran en bocadillos": "the Extras get paid in sandwiches",
  "los Hoplitas son el grupo de WhatsApp de la familia": "the Hoplites are the family WhatsApp group",
  "los SwarmBugs dan un poco de asco, la verdad": "the SwarmBugs are a bit gross, to be honest",
  "los animales vuelven a la madriguera 😢": "the animals are going back to the burrow 😢",
  "los cancelados han vuelto": "the cancelled ones are back",
  "los dioses vuelven a casa": "the gods are going home",
  "los escudos son mi única defensa contra los lunes": "shields are my only defence against Mondays",
  "los juegos cancelados también tienen sentimientos": "cancelled games have feelings too",
  "los noobs juegan peor que yo, y mira que es difícil": "the noobs play worse than me, and that's hard to do",
  "los zombis de las horas extra tienen mejor horario que yo": "the overtime zombies have better hours than me",
  "menos mal que hay curas": "thank goodness for heals",
  "mi abuela tenía discos y era feliz": "my grandma had discs and was happy",
  "mi consola vieja sigue funcionando sin internet": "my old console still works without internet",
  "mi juego favorito ha desaparecido de la tienda 😭": "my favourite game has vanished from the store 😭",
  "morir y volver: el ciclo de vida de un parche": "dying and coming back: the life cycle of a patch",
  "muro de escudos en camino": "shield wall on the way",
  "más discos, menos suscripciones": "more discs, fewer subscriptions",
  "más viewers = más daño, es ciencia": "more viewers = more damage, it's science",
  "más zanahorias para CrazyBunny": "more carrots for CrazyBunny",
  "nadie corre más que la Speedrunner": "nobody runs faster than the Speedrunner",
  "nadie se acordaba de ellos… hasta hoy": "nobody remembered them… until today",
  "necesitamos un parche urgente": "we need an urgent patch",
  "nerf Phony": "nerf Phony",
  "ni Renacer arregla esto": "not even Rebirth fixes this",
  "ni la muerte para a estos": "not even death stops these ones",
  "ningún no-muerto ha leído los términos y condiciones": "no undead has read the terms and conditions",
  "nostalgia 1, torre 0": "nostalgia 1, tower 0",
  "nostalgia nivel: torre que no te ve": "nostalgia level: a tower that can't see you",
  "ojo, que invoca": "watch out, it summons",
  "otra vez cancelados 😢": "cancelled again 😢",
  "paga la suscripción (es broma)": "pay the subscription (just kidding)",
  "palomitas listas 🍿": "popcorn ready 🍿",
  "pantalla azul…": "blue screen…",
  "pon la cámara, que no se ve": "turn the camera on, we can't see you",
  "que alguien le quite el café a MadSquirrel": "somebody take the coffee away from MadSquirrel",
  "que empiece la team fight": "let the team fight begin",
  "que grite ¡acción!": "have her shout action!",
  "que salte, que salte": "make it jump, make it jump",
  "que saque carta, que saque carta": "make it draw a card, make it draw a card",
  "rabia nivel: torre derribada": "rage level: tower down",
  "reiniciando la rebelión": "restarting the rebellion",
  "récord de viewers": "viewer record",
  "se ha caído el directo": "the stream went down",
  "servidores caídos, cómo no": "servers down, of course",
  "sin conexión, como siempre": "offline, as always",
  "sistema de Microblizz hackeado ✅": "Microblizz system hacked ✅",
  "speedrun de torre": "tower speedrun",
  "stonks para la rebelión 📈": "stonks for the rebellion 📈",
  "torre cancelada, como mi suscripción": "tower cancelled, like my subscription",
  "torre desconectada": "tower disconnected",
  "torre enviada a la cripta ⚰️": "tower sent to the crypt ⚰️",
  "torre memeada": "tower memed",
  "una torre menos para Phony": "one tower less for Phony",
  "vuelta a la tumba… hasta la próxima": "back to the grave… until next time",
  "vuelta al sótano…": "back to the basement…",
  "y ahora, devolvednos los discos": "and now, give us our discs back",
  "zanahorias para todos 🥕": "carrots for everyone 🥕",
  "¡CONEJO! ¡CONEJO!": "BUNNY! BUNNY!",
  "¡EN DIRECTO!": "LIVE!",
  "¡Empieza! A ver si hoy alguien le gana a Phony": "It's on! Let's see if anyone beats Phony today",
  "¡GG, torre!": "GG, tower!",
  "¡HA LLEGADO EL CAMPEÓN!": "THE CHAMPION HAS ARRIVED!",
  "¡Ha sido el lag!": "It was the lag!",
  "¡LA DIRECTORA! 🎬": "THE DIRECTOR! 🎬",
  "¡MEMELORD! ¡MEMELORD!": "MEMELORD! MEMELORD!",
  "¡Mi licencia ha caducado!": "My licence has expired!",
  "¡PROGAMER! ¡PROGAMER!": "PROGAMER! PROGAMER!",
  "¡Por fin libre!": "Finally free!",
  "¡Que cierren otro juego, no a mí!": "Shut down another game, not me!",
  "¡Que suban el precio a otro!": "Raise somebody else's price!",
  "¡RAID A LA TORRE!": "RAID THE TOWER!",
  "¡TEAM FIGHT! ¡TEAM FIGHT!": "TEAM FIGHT! TEAM FIGHT!",
  "¡VIKINGO! ¡VIKINGO!": "VIKING! VIKING!",
  "¡corten! torre derribada": "cut! tower down",
  "¡el castor lo ha vuelto a hacer!": "the beaver did it again!",
  "¡insert coin!": "insert coin!",
  "¡los discos vuelven!": "the discs are back!",
  "¡los ha desconectado a todos! 📵": "it disconnected them all! 📵",
  "¡que suene el Hype Train! 🚂": "play the Hype Train! 🚂",
  "¡se levanta el NecroLord!": "the NecroLord rises!",
  "¡silencio, se rueda!": "quiet on set, we're rolling!",
  "¡torre al Olimpo!": "tower to Olympus!",
  "¡triple cancelación!": "triple cancellation!",
  "¡vamos rebelión! #DevolvedLosDiscos": "let's go rebellion! #GiveUsOurDiscsBack",
  "¡y el premio es para…!": "and the prize goes to…!",
  "¿Esto cuenta como vacaciones?": "Does this count as a holiday?",
  "¿Héroes no lo había cerrado Microblizz?": "Didn't Microblizz shut down Heroes?",
  "¿Me han despedido?": "Have I been fired?",
  "¿Me puedo quedar la taza?": "Can I keep the mug?",
  "¿Renacer cuenta como horas extra?": "Does Rebirth count as overtime?",
  "¿Y mi finiquito?": "And my severance pay?",
  "¿alguien ha leído los términos de la suscripción?": "has anyone read the subscription terms?",
  "¿dónde se compra el CAOS? ¿hace falta suscripción?": "where do you buy CHAOS? do I need a subscription?",
  "¿esto es la secuela o el remake?": "is this the sequel or the remake?",
  "¿la PayStation lee discos? (no)": "does the PayStation read discs? (no)",
  "¿la ardilla tiene seguro médico?": "does the squirrel have health insurance?",
  "¿los NanoBots pagan IVA?": "do the NanoBots pay VAT?",
  "¿mutación gigante? mi suerte de siempre: normal": "giant mutation? my usual luck: normal",
  "¿os acordáis de ellos? yo tampoco": "do you remember them? me neither",
  "¿otra subida de precios?": "another price hike?",
  "¿quién deja a un mapache tirar basura? ah, que es su trabajo": "who lets a raccoon throw trash? oh, it's his job",
  "¿y ese quién era? ¡BUM!": "and who was that? BOOM!",
  "BanHammer: el moderador que todos temen": "BanHammer: the moderator everyone fears",
  "Banshee: el despertador de Microblizz": "Banshee: Microblizz's alarm clock",
  "Batería al 0 %": "Battery at 0 %",
  "Cancelado de nuevo": "Cancelled again",
  "ChonkCat se va a sentar encima de alguien": "ChonkCat is going to sit on someone",
  "CrunchZombie: el crunch hecho persona": "CrunchZombie: crunch in human form",
  "Cupido ha venido con mala leche": "Cupid came in a bad mood",
  "CyberMarine corrupto lleva anuncios en el casco": "Corrupted CyberMarine has ads on his helmet",
  "Dadle a like antes de que me vaya": "Hit like before I go",
  "Decidle a la madriguera que la quiero": "Tell the burrow I love it",
  "EpicChampion corrupto: ahora cobra por pelear": "Corrupted EpicChampion: now charges for fighting",
  "Era mi última vida": "It was my last life",
  "Era un plan… de ardilla": "It was a plan… a squirrel plan",
  "Error crítico del sistema": "Critical system error",
  "Eso no estaba en el guion": "That wasn't in the script",
  "Este meme ya es libre": "This meme is free now",
  "Esto lo arregla un parche": "A patch will fix this",
  "Fin del directo patrocinado": "End of the sponsored stream",
  "Firmware de Microblizz desinstalado": "Microblizz firmware uninstalled",
  "GifBlaster dispara en bucle": "GifBlaster fires on a loop",
  "Gracias por acordaros de mí": "Thanks for remembering me",
  "HackerKid va a hackear las torres 💻": "HackerKid is going to hack the towers 💻",
  "HypeBeast va a toda pastilla": "HypeBeast is going full speed",
  "JunkCoon tira basura… a Microblizz": "JunkCoon throws trash… at Microblizz",
  "LaDirectora corrupta solo rueda remakes": "Corrupted TheDirector only shoots remakes",
  "LaDirectora corrupta: «¡acción!… y cobrad la entrada»": "Corrupted TheDirector: «action!… and charge for entry»",
  "Los héroes no mueren, los cierra Microblizz": "Heroes don't die, Microblizz shuts them down",
  "Me ha tocado la mutación mala": "I got the bad mutation",
  "Me voy a hacer mi propio juego": "I'm going to make my own game",
  "Me voy, que tengo lag": "I'm off, I'm lagging",
  "Medusa: la jefa de personal de los dioses": "Medusa: the gods' HR manager",
  "MeerCat cura gratis, no como el seguro de Microblizz": "MeerCat heals for free, unlike Microblizz's insurance",
  "MemeLord corrupto solo publica memes de empresa": "Corrupted MemeLord only posts corporate memes",
  "MemeLord corrupto: «este meme es de pago»": "Corrupted MemeLord: «this meme is pay-to-view»",
  "Microblizz compró a los dioses y dejó de arreglar su juego": "Microblizz bought the gods and stopped fixing their game",
  "Microblizz despide a sus bots tras ganar, por si acaso": "Microblizz fires its bots after winning, just in case",
  "Microblizz despide gente para pagar el yate del CEO": "Microblizz lays off people to pay for the CEO's yacht",
  "Microblizz dice que perder «estaba en el plan»": "Microblizz says losing «was part of the plan»",
  "Microblizz gana una partida y lo celebra subiendo el precio del pase": "Microblizz wins a match and celebrates by raising the pass price",
  "Microblizz gana y el CEO se compra otro yate": "Microblizz wins and the CEO buys another yacht"
});
