// Fans of Rumble · Inglés: novedades de la 0.9.113 (la IA rival con tácticas según la dificultad) y de la 0.9.114 (miniaturas nuevas)
'use strict';
IDIOMA.add({
  "<b>RIVALES CON CABEZA</b>: la máquina ya tiene tácticas según la dificultad. En Normal, si te quedas sin CAOS te ataca por el carril donde no estás, y guarda los hechizos para pillar a un grupo. En Difícil, Heroica, Mítica, CEO y los jefes duros, además ataca con combos (el tanque y el apoyo casi a la vez), presiona el otro carril y no te ataca si tienes el CAOS lleno. En Fácil juega como siempre.": "<b>RIVALS WITH BRAINS</b>: the machine now has tactics depending on the difficulty. On Normal, if you run out of CHAOS it attacks down the lane where you aren't, and it saves its spells to catch a group. On Hard, Heroic, Mythic, CEO and the tough bosses, it also attacks with combos (the tank and the support almost at once), pressures the other lane and won't attack you while your CHAOS is full. On Easy it plays as always.",
  "<b>PARTIDA RÁPIDA CON LA IA NUEVA</b>: SurvivalBot ya no sigue un guion fijo: juega con la IA nueva y sus tácticas según la dificultad que elijas. Las primeras fases de la campaña siguen siendo para aprender.": "<b>QUICK MATCH WITH THE NEW AI</b>: SurvivalBot no longer follows a fixed script: it plays with the new AI and its tactics for the difficulty you pick. The first campaign levels are still for learning.",
  "<b>ENTRENAMIENTO</b>: los rivales FÁCIL, IGUALADO y DIFÍCIL ahora también juegan distinto: el fácil sin tácticas, el igualado como en Normal y el difícil con todas.": "<b>TRAINING</b>: the EASY, EVEN and HARD rivals now also play differently: the easy one without tactics, the even one like on Normal and the hard one with all of them.",
  "Microblizz ha enseñado a su IA a contar tu CAOS. Dice que no es espiar: es «analítica del comportamiento del usuario».": "Microblizz has taught its AI to count your CHAOS. It says it isn't spying: it's \"user behaviour analytics\".",
  "<b>MINIATURAS NUEVAS</b>: cada habilidad y cada objeto tiene ahora su propio dibujo, en lugar de dos letras o del mismo icono para todos. El fondo lleva el color de su rareza, y las Épicas y Legendarias brillan con rayos de luz. Las verás en la Biblioteca, el inventario y el gashapón.": "<b>NEW THUMBNAILS</b>: every ability and item now has its own drawing, instead of two letters or the same icon for all. The background shows its rarity colour, and Epics and Legendaries shine with rays of light. You'll see them in the Library, the inventory and the gacha.",
  "Microblizz ha encargado 75 dibujos nuevos. Al ilustrador le ha pagado en «visibilidad».": "Microblizz commissioned 75 new drawings. It paid the illustrator in \"exposure\".",
});
