// Fans of Rumble · Inglés (3/8): frases del chat de las partidas (2/2).
'use strict';
IDIOMA.add({
  "Microblizz les cobra el alquiler de la tumba": "Microblizz charges them rent for the grave",
  "Microblizz les ha metido anuncios en el cerebro": "Microblizz has put ads in their brains",
  "Microblizz les hace trabajar hasta muertos (literal)": "Microblizz makes them work even when dead (literally)",
  "Microblizz los canceló y los encerró en el sótano": "Microblizz cancelled them and locked them in the basement",
  "Microblizz no paga ni a los muertos": "Microblizz doesn't even pay the dead",
  "Microblizz pierde y cierra otro juego para animarse": "Microblizz loses and shuts down another game to cheer itself up",
  "NO VAS A CREER LO QUE HACE ESTE MEME": "YOU WON'T BELIEVE WHAT THIS MEME DOES",
  "Nadie se acordará de mí": "Nobody will remember me",
  "NeonSniper apunta desde casa": "NeonSniper aims from home",
  "Nos vemos en el próximo stream": "See you at the next stream",
  "Otra vez a la tumba": "Back to the grave again",
  "Otra vez al olvido…": "Back to oblivion again…",
  "Phony dice que perder «es una experiencia digital exclusiva»": "Phony says losing «is an exclusive digital experience»",
  "Phony gana una partida y lo celebra subiendo los precios": "Phony wins a match and celebrates by raising prices",
  "Phony gana y borra la partida de tu biblioteca, por si acaso": "Phony wins and deletes the match from your library, just in case",
  "Phony les obliga a jugar con contrato de exclusividad": "Phony forces them to play under an exclusivity contract",
  "Phony se ahorra millones y nos sube los precios": "Phony saves millions and raises our prices",
  "Phony solo les deja rodar remakes": "Phony only lets them shoot remakes",
  "Phony: «el futuro es digital». El futuro es alquilar": "Phony: «the future is digital». The future is renting",
  "Por fin juego por diversión": "Finally playing for fun",
  "Por fin una película original": "Finally an original movie",
  "RageQuitter a punto de tirar el mando": "RageQuitter about to throw the controller",
  "Reiniciando…": "Restarting…",
  "ShieldMaiden aguanta lo que le echen": "ShieldMaiden takes whatever you throw at her",
  "SiegeMech viene a demoler": "SiegeMech is here to demolish",
  "Sistema liberado": "System freed",
  "SnackMom trae bocatas para todos 🥪": "SnackMom brings sandwiches for everyone 🥪",
  "SoporteBot: «¿ha probado a apagar y encender?»": "SupportBot: «have you tried turning it off and on again?»",
  "StitchBrute viene a dar abrazos tóxicos": "StitchBrute is here to give toxic hugs",
  "StreamKing corrupto banea a todo el chat": "Corrupted StreamKing bans the entire chat",
  "SurvivalBot sobrevive a todo menos a las críticas": "SurvivalBot survives everything except the reviews",
  "SurvivalBot, ¿quién te ha diseñado?": "SurvivalBot, who designed you?",
  "SynthCat pincha música y daño": "SynthCat spins music and damage",
  "TechDroid lo arregla todo menos mi vida": "TechDroid fixes everything except my life",
  "ThunderGod ha venido sin paraguas": "ThunderGod came without an umbrella",
  "TrollBot va a provocar a todos 😈": "TrollBot is going to provoke everyone 😈",
  "Un jugador gana a Microblizz sin comprar ningún pack. Escándalo": "A player beats Microblizz without buying a single pack. Scandal",
  "Un jugador gana a Phony sin pagar la suscripción. Escándalo": "A player beats Phony without paying the subscription. Scandal",
  "ViralBot va a hacerse viral (aturdiendo)": "ViralBot is going viral (by stunning)",
  "Volveré en la secuela": "I'll be back in the sequel",
  "Vuelvo enseguida (literal)": "Be right back (literally)",
  "Ya estaba muerto, no cuenta": "It was already dead, doesn't count",
  "Ya puedo volver a hacer gracia": "I can be funny again",
  "antes jugaba por diversión 😢": "I used to play for fun 😢",
  "arreglos gratis, como debe ser": "free repairs, as it should be",
  "bichitos de metal en camino": "little metal critters on the way",
  "caballero sin cabeza (pero con calavera)": "headless knight (but with a skull)",
  "combo patrocinado por Phony 🙄": "combo sponsored by Phony 🙄",
  "congelar unidades: la única actualización de SurvivalBot en 5 años": "freezing units: SurvivalBot's only update in 5 years",
  "cosido a mano y con mal olor": "hand-stitched and smelly",
  "cuanto más pega, más sube": "the more it hits, the more it climbs",
  "cuatro NanoBots, mil problemas": "four NanoBots, a thousand problems",
  "cuatro bichos con mucha hambre": "four critters with big appetites",
  "cuatro esqueletos y ningún contrato": "four skeletons and no contract",
  "cuatro extras con espadas de cartón": "four extras with cardboard swords",
  "cuidado, que lo graba todo": "careful, it records everything",
  "devolvednos el formato físico": "give us the physical format back",
  "dinamita y ningún plan B": "dynamite and no plan B",
  "dispara desde lejos, como los jefes por correo": "shoots from afar, like bosses by email",
  "dos ardillas, cero paciencia": "two squirrels, zero patience",
  "dos perritos con ganas": "two eager doggos",
  "dron cazador en el aire 🚁": "hunter drone in the air 🚁",
  "drones de Microblizz con anuncios": "Microblizz drones with ads",
  "el CEO cobra más que todo el estudio junto": "the CEO earns more than the whole studio combined",
  "el CEO ha venido a cerrar otro juego": "the CEO came to shut down another game",
  "el CEO se ha comprado otro yate con tus gemas": "the CEO bought another yacht with your gems",
  "el Coleccionista no presta sus juegos: los lanza": "the Collector doesn't lend his games: he throws them",
  "el Detective busca pistas 🔍": "the Detective is looking for clues 🔍",
  "el Minotauro corrupto se ha perdido en su propio laberinto": "the corrupted Minotaur got lost in his own maze",
  "el Minotauro viene embistiendo": "the Minotaur comes charging",
  "el Modder trae el parche que Phony no hizo": "the Modder brings the patch Phony never made",
  "el NecroLord corrupto despide a los muertos… otra vez": "the corrupted NecroLord fires the dead… again",
  "el Parche Día 1 pesa 80 GB": "the Day 1 Patch weighs 80 GB",
  "el Presidente acaba de anunciar la PayStation 7 (sin botones)": "the President just announced the PayStation 7 (no buttons)",
  "el Presidente cobra hasta el aire que respiras": "the President charges even for the air you breathe",
  "el Presidente de Phony ha subido la suscripción en directo": "the Phony President raised the subscription live",
  "el ProGamer corrupto solo juega si le pagan": "the corrupted ProGamer only plays if he's paid",
  "el ProGamer corrupto ya no saluda al chat": "the corrupted ProGamer doesn't greet the chat anymore",
  "el Spoiler va a destrozar la película": "the Spoiler is going to ruin the movie",
  "el Stonks corrupto solo sube para el CEO": "the corrupted Stonks only goes up for the CEO",
  "el StreamKing corrupto: «usa mi código de descuento»": "the corrupted StreamKing: «use my discount code»",
  "el VikingoPerdido lleva años sin ver la luz": "the LostViking hasn't seen the light in years",
  "el campero lleva 20 minutos ahí": "the camper has been there for 20 minutes",
  "el campeón se ha vendido a Microblizz": "the champion sold out to Microblizz",
  "el castor va directo a la torre 💣": "the beaver is heading straight for the tower 💣",
  "el chat de ese lado son todo bots": "the chat on that side is all bots",
  "el clickbait ha funcionado, he hecho clic": "the clickbait worked, I clicked",
  "el doble hace todas las escenas peligrosas": "the double does all the dangerous scenes",
  "el dron ha fichado al sanador": "the drone has signed the healer",
  "el espía de un juego que nunca salió": "the spy from a game that never came out",
  "el hater no ha visto el juego pero opina": "the hater hasn't seen the game but has opinions",
  "el mando cuesta más que la consola": "the controller costs more than the console",
  "el mapache ha traído su contenedor": "the raccoon brought his dumpster",
  "el meme del jefe lleva marca de agua": "the boss's meme has a watermark",
  "el muro de escudos del jefe es de la beta, seguro que tiene bugs": "the boss's shield wall is from the beta, it must have bugs",
  "el paparazzi no respeta a nadie": "the paparazzi respects no one",
  "el zorro ya ha desaparecido 👀": "the fox has already vanished 👀",
  "elemental, querido chat": "elementary, dear chat",
  "esa Medusa petrifica con cartas de despido": "that Medusa petrifies with layoff letters",
  "esa película la he visto mil veces": "I've seen that movie a thousand times",
  "esas ardillas van más rápido que mi wifi": "those squirrels are faster than my wifi",
  "ese HackerKid ahora trabaja para la empresa": "that HackerKid works for the company now",
  "ese arbusto se ha movido": "that bush moved",
  "ese caballero frena a cualquiera": "that knight slows anyone down",
  "ese castor no tiene seguro de vida": "that beaver has no life insurance",
  "ese coche va directo a las torres": "that car is heading straight for the towers",
  "ese dron tiene orden de búsqueda": "that drone has an arrest warrant",
  "ese escudo es más duro que un lunes": "that shield is tougher than a Monday",
  "ese espía lleva gafas de sol de noche": "that spy wears sunglasses at night",
  "ese hater va a por la curandera": "that hater is going for the healer",
  "ese hurón ha visto demasiadas pelis": "that ferret has watched too many movies",
  "ese jefe tiene 3 viewers y son bots": "that boss has 3 viewers and they're bots",
  "ese marine es de otra década": "that marine is from another decade",
  "ese niño ha borrado el servidor de Microblizz": "that kid deleted Microblizz's server",
  "ese toro no entiende de laberintos": "that bull doesn't understand mazes",
  "ese tren no para en ninguna estación": "that train doesn't stop at any station",
  "ese va con tres bebidas energéticas": "that one is on three energy drinks",
  "ese vikingo se perdió en 1995 y sigue buscando la salida": "that viking got lost in 1995 and is still looking for the exit",
  "eso de congelar es muy de rey exánime": "that freezing thing is very lich-king",
  "esos gamers ahora pagan por jugar online": "those gamers now pay to play online",
  "esos juegos nunca llegaron a salir 😢": "those games never came out 😢",
  "esos servidores gastan más luz que mi pueblo": "those servers use more electricity than my town",
  "esos streamers corrompidos solo hacen directos de anuncios": "those corrupted streamers only do ad streams",
  "esqueletos en fila, como en la oficina": "skeletons in a row, like at the office",
  "esta música me suena del ascensor…": "this music sounds like it's from the lift…",
  "esta música suena a anuncio de consola": "this music sounds like a console ad",
  "esta película ya la he visto… tres veces": "I've already seen this movie… three times",
  "exclusiva: el sanador, sin maquillaje": "exclusive: the healer, without makeup",
  "flechas de amor (y de daño) 💘": "arrows of love (and damage) 💘",
  "francotirador invisible, qué miedo": "invisible sniper, how scary",
  "francotiradora fluorescente": "fluorescent sniper",
  "gato con sintetizador, lo que faltaba 🎹": "cat with a synthesizer, just what we needed 🎹",
  "gato gordo, problemas gordos": "fat cat, fat problems",
  "gorros de hélice en formación": "propeller hats in formation",
  "ha llegado el hater: BUUUU": "the hater has arrived: BOOOO",
  "hombreras XXL en camino": "XXL shoulder pads on the way",
  "hoplitas en formación": "hoplites in formation",
  "huesos baratos, mucho daño": "cheap bones, lots of damage",
  "insert coin, insert coin": "insert coin, insert coin",
  "la MechaVaca no frena ni en las curvas": "the MechaVaca doesn't brake even on corners",
  "la NeonSniper corrupta cobra por disparo": "the corrupted NeonSniper charges per shot",
  "la PayStation sin lector cuesta 600 € y no lee nada": "the PayStation without a drive costs 600 € and reads nothing",
  "la PayStation te cobra hasta por mirarla": "the PayStation charges you even for looking at it",
  "la arpía tiene peor humor que el CEO": "the harpy has a worse mood than the CEO",
  "la caja de mi juego viene vacía, solo trae un código": "my game's box comes empty, only with a code",
  "la madre del streamer cura mejor que nadie": "the streamer's mum heals better than anyone",
  "la sombra va directa al sanador 👻": "the shadow goes straight for the healer 👻",
  "la suricata trae tiritas para todos": "the meerkat brings plasters for everyone",
  "llega el técnico, y sin cita previa": "the technician arrives, without an appointment",
  "llega la enfermera 🩹": "the nurse arrives 🩹",
  "lleva el logo de Phony hasta en la frente": "has the Phony logo even on his forehead",
  "los Memes corrompidos ya no hacen gracia: son anuncios": "corrupted Memes aren't funny anymore: they're ads",
  "los becarios de Microblizz trabajan gratis": "Microblizz interns work for free",
  "los extras cobran en bocadillos": "the extras get paid in sandwiches",
  "mi colección de discos vale más que toda su consola": "my disc collection is worth more than their whole console",
  "mi consola vieja leía discos y era más feliz": "my old console read discs and was happier",
  "mi juego ha desaparecido de la biblioteca de un día para otro": "my game vanished from the library overnight",
  "misión: el sanador. Estado: cancelada… o no": "mission: the healer. Status: cancelled… or not",
  "monstruo de goma en camino": "rubber monster on the way",
  "nadie ha visto saltar así a un hurón": "nobody has seen a ferret jump like that",
  "ni la sombra cobra en Microblizz": "not even the shadow gets paid at Microblizz",
  "ninja con lag cero": "ninja with zero lag",
  "no la miréis a los ojos 🐍": "don't look her in the eyes 🐍",
  "no le hagáis caso al TrollBot (imposible)": "don't listen to the TrollBot (impossible)",
  "número 7: ataca al sanador": "number 7: attack the healer",
  "ojo con la arpía, va a por el sanador": "watch the harpy, she's going for the healer",
  "ojo, que el zorro pega x3": "careful, the fox hits x3",
  "ojo, que ese explota": "careful, that one explodes",
  "ojos rojos = ahora son de Microblizz": "red eyes = they belong to Microblizz now",
  "otra secuela que nadie ha pedido": "another sequel nobody asked for",
  "otra subida de la suscripción…": "another subscription hike…",
  "pagué 80 € por un juego que ya no existe": "I paid 80 € for a game that no longer exists",
  "patrocinado por Phony, qué tristeza": "sponsored by Phony, how sad",
  "que grite la Banshee 😱": "let the Banshee scream 😱",
  "reciclaje ofensivo": "offensive recycling",
  "ráfaga de gifs en camino": "burst of GIFs on the way",
  "récord mundial en camino": "world record on the way",
  "se ha saltado medio mapa": "skipped half the map",
  "sin lector no hay segunda mano ni préstamos": "without a drive there's no second-hand or lending",
  "such dog, very rápido, wow 🐕": "such dog, very fast, wow 🐕",
  "superhéroe de oferta": "bargain superhero",
  "todo son secuelas desde que llegó Phony": "it's all sequels since Phony arrived",
  "tres lanzas, cero miedo": "three spears, zero fear",
  "tres noobs y ningún plan": "three noobs and no plan",
  "tres subs y un sueño": "three subs and a dream",
  "tres vikingos y una brújula rota": "three vikings and a broken compass",
  "tres zombis = un lunes por la mañana": "three zombies = a Monday morning",
  "un MMO entero cancelado… y ahí está, enfadado": "a whole MMO cancelled… and there it is, angry"
});
