// Fans of Rumble · Inglés (4/8): últimas frases del chat y la campaña 3 (IAhorro y Los Creadores).
'use strict';
IDIOMA.add({
  "un fantasma con varita, lo normal": "a ghost with a wand, the usual",
  "un gigante en beta, ¿qué puede salir mal?": "a giant in beta, what could go wrong?",
  "una consola sin lector, qué gran invento": "a console without a drive, what a great invention",
  "una secuela más y me voy al cine de verdad": "one more sequel and I'm off to a real cinema",
  "zombis lentos pero cobran horas extra": "slow zombies but they get overtime pay",
  "¡Adiós al contrato de exclusividad!": "Goodbye, exclusivity contract!",
  "¡BANEO MASIVO!": "MASS BAN!",
  "¡CAMPERO! ¡reportadlo!": "CAMPER! report him!",
  "¡CHU CHUUU! a la torre 🚂": "CHOO CHOOO! to the tower 🚂",
  "¡Corten!": "Cut!",
  "¡FLASH! el paparazzi ha pillado al sanador": "FLASH! the paparazzi caught the healer",
  "¡HéroeDeSaldo al rescate! (2x1)": "BargainHero to the rescue! (2-for-1)",
  "¡KAIJU! 🦖 (se le ve la cremallera)": "KAIJU! 🦖 (you can see the zipper)",
  "¡Libre de Microblizz!": "Free from Microblizz!",
  "¡MECHAVACA! 🐄🤖": "MECHACOW! 🐄🤖",
  "¡Mis bellotas!": "My acorns!",
  "¡Por el Olimpo!": "For Olympus!",
  "¡Por fin descanso en paz!": "Finally resting in peace!",
  "¡Por fin fuera del sótano!": "Finally out of the basement!",
  "¡Por fin sin patrocinadores!": "Finally free of sponsors!",
  "¡Se acabaron los remakes!": "No more remakes!",
  "¡Se me ha caído el directo!": "My stream crashed!",
  "¡TITÁN! cuidado cuando se enfade": "TITAN! careful when it gets angry",
  "¡acrobacia!": "stunt!",
  "¡ardillas con café!": "squirrels with coffee!",
  "¡artillería pesada! 💥": "heavy artillery! 💥",
  "¡bichos! 🐜": "critters! 🐜",
  "¡brum, brum! 🏎️": "vroom, vroom! 🏎️",
  "¡devuélvenos los discos!": "give us our discs back!",
  "¡discos físicos! 💿": "physical discs! 💿",
  "¡el hurón ninja va a por la enfermera!": "the ninja ferret is going for the nurse!",
  "¡la arpía viene del cielo!": "the harpy is coming from the sky!",
  "¡libéralos!": "free them!",
  "¡llegan los subs!": "the subs are here!",
  "¡no me digas el final!": "don't tell me the ending!",
  "¡noobs al ataque!": "noobs attack!",
  "¡que alguien le devuelva los discos a la gente!": "somebody give people their discs back!",
  "¡rayo en cadena! ⚡": "chain lightning! ⚡",
  "¡speedrun! ⏱️": "speedrun! ⏱️",
  "¡una recreativa con piernas! 🕹️": "an arcade machine with legs! 🕹️",
  "¡vikingos perdidos!": "lost vikings!",
  "¿alguien ve al GhostAgent? yo no 👀": "can anyone see the GhostAgent? I can't 👀",
  "¿cuántos juegos guardaba Microblizz en este sótano?": "how many games did Microblizz keep in this basement?",
  "¿dónde está el zorro? ¿alguien lo ve?": "where's the fox? can anyone see it?",
  "¿dónde está la sombra? ah, detrás de tu curandera": "where's the shadow? oh, behind your healer",
  "¿dónde está mi disco? 😡": "where's my disc? 😡",
  "¿la CajaBotín da algo bueno? (no)": "does the LootBoxBot give anything good? (no)",
  "¿pagar para jugar online? ¿otra vez?": "pay to play online? again?",
  "¿y ahora mis discos dónde los meto?": "and now where do I put my discs?",
  "Aquí no se hace crunch: si una unidad pasa 3 s sin recibir daño, descansa y se cura un 2 % de su vida por segundo.": "No crunch here: if a unit goes 3 s without taking damage, it rests and heals 2 % of its health per second.",
  "Arte con seis dedos": "Art with Six Fingers",
  "Asistente Alucinado": "Hallucinating Assistant",
  "Banda sonora": "Soundtrack",
  "Becario Virtual": "Virtual Intern",
  "Cada 8 s rediseña el nivel bajo los pies del enemigo: aturde 1 s a los que tiene cerca.": "Every 8 s it redesigns the level under the enemy's feet: stuns nearby ones for 1 s.",
  "Centro de datos": "Data Centre",
  "Clonador 3000": "Cloner 3000",
  "Clones": "Clones",
  "Como modelo de lenguaje, me rindo": "As a language model, I give up",
  "Compositora": "Composer",
  "Copiapega": "Copy-Paste",
  "Creadores corrompidos": "Corrupted Creators",
  "Créditos finales": "End Credits",
  "CyberMarine entrenado": "Trained CyberMarine",
  "DESCANSO": "REST",
  "Datos sin permiso": "Data Without Permission",
  "Dibuja a mano, píxel a píxel. Lanza píxeles que salpican a los de alrededor.": "Draws by hand, pixel by pixel. Throws pixels that splash those around.",
  "Directo de nadie": "Nobody's Stream",
  "Diseñadora de Niveles": "Level Designer",
  "Doblaje sintético": "Synthetic Dubbing",
  "Dron de Contenido": "Content Drone",
  "EL ESTUDIO INDIE": "THE INDIE STUDIO",
  "ENTRENADA CON TU TRABAJO": "TRAINED ON YOUR WORK",
  "El Almacén de Datos": "The Data Warehouse",
  "El Estudio Vacío": "The Empty Studio",
  "El Núcleo de IAhorro": "The IAhorro Core",
  "El Prototipo": "The Prototype",
  "El corazón de IAhorro. Cuanto más juegos copia, más grande se hace. Los programadores, diseñadores y artistas despedidos esperan fuera: si la apagas, se unen a ti.": "IAhorro's heart. The more games it copies, the bigger it gets. The fired programmers, designers and artists wait outside: if you switch it off, they join you.",
  "El prompt definitivo": "The Ultimate Prompt",
  "El último prompt": "The Last Prompt",
  "Encuentra bugs": "Finds bugs",
  "Entrenada con tu trabajo": "Trained on your work",
  "Error 404: alma no encontrada": "Error 404: soul not found",
  "Esto lo hice a mano": "I made this by hand",
  "Esto no estaba en mis datos": "This wasn't in my data",
  "GRACIAS POR JUGAR": "THANKS FOR PLAYING",
  "Generador de Clones": "Clone Generator",
  "Granja de Servidores": "Server Farm",
  "Guardé la partida": "I saved the game",
  "He sido entrenado para esto": "I've been trained for this",
  "Hizo un juego entero ella sola, en su cuarto. Dispara líneas de código y cada 8 s lanza un ¡HOTFIX!: cura 70 a los aliados cercanos y les quita los aturdimientos. Si cae, vuelve a los 12 s.": "She made a whole game by herself, in her bedroom. Fires lines of code and every 8 s casts a HOTFIX!: heals 70 to nearby allies and removes their stuns. If she falls, she comes back after 12 s.",
  "IAhorro copiando en directo": "IAhorro copying live",
  "IAhorro está generando su propio discurso de victoria": "IAhorro is generating its own victory speech",
  "IAhorro gana y genera 300 notas de prensa celebrándolo": "IAhorro wins and generates 300 press releases celebrating it",
  "IAhorro gana: «ha sido muy eficiente»": "IAhorro wins: «it was very efficient»",
  "IAhorro ha despedido a 300 personas para ahorrar en café": "IAhorro laid off 300 people to save on coffee",
  "IAhorro ha generado 40 juegos mientras escribía esto": "IAhorro generated 40 games while I typed this",
  "IAhorro lo celebra despidiendo a alguien más": "IAhorro celebrates by laying off someone else",
  "IAhorro me prometió «eficiencia»": "IAhorro promised me «efficiency»",
  "IAhorro promete «mejorar el modelo» tras perder contra gente de verdad": "IAhorro promises to «improve the model» after losing to real people",
  "IAhorro se entrena con todo lo que encuentra… sin pedir permiso. Ha obligado a los Ciberpunks a vigilar sus servidores, llenos de juegos copiados.": "IAhorro trains on everything it finds… without asking permission. It has forced the Cyberpunks to guard its servers, full of copied games.",
  "IAhorro ya está redactando el comunicado (con IA)": "IAhorro is already drafting the statement (with AI)",
  "IAhorro: «esa torre era un error de redondeo»": "IAhorro: «that tower was a rounding error»",
  "IAhorro: «estamos mejorando el modelo»": "IAhorro: «we're improving the model»",
  "IAhorro: «he generado tu derrota en 0,3 s»": "IAhorro: «I generated your defeat in 0.3 s»",
  "IAhorro: «he leído todos los juegos». Sin pagar ninguno": "IAhorro: «I've read every game». Without paying for any",
  "IAhorro: «puedo hacer tu juego en 5 segundos». Y se nota": "IAhorro: «I can make your game in 5 seconds». And it shows",
  "Juegos en serie": "Mass-Produced Games",
  "La Granja de Prompts": "The Prompt Farm",
  "La sala fría": "The Cold Room",
  "Llueven portfolios de gente despedida (y con mucho talento): 160 de daño en la zona. A los sanadores, un 50 % más.": "Portfolios of laid-off (and very talented) people rain down: 160 damage in the area. Healers take 50 % more.",
  "Lluvia de portfolios": "Portfolio Rain",
  "Lo rompe todo antes que nadie: recibe un 30 % menos de daño y marca a lo que golpea (tu equipo le hace un 20 % más durante 4 s).": "Breaks everything before anyone else: takes 30 % less damage and marks what it hits (your team deals 20 % more to it for 4 s).",
  "Los Creadores": "The Creators",
  "Mi contexto se ha llenado": "My context is full",
  "Microblizz y Phony se han juntado para comprar IAhorro, la IA del ahorro… de sueldos. Han despedido a todo el estudio: ahora unas pantallas escriben juegos solas, uno cada cinco minutos, y todos son iguales.": "Microblizz and Phony have joined forces to buy IAhorro, the AI that saves… on salaries. They've laid off the entire studio: now some screens write games on their own, one every five minutes, and they're all the same.",
  "Nos vemos en la secuela (si hay presupuesto)": "See you in the sequel (if there's budget)",
  "POV: eres un prompt de IAhorro": "POV: you're an IAhorro prompt",
  "Pasillo de servidores": "Server Corridor",
  "Pizza, café y ganas: cura 110 a tus tropas de la zona y atacan un 30 % más rápido durante 5 s.": "Pizza, coffee and enthusiasm: heals 110 to your troops in the area and they attack 30 % faster for 5 s.",
  "Prompt rechazado": "Prompt rejected",
  "Puestos vacíos": "Empty Desks",
  "Regenerando respuesta…": "Regenerating response…",
  "SIN CRUNCH": "NO CRUNCH",
  "Sala de entrenamiento": "Training Room",
  "Salen los créditos con el nombre de toda la gente que hizo el juego. Los enemigos de la zona se quedan 3 s leyéndolos sin hacer nada.": "The credits roll with the names of everyone who made the game. The enemies in the area stand reading them for 3 s, doing nothing.",
  "Sillas vacías y arte con seis dedos. IAhorro ha cambiado a los streamers por copias generadas: todas con la misma cara, la misma voz y el mismo chiste.": "Empty chairs and art with six fingers. IAhorro has replaced the streamers with generated copies: all with the same face, the same voice and the same joke.",
  "Sin crunch": "No crunch",
  "StreamKing IA": "StreamKing AI",
  "StreamKing generado": "Generated StreamKing",
  "Su música épica anima a los de alrededor: los aliados cercanos pegan un 20 % más.": "Her epic music cheers on those around her: nearby allies hit 20 % harder.",
  "Sustitución por IA": "Replaced by AI",
  "Tanque + jam": "Tank + jam",
  "Taza «Sin crunch»": "«No crunch» Mug",
  "Tester de QA": "QA Tester",
  "Trabaja por su cuenta y va directo al grano: salta a por el sanador o el tirador enemigo y les hace el doble de daño.": "Works on his own and gets straight to the point: jumps at the enemy healer or shooter and deals them double damage.",
  "Tras 3 s sin recibir daño, tus unidades descansan y se curan un 2 % por segundo": "After 3 s without taking damage, your units rest and heal 2 % per second",
  "Tres creadores que han hecho un juego en 48 horas. Rápidos y con mucho café.": "Three creators who made a game in 48 hours. Fast and full of coffee.",
  "Un robot gigante hecho con cinta americana y mucho cariño. Aguanta muchísimo y, cuando cae, salen 2 creadores de la Game Jam a por la segunda versión.": "A giant robot made with duct tape and lots of love. It takes a ton of damage and, when it falls, 2 Game Jam creators come out for the second version.",
  "Volveré en la versión 5": "I'll be back in version 5",
  "Vuelvo a tener mi cara": "I have my face back",
  "Ya no tengo que copiar a nadie": "I don't have to copy anyone anymore",
  "actualización obligatoria, cómo no": "mandatory update, of course",
  "apágala, apágala": "switch it off, switch it off",
  "bug encontrado: la torre ya no existe": "bug found: the tower no longer exists",
  "créditos finales con nombres de verdad": "end credits with real names",
  "cuidado, que ha aprendido a copiar los hechizos": "careful, it learned to copy the spells",
  "el Asistente Alucinado acaba de inventarse una regla": "the Hallucinating Assistant just made up a rule",
  "el CyberMarine entrenado juega igual que tú… porque te ha copiado": "the trained CyberMarine plays just like you… because it copied you",
  "el Generador de Clones ha copiado hasta el chat": "the Clone Generator even copied the chat",
  "el Núcleo de IAhorro": "the IAhorro Core",
  "el Prototipo va con cinta americana y fe": "the Prototype runs on duct tape and faith",
  "el StreamKing generado tiene 3 millones de seguidores bots": "the generated StreamKing has 3 million bot followers",
  "el Tester ya ha encontrado 47 bugs": "the Tester has already found 47 bugs",
  "entrenada con tu trabajo, literal": "trained on your work, literally",
  "esa torre la ha hecho una IA, se nota": "an AI made that tower, you can tell",
  "ese CyberMarine tiene seis dedos": "that CyberMarine has six fingers",
  "eso era mío": "that was mine",
  "esos bots son todos iguales": "those bots are all the same",
  "estos sí que hacen juegos con cariño": "these ones actually make games with love",
  "hecho a mano > hecho en serie": "handmade > mass-produced",
  "hola desde el trabajo (que aún tengo) 👀": "hello from work (which I still have) 👀",
  "la Compositora tiene banda sonora hasta para ir al baño": "the Composer has a soundtrack even for going to the bathroom",
  "la IndieDev ha salido con su café": "the IndieDev came out with her coffee",
  "la IndieDev hizo su juego en su cuarto, respeto": "the IndieDev made her game in her bedroom, respect",
  "la próxima sí": "next time for sure",
  "los Creadores": "the Creators",
  "los creadores vuelven a casa": "the creators are going home",
  "mi juego favorito lo hizo gente, no un servidor": "my favourite game was made by people, not a server",
  "parche del día 0, por fin uno bueno": "day-0 patch, finally a good one",
  "servidor apagado 🔌": "server switched off 🔌",
  "sin crunch y siguen ganando, ¿veis?": "no crunch and still winning, see?",
  "su voz es de un robot leyendo un guion": "its voice is a robot reading a script",
  "todos esos juegos son el mismo juego": "all those games are the same game",
  "torre rediseñada": "tower redesigned",
  "tu Estudio indie": "your Indie Studio",
  "una torre menos para IAhorro": "one tower less for IAhorro",
  "yo solo vengo por la música (que la ha compuesto alguien)": "I'm only here for the music (somebody composed it)",
  "¡ACTUALIZANDO!": "UPDATING!",
  "¡Empieza! Hoy apagamos a IAhorro": "It's on! Today we switch IAhorro off",
  "¡HOTFIX! ¡HOTFIX!": "HOTFIX! HOTFIX!",
  "¡Hotfix!": "Hotfix!",
  "¡IAhorro desconectada!": "IAhorro disconnected!",
  "¡IAhorro en persona!": "IAhorro in person!",
  "¡Me desconecto!": "I'm logging off!",
  "¡Me voy a mi hora!": "I'm leaving on time!",
  "¡REDISEÑO!": "REDESIGN!",
  "¡Rediseño!": "Redesign!"
});
