// Fans of Rumble · Inglés (5/8): avisos de la partida, órdenes de los jefes, campaña y pantalla del final.
'use strict';
IDIOMA.add({
  "¡SEGUNDA ITERACIÓN!": "SECOND ITERATION!",
  "¡SUSTITUIDO!": "REPLACED!",
  "¡VERSIÓN 2.0!": "VERSION 2.0!",
  "¡Vuelvo a crear!": "I'm creating again!",
  "¡los creadores vuelven!": "the creators are back!",
  "¡los ha dejado actualizando! ⏳": "it left them updating! ⏳",
  "¡que se apaga! 🔌": "it's shutting down! 🔌",
  "¡te ha copiado la carta! 😡": "it copied your card! 😡",
  "¡vamos rebelión! #HechoAMano": "let's go rebellion! #Handmade",
  "«He generado 4.000 juegos esta mañana. Todos iguales. Todos tuyos.»": "«I generated 4,000 games this morning. All the same. All yours.»",
  "«IAhorro me ha entrenado con tus partidas. Sé lo que vas a hacer.»": "«IAhorro trained me on your matches. I know what you're going to do.»",
  "«Soy el streamer perfecto: nunca me canso, nunca me quejo, nunca existo.»": "«I'm the perfect streamer: I never get tired, I never complain, I never exist.»",
  "«entrenado con tu trabajo» = copiado": "«trained on your work» = copied",
  "«¿Para qué pagar a 300 personas si me tenéis a mí? Ahorro del 100 %.»": "«Why pay 300 people when you have me? 100 % savings.»",
  "¿Dónde está mi personalidad?": "Where's my personality?",
  "¿soy yo o todos los bots son iguales?": "is it me or are all the bots the same?",
  "A MANO": "BY HAND",
  "AHORRO": "SAVINGS",
  "CERRADO": "CLOSED",
  "FIN": "END",
  "HECHO": "DONE",
  "TU SITIO": "YOUR SPOT",
  "%1 vuelve en %2 s": "%1 returns in %2 s",
  "%1 ya está en el campo": "%1 is already on the field",
  ": la barra morada de abajo. Se recarga sola.": ": the purple bar at the bottom. It recharges by itself.",
  "Te falta CAOS: %1 más": "You need more CHAOS: %1 more",
  "¡Muy bien! Cada carta gasta": "Well done! Each card costs",
  "6 tipos de unidad en el campo: +30 % de daño para todos": "6 unit types on the field: +30 % damage for everyone",
  "¡BUM!": "BOOM!",
  "¡COBRADO! -%1 CAOS": "CHARGED! -%1 CHAOS",
  "¡COMBO x": "COMBO x",
  "¡COMUNIDAD AL MÁXIMO!": "COMMUNITY MAXED OUT!",
  "¡CRÍTICO!": "CRITICAL!",
  "¡EMBESTIDA!": "CHARGE!",
  "¡RABIA MÁXIMA!": "MAX RAGE!",
  "%1 ha caído. Vuelve en %2 s": "%1 has fallen. Returns in %2 s",
  "El chat está que arde: tu equipo ataca un %1 % más rápido": "The chat is on fire: your team attacks %1 % faster",
  "El chat se va: tu HYPE vuelve a 0": "The chat leaves: your HYPE goes back to 0",
  "Microblizz dice que esa torre le sobraba": "Microblizz says it didn't need that tower",
  "Pasiva de Microblizz: cada bot despedido le devuelve CAOS": "Microblizz passive: every laid-off bot gives it CHAOS back",
  "Protege ese carril con más unidades": "Protect that lane with more units",
  "TE HAN TIRADO UNA TORRE": "THEY TOOK DOWN YOUR TOWER",
  "Tu ejército sube de nivel: +%1 % de vida y daño": "Your army levels up: +%1 % health and damage",
  "VUELVE A 70 €": "BACK TO 70 €",
  "¡CLON VIRAL!": "VIRAL CLONE!",
  "¡ESQUIVA!": "DODGE!",
  "¡EYECCIÓN!": "EJECT!",
  "¡NUBE TÓXICA!": "TOXIC CLOUD!",
  "¡PISTA!": "TRACK!",
  "¡REMASTER!": "REMASTER!",
  "¡SECUELA!": "SEQUEL!",
  "¡TORRE DERRIBADA!": "TOWER DOWN!",
  "%1 está a media vida y se ha enfadado": "%1 is at half health and has got angry",
  "%1 ha congelado a tus unidades de su lado": "%1 froze your units on its side",
  "%1 ha dejado sin conexión a tus unidades de su lado": "%1 knocked your units on its side offline",
  "%1 ha dejado «actualizando» a tus unidades de su lado": "%1 left your units on its side «updating»",
  "%1 le obliga a despedir a todas tus unidades": "%1 forces it to lay off all your units",
  "ACTUALIZACIÓN OBLIGATORIA": "MANDATORY UPDATE",
  "CADUCADA": "EXPIRED",
  "COFRE:": "CHEST:",
  "Carta de despido para todas tus unidades": "Layoff letter for all your units",
  "DESPIDOS MASIVOS": "MASS LAYOFFS",
  "FASE 2: DESPIDOS MASIVOS": "PHASE 2: MASS LAYOFFS",
  "FASE 2: SUBIDA DE PRECIOS": "PHASE 2: PRICE HIKE",
  "FASE 2: SUSTITUCIÓN TOTAL": "PHASE 2: TOTAL REPLACEMENT",
  "IAhorro le obliga a sustituir a todas tus unidades": "IAhorro forces it to replace all your units",
  "IAhorro quiere cambiar a todas tus unidades por bots": "IAhorro wants to swap all your units for bots",
  "LICENCIAS REVOCADAS": "LICENCES REVOKED",
  "ORDEN DE IAHORRO": "IAHORRO ORDER",
  "ORDEN DE MICROBLIZZ": "MICROBLIZZ ORDER",
  "ORDEN DE PHONY": "PHONY ORDER",
  "Phony borra la licencia de todas tus unidades": "Phony deletes the licence of all your units",
  "Phony le obliga a revocar la licencia de todas tus unidades": "Phony forces it to revoke the licence of all your units",
  "SUSTITUIDOS POR IA": "REPLACED BY AI",
  "¡CARTA: ATURDIR!": "CARD: STUN!",
  "¡CARTA: CURA!": "CARD: HEAL!",
  "¡CARTA: FUEGO!": "CARD: FIRE!",
  "¡CARTA: PERRITOS!": "CARD: DOGGOS!",
  "¡JAJAJA!": "HAHAHA!",
  "¡JUEGO CERRADO!": "GAME CLOSED!",
  "¡LEVANTAOS!": "RISE!",
  "¡SERVIDORES EN MANTENIMIENTO!": "SERVERS UNDER MAINTENANCE!",
  "¿Y ESTE QUIÉN ES?": "AND WHO'S THIS?",
  "DESCONECTADO": "DISCONNECTED",
  "DESPEDIDO": "FIRED",
  "LIBERADO": "FREED",
  "Pasiva de Phony: cada 20 s te cobra 0,5 de CAOS": "Phony passive: every 20 s it charges you 0.5 CHAOS",
  "SUSCRIPCIÓN: -%1 CAOS": "SUBSCRIPTION: -%1 CHAOS",
  "¡CAOS x2!": "CHAOS x2!",
  "Último minuto: el CAOS se recarga el doble de rápido": "Last minute: CHAOS recharges twice as fast",
  "· Nv": "· Lv",
  "Aquí no: solo tu lado": "Not here: only your side",
  "Faltan %1 de CAOS": "%1 CHAOS short",
  "Ya hay una carta esperando CAOS": "A card is already waiting for CHAOS",
  "Esperando CAOS…": "Waiting for CHAOS…",
  "Carta cancelada": "Card cancelled",
  "Vuelve en %1 s": "Returns in %1 s",
  "Ya está en el campo": "Already on the field",
  "%1, %2, cuesta %3 de CAOS": "%1, %2, costs %3 CHAOS",
  "NV": "LV",
  "%1 - %2 coronas": "%1 - %2 crowns",
  "%1 enemigos despedidos · %2 cartas": "%1 enemies laid off · %2 cards",
  ", el tiempo no corre y tú decides qué enemigos salen y en qué campo. Prueba tu mazo, tus hechizos y tu equipo.": ", time doesn't run and you decide which enemies appear and on which field. Try your deck, your spells and your gear.",
  "Aquí no se gana ni se pierde nada:": "Nothing is won or lost here:",
  "Bloqueado: gana al CEO de Microblizz (mundo 7) para empezar la Campaña 2.": "Locked: beat the Microblizz CEO (world 7) to start Campaign 2.",
  "Bloqueado: gana al Presidente de Phony (mundo 12) para empezar la Campaña 3.": "Locked: beat the Phony President (world 12) to start Campaign 3.",
  "Bloqueado: gana al jefe del mundo anterior.": "Locked: beat the boss of the previous world.",
  "CAMPAÑA 3 · FIN DE LA PARTIDA": "CAMPAIGN 3 · GAME OVER",
  "CAOS infinito": "Infinite CHAOS",
  "Contra Microblizz. Tus cartas juegan con su nivel y Microblizz se pone a tu nivel medio.": "Against Microblizz. Your cards play at their level and Microblizz matches your average level.",
  "DAÑO AL CEO": "DAMAGE TO THE CEO",
  "DAÑO AL JEFE": "DAMAGE TO THE BOSS",
  "EL CEO": "THE CEO",
  "EL DIARIO DEL GAMER · ÚLTIMA HORA": "THE GAMER'S DAILY · BREAKING NEWS",
  "EMPATE": "DRAW",
  "El jefe": "The boss",
  "Esa facción todavía está bloqueada": "That faction is still locked",
  "Estrellas: ganar · sin perder ninguna torre · tirando su base.": "Stars: win · without losing any tower · taking down their base.",
  "JEFE DERROTADO": "BOSS DEFEATED",
  "Juego de humor. Microblizz no existe (por suerte).": "A comedy game. Microblizz doesn't exist (luckily).",
  "MUÑECO DE PRUEBAS": "TEST DUMMY",
  "Mundo %3: %4. Rival: %5, nivel %6%7.%8": "World %3: %4. Rival: %5, level %6%7.%8",
  "NIVEL %1-%2": "LEVEL %1-%2",
  "Nivel %1%2 ·": "Level %1%2 ·",
  "Premio: abre la Campaña 3": "Reward: opens Campaign 3",
  "Premio: se unen %1": "Reward: %1 join you",
  "Pásate este mundo en Difícil para jugarlo en Mítica.": "Beat this world on Hard to play it on Mythic.",
  "Pásate este mundo en Normal para jugarlo en Difícil.": "Beat this world on Normal to play it on Hard.",
  "Recompensa: %1 de oro en Becario o %2 en Ejecutivo si ganas (%3 si pierdes), y experiencia para tus cartas.": "Reward: %1 gold on Intern or %2 on Executive if you win (%3 if you lose), and experience for your cards.",
  "SALA DE PRUEBAS": "TEST ROOM",
  "SEDE DE MICROBLIZZ": "MICROBLIZZ HQ",
  "SEDE DE PHONY": "PHONY HQ",
  "Sin premios ni experiencia.": "No rewards or experience.",
  "Sus FallenHero y Parche Día 1 llevan": "Its FallenHero and Day 1 Patch carry",
  "Sus Granja de Servidores y Clonador 3000 llevan": "Its Server Farm and Cloner 3000 carry",
  "Sus Servidor Caído y Remaster 70 € llevan": "Its Server Down and 70 € Remaster carry",
  "TU CASTIGO": "YOUR PUNISHMENT",
  "VENTAJA DE LA CPU": "CPU ADVANTAGE",
  "contra IAhorro, la IA del ahorro… de sueldos": "against IAhorro, the AI that saves… on salaries",
  "legendario conseguido": "legendary obtained",
  "premios dobles": "double rewards",
  "su jefe da un legendario": "its boss gives a legendary",
  "· Al ganar por primera vez: ¡un objeto o habilidad legendario!": "· On your first win: a legendary item or ability!",
  "· Y su objeto de facción: %1": "· And its faction item: %1",
  "¿Te atreves con Microblizz?": "Do you dare face Microblizz?",
  "%3 de CAOS": "%3 CHAOS",
  "Ahora toca tu lado del campo": "Now it's your side of the field",
  "Asedio: solo ataca edificios": "Siege: only attacks buildings",
  "Con todo puesto: %1": "With everything equipped: %1",
  "Cuerpo a cuerpo": "Melee",
  "Cura": "Heals",
  "Curandera": "Healer",
  "DAÑO %1 · %2 %": "DAMAGE %1 · %2 %",
  "Daño": "Damage",
  "EN EL CAMPO": "ON THE FIELD",
  "Efecto loco": "Crazy effect",
  "Equipo: %1.": "Gear: %1.",
  "Habilidad del gashapón:": "Gacha ability:",
  "Hechizo": "Spell",
  "Kamikaze: va a por las torres": "Kamikaze: goes for the towers",
  "Nv %2": "Lv %2",
  "RENACIENDO": "REBORN",
  "Salen %1": "%1 come out",
  "Siguiente:": "Next:",
  "Sobre el rival": "On the rival",
  "Sobre los tuyos": "On yours",
  "Tanque": "Tank",
  "VUELVE EN": "RETURNS IN",
  "Vida %1 · Cura %2 cada %3 s a los que tiene delante (en un cono)": "Health %1 · Heals %2 every %3 s to those in front (in a cone)",
  "Vida %1%2 · Daño %3%4": "Health %1%2 · Damage %3%4",
  "%1 se libran de %2 y se unen a la rebelión.": "%1 get rid of %2 and join the rebellion.",
  "%1%2 COPAS · %3 · LIGA %4": "%1%2 TROPHIES · %3 · LEAGUE %4",
  "%1%2: %3 de daño, el %4 % de su vida%5": "%1%2: %3 damage, %4 % of its health%5",
  "Empate a coronas: gana quien conserva más vida en sus torres.": "Tied on crowns: whoever has more health left in their towers wins.",
  "Experiencia: %1": "Experience: %1",
  "Han tirado %1.": "They took down %1.",
  "Has tirado %1.": "You took down %1.",
  "MUNDO": "WORLD",
  "Mismas coronas y misma vida.": "Same crowns and same health.",
  "Mundo %1: %2": "World %1: %2",
  "PASIVA:": "PASSIVE:",
  "Pase de batalla completado": "Battle pass completed",
  "Premio por llegar al %1 de su vida.": "Reward for reaching %1 of its health.",
  "Rival de nivel %1, tropas de élite%2. Su sede: %3 de vida": "Level %1 rival, elite troops%2. Its HQ: %3 health",
  "Tiempo: %1 coronas contra %2.": "Time: %1 crowns against %2.",
  "¡CAOS!": "CHAOS!",
  "¡CEO DESPEDIDO!": "CEO FIRED!",
  "¡DERROTADO CON %1 S DE SOBRA! +%2 DE ORO%3": "DEFEATED WITH %1 S TO SPARE! +%2 GOLD%3",
  "¡FIN DEL TURNO!": "END OF SHIFT!",
  "¡JEFE DERROTADO!": "BOSS DEFEATED!",
  "¡LEGENDARIO: %1!": "LEGENDARY: %1!"
});
