// Fans of Rumble · Inglés (6/8): dificultad Mítica y su ruleta, tutorial, código de progreso, mazo y cartas del gashapón.
'use strict';
IDIOMA.add({
  "¡Listas para subir de nivel en la Colección: %1!": "Ready to level up in the Collection: %1!",
  "¡NUEVA FACCIÓN: %1!": "NEW FACTION: %1!",
  "¡OBJETO DE FACCIÓN: %1!": "FACTION ITEM: %1!",
  "«Hemos comprado vuestro juego… y lo vamos a cerrar.»": "«We've bought your game… and we're going to shut it down.»",
  "«Microblizz me encerró aquí abajo. Ahora no sale nadie.»": "«Microblizz locked me down here. Now nobody leaves.»",
  "«Microblizz me ha ascendido. Ahora despido yo.»": "«Microblizz promoted me. Now I do the firing.»",
  "«Os he comprado. Ahora os cierro.»": "«I've bought you. Now I'm shutting you down.»",
  "«Phony me paga por ganar. Tú pagas por jugar.»": "«Phony pays me to win. You pay to play.»",
  "«Phony quiere otra secuela. Y la vas a protagonizar tú.»": "«Phony wants another sequel. And you're going to star in it.»",
  "«Todo lo que compraste es mío. Lo borro cuando quiera.»": "«Everything you bought is mine. I'll delete it whenever I want.»",
  "«¿Discos? Eso es del siglo pasado. Ahora pagas cada mes.»": "«Discs? That's so last century. Now you pay every month.»",
  "% menos de daño": "% less damage",
  "% más rápido": "% faster",
  "% por segundo": "% per second",
  "%1 va equipado hasta los dientes": "%1 is armed to the teeth",
  "%1: rival de nivel %2, más CAOS y tropas de élite%3.": "%1: level %2 rival, more CHAOS and elite troops%3.",
  "+%1 CAOS": "+%1 CHAOS",
  "Becarios": "Interns",
  "Becarios en prácticas": "Trainee Interns",
  "Blindaje": "Armour",
  "Bonus de productividad": "Productivity Bonus",
  "Café nº 14": "Coffee No. 14",
  "Carga": "Loading",
  "Cartón": "Cardboard",
  "DIFÍCIL": "HARD",
  "DLC: +%1 CAOS": "DLC: +%1 CHAOS",
  "Despidos": "Layoffs",
  "Difícil: rivales de nivel 6 a 10 y líderes equipados. Te hará falta subir tus cartas y equiparlas bien. Premios dobles.": "Hard: level 6 to 10 rivals and equipped leaders. You'll need to level up your cards and equip them well. Double rewards.",
  "EQUIPADO": "EQUIPPED",
  "ESTA SEMANA EN MÍTICA": "THIS WEEK IN MYTHIC",
  "Inversión": "Investment",
  "Inversión millonaria": "Million-Dollar Investment",
  "LA VENTAJA DE LA CPU": "THE CPU'S ADVANTAGE",
  "La ruleta de Microblizz decide cómo te complica la Mítica esta semana. Cambia cada lunes.": "Microblizz's wheel decides how Mythic gets harder for you this week. It changes every Monday.",
  "Libera cada mundo corrompido y su facción se unirá a ti. Campaña 1: Microblizz. Al ganar al CEO se abren el sótano y la Campaña 2, contra Phony; y al ganar a Phony, la Campaña 3, contra IAhorro.": "Free every corrupted world and its faction will join you. Campaign 1: Microblizz. Beating the CEO opens the basement and Campaign 2, against Phony; beating Phony opens Campaign 3, against IAhorro.",
  "Líder de vacaciones": "Leader on Holiday",
  "MÍTICA": "MYTHIC",
  "Mítica, el verdadero desafío: rivales de nivel 9 a 12, equipo perfecto y la ruleta de la semana. Premios triples y un legendario por cada jefe.": "Mythic, the real challenge: level 9 to 12 rivals, perfect gear and the wheel of the week. Triple rewards and a legendary for every boss.",
  "Pantalla de carga": "Loading Screen",
  "Parche": "Patch",
  "Parche sorpresa": "Surprise Patch",
  "Recorte": "Cut",
  "Recorte de presupuesto": "Budget Cut",
  "Robots nuevos": "New Robots",
  "Sin CAOS": "No CHAOS",
  "Sin líder": "No Leader",
  "Sin presupuesto": "No Budget",
  "Sus robots grandes van equipados": "Its big robots come equipped",
  "TU CASTIGO DE LA SEMANA": "YOUR PUNISHMENT OF THE WEEK",
  "Torres blindadas": "Armoured Towers",
  "Torres de cartón": "Cardboard Towers",
  "Torretas": "Turrets",
  "Torretas turbo": "Turbo Turrets",
  "Tu castigo: %1 · CPU: %2": "Your punishment: %1 · CPU: %2",
  "TÚ": "YOU",
  "VER LA RULETA": "SEE THE WHEEL",
  "Ventaja de la CPU, %1: %2": "CPU advantage, %1: %2",
  "Vida %1 · Cura %2": "Health %1 · Heals %2",
  "Vida %1%2 · Daño %3": "Health %1%2 · Damage %3",
  "Y ahora, el regalo de Microblizz para la CPU.": "And now, Microblizz's gift to the CPU.",
  "ataca un": "attacks",
  "cada unidad tuya que cae le da 1 de CAOS.": "every unit of yours that falls gives it 1 CHAOS.",
  "cambia en %1": "changes in %1",
  "empiezas cada partida sin CAOS.": "you start every match with no CHAOS.",
  "la CPU gana CAOS un 30 % más rápido.": "the CPU gains CHAOS 30 % faster.",
  "recibe un": "takes",
  "rival de nivel %2": "level %2 rival",
  "se cura un": "heals",
  "sus torres disparan un 40 % más rápido.": "its towers shoot 40 % faster.",
  "sus torres y su sede tienen un 40 % más de vida.": "its towers and HQ have 40 % more health.",
  "sus unidades atacan un 30 % más rápido.": "its units attack 30 % faster.",
  "sus unidades hacen un 25 % más de daño.": "its units deal 25 % more damage.",
  "sus unidades tienen un 25 % más de vida.": "its units have 25 % more health.",
  "sus unidades van un 25 % más rápido.": "its units move 25 % faster.",
  "tu CAOS se recarga un 30 % más lento.": "your CHAOS recharges 30 % slower.",
  "tu líder tarda el doble en volver.": "your leader takes twice as long to return.",
  "tus cartas tardan 1,5 segundos más en entrar.": "your cards take 1.5 seconds longer to come in.",
  "tus torres y tu base tienen un 35 % menos de vida.": "your towers and base have 35 % less health.",
  "tus unidades hacen un 20 % menos de daño.": "your units deal 20 % less damage.",
  "tus unidades tienen un 20 % menos de vida.": "your units have 20 % less health.",
  "tus unidades van un 20 % más lentas.": "your units move 20 % slower.",
  "¡A JUGAR!": "LET'S PLAY!",
  "¡BEBIDA XXL!": "XXL DRINK!",
  "¡FOTO!": "PHOTO!",
  "¡FURIA DE TITÁN!": "TITAN FURY!",
  "¡MICROPAGO! +%1 CAOS": "MICROPAYMENT! +%1 CHAOS",
  "¡MODO GIGANTE!": "GIANT MODE!",
  "¿Y las vacaciones?": "What about the holidays?",
  "! Microblizz, una empresa millonaria, compró el estudio donde yo trabajaba, nos despidió a todos y ahora quiere cerrar tus juegos favoritos. ¡Vamos a impedirlo! Toca": "! Microblizz, a billion-dollar company, bought the studio where I worked, fired us all and now wants to shut down your favourite games. Let's stop it! Tap",
  ", que hace que una carta corra más. Toca": ", which makes a card run faster. Tap",
  ". Toca la de tu líder.": ". Tap your leader's one.",
  ". ¡Tú puedes!": ". You can do it!",
  ": ahí están tus cartas y lo que llevan puesto.": ": there are your cards and what they wear.",
  ": ahí salen habilidades y equipo para tus cartas.": ": that's where abilities and gear for your cards come from.",
  ": es gratis. Lo que te toque, póntelo en Colección como antes.": ": it's free. Whatever you get, equip it in the Collection like before.",
  "Aquí eliges con qué facción juegas. Por ahora tienes a los": "Here you choose which faction to play. For now you have the",
  "Cada carta tiene una": "Every card has an",
  "Elige": "Choose",
  "Elige una habilidad.": "Choose an ability.",
  "Empieza por el primer nivel:": "Start with the first level:",
  "Gira": "Spin",
  "Pack de bienvenida": "Welcome Pack",
  "Te regalo una habilidad:": "I'm giving you an ability:",
  "Toca": "Tap",
  "Truco:": "Tip:",
  "Tu objetivo: tira sus": "Your goal: take down their",
  "Tutorial saltado. Puedes repetirlo en Opciones": "Tutorial skipped. You can repeat it in Options",
  "Velocidad normal": "Normal speed",
  "Velocidad x2. Pulsa para volver a la normal": "Speed x2. Press to go back to normal",
  "Velocidad x2: todo va el doble de rápido": "Speed x2: everything goes twice as fast",
  "Versión de prueba: no se cobra nada y te lo llevas gratis. Solo se puede comprar una vez.": "Trial version: nothing is charged and you get it for free. It can only be bought once.",
  "Vuelve al menú con la flecha.": "Go back to the menu with the arrow.",
  "Vuelve al menú principal con la flecha.": "Go back to the main menu with the arrow.",
  "Y un objeto épico de equipo con calidad Director (excelente) o mejor. Vale casi el doble que comprarlo por separado. Microblizz lo llama «regalo».": "And an epic gear item of Director (excellent) quality or better. It's worth almost double buying it separately. Microblizz calls it a «gift».",
  "del gashapón.": "from the gacha.",
  "mantén pulsada": "press and hold",
  "ranura de HABILIDAD": "ABILITY slot",
  "sede de Microblizz": "Microblizz HQ",
  "y la": "and the",
  "y un objeto épico de calidad Director (excelente) o mejor, por": "and an epic item of Director (excellent) quality or better, for",
  "y vamos a ponerle una habilidad a una carta.": "and let's give a card an ability.",
  "y vamos a ponérsela.": "and let's equip it.",
  "y vuelve a intentarlo.": "and try again.",
  "¡Casi! Esta vez ha ganado Microblizz. Toca": "So close! Microblizz won this time. Tap",
  "¡Encantada,": "Nice to meet you,",
  "¡Hecho!": "Done!",
  "¡Hecho! Tu carta ya lleva su habilidad. Y te regalo": "Done! Your card now has its ability. And I'm giving you",
  "¡Pack de bienvenida!": "Welcome Pack!",
  "¡Pack de bienvenida! Microblizz te da las gracias": "Welcome Pack! Microblizz thanks you",
  "¡Victoria, %1!": "Victory, %1!",
  "BLOQUEADA": "LOCKED",
  "Bloqueada: libera su mundo en la campaña": "Locked: free its world in the campaign",
  "Copia el código del recuadro": "Copy the code from the box",
  "Código copiado": "Code copied",
  "EDITAR": "EDIT",
  "Ese código no es válido": "That code isn't valid",
  "Pasiva de facción: %1. Pulsa para ver qué hace": "Faction passive: %1. Press to see what it does",
  "Progreso borrado": "Progress deleted",
  "Progreso cargado": "Progress loaded",
  "Tutorial reiniciado: sigue a Lola": "Tutorial restarted: follow Lola",
  "¿SEGURO?": "SURE?",
  "+%1 DE CAOS": "+%1 CHAOS",
  "Aquí no hay nada que reseñar": "Nothing to review here",
  "VERSIÓN REMAKE · 70 €": "REMAKE VERSION · 70 €",
  "¡A POR EL SANADOR!": "GO FOR THE HEALER!",
  "¡A POR ÉL!": "GET HIM!",
  "¡FLASH!": "FLASH!",
  "¡UNO GORDO!": "A BIG ONE!",
  "%2: toca una de tus tropas para ponerla.": "%2: tap one of your troops to equip it.",
  "%6 de CAOS · %7": "%6 CHAOS · %7",
  "%9 de CAOS · %10": "%9 CHAOS · %10",
  "CARTAS DEL GASHAPÓN · %1/%2": "GACHA CARDS · %1/%2",
  "Como mucho %1 hechizos: cambia uno de tus hechizos": "At most %1 spells: swap one of your spells",
  "Coste medio": "Average cost",
  "DE CARTAS": "OF CARDS",
  "EN EL MAZO": "IN THE DECK",
  "Faltaban cartas: se completa con las básicas": "Cards were missing: filled in with the basic ones",
  "Hechizos %1/%2": "Spells %1/%2",
  "LÍDER": "LEADER",
  "Líder + 6 cartas · %1 %2 · coste medio %3": "Leader + 6 cards · %1 %2 · average cost %3",
  "MAZO": "DECK",
  "Nivel medio": "Average level",
  "Ponlas en tu mazo desde la Colección.": "Put them in your deck from the Collection.",
  "Probabilidades: rara %1 %, épica %2 %, legendaria %3 %. Garantías: épica o mejor como mucho cada %4 tiradas (llevas %5) y legendaria a las %6 (llevas %7). Con 5 estrellas, una repetida da %8 gemas.": "Odds: rare %1 %, epic %2 %, legendary %3 %. Guarantees: epic or better at least every %4 pulls (you're at %5) and legendary at %6 (you're at %7). With 5 stars, a duplicate gives %8 gems.",
  "Salen en la máquina de cartas. Las repetidas le dan estrellas: +5 % cada una, hasta 5.": "They come from the card machine. Duplicates give it stars: +5 % each, up to 5.",
  "Te faltan": "You need",
  "Tienes %1 de %2": "You have %1 of %2",
  "Toca la carta de tu mazo que quieres cambiar por": "Tap the card in your deck that you want to swap for",
  "Toca una de tus tropas de abajo para ponerla aquí": "Tap one of your troops below to put it here",
  "Toca una de tus tropas y luego la carta del mazo que quieres cambiar.": "Tap one of your troops and then the deck card you want to swap.",
  "VACÍO": "EMPTY",
  "Ver en la Colección": "View in the Collection",
  "Ya tenía 5 ★: +%1 gemas": "Already had 5 ★: +%1 gems",
  "¡SUBE A %1 ★!": "LEVELS UP TO %1 ★!",
  "área de %1": "area of %1",
  "CARTAS": "CARDS",
  "Gana a %1 en la campaña (mundo %2) para retarle aquí": "Beat %1 in the campaign (world %2) to challenge it here",
  "Gemas la primera vez que le quitas el %10 · %11. Y oro según el daño (más si lo derrotas).": "Gems the first time you take off %10 · %11. And gold depending on the damage (more if you defeat it).",
  "Sede de %5 de vida y 4 minutos para hacerle todo el daño posible. Rival de nivel %6%7. Récord:": "HQ with %5 health and 4 minutes to deal as much damage as possible. Level %6%7 rival. Record:",
  "derrotarlo → %1": "defeat it → %1",
  "¡Objetos de facción nuevos en tu inventario: %1!": "New faction items in your inventory: %1!",
  "%1 horas de golpe: +%2 de oro%3%4": "%1 hours at once: +%2 gold%3%4",
  "ANUNCIO": "AD",
  "Ahora sin lector, sin botones y sin consola. Solo la factura.": "Now without a drive, without buttons and without a console. Just the bill.",
  "Anuncio cerrado: sin premio": "Ad closed: no reward",
  "Anuncio de prueba. En la app de Google Play aquí saldrá un anuncio de verdad.": "Test ad. In the Google Play app a real ad will show here.",
  "CAMBIAR": "CHANGE",
  "Café del Becario": "Intern's Coffee",
  "Caja de botín misteriosa": "Mystery Loot Box"
});
