// Fans of Rumble · Inglés (7/8): anuncios, campos de jefe, sala de pruebas, arena, IAhorro y las novedades.
'use strict';
IDIOMA.add({
  "IDIOMAS": "LANGUAGES",
  ": el juego está ahora en español y en inglés. Se elige solo según el idioma de tu navegador y puedes cambiarlo en Opciones (Idioma / Language).": ": the game is now in Spanish and English. It's picked automatically from your browser's language and you can change it in Options (Language).",
  "El inglés cubre los menús, las cartas, el chat de las partidas, las misiones y los logros. Si ves algo que sigue en español, ya lo sabemos.": "English covers the menus, the cards, the match chat, the missions and the achievements. If you see something still in Spanish, we know.",
  "Microblizz ha descubierto que existen más idiomas y quiere cobrarte la traducción.": "Microblizz has discovered there are more languages and wants to charge you for the translation.",
  "Phony lo llama «localización premium». Tú, «por fin».": "Phony calls it «premium localisation». You call it «finally».",
  "Cambiar una misión diaria": "Change a daily mission",
  "Cerrar sin premio": "Close without reward",
  "Curso: despedir con una sonrisa": "Course: Firing With a Smile",
  "El café que se toma solo… porque ya no queda nadie en la oficina.": "The coffee that drinks itself… because there's nobody left in the office.",
  "El mismo juego de siempre, con un filtro nuevo y el precio de estreno.": "The same old game, with a new filter and the launch price.",
  "El premio llega en %1…": "The reward arrives in %1…",
  "Ergonómica, con ruedas y con un contrato de permanencia de 24 meses.": "Ergonomic, with wheels and a 24-month minimum contract.",
  "GANANCIAS DE %1 h": "%1 h OF EARNINGS",
  "Ganancias de 4 h en HORAS EXTRA": "4 h of earnings in OVERTIME",
  "Guarda tus juegos en la nube. Te los borramos cuando nos apetezca.": "Store your games in the cloud. We delete them whenever we feel like it.",
  "Impartido por el CEO de Microblizz. Plazas limitadas (las demás las hemos recortado).": "Taught by the Microblizz CEO. Limited places (we've cut the rest).",
  "Los premios de los anuncios (tirada gratis, premio x2, turbo…) te llegan al momento, sin ver nada. Hasta %2 al día.": "Ad rewards (free pull, x2 reward, turbo…) arrive instantly, without watching anything. Up to %2 a day.",
  "Microblizz Premium Plus Gold": "Microblizz Premium Plus Gold",
  "Misión cambiada": "Mission changed",
  "PARA SIEMPRE": "FOREVER",
  "Paga más y te dejamos jugar a lo que ya compraste.": "Pay more and we'll let you play what you already bought.",
  "Phony Cloud Infinito": "Phony Infinite Cloud",
  "Por hoy ya no quedan más aquí. ¡Mañana más!": "No more here for today. More tomorrow!",
  "Premio doblado": "Reward doubled",
  "Premio x2 al acabar una partida": "x2 reward at the end of a match",
  "RECOGER PREMIO": "COLLECT REWARD",
  "RECOGER x2": "COLLECT x2",
  "Recoger x2 en HORAS EXTRA": "Collect x2 in OVERTIME",
  "Regalo diario x2": "Daily gift x2",
  "Seguro anti-cierre de juegos": "Game Closure Insurance",
  "Silla Gamer Ejecutiva": "Executive Gaming Chair",
  "Sin anuncios": "No ads",
  "Sin anuncios: los premios te llegan al momento": "No ads: rewards arrive instantly",
  "TIRADA GRATIS EN ESTA MÁQUINA": "FREE PULL ON THIS MACHINE",
  "TURBO %1 h": "TURBO %1 h",
  "TURBO x2 · %1:%2": "TURBO x2 · %1:%2",
  "Te prestamos para el pase de batalla. Intereses del 300 %. ¡Sin preguntas!": "We lend you money for the battle pass. 300 % interest. No questions asked!",
  "Te protege de todo. No cubre cierres de juegos.": "Protects you from everything. Doesn't cover game closures.",
  "Tirada gratis: cartas": "Free pull: cards",
  "Tirada gratis: equipo": "Free pull: gear",
  "Tirada gratis: habilidades": "Free pull: abilities",
  "Turbo de HORAS EXTRA": "OVERTIME Turbo",
  "Un mensaje de nuestros patrocinadores… que somos nosotros.": "A message from our sponsors… which is us.",
  "Ya has visto los %1 anuncios de hoy. ¡Mañana más!": "You've seen today's %1 ads. More tomorrow!",
  "Ya lo tienes: los premios de los anuncios llegan al momento. Hoy: %2 de %3.": "You've got it: ad rewards arrive instantly. Today: %2 of %3.",
  "¡PREMIO DOBLADO! %1 %2": "REWARD DOUBLED! %1 %2",
  "¡Turbo! %1 horas ganando el doble": "Turbo! %1 hours earning double",
  "¿Qué habrá dentro? Spoiler: nada. Pero el cofre brilla mucho.": "What's inside? Spoiler: nothing. But the chest sure shines.",
  "VISTA NORMAL": "NORMAL VIEW",
  "DIAPOSITIVA %1 DE 300": "SLIDE %1 OF 300",
  "EL PLATÓ ARCOÍRIS": "THE RAINBOW SET",
  "EL SÓTANO": "THE BASEMENT",
  "FACTURA: 9,99 €": "INVOICE: 9.99 €",
  "FÁBRICA DE DULCES": "CANDY FACTORY",
  "Grietas que queman a los dos bandos, en sitios distintos cada vez. ¡Y caen meteoritos!": "Cracks that burn both sides, in different places every time. And meteorites fall!",
  "LA CRIPTA DEL TÚNEL": "THE TUNNEL CRYPT",
  "LA SALA DE JUNTAS": "THE BOARDROOM",
  "LA SEDE DE PAGO": "THE PAY-TO-ENTER HQ",
  "LA TIENDA SIN DISCOS": "THE STORE WITHOUT DISCS",
  "Los puentes tienen PEAJE: cada vez que una unidad cruza, su equipo paga 0,3 de CAOS. Suelo de mármol que resbala y facturas que vuelan.": "The bridges have a TOLL: every time a unit crosses, its team pays 0.3 CHAOS. Slippery marble floor and flying invoices.",
  "OFICINA INUNDADA": "FLOODED OFFICE",
  "OLIMPO NEVADO": "SNOWY OLYMPUS",
  "PEAJE -%1 CAOS": "TOLL -%1 CHAOS",
  "PLATÓ EN DIRECTO": "LIVE SET",
  "RÍO DE LAVA": "LAVA RIVER",
  "Río de arcoíris, pintura fresca que frena, maquillaje que cura… y focos que caen.": "Rainbow river, wet paint that slows you down, makeup that heals… and falling spotlights.",
  "Río de bebida energética, tres puentes, alfombras RGB que te aceleran, cables… ¡y picos de lag!": "Energy drink river, three bridges, RGB carpets that speed you up, cables… and lag spikes!",
  "Río de café, charcos que resbalan y cartas de despido que caen del techo.": "Coffee river, slippery puddles and layoff letters falling from the ceiling.",
  "Río de chat, tres puentes, cables por el suelo y focos que se descuelgan.": "Chat river, three bridges, cables on the floor and spotlights that come loose.",
  "Río de chocolate, puentes de galleta y chicle por todas partes: ¡te quedas pegado!": "Chocolate river, biscuit bridges and chewing gum everywhere: you get stuck!",
  "Río de monedas, piezas de construcción en el suelo (1 de daño al pisarlas) y… ¡diapositivas del CEO!": "River of coins, building bricks on the floor (1 damage when stepped on) and… the CEO's slides!",
  "Un río de discos de verdad (formato físico), cristales rotos en el suelo y una lluvia de CDs.": "A river of real discs (physical format), broken glass on the floor and a rain of CDs.",
  "Un solo puente en el centro, ratoneras escondidas y cajas que se caen de las estanterías.": "A single bridge in the centre, hidden mousetraps and boxes falling off the shelves.",
  "Un túnel cruza por debajo del río: lo que pasa dentro, no se ve. Y las tumbas te agarran.": "A tunnel runs under the river: what happens inside can't be seen. And the graves grab you.",
  "¡AGARRADO!": "GRABBED!",
  "¡CLAC!": "CLACK!",
  "¡El río está helado! Se cruza por donde quieras, pero resbala. Y ojo con las bolas de nieve.": "The river is frozen! You can cross anywhere, but it's slippery. And watch out for snowballs.",
  "¡PEGADO!": "STUCK!",
  "¡QUEMA!": "BURNS!",
  "¡RETOQUE!": "TOUCH-UP!",
  "¡TROPIEZO!": "TRIP!",
  "DENTRO": "INSIDE",
  "DESPIDO": "LAYOFF",
  "TÚNEL": "TUNNEL",
  "+ GRUPO": "+ GROUP",
  "+ LÍDER": "+ LEADER",
  "+ SANADOR": "+ HEALER",
  "+ TANQUE": "+ TANK",
  "+ TIRADOR": "+ SHOOTER",
  "CAMPO:": "FIELD:",
  "CONTADOR A 0": "COUNTER TO 0",
  "Daño al rival:": "Damage to the rival:",
  "Este rival no tiene de esos": "This rival doesn't have any of those",
  "Este rival no tiene sanadores": "This rival has no healers",
  "IA RIVAL: NO": "RIVAL AI: OFF",
  "IA RIVAL: SÍ": "RIVAL AI: ON",
  "LIMPIAR": "CLEAR",
  "NORMAL": "NORMAL",
  "RIVAL:": "RIVAL:",
  "%5 · nivel %6 · %7 copas": "%5 · level %6 · %7 trophies",
  "Elige rival. Son mazos de otros «jugadores» (de momento, inventados: los maneja la CPU).": "Pick a rival. These are decks of other «players» (for now, made up: the CPU plays them).",
  "Ganar: +%8 copas, %9 de oro y %10 gemas · Perder: -%11 copas": "Win: +%8 trophies, %9 gold and %10 gems · Lose: -%11 trophies",
  "LIGA %2": "LEAGUE %2",
  "Otros rivales": "Other rivals",
  "copas · récord %4 · %5 ganadas, %6 perdidas": "trophies · record %4 · %5 won, %6 lost",
  "ARTE CON SEIS DEDOS": "ART WITH SIX FINGERS",
  "COPIA DE %1": "COPY OF %1",
  "DATOS SIN PERMISO": "DATA WITHOUT PERMISSION",
  "EL ALMACÉN DE DATOS": "THE DATA WAREHOUSE",
  "EL ESTUDIO VACÍO": "THE EMPTY STUDIO",
  "EL NÚCLEO DE IAHORRO": "THE IAHORRO CORE",
  "Empate. IAhorro dice que ha ganado (se lo ha inventado).": "Draw. IAhorro says it won (it made that up).",
  "Error: victoria no encontrada en los datos de entrenamiento.": "Error: victory not found in the training data.",
  "IAhorro ha generado tu derrota en 0,3 segundos.": "IAhorro generated your defeat in 0.3 seconds.",
  "IAhorro ha generado una disculpa. Se nota que no la ha escrito nadie.": "IAhorro generated an apology. You can tell nobody wrote it.",
  "IAhorro promete «mejorar el modelo». Nadie se lo cree.": "IAhorro promises to «improve the model». Nobody believes it.",
  "IAhorro se ha desconectado. Los creadores vuelven al estudio.": "IAhorro has disconnected. The creators go back to the studio.",
  "IAhorro te da las gracias por los datos de entrenamiento.": "IAhorro thanks you for the training data.",
  "Jefe: CyberMarine entrenado": "Boss: Trained CyberMarine",
  "Jefe: Generador de Clones": "Boss: Clone Generator",
  "Jefe: StreamKing generado": "Boss: Generated StreamKing",
  "LA GRANJA DE PROMPTS": "THE PROMPT FARM",
  "La sala fría: el río de datos está congelado (se cruza por donde quieras) y el suelo pulido resbala. Caen discos duros.": "The cold room: the data river is frozen (cross anywhere) and the polished floor is slippery. Hard drives fall.",
  "Los servidores se sobrecalientan (las grietas queman), las alfombras de datos aceleran y, de vez en cuando, IAhorro se reinicia.": "The servers overheat (the cracks burn), the data carpets speed you up and, every now and then, IAhorro reboots.",
  "PROMPT: «HAZ UN JUEGO IGUAL»": "PROMPT: «MAKE AN IDENTICAL GAME»",
  "Pasiva de IAhorro: cada 25 s copia la última unidad que has sacado": "IAhorro passive: every 25 s it copies the last unit you played",
  "REINICIANDO…": "REBOOTING…",
  "Río de arte generado, pintura que frena, cristales rotos y focos que caen sobre sillas vacías.": "River of generated art, paint that slows you down, broken glass and spotlights falling on empty chairs.",
  "Un río de datos con tres puentes, cables por el suelo y prompts que caen del techo.": "A data river with three bridges, cables on the floor and prompts falling from the ceiling.",
  "(0.9.24) y opción de": "(0.9.24) and an option for",
  "(0.9.28): cada líder hace ahora su propio especial. NecroLord invoca esqueletos, CyberMarine llama a sus drones, el Vikingo levanta su muro de escudos… Antes todos saltaban como CrazyBunny.": "(0.9.28): every leader now does their own special. NecroLord summons skeletons, CyberMarine calls his drones, the Viking raises his shield wall… Before, they all jumped like CrazyBunny.",
  "(de prueba). En la app, el botón ATRÁS del móvil pausa la partida, cierra ventanas y vuelve al menú.": "(test version). In the app, the phone's BACK button pauses the match, closes windows and returns to the menu.",
  ": Lola te pregunta cómo te llamas. Tu nombre sale en la Arena, en el chat de las partidas y en los mensajes de Lola.": ": Lola asks what your name is. Your name appears in the Arena, in the match chat and in Lola's messages.",
  "El chat ya sabe cómo te llamas. El CEO de Microblizz, también.": "The chat knows your name now. So does the Microblizz CEO.",
  "Golpes con más jugo": "Hits with more juice",
  "IAhorro ha intentado llamarse como tú. Le salió «Usuario_7714».": "IAhorro tried to name itself after you. It came out as «User_7714».",
  "Microblizz quería cobrarte 9,99 € por cambiar de nombre. Lola dijo que no.": "Microblizz wanted to charge you 9.99 € to change your name. Lola said no.",
  "Temblor de pantalla SÍ/NO": "Screen shake YES/NO",
  "Toca tu avatar arriba a la izquierda del menú para ver tus números (Arena, copas, estrellas, logros…), cambiar el nombre o elegir avatar entre los líderes de tus facciones.": "Tap your avatar at the top left of the menu to see your numbers (Arena, trophies, stars, achievements…), change your name or pick an avatar among the leaders of your factions.",
  "en Opciones (0.9.25).": "in Options (0.9.25).",
  "¡YA HAY APP DE ANDROID!": "THERE'S AN ANDROID APP NOW!",
  "(Difícil)": "(Hard)",
  "(Mítica)": "(Mythic)",
  "Ahora el juego es tuyo. De verdad.": "Now the game is yours. For real.",
  "Antes era tu héroe favorito.": "Before, it was your favourite hero.",
  "Apaga a IAhorro (mundo 16).": "Switch off IAhorro (world 16).",
  "Bajo coste": "Low Cost",
  "Becario eterno": "Eternal Intern",
  "Cada carta, un becario menos.": "Every card, one intern less.",
  "CajaBotines": "LootBoxes",
  "Cajas abiertas": "Boxes Opened",
  "Cazajefes": "Boss Hunter",
  "Cazalíderes": "Leader Hunter",
  "Cinco estrellas, como las reseñas compradas.": "Five stars, like bought reviews.",
  "Cita con el CEO": "Date With the CEO",
  "Cliente fiel": "Loyal Customer",
  "Coleccionista de cartas": "Card Collector",
  "Coleccionista de estrellas%1": "Star Collector%1",
  "Comparte el resultado de una partida.": "Share the result of a match.",
  "Consigue %1 estrellas en el mundo %2%3.": "Get %1 stars in world %2%3.",
  "Consigue %1 estrellas en la campaña%2.": "Get %1 stars in the campaign%2.",
  "Consigue el pack de bienvenida de la tienda.": "Get the welcome pack from the shop.",
  "Consigue las 12 estrellas del mundo %1%2.": "Get all 12 stars in world %1%2.",
  "Consigue las 36 cartas del gashapón de cartas.": "Get all 36 cards from the card gacha.",
  "Consigue todas las estrellas de la campaña%1.": "Get all the stars in the campaign%1.",
  "Consigue una carta del gashapón de cartas.": "Get a card from the card gacha.",
  "Contra IAhorro": "Against IAhorro",
  "Contra Microblizz": "Against Microblizz",
  "Contra Phony": "Against Phony"
});
