// Fans of Rumble · Inglés (8/8): logros del Rumble (nombres y descripciones), pistas y misiones.
'use strict';
IDIOMA.add({
  "Dentro solo había otra caja.": "Inside there was only another box.",
  "Derriba %1 torres.": "Knock down %1 towers.",
  "Derrota a %1 bots de IAhorro.": "Defeat %1 IAhorro bots.",
  "Derrota a %1 enemigos de Microblizz.": "Defeat %1 Microblizz enemies.",
  "Derrota a %1 enemigos de Phony.": "Defeat %1 Phony enemies.",
  "Derrota a %1 jefes distintos en el Modo Jefe.": "Defeat %1 different bosses in Boss Mode.",
  "Derrota a 60 enemigos en una sola partida.": "Defeat 60 enemies in a single match.",
  "Derrota a los 12 jefes en el Modo Jefe.": "Defeat all 12 bosses in Boss Mode.",
  "Derrota a un jefe en Mítica (Modo Jefe).": "Defeat a boss on Mythic (Boss Mode).",
  "Derrota a un jefe en el Modo Jefe.": "Defeat a boss in Boss Mode.",
  "Derrota a un líder enemigo.": "Defeat an enemy leader.",
  "Descarga cancelada": "Download Cancelled",
  "Desconectada": "Disconnected",
  "El CEO ya había abierto el champán.": "The CEO had already opened the champagne.",
  "El de 2005 se veía mejor.": "The 2005 one looked better.",
  "El final del juego ya no se vende aparte.": "The game's ending is no longer sold separately.",
  "El resto del equipo estaba de vacaciones.": "The rest of the team was on holiday.",
  "Esto ya es otra cosa": "Now This Is Something Else",
  "Estrellas fugaces": "Shooting Stars",
  "Fama mundial": "World Fame",
  "Gana 10 partidas rápidas contra el Becario.": "Win 10 quick matches against the Intern.",
  "Gana a un jefe en Difícil.": "Beat a boss on Hard.",
  "Gana a un jefe en Mítica.": "Beat a boss on Mythic.",
  "Gana al CEO de Microblizz.": "Beat the Microblizz CEO.",
  "Gana al Presidente de Phony.": "Beat the Phony President.",
  "Gana por vida cuando se acaba el tiempo.": "Win on health when time runs out.",
  "Gana una partida después de perder dos torres.": "Win a match after losing two towers.",
  "Gana una partida gastando 30 de CAOS o menos.": "Win a match spending 30 CHAOS or less.",
  "Gana una partida jugando solo a tu líder.": "Win a match playing only your leader.",
  "Gana una partida sin perder ninguna torre.": "Win a match without losing any tower.",
  "Gasta 100 de CAOS en una sola partida.": "Spend 100 CHAOS in a single match.",
  "Gira la ruleta de la Mítica.": "Spin the Mythic wheel.",
  "Golpe al bolsillo": "Blow to the Wallet",
  "Gratis en esta versión. Shh.": "Free in this version. Shh.",
  "Ha vuelto a caer. Por tu culpa.": "It fell again. Your fault.",
  "Hasta el último segundo": "Until the Last Second",
  "Haz %1 de daño en una partida del Modo Jefe.": "Deal %1 damage in a Boss Mode match.",
  "Hechizo del gashapón de cartas.": "Spell from the card gacha.",
  "Hechizos, mata-sanadores y cero remordimientos.": "Spells, healer-killers and zero regrets.",
  "Hecho a mano": "Handmade",
  "Hombre orquesta": "One-Man Band",
  "Huelga general": "General Strike",
  "Héroes caídos": "Fallen Heroes",
  "Incidencia cerrada": "Ticket Closed",
  "Jefe de jefes": "Boss of Bosses",
  "Juega %1 cartas.": "Play %1 cards.",
  "Juega %1%2 por primera vez.": "Play %1%2 for the first time.",
  "Juega a %1 por primera vez.": "Play %1 for the first time.",
  "Juega una partida del Modo Jefe.": "Play a Boss Mode match.",
  "Juega una partida rápida.": "Play a quick match.",
  "Juego salvado": "Game Saved",
  "La casa siempre gana. O casi.": "The house always wins. Or almost.",
  "La rebelión crece": "The Rebellion Grows",
  "La ruleta de la semana": "The Wheel of the Week",
  "Le duele más que perder dinero.": "It hurts more than losing money.",
  "Leyenda mítica": "Mythic Legend",
  "Libera %1 facciones en la campaña.": "Free %1 factions in the campaign.",
  "Libera a los Olvidados del sótano de Microblizz.": "Free the Forgotten from Microblizz's basement.",
  "Libera todas las facciones.": "Free all the factions.",
  "Libera una facción en la campaña.": "Free a faction in the campaign.",
  "Licencia revocada": "Licence Revoked",
  "Lluvia de estrellas": "Star Shower",
  "Los colecciona como cromos.": "Collects them like trading cards.",
  "Los juegos vuelven a tener alma.": "Games have a soul again.",
  "Mata-sanadores del gashapón de cartas.": "Healer-killers from the card gacha.",
  "Mazo caliente": "Hot Deck",
  "Mejor el original": "The Original Was Better",
  "Microblizz ha visto tu publicación.": "Microblizz has seen your post.",
  "Microblizz pide refuerzos.": "Microblizz calls for backup.",
  "Más rentable que Microblizz.": "More profitable than Microblizz.",
  "Más rápido que un despido.": "Faster than a layoff.",
  "Ni el consejo de administración se lo cree.": "Not even the board believes it.",
  "Ni la ruleta de Microblizz ha podido contigo.": "Not even Microblizz's wheel could stop you.",
  "Ni la ruleta de la semana pudo contigo.": "Not even the wheel of the week could stop you.",
  "Ni un becario trabajaría tan poco.": "Not even an intern would work this little.",
  "Ni una torre para Microblizz.": "Not a single tower for Microblizz.",
  "Ningún prompt sobrevive.": "No prompt survives.",
  "Otro juego que no se cierra.": "Another game that doesn't get shut down.",
  "Parcheado": "Patched",
  "Parches Día 1": "Day 1 Patches",
  "Partida rápida": "Quick match",
  "Pesa 80 GB y no arregla nada.": "Weighs 80 GB and fixes nothing.",
  "Pista: a veces lo mejor es no hacer nada.": "Hint: sometimes the best thing is to do nothing.",
  "Pista: algo de la tienda.": "Hint: something from the shop.",
  "Pista: el reloj es tu enemigo.": "Hint: the clock is your enemy.",
  "Pista: el rival más fácil.": "Hint: the easiest rival.",
  "Pista: ganar sin gastar.": "Hint: win without spending.",
  "Pista: nunca te rindas, aunque vayas perdiendo.": "Hint: never give up, even when you're losing.",
  "Pista: presume de tus victorias.": "Hint: show off your victories.",
  "Pista: se acaba el tiempo y vais empatados.": "Hint: time runs out and you're tied.",
  "Pista: ¿quién necesita equipo?": "Hint: who needs a team?",
  "Por algo se empieza.": "You've got to start somewhere.",
  "Remasters 70 €": "70 € Remasters",
  "Remontada épica": "Epic Comeback",
  "Rescate: %1": "Bailout: %1",
  "Rápida como un despido.": "Quick as a layoff.",
  "Saca a tu líder %1 veces.": "Play your leader %1 times.",
  "Se decidió en la foto finish.": "It was decided in a photo finish.",
  "Se quedó en el 99 %.": "It stayed at 99 %.",
  "Se van de Microblizz sin avisar.": "They leave Microblizz without notice.",
  "Según Microblizz, sobraban.": "According to Microblizz, they were surplus.",
  "Servidor reiniciado": "Server Rebooted",
  "Servidores Caídos": "Servers Down",
  "Siempre tiene un hueco en la agenda para ti.": "Always has a slot in the diary for you.",
  "Sin becarios": "No Interns",
  "Sin crunch y sin rendirse.": "No crunch and no giving up.",
  "Sin jefe, el equipo se toma el día libre.": "Without the boss, the team takes the day off.",
  "Sin permanencia.": "No minimum contract.",
  "Su respuesta: «reinicia el juego».": "Their answer: «restart the game».",
  "Su valoración media: una estrella.": "Their average rating: one star.",
  "Sube %1%2 a nivel %3.": "Level %1%2 up to level %3.",
  "Suma %1 estrellas en tus cartas del gashapón.": "Add up %1 stars on your gacha cards.",
  "Suscripción cancelada": "Subscription Cancelled",
  "Suscripción cancelada.": "Subscription cancelled.",
  "Termina una partida sin jugar ninguna carta.": "Finish a match without playing any card.",
  "Tira la base enemiga en menos de 100 segundos.": "Bring down the enemy base in under 100 seconds.",
  "Tira una base enemiga.": "Bring down an enemy base.",
  "Torres fuera": "Towers Out",
  "Trabajan gratis… y se nota.": "They work for free… and it shows.",
  "en Difícil": "on Hard",
  "en Mítica": "on Mythic",
  "personajes de Cultura Pop corrompidos": "corrupted Pop Culture characters",
  ", me despidió Microblizz. Antes de empezar, ¿cómo quieres que te llame? Será tu nombre en la": ", Microblizz fired me. Before we start, what should I call you? It'll be your name in the",
  "Arena": "Arena",
  "Así te verán en la": "That's how you'll be seen in the",
  "FACCIONES": "FACTIONS",
  "Liga": "League",
  "Liga %1 · %2 copas": "League %1 · %2 trophies",
  "RÉCORD DE COPAS": "TROPHY RECORD",
  "estrellas en normal": "stars on normal",
  "ganadas - perdidas · %1": "won - lost · %1",
  "tu mejor marca": "your best record",
  "y en el chat de las partidas.": "and in the match chat.",
  "y en el chat.": "and in the chat.",
  "Derriba 20 torres": "Knock down 20 towers",
  "Derriba 3 torres": "Knock down 3 towers",
  "Derrota a 40 enemigos": "Defeat 40 enemies",
  "Derrota a 400 enemigos": "Defeat 400 enemies",
  "Gana 5 partidas sin perder torres": "Win 5 matches without losing towers",
  "Gana sin perder ninguna torre": "Win without losing any tower",
  "Gasta 120 de CAOS": "Spend 120 CHAOS",
  "Juega 2 partidas rápidas": "Play 2 quick matches",
  "Juega 20 cartas": "Play 20 cards",
  "Juega 200 cartas": "Play 200 cards",
  "Juega 3 partidas del Modo Jefe": "Play 3 Boss Mode matches",
  "Juega una partida del Modo Jefe": "Play a Boss Mode match",
  "Saca a tu líder 5 veces": "Play your leader 5 times",
  "Sube 5 niveles de unidades": "Level up units 5 times",
  "Sube de nivel una unidad": "Level up a unit",
  "Tira una base enemiga": "Bring down an enemy base"
});
