// Fans of Rumble · Inglés (plantillas): efectos de habilidades y objetos (con sus números) y frases del chat de las despedidas.
'use strict';
IDIOMA.add({
  "+%1 % de daño.": "+%1 % damage.",
  "+%1 % de vida.": "+%1 % health.",
  "%1 % de daño y su Chaos Jump vuelve un": "%1 % damage and its Chaos Jump comes back",
  "Al caer se enfada y explota: %1 de daño alrededor.": "When it falls it gets angry and explodes: %1 damage around it.",
  "Al caer te devuelve %1 de CAOS.": "When it falls it gives you back %1 CHAOS.",
  "Al entrar congela %1 s a los enemigos de alrededor. ¡Sonreíd!": "On entering, it freezes the surrounding enemies for %1 s. Say cheese!",
  "Al entrar en el campo le roba %1 de CAOS al rival.": "On entering the field it steals %1 CHAOS from the rival.",
  "Al morir se divide en 2 copias pequeñas con el %1 % de su vida. No funciona en los líderes.": "On death it splits into 2 small copies with %1 % of its health. Doesn't work on leaders.",
  "Ataca un %1 % más rápido.": "Attacks %1 % faster.",
  "Cada 9 s aturde %1 s a los enemigos cercanos.": "Every 9 s it stuns nearby enemies for %1 s.",
  "Cada enemigo que derrota te da %1 de CAOS.": "Every enemy it defeats gives you %1 CHAOS.",
  "Cada golpe salta a otro enemigo con el %1 % del daño.": "Every hit jumps to another enemy with %1 % of the damage.",
  "Con menos de la mitad de vida: +%1 % de daño y velocidad.": "With less than half health: +%1 % damage and speed.",
  "Escudo del %1 % de su vida que se recarga.": "A shield worth %1 % of its health that recharges.",
  "Esquiva el %1 % de los golpes. Nadie sabe cómo.": "Dodges %1 % of hits. Nobody knows how.",
  "Los enemigos cercanos (a %1) le atacan a él.": "Nearby enemies (within %1) attack it.",
  "Los primeros %1 s va al triple de velocidad.": "For the first %1 s it moves at triple speed.",
  "Revive una vez con el %1 % de su vida.": "Revives once with %1 % of its health.",
  "Sale invisible %1 s y su primer golpe hace el doble.": "Comes out invisible for %1 s and its first hit does double.",
  "Se cura el %1 % del daño que hace.": "Heals %1 % of the damage it deals.",
  "Se hace enorme: +%1 % de vida y de daño, pero va más lento.": "Grows huge: +%1 % health and damage, but moves slower.",
  "Se mueve un %1 % más rápido.": "Moves %1 % faster.",
  "Sus golpes frenan al enemigo %1 s.": "Its hits slow the enemy for %1 s.",
  "Phony saca a %1, se viene lo gordo": "Phony plays %1, here comes the big one",
  "%1 aguanta %2 de daño escondido detrás de su montaña de dinero": "%1 takes %2 damage hiding behind its mountain of money",
  "%1 cae ante Microblizz: «el problema es que no compraste el pack»": "%1 falls to Microblizz: «the problem is you didn't buy the pack»",
  "%1 cae ante Phony: «el problema es que no tenías suscripción»": "%1 falls to Phony: «the problem is you didn't have a subscription»",
  "%1 dejan Microblizz y se unen a la rebelión": "%1 leave Microblizz and join the rebellion",
  "%1 recibe %2 de daño y dice que no le ha dolido": "%1 takes %2 damage and says it didn't hurt",
  "%1 recibe %2 de daño y pide un aumento de sueldo": "%1 takes %2 damage and asks for a pay rise",
  "%1 rompen su contrato con Phony y se unen a la rebelión": "%1 break their contract with Phony and join the rebellion",
  "%1 se escapan de Microblizz y piden su finiquito": "%1 escape from Microblizz and ask for their severance pay",
  "%1 se escapan de Phony y exigen sus discos": "%1 escape from Phony and demand their discs",
  "Microblizz pierde %1 torres y el CEO llora en su yate": "Microblizz loses %1 towers and the CEO cries on his yacht",
  "Phony pierde %1 torres y sube la suscripción para compensar": "Phony loses %1 towers and raises the subscription to make up for it",
  "%1 apaga a IAhorro con un juego hecho a mano": "%1 switch IAhorro off with a handmade game",
  "%1 cae ante IAhorro, que ya ha copiado la partida": "%1 falls to IAhorro, which has already copied the match",
  "%1 se unen a la rebelión y prometen no hacer crunch": "%1 join the rebellion and promise not to crunch",
  "%1 vuelven a crear: «nadie hace esto como nosotros»": "%1 create again: «nobody does this like us»",
  "IAhorro pierde %1 torres: «es un problema de los datos de entrenamiento»": "IAhorro loses %1 towers: «it's a training data problem»",
  "IAhorro saca a %1, se viene lo gordo": "IAhorro plays %1, here comes the big one",
  "Consigue %1 cartas del gashapón de cartas.": "Get %1 cards from the card gacha.",
  "Derrota a %1 jefes distintos en Mítica (Modo Jefe).": "Defeat %1 different bosses on Mythic (Boss Mode).",
  "Derrota a %1 jefes en el Modo Jefe.": "Defeat %1 bosses in Boss Mode.",
  "Derrota a %1 líderes enemigos.": "Defeat %1 enemy leaders.",
  "Gana %1 partidas sin perder ninguna torre.": "Win %1 matches without losing any tower.",
  "Gana a %1 jefes en Difícil.": "Beat %1 bosses on Hard.",
  "Gana a %1 jefes en Mítica.": "Beat %1 bosses on Mythic.",
  "Gira %1 veces la ruleta de la Mítica.": "Spin the Mythic wheel %1 times.",
  "Juega %1 partidas del Modo Jefe.": "Play %1 Boss Mode matches.",
  "Juega %1 partidas rápidas.": "Play %1 quick matches.",
  "Juega %1%2 %3 veces.": "Play %1%2 %3 times.",
  "Juega a %1 %2 veces.": "Play %1 %2 times.",
  "Tira %1 bases enemigas.": "Bring down %1 enemy bases.",
  "Juega a Fans of Rumble:": "Play Fans of Rumble:",
  "¡COMBO x%#1!": "COMBO x%1!",
  "%1 DENTRO": "%1 INSIDE",
  "ARREGLADO": "FIXED",
  ": al subir de nivel a tu líder (o a cualquier carta), en la partida seguía saliendo el nivel antiguo hasta que cerrabas el juego y volvías a entrar. Ahora se ve el nivel nuevo al momento.": ": after levelling up your leader (or any card), matches kept showing the old level until you closed the game and came back. The new level now shows right away.",
  "Microblizz jura que tu líder siempre fue nivel 2 «en espíritu».": "Microblizz swears your leader was always level 2 «in spirit».",
  // Descripciones de habilidades y objetos partidas por su número (solo el Rumble)
  "% a los de alrededor.": "% to those nearby.",
  "% cada segundo.": "% every second.",
  "% de daño y cada golpe aparta al enemigo.": "% damage and every hit knocks the enemy back.",
  "% de daño y los aliados de alrededor se curan un": "% damage and nearby allies heal",
  "% de daño y se cura un": "% damage and heals",
  "% de daño y velocidad.": "% damage and speed.",
  "% de los golpes. Nadie sabe cómo.": "% of hits. Nobody knows how.",
  "% de su vida y +": "% of its health and +",
  "% de vida y de daño, pero va más lento.": "% health and damage, but it's slower.",
  "% de vida y de daño, y las torres tardan": "% health and damage, and towers take",
  "Al caer te devuelve": "When it falls, it gives you back",
  "Al entrar en el campo le roba": "When it enters the field, it steals",
  "Escudo de plasma del": "Plasma shield worth",
  "Sale invisible": "Enters invisible for",
  "Se hace enorme: +": "Becomes huge: +",
  "Se mueve un": "Moves",
  "Si cae, vuelve un": "If it falls, it comes back",
  "de CAOS al rival.": "CHAOS from the rival.",
  "s más en acordarse de él.": "s longer to notice it.",
  "s y su primer golpe hace el doble.": "s and its first hit deals double.",
  // (más trozos del Rumble)
  "Con menos de la mitad de vida: +": "Below half health: +",
  "% a todo. Algo es algo.": "% to everything. Better than nothing.",
  "% antes.": "% sooner.",
  "% de velocidad. Viste como el que te despide. Exclusivo del Pase Ejecutivo.": "% speed. Dresses like the guy who fires you. Executive Pass exclusive.",
  "% de su vida cada segundo. Pone «Me voy a mi hora».": "% of its health every second. It says «I clock out on time».",
  // Arena nueva (v0.9.35)
  "%#1 copas": "%1 cups",
  "+%#1 copas": "+%1 cups",
  "Récord %#1": "Record %1",
  "%#1 ganadas": "%1 won",
  "%#1 perdidas": "%1 lost",
  "Racha %#1": "Streak %1",
  "ELIGE RIVAL": "CHOOSE A RIVAL",
  "FÁCIL": "EASY",
  "IGUALADO": "EVEN",
  "DIFÍCIL": "HARD",
  "De momento son «jugadores» inventados: los maneja la CPU.": "For now they're made-up «players»: the CPU plays them.",
  "Si ganas:": "If you win:",
  "Si pierdes: −%#1 copas": "If you lose: −%1 cups",
  "tu facción para esta partida": "your faction for this match",
  "BATALLA": "BATTLE",
  "contra %1": "vs %1",
  "LISTO": "DONE",
  "LIGA MÁXIMA": "TOP LEAGUE",
  "+%#1 TIRADA GRATIS": "+%1 FREE PULL",
  "+%#1 TIRADAS GRATIS": "+%1 FREE PULLS",
  "<b>ARENA</b> renovada: tu liga en grande con su escudo, tus copas y una barra hasta la siguiente liga. Los rivales salen en tarjetas con su dificultad, ves lo que ganas o pierdes, y la facción se cambia con un botón.": "<b>ARENA</b> revamped: your league front and centre with its shield, your cups and a bar to the next league. Rivals come as cards with their difficulty, you can see what you win or lose, and you change faction with one button.",
  "<b>RACHA</b> de victorias y <b>REGALOS DEL CAMINO</b>: cada 100 copas de récord, una tirada gratis del gashapón.": "Win <b>STREAK</b> and <b>ROAD GIFTS</b>: every 100 record cups, a free gashapon pull.",
  "En Microblizz las ligas se deciden por antigüedad. En la arena, de momento, no.": "At Microblizz, leagues are decided by seniority. In the arena, for now, they aren't.",
  // Arena 0.9.37
  "FACCIÓN": "FACTION",
  "MAZO": "DECK",
  "<b>ARENA</b>: tu facción y tu mazo van juntos en una fila pequeña. FACCIÓN abre una lista compacta y MAZO abre el editor de la Colección; al guardar vuelves a la arena.": "<b>ARENA</b>: your faction and your deck share one small row. FACTION opens a compact list and DECK opens the Collection's editor; when you save, you're back in the arena.",
  "Microblizz ha encogido la fila de la facción. Dice que es para ahorrar píxeles.": "Microblizz shrank the faction row. They say it saves pixels.",
  "Modo ahorro": "Saver mode",
  "Para móviles sencillos: dibuja con menos resolución, a 30 imágenes por segundo y con menos polvo y humo. Gasta menos batería y calienta menos.": "For simpler phones: draws at lower resolution, at 30 frames per second and with less dust and smoke. Uses less battery and runs cooler.",
  "Contador de FPS": "FPS counter",
  "Enseña arriba a la izquierda cuántas imágenes por segundo dibuja el juego. Por encima de 50 va fluido; por debajo de 25 va a tirones.": "Shows at the top left how many frames per second the game draws. Above 50 is smooth; below 25 is choppy.",
  "<b>MODO AHORRO</b> (en Opciones): para móviles sencillos. Dibuja con menos resolución, a 30 imágenes por segundo y con menos polvo y humo, así gasta menos batería y calienta menos.": "<b>SAVER MODE</b> (in Options): for simpler phones. Draws at lower resolution, at 30 frames per second and with less dust and smoke, so it uses less battery and runs cooler.",
  "<b>CONTADOR DE FPS</b> (en Opciones): enseña arriba a la izquierda cuántas imágenes por segundo dibuja el juego. Verde, va fluido; amarillo, justo; rojo, a tirones.": "<b>FPS COUNTER</b> (in Options): shows at the top left how many frames per second the game draws. Green is smooth; yellow is borderline; red is choppy.",
  "Microblizz también tiene un modo ahorro: lo aplica a los sueldos.": "Microblizz has a saver mode too: it applies it to salaries.",
  "<b>GASHAPÓN EN LA NUBE</b>: con tu cuenta, las tiradas de habilidades y equipo las hace nuestro servidor, así tus objetos quedan a salvo. Para tirar hace falta conexión.": "<b>GASHAPON IN THE CLOUD</b>: with your account, ability and gear pulls are now done by our server, so your items are kept safe. You need a connection to pull.",
  "Microblizz jura que el servidor no se queda con ninguna copia. Solo con las mejores.": "Microblizz swears the server doesn't keep any copies. Only the best ones.",
  "Te faltan gemas": "You are short on gems",
  "Necesitas conexión para esto": "You need a connection for this",
  "<b>CARTAS EN LA NUBE</b>: con tu cuenta, la máquina de cartas también la hace nuestro servidor, y tus cartas y estrellas quedan guardadas en ella. Para tirar hace falta conexión.": "<b>CARDS IN THE CLOUD</b>: with your account, the card machine is now run by our server too, and your cards and stars are saved in it. You need a connection to pull.",
  "El servidor de Microblizz cuenta tus estrellas. Dice que las suyas ya las perdió.": "Microblizz's server counts your stars. It says it already lost its own.",
});
