// Fans of Rumble · Inglés (plantillas): efectos de habilidades y objetos (con sus números) y frases del chat de las despedidas.
'use strict';
IDIOMA.add({
  "+%1 % de daño.": "+%1 % damage.",
  "+%1 % de vida.": "+%1 % health.",
  "%1 % de daño y su Chaos Jump vuelve un": "%1 % damage and its Chaos Jump comes back",
  "Al caer se enfada y explota: %1 de daño alrededor.": "When it falls it gets angry and explodes: %1 damage around it.",
  "Al caer te devuelve %1 de CAOS.": "When it falls it gives you back %1 CHAOS.",
  "Al entrar congela %1 s a los enemigos de alrededor. ¡Sonreíd!": "On entering, it freezes the surrounding enemies for %1 s. Say cheese!",
  "Al entrar en el campo le roba %1 de CAOS al rival.": "On entering the field it steals %1 CHAOS from the rival.",
  "Al morir se divide en 2 copias pequeñas con el %1 % de su vida. No funciona en los líderes.": "On death it splits into 2 small copies with %1 % of its health. Doesn't work on leaders.",
  "Ataca un %1 % más rápido.": "Attacks %1 % faster.",
  "Cada 9 s aturde %1 s a los enemigos cercanos.": "Every 9 s it stuns nearby enemies for %1 s.",
  "Cada enemigo que derrota te da %1 de CAOS.": "Every enemy it defeats gives you %1 CHAOS.",
  "Cada golpe salta a otro enemigo con el %1 % del daño.": "Every hit jumps to another enemy with %1 % of the damage.",
  "Con menos de la mitad de vida: +%1 % de daño y velocidad.": "With less than half health: +%1 % damage and speed.",
  "Escudo del %1 % de su vida que se recarga.": "A shield worth %1 % of its health that recharges.",
  "Esquiva el %1 % de los golpes. Nadie sabe cómo.": "Dodges %1 % of hits. Nobody knows how.",
  "Los enemigos cercanos (a %1) le atacan a él.": "Nearby enemies (within %1) attack it.",
  "Los primeros %1 s va al triple de velocidad.": "For the first %1 s it moves at triple speed.",
  "Revive una vez con el %1 % de su vida.": "Revives once with %1 % of its health.",
  "Sale invisible %1 s y su primer golpe hace el doble.": "Comes out invisible for %1 s and its first hit does double.",
  "Se cura el %1 % del daño que hace.": "Heals %1 % of the damage it deals.",
  "Se hace enorme: +%1 % de vida y de daño, pero va más lento.": "Grows huge: +%1 % health and damage, but moves slower.",
  "Se mueve un %1 % más rápido.": "Moves %1 % faster.",
  "Sus golpes frenan al enemigo %1 s.": "Its hits slow the enemy for %1 s.",
  "Phony saca a %1, se viene lo gordo": "Phony plays %1, here comes the big one",
  "%1 aguanta %2 de daño escondido detrás de su montaña de dinero": "%1 takes %2 damage hiding behind its mountain of money",
  "%1 cae ante Microblizz: «el problema es que no compraste el pack»": "%1 falls to Microblizz: «the problem is you didn't buy the pack»",
  "%1 cae ante Phony: «el problema es que no tenías suscripción»": "%1 falls to Phony: «the problem is you didn't have a subscription»",
  "%1 dejan Microblizz y se unen a la rebelión": "%1 leave Microblizz and join the rebellion",
  "%1 recibe %2 de daño y dice que no le ha dolido": "%1 takes %2 damage and says it didn't hurt",
  "%1 recibe %2 de daño y pide un aumento de sueldo": "%1 takes %2 damage and asks for a pay rise",
  "%1 rompen su contrato con Phony y se unen a la rebelión": "%1 break their contract with Phony and join the rebellion",
  "%1 se escapan de Microblizz y piden su finiquito": "%1 escape from Microblizz and ask for their severance pay",
  "%1 se escapan de Phony y exigen sus discos": "%1 escape from Phony and demand their discs",
  "Microblizz pierde %1 torres y el CEO llora en su yate": "Microblizz loses %1 towers and the CEO cries on his yacht",
  "Phony pierde %1 torres y sube la suscripción para compensar": "Phony loses %1 towers and raises the subscription to make up for it",
  "%1 apaga a IAhorro con un juego hecho a mano": "%1 switch IAhorro off with a handmade game",
  "%1 cae ante IAhorro, que ya ha copiado la partida": "%1 falls to IAhorro, which has already copied the match",
  "%1 se unen a la rebelión y prometen no hacer crunch": "%1 join the rebellion and promise not to crunch",
  "%1 vuelven a crear: «nadie hace esto como nosotros»": "%1 create again: «nobody does this like us»",
  "IAhorro pierde %1 torres: «es un problema de los datos de entrenamiento»": "IAhorro loses %1 towers: «it's a training data problem»",
  "IAhorro saca a %1, se viene lo gordo": "IAhorro plays %1, here comes the big one",
  "Consigue %1 cartas del gashapón de cartas.": "Get %1 cards from the card gacha.",
  "Derrota a %1 jefes distintos en Mítica (Modo Jefe).": "Defeat %1 different bosses on Mythic (Boss Mode).",
  "Derrota a %1 jefes en el Modo Jefe.": "Defeat %1 bosses in Boss Mode.",
  "Derrota a %1 líderes enemigos.": "Defeat %1 enemy leaders.",
  "Gana %1 partidas sin perder ninguna torre.": "Win %1 matches without losing any tower.",
  "Gana a %1 jefes en Difícil.": "Beat %1 bosses on Hard.",
  "Gana a %1 jefes en Mítica.": "Beat %1 bosses on Mythic.",
  "Gira %1 veces la ruleta de la Mítica.": "Spin the Mythic wheel %1 times.",
  "Juega %1 partidas del Modo Jefe.": "Play %1 Boss Mode matches.",
  "Juega %1 partidas rápidas.": "Play %1 quick matches.",
  "Juega %1%2 %3 veces.": "Play %1%2 %3 times.",
  "Juega a %1 %2 veces.": "Play %1 %2 times.",
  "Tira %1 bases enemigas.": "Bring down %1 enemy bases.",
  "Juega a Fans of Rumble:": "Play Fans of Rumble:",
  "¡COMBO x%#1!": "COMBO x%1!",
  "%1 DENTRO": "%1 INSIDE",
  "ARREGLADO": "FIXED",
  ": al subir de nivel a tu líder (o a cualquier carta), en la partida seguía saliendo el nivel antiguo hasta que cerrabas el juego y volvías a entrar. Ahora se ve el nivel nuevo al momento.": ": after levelling up your leader (or any card), matches kept showing the old level until you closed the game and came back. The new level now shows right away.",
  "Microblizz jura que tu líder siempre fue nivel 2 «en espíritu».": "Microblizz swears your leader was always level 2 «in spirit»."
});
