// Fans of Survivors · Inglés: los textos de este juego (los de la serie están en core/idioma).
'use strict';
IDIOMA.add({
  // página de entrada, menú y novedades
  'El nuevo (prototipo). CrazyBunny contra toda la plantilla de Microblizz: muévete, tus cartas disparan solas. Aguanta 10 minutos y despide a SurvivalBot.': 'The new one (prototype). CrazyBunny against the entire Microblizz staff: move, your cards fire on their own. Survive 10 minutes and fire SurvivalBot.',
  'CrazyBunny': 'CrazyBunny', 'contra': 'against', 'toda la plantilla de Microblizz': 'the entire Microblizz staff',
  'Tu récord:': 'Your best:', 'robots': 'robots', '· nivel': '· level',
  'PRIMER PROTOTIPO': 'FIRST PROTOTYPE', ': CrazyBunny contra toda la plantilla de Microblizz y Phony. Muévete, que tus cartas disparan solas.': ': CrazyBunny against the entire staff of Microblizz and Phony. Move — your cards fire on their own.',
  'Microblizz confirma que esta vez los becarios atacan en grupo. Lo llama «sinergia».': 'Microblizz confirms the interns now attack in groups. It calls it "synergy".',
  // cómo se juega
  'Muévete': 'Move', 'arrastrando el dedo en cualquier sitio (o con WASD o las flechas). Es lo único que haces tú.': 'by dragging your finger anywhere (or with WASD or the arrow keys). That is all you do.',
  'Tus cartas disparan solas.': 'Your cards fire on their own.', 'Empiezas con las Zanahorias de CrazyBunny; las demás cartas de Animales Locos son armas que se van sumando.': 'You start with CrazyBunny\'s Carrots; the other Crazy Animals cards are weapons you add along the way.',
  'Los robots que caen sueltan cristales de': 'Fallen robots drop crystals of', 'Recógelos para': 'Collect them to', 'subir de nivel': 'level up', 'y elige 1 de 3 mejoras: un arma nueva, subir una que ya tienes o una habilidad.': 'and pick 1 of 3 upgrades: a new weapon, a better one you already have, or a skill.',
  'enemigos gigantes': 'giant enemies', 'sueltan un Cofre de botín que mejora algo gratis. Sin microtransacciones.': 'drop a Loot chest that upgrades something for free. No microtransactions.',
  'Aguanta 10 minutos': 'Survive 10 minutes', 'y llega SurvivalBot. Despídelo y ganas.': 'and SurvivalBot arrives. Fire him and you win.',
  'Al acabar ganas': 'When it ends you earn', 'y experiencia.': 'and experience.', 'Sube tus cartas': 'Level up your cards', 'en la Colección: cada nivel de una carta sube el daño de su arma, y el del líder, el de todas. Lo del': 'in the Collection: each card level raises its weapon\'s damage, and the leader\'s raises all of them. What you get in the', 'también cuenta.': 'counts too.',
  // colección
  'Tu personaje. Lanza zanahorias y salta con Chaos Jump. Su nivel, su habilidad y sus objetos mejoran a todas tus armas.': 'Your character. Throws carrots and jumps with Chaos Jump. His level, skill and items boost all your weapons.',
  'En este juego, tus 6 cartas son tus armas: cuanto más nivel tenga cada una, más daño hace su arma.': 'In this game your 6 cards are your weapons: the higher a card\'s level, the more damage its weapon does.',
  'Todavía no se puede jugar con esta facción en Fans of Survivors.': 'This faction is not playable in Fans of Survivors yet.',
  'Todavía no es un arma en este juego': 'Not a weapon in this game yet', 'No hace nada en este juego.': 'Does nothing in this game.',
  'Equipo freak para tu líder: arma, cabeza y accesorio. Mejora a CrazyBunny y a todas sus armas. Cada objeto sale con su propia calidad.': 'Freak gear for your leader: weapon, head and accessory. Boosts CrazyBunny and all his weapons. Each item comes with its own quality.',
  // partida y final
  'RENDIRSE': 'GIVE UP', 'Los becarios no tienen pausa. Tú sí.': 'Interns don\'t get breaks. You do.', 'El CEO aprovecha la pausa para subir los precios.': 'The CEO uses the break to raise prices.',
  'Microblizz ya está pensando qué juego cerrar ahora.': 'Microblizz is already thinking about which game to shut down next.', 'SurvivalBot también se toma un café. Descafeinado.': 'SurvivalBot is having a coffee too. Decaf.',
  'tiempo': 'time', 'robots despedidos': 'robots fired', 'Experiencia: +%#1 para las cartas que has usado': 'Experience: +%1 for the cards you used',
  'SurvivalBot despedido en %1 de pelea.': 'SurvivalBot fired after %1 of fighting.', 'Has aguantado %1 contra la plantilla de Microblizz.': 'You lasted %1 against the Microblizz staff.',
  '¡REVIVES!': 'YOU\'RE BACK!', 'Te habían despedido… pero el contrato tenía letra pequeña': 'You were fired… but the contract had fine print',
  'Chat en directo': 'Live chat', 'Los comentarios falsos durante la partida.': 'The fake comments during the match.',
  // misiones
  'Juega 3 partidas': 'Play 3 matches', 'Despide a 500 robots': 'Fire 500 robots', 'Despide a 1.500 robots': 'Fire 1,500 robots', 'Aguanta 10 minutos en total': 'Survive 10 minutes in total',
  'Aguanta 5 minutos en total': 'Survive 5 minutes in total', 'Sube 30 niveles en tus partidas': 'Gain 30 levels in your matches', 'Abre un Cofre de botín': 'Open a Loot chest',
  'Despide a 2 enemigos gigantes': 'Fire 2 giant enemies', 'Despide a SurvivalBot': 'Fire SurvivalBot', 'Juega 20 partidas': 'Play 20 matches', 'Despide a 10.000 robots': 'Fire 10,000 robots',
  'Aguanta 60 minutos en total': 'Survive 60 minutes in total', 'Despide a SurvivalBot 3 veces': 'Fire SurvivalBot 3 times', 'Abre 8 Cofres de botín': 'Open 8 Loot chests',
  'Sube 200 niveles en tus partidas': 'Gain 200 levels in your matches', 'Gira 10 veces el gashapón': 'Spin the gacha 10 times', 'Sube 5 niveles a tus cartas': 'Level up your cards 5 times',
  'RÉCORD': 'BEST', 'aguantado': 'survived', 'veces despedido': 'times fired', 'jugadas': 'played', 'ROBOTS': 'ROBOTS', 'despedidos': 'fired', 'PARTIDAS': 'MATCHES',
  // título
  'Microblizz ha mandado a toda su plantilla a por CrazyBunny. Tus cartas disparan solas: tú solo tienes que moverte, recoger el CAOS y elegir mejoras.': 'Microblizz has sent its entire staff after CrazyBunny. Your cards fire on their own: you just move, collect the CHAOS and pick upgrades.',
  'JUGAR': 'PLAY',
  'Moverte:': 'Move:', 'arrastra el dedo en cualquier sitio, o usa WASD o las flechas.': 'drag your finger anywhere, or use WASD or the arrow keys.',
  'Atacar:': 'Attack:', 'lo hacen tus cartas solas.': 'your cards do it on their own.',
  'Subir de nivel:': 'Level up:', 'recoge los cristales de CAOS y elige 1 de 3 mejoras.': 'collect the CHAOS crystals and pick 1 of 3 upgrades.',
  'Temblor: SÍ': 'Shake: ON', 'Temblor: NO': 'Shake: OFF', 'Números de daño: SÍ': 'Damage numbers: ON', 'Números de daño: NO': 'Damage numbers: OFF',
  'prototipo': 'prototype', 'versión': 'version',
  'Tu récord': 'Your best', 'bajas': 'kills', 'nivel': 'level',
  'Aguanta 10 minutos y despide a SurvivalBot.': 'Survive 10 minutes and fire SurvivalBot.',
  'Activar sonido': 'Turn sound on', 'Silenciar sonido': 'Mute sound', 'Pausar': 'Pause', 'Campo de batalla': 'Battlefield',
  // subir de nivel, pausa y final
  '¡ASCENSO!': 'PROMOTION!', 'NIVEL': 'LEVEL', 'Nivel %#1': 'Level %1', '¡NUEVO!': 'NEW!',
  'Elige una mejora. Microblizz no te la va a pagar.': 'Pick an upgrade. Microblizz won\'t pay for it.',
  'PAUSA': 'PAUSED', 'Lo que llevas:': 'What you have:', 'SEGUIR': 'RESUME', 'Rendirse (firmar el despido)': 'Give up (sign the dismissal)',
  '¡HAS GANADO!': 'YOU WIN!', 'TE HAN DESPEDIDO': 'YOU\'RE FIRED', 'Tiempo': 'Time', 'Bajas': 'Kills', 'Nivel': 'Level', 'Puntos': 'Score',
  '¡NUEVO RÉCORD!': 'NEW RECORD!', 'OTRA VEZ': 'AGAIN', 'Menú': 'Menu',
  // en la partida
  '¡SOBREVIVE 10 MINUTOS!': 'SURVIVE 10 MINUTES!', 'Microblizz manda a toda su plantilla a por CrazyBunny': 'Microblizz sends its whole staff after CrazyBunny',
  '¡RONDA DE CONTRATACIÓN!': 'HIRING SPREE!', '¡CAJABOTÍN GIGANTE!': 'GIANT LOOTBOX!', '¡DESCARGA MASIVA AL 99 %!': 'MASS DOWNLOAD AT 99%!',
  '¡EL PARCHE DE 80 GB!': 'THE 80 GB PATCH!', '¡RENOVACIÓN DE LICENCIAS!': 'LICENSE RENEWAL!', '¡HÉROE DESCARTADO!': 'DISCARDED HERO!',
  'Suelta un Cofre de botín (sin microtransacciones)': 'Drops a Loot chest (no microtransactions)', '¡Que no te rodeen!': 'Don\'t get surrounded!',
  '¡LLEGA SURVIVALBOT!': 'SURVIVALBOT IS HERE!', '«Hemos comprado vuestro juego… y lo vamos a cerrar.»': '"We bought your game… and we\'re shutting it down."',
  'ENTIERRO DE IP': 'IP BURIAL', '¡DESPIDOS MASIVOS!': 'MASS LAYOFFS!', 'SurvivalBot llama a los becarios': 'SurvivalBot calls in the interns',
  '¡CONGELADO!': 'FROZEN!', '¡ESQUIVADO!': 'DODGED!', '¡IMÁN!': 'MAGNET!', 'LICENCIA CADUCADA': 'LICENSE EXPIRED', '¡COFRE DE BOTÍN!': 'LOOT CHEST!',
  '¡SURVIVALBOT DESPEDIDO!': 'SURVIVALBOT FIRED!', 'Microblizz anuncia que «nunca le gustó ese robot»': 'Microblizz says it "never liked that robot"',
  'DESPEDIDO': 'FIRED',
  // armas
  'Zanahorias': 'Carrots', 'CrazyBunny lanza zanahorias al enemigo más cercano.': 'CrazyBunny throws carrots at the nearest enemy.',
  '+1 zanahoria': '+1 carrot', '+30 % daño y atraviesa 1 más': '+30% damage and pierces 1 more', '+30 % daño, más rápidas': '+30% damage, faster',
  'Salta (sin recibir daño) y aplasta todo lo que hay alrededor al caer.': 'Jumps (taking no damage) and crushes everything around on landing.',
  'Salta más a menudo': 'Jumps more often', '+40 % daño': '+40% damage', 'Área más grande': 'Bigger area', 'Salta más a menudo y +40 % daño': 'Jumps more often and +40% damage',
  'Salen ardillas corriendo en todas direcciones y atraviesan a todos.': 'Squirrels run out in every direction and go through everyone.',
  '+1 ardilla': '+1 squirrel', '+30 % daño': '+30% damage', '+2 ardillas': '+2 squirrels', 'Salen más a menudo': 'Come out more often',
  'Un castor con dinamita corre hacia un grupo de enemigos y explota.': 'A beaver with dynamite runs into a group of enemies and blows up.',
  'Explosión más grande': 'Bigger explosion', '+1 castor': '+1 beaver', 'Sale más a menudo y +30 % daño': 'Comes out more often and +30% damage',
  'SlyFox aparece por sorpresa junto al enemigo con más vida y le pega x3.': 'SlyFox pops up next to the toughest enemy and hits it x3.',
  '+1 objetivo': '+1 target', 'Aparece más a menudo': 'Shows up more often',
  'Un aura alrededor que daña a los enemigos y te cura poco a poco.': 'An aura around you that hurts enemies and slowly heals you.',
  'Aura más grande': 'Bigger aura', '+50 % daño': '+50% damage', 'Cura el doble': 'Heals twice as much', 'Aura más grande y +50 % daño': 'Bigger aura and +50% damage',
  'Lanza bolsas de basura que explotan donde caen.': 'Throws trash bags that explode where they land.',
  '+1 bolsa': '+1 bag', '+1 bolsa y explosión más grande': '+1 bag and bigger explosion', 'Lanza más a menudo': 'Throws more often',
  'Vacas que giran a tu alrededor y empujan a los enemigos.': 'Cows that spin around you and push enemies away.',
  '+1 vaca': '+1 cow', 'Duran más': 'Last longer', '+1 vaca y +40 % daño': '+1 cow and +40% damage',
  // mejoras
  'Cafeína': 'Caffeine', '+8 % de velocidad al andar.': '+8% movement speed.',
  'Piel dura': 'Tough skin', '+20 de vida máxima (y te cura 20).': '+20 max health (and heals 20).',
  'Puños de hierro': 'Iron fists', '+10 % de daño con todas las armas.': '+10% damage with every weapon.',
  'Reflejos': 'Reflexes', 'Las armas se recargan un 7 % antes.': 'Weapons recharge 7% faster.',
  'Imán de CAOS': 'CHAOS magnet', 'Recoges el CAOS desde un 25 % más lejos.': 'You pick up CHAOS from 25% further away.',
  'Vampirismo': 'Vampirism', 'Cada enemigo que cae te cura un poco.': 'Every enemy that falls heals you a little.',
  'Hitbox dudosa': 'Dodgy hitbox', 'Un 6 % de los golpes no te dan. Nadie sabe por qué.': '6% of hits miss you. Nobody knows why.',
  'Becario del Mes': 'Intern of the Month', '+10 % de CAOS de cada cristal.': '+10% CHAOS from each crystal.',
  'Café de máquina': 'Vending machine coffee', 'Te cura 40 de vida. Sabe a despacho.': 'Heals 40 health. Tastes like an office.',
  'Bonus del CEO': 'CEO bonus', '+500 puntos. El CEO se ha llevado el resto.': '+500 points. The CEO kept the rest.',
  "<b>SESIÓN MÁS ESTABLE</b>: arreglado el error «invalid refresh token» que a veces te sacaba de la cuenta.": "<b>MORE STABLE SESSION</b>: fixed the “invalid refresh token” error that sometimes logged you out of your account.",
  "Microblizz asegura que la sesión ahora es de las que no se cae. Ya lo dijo del puente.": "Microblizz swears the session is now the kind that doesn't drop. It said the same about the bridge.",
  "<b>PASE CON ASPECTO NUEVO</b>: el pase tiene un diseño renovado y pasa a funcionar como en Rumble.": "<b>PASS WITH A NEW LOOK</b>: the pass has a renewed design and now works as in Rumble.",
  "Microblizz ha pintado el pase de otro color y lo llama «rediseño».": "Microblizz painted the pass another colour and calls it a “redesign”.",
  "<b>INICIAR SESIÓN, MÁS FÁCIL</b>: el menú tiene un botón «Iniciar sesión / crear cuenta» para guardar tu progreso con Google o con tu email.": "<b>EASIER SIGN-IN</b>: the menu has a «Sign in / create account» button to save your progress with Google or email.",
  "Microblizz ha puesto un cartel de «Entrada» en la puerta. Antes había que adivinar dónde estaba.": "Microblizz has put an «Entrance» sign on the door. Before, you had to guess where it was.",
  "<b>MÁS TEXTOS EN INGLÉS</b>: hemos repasado y traducido textos que se habían quedado sin traducir.": "<b>MORE TEXTS IN ENGLISH</b>: we have gone through the game and translated texts that had been left untranslated.",
  "Microblizz ha descubierto que el inglés también existe. Está muy orgulloso.": "Microblizz has discovered that Spanish is not the only language. They are very proud.",
  "<b>MENOS TECNICISMOS</b>: repasados textos en español para que se entiendan mejor.": "<b>FEWER TECHNICAL TERMS</b>: Spanish texts reviewed so they are easier to understand.",
  "Microblizz ha quitado una sigla. Dice que la nota del cambio es más larga que el cambio.": "Microblizz removed one acronym. He says the change note is longer than the change.",
});
