// Fans Of · Inglés de la ventana NOVEDADES de la raíz (novedades/lista.js y sus botones).
'use strict';
IDIOMA.add({
  // la ventana
  "NOVEDADES": "NEWS",
  "LO ÚLTIMO": "LATEST",
  "PARCHES DE CADA JUEGO": "PATCH NOTES BY GAME",
  "Cada juego se actualiza por su cuenta: aquí tienes su última versión y lo que trae.": "Each game updates on its own: here is its latest version and what it brings.",
  "¡A JUGAR!": "LET'S PLAY!",
  "Cerrar": "Close",
  "Ir al juego": "Go to the game",
  "Novedades y parches": "News and patches",
  "versión %1": "version %1",
  // el boletín del 10-10-2026
  "Lo publicado en las últimas 24 horas": "What we released in the last 24 hours",
  "10 de octubre de 2026": "10 October 2026",
  "FANS OF RUMBLE: TÁCTICAS": "FANS OF RUMBLE: TACTICS",
  "FANS OF TD Y FANS OF SKATE": "FANS OF TD AND FANS OF SKATE",
  "PROTOTIPOS NUEVOS EN LA BIBLIOTECA": "NEW PROTOTYPES IN THE LIBRARY",
  "<b>12 HABILIDADES LOCAS</b> en el gashapón, cada una con su animación en batalla: la Llamada del CEO, el Modo Dios, el Bullet Time, el Pay to Win…": "<b>12 CRAZY SKILLS</b> in the gashapon, each with its own battle animation: the CEO's Call, God Mode, Bullet Time, Pay to Win…",
  "<b>MINIATURAS NUEVAS</b>: cada habilidad y cada objeto tiene su propio dibujo, y las Épicas y Legendarias brillan.": "<b>NEW THUMBNAILS</b>: every skill and every item has its own drawing, and Epics and Legendaries shine.",
  "<b>RIVALES CON CABEZA</b>: la máquina juega con tácticas según la dificultad, también en la partida rápida y en el entrenamiento.": "<b>SMARTER RIVALS</b>: the CPU plays with tactics depending on the difficulty, in quick match and training too.",
  "<b>LA ARENA, TODA JUNTA</b>: una sola puerta con dos pestañas, CONTRA JUGADORES (copas y ligas) y ENTRENAMIENTO (contra la CPU).": "<b>ONE ARENA</b>: a single door with two tabs, VS PLAYERS (trophies and leagues) and TRAINING (against the CPU).",
  "<b>MÍTICA SEMANAL</b>: las estrellas vuelven a 0 cada lunes, cada semana se cobra oro y gemas y los 10 primeros se llevan un título.": "<b>WEEKLY MYTHIC</b>: stars reset to 0 every Monday, gold and gems pay out every week and the top 10 earn a title.",
  "<b>FRASES Y EMOTICONOS</b> durante la partida, sin escribir. Se ganan en los dos pases y se eligen en el Armario.": "<b>PHRASES AND EMOTES</b> during the match, no typing. Earn them in both passes and pick them in the Wardrobe.",
  "<b>13 LOGROS NUEVOS</b>, tu puesto en la clasificación en el menú y, en el PvP, tu rival ve tu avatar, tu marco y tu título.": "<b>13 NEW ACHIEVEMENTS</b>, your leaderboard spot on the menu and, in PvP, your rival sees your avatar, frame and title.",
  "<b>CARTAS A LA ESPERA</b>: si te falta CAOS, la carta se queda reservada y sale sola en cuanto llega.": "<b>QUEUED CARDS</b>: if you're short on CHAOS, the card stays reserved and comes out on its own as soon as you have it.",
  "<b>8 FACCIONES NUEVAS</b> jugables, con 8 armas cada una. Se abren aguantando minutos en total.": "<b>8 NEW FACTIONS</b> to play, with 8 weapons each. Unlock them by surviving minutes in total.",
  "<b>CADA LÍDER CON SU ARMA</b>: espadazos en abanico, manos que salen del suelo, una torreta, un hacha bumerán…": "<b>A WEAPON FOR EACH LEADER</b>: fan-shaped sword swings, hands rising from the ground, a turret, a boomerang axe…",
  "<b>COFRES DE ESPECTÁCULO</b>: de 1 a 3 mejoras, 777 de tragaperras, suspense, sustos y, con mucha suerte, 5 mejoras de golpe.": "<b>SHOWSTOPPER CHESTS</b>: 1 to 3 upgrades, slot-machine 777, suspense, scares and, with real luck, 5 upgrades at once.",
  "<b>MINI JEFES Y BICHOS SHINY</b>: un mini jefe cada 2 minutos y bichos brillantes que sueltan cofre.": "<b>MINI BOSSES AND SHINY BUGS</b>: a mini boss every 2 minutes and shiny bugs that drop a chest.",
  "<b>CAJAS ROMPIBLES</b> en el mapa, que dan oro y, rara vez, un objeto.": "<b>BREAKABLE CRATES</b> on the map, which give gold and, rarely, an item.",
  "<b>COMBATES EN ESTILO MAQUETA</b>: 4 mundos en píxeles con luz de verdad e interfaz nueva con línea de turnos.": "<b>DIORAMA-STYLE BATTLES</b>: 4 pixel worlds with real lighting and a new interface with a turn timeline.",
  "<b>ATAQUES ESPECTACULARES</b>: las 18 técnicas y los ataques de los jefes tienen su propia animación.": "<b>SPECTACULAR ATTACKS</b>: all 18 techniques and the bosses' attacks have their own animation.",
  "<b>MENÚS NUEVOS</b>: el título es el despacho del CEO al atardecer, y el mapa, el grupo y la tienda llevan ventanas de marco dorado.": "<b>NEW MENUS</b>: the title screen is the CEO's office at sunset, and the map, party and shop have gold-framed windows.",
  "<b>MENÚ DEL TÍTULO</b> con campaña, novedades y opciones, y el CAOS de cada personaje siempre a la vista.": "<b>TITLE MENU</b> with campaign, news and options, and every character's CHAOS always in sight.",
  "<b>MINIATURAS NUEVAS</b> de habilidades y objetos en el TD, más textos traducidos al inglés y mejoras por dentro en los dos.": "<b>NEW THUMBNAILS</b> for skills and items in TD, more texts translated into English and behind-the-scenes improvements in both.",
  "<b>FANS OF ROGUELITE</b> (hasta la 0.4): La Madriguera, 3 mundos de 40 días divididos en capítulos, mapa del camino, raids, un comerciante misterioso y el chat del directo.": "<b>FANS OF ROGUELITE</b> (up to 0.4): The Burrow, 3 worlds of 40 days split into chapters, a road map, raids, a mystery merchant and the live-stream chat.",
  "<b>FANS OF RUMBLE 3D</b>: el boceto en 3D con su primera misión, comentarista, MeerCat, MechaVaca y la música del juego.": "<b>FANS OF RUMBLE 3D</b>: the 3D sketch with its first mission, a commentator, MeerCat, MechaVaca and the game's music.",
  "<b>FANS OF TACTICS ADVANCE</b>: tácticas por casillas en pixel art de consola portátil. Ya es jugable (2 contra 4), con presentación, pantalla de título y tutorial con Lola.": "<b>FANS OF TACTICS ADVANCE</b>: grid tactics in handheld-console pixel art. It's now playable (2 vs 4), with an intro, title screen and a tutorial with Lola.",
  "<b>DEMO LARGA</b>: 13 salas, Zoe y un final con el Núcleo Albright.": "<b>LONGER DEMO</b>: 13 rooms, Zoe and an ending with the Albright Core.",
  "<b>PERSONAJES ESTILO PS1</b>: el protagonista con su uniforme de enfermero, animación natural y ambiente más oscuro.": "<b>PS1-STYLE CHARACTERS</b>: the hero in his nurse's uniform, natural animation and a darker atmosphere.",
  "<b>PUERTAS DETALLADAS</b>, cámaras que ya no pierden al personaje y música ambiental.": "<b>DETAILED DOORS</b>, cameras that no longer lose the character and ambient music.",
  "Microblizz ha leído este boletín entero. Pide que el próximo sea más corto y que cueste 4,99 €.": "Microblizz read this whole bulletin. It wants the next one shorter, and priced at €4.99.",
});
